### PR TITLE
Gas_Limit as string

### LINKED ISSUE #11258: Proposer config "gas_limit" string issue
# 🐞 Bug Report

### Description

Hello, there seems to be an incompatibility with the proposer config "gas_limit" field.

Your documentation does show an integer. But other clients and flashbots all use a string.

Relevant section in flashbots spec:
```
interface configuration {
    proposer_config: {
        [key: string]: {
            fee_recipient: string;
            builder: {
                enabled: boolean;
                gas_limit: string;
            }
        };
    },
}
```

### Has this worked before in a previous version?

I haven't tested this on previous versions.

## 🔬 Minimal Reproduction

```
"builder": {
  "enabled": true
  "gas_limit": "30000000"
}
```

## 🔥 Error
Prysm logs this error if the `gas_limit` value is not passed as an integer:
<pre><code>

time="2022-08-18 15:49:52" level=error msg="failed to unmarshal yaml file: yaml: unmarshal errors:

</code></pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
    v2.1.4
  </code>
</pre>

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

 Bug fix

**What does this PR do? Why is it needed?**

currently, the gas limit in the proposer settings YAML is represented as a number. JSON numbers can't hold the data required for the maximum number in the type uint64 and so the spec has the gas limit as a string instead of a number. This PR changes the following
- [x] suggested-gas-limit flag is changed from an int to a string 
- [x] gas_limit field defined in proposer settings json/yaml can be represented as either a number or a string
unit tests are added to for testing.

**Which issues(s) does this PR fix?**

Fixes #11258

### CODE REVIEW

File: config/validator/service/proposer-settings.go [hunk 1]
```diff
@@ -25,10 +27,41 @@ type ProposerOptionPayload struct {
 // GasLimit is a number set to help the network decide on the maximum gas in each block.
 type BuilderConfig struct {
 	Enabled  bool     `json:"enabled" yaml:"enabled"`
-	GasLimit uint64   `json:"gas_limit,omitempty" yaml:"gas_limit,omitempty"`
+	GasLimit Uint64   `json:"gas_limit,omitempty" yaml:"gas_limit,omitempty"`
 	Relays   []string `json:"relays" yaml:"relays"`
 }
 
+type Uint64 uint64
```
Comment (terencechain) [inline config/validator/service/proposer-settings.go:34]: Do we need to reinvent the wheel here? It seems to me we could just use geth's hexutil
```go
type Uint64 uint64

// MarshalText implements encoding.TextMarshaler.
func (b Uint64) MarshalText() ([]byte, error) {
	buf := make([]byte, 2, 10)
	copy(buf, `0x`)
	buf = strconv.AppendUint(buf, uint64(b), 16)
	return buf, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (b *Uint64) UnmarshalJSON(input []byte) error {
	if !isString(input) {
		return errNonString(uint64T)
	}
	return wrapTypeError(b.UnmarshalText(input[1:len(input)-1]), uint64T)
}

// UnmarshalText implements encoding.TextUnmarshaler
func (b *Uint64) UnmarshalText(input []byte) error {
	raw, err := checkNumberText(input)
	if err != nil {
		return err
	}
	if len(raw) > 16 {
		return ErrUint64Range
	}
	var dec uint64
	for _, byte := range raw {
		nib := decodeNibble(byte)
		if nib == badNibble {
			return ErrSyntax
		}
		dec *= 16
		dec += nib
	}
	*b = Uint64(dec)
	return nil
}
```

Comment (james-prysm) [reply config/validator/service/proposer-settings.go:34]: the thing is this value is not a hex value 
> // Uint64 marshals/unmarshals as a JSON string with 0x prefix.
   // The zero value marshals as "0x0".
   
   it's just a string version of uint64 i.e. `"30000000"`

Comment (terencechain) [reply config/validator/service/proposer-settings.go:34]: Ah ok!

**Review by terencechain — APPROVED** [review]
