### PR TITLE
Make Follow Distance Lookup Simpler

### LINKED ISSUE #7856: eth1data: Prysm does not vote with the majority if the majority is voting on an older block
# 🐞 Bug Report

### Description

At the moment, eth1data consensus is not being reached.

image

Nimbus is voting for a very old block, 5 days old. https://goerli.etherscan.io/block/0x0566a632683a61180a735bf72f7daea59deeb9781d4a43be41a86d484df6287f

Lighthouse and Teku are voting on a block that is 30 minutes older than what Prysm thinks is the start of the eth1voting period.
https://goerli.etherscan.io/block/0x3da88bec112d32d5e81741dfd395df14381346ebf48b91b1bfa111fdb7a69b5f
(Nov-18-2020 10:18:00 AM +UTC)

Prysm thinks the start of this eth1data voting period is 
```javascript
new Date((1605700807 + 2048*12-2048*14)*1000)
// Wed Nov 18 2020 02:51:51 GMT-0800 (Pacific Standard Time)
```
Genesis time is 1605700807
Slot is 2048
Eth1FollowDistance is 2048

So the current start slot time minus the eth1followdistance comes out to be `Wed Nov 18 2020 02:51:51 GMT-0800 (Pacific Standard Time)`.

So Prysm considers this block to be the highest block in the previous eth1data voting period. https://goerli.etherscan.io/block/0x227ed776f1e4a705ec8fae4ac1342d316be3f4cb9bf5248a9848bf344776f9c5 (Nov-18-2020 10:51:45 AM +UTC)

The reason I am filing a bug in Prysm is that I think that Prysm's voting with the majority mechanism should consider votes from the previous voting period to be acceptable. Otherwise we could see these types of issues or off by one issues when multiple blocks are produced in quick succession on eth1.

Another thing to consider, if client teams do not have the same eth1 block time of 14s then it will be even more difficult to reach eth1data consensus at mainnet.  Some additional context: https://github.com/ethereum/eth2.0-specs/issues/2132 Prysm MUST conform with other clients in this regard for mainnet configuration. As such, I am marking this as a P0.

### Has this worked before in a previous version?

Maybe when Prysm was the majority then Lighthouse and Teku would favor Prysm's block vote because it is still in range of their interpreted eth1data voting period.

## 🔬 Minimal Reproduction

This is occuring in Pyrmont testnet.

## 🔥 Error

N/A

## 🌍  Your Environment

**Operating System:**

N/A

**What version of Prysm are you running? (Which release)**

v1.0.0-beta.3

**Anything else relevant (validator index / public key)?**

- [x] Fix caching issue
- [ ] Fix mainnet spec config difference

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Cleanup

**What does this PR do? Why is it needed?**

- [x] Remove a lot of unnecessary blocks of code.

**Which issues(s) does this PR fix?**

Fixes #7856 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/powchain/block_reader.go [hunk 1]
```diff
@@ -160,6 +160,7 @@ func (s *Service) BlockNumberByTimestamp(ctx context.Context, time uint64) (*big
 		}
 		cursorNum = hinfo.Number
 		cursorTime = hinfo.Time
+		log.Errorf("cursor time: %d", cursorTime)
```
Comment (terencechain) [inline beacon-chain/powchain/block_reader.go:163]: ?

Comment (nisdas) [reply beacon-chain/powchain/block_reader.go:163]:
```suggestion
```
Debug log, removing now

**Review by prestonvanloon — APPROVED** [review]
