### PR TITLE
Handle empty local slashing protection data

### LINKED ISSUE #6468: Validator isNewAttSlashable panic
# 🐞 Bug Report

### Description

Validator client panics on `isNewAttSlashable`.

## 🔥 Error

<pre><code>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1eef9a1]

goroutine 683200 [running]:
github.com/prysmaticlabs/prysm/validator/client/polling.isNewAttSlashable(0x0, 0xfca, 0xfcb, 0x217afa0)
        validator/client/polling/attest.go:268 +0x41
github.com/prysmaticlabs/prysm/validator/client/polling.(*validator).preSigningValidations(0xc000706000, 0x879da0, 0xc000792120, 0xc000a33d40, 0x17965fa2490c0799, 0x9cf7d5e901f27000, 0xe1b0a6c2366ad6a8, 0x9b04c82d76edaca5, 0x4b0c0ddb1d73323d, 0x730b352b17995937, ...)
        validator/client/polling/attest.go:152 +0x46a
github.com/prysmaticlabs/prysm/validator/client/polling.(*validator).SubmitAttestation(0xc000706000, 0x879da0, 0xc000792120, 0x1f967, 0x17965fa2490c0799, 0x9cf7d5e901f27000, 0xe1b0a6c2366ad6a8, 0x9b04c82d76edaca5, 0x4b0c0ddb1d73323d, 0x730b352b17995937)
        validator/client/polling/attest.go:69 +0xc4f
github.com/prysmaticlabs/prysm/validator/client/polling.run.func1(0xc000243430, 0x88f520, 0xc000706000, 0x879d60, 0xc000a33740, 0x1f967, 0xc0000bb960, 0x965fa2490c079901, 0xf7d5e901f2700017, 0xb0a6c2366ad6a89c, ...)
        validator/client/polling/runner.go:126 +0x1ea
created by github.com/prysmaticlabs/prysm/validator/client/polling.run
        validator/client/polling/runner.go:122 +0xd56
</code></pre>

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
  Prysm/v1.0.0-alpha.13/6c7131cb544413e1ca73aeb18e6ff5b9acc813b7
  </code>
</pre>

### PR DESCRIPTION
**Pull request by 0xKiwi**
**What type of PR is this?**
Panic fix

**What does this PR do? Why is it needed?**
This PR fixes #6468, by handling several cases to prevent a panic in case the history data is nil. Also adds regression tests.

### CODE REVIEW

File: validator/db/kv/attestation_history.go [hunk 1]
```diff
@@ -14,9 +14,10 @@ import (
 func unmarshalAttestationHistory(ctx context.Context, enc []byte) (*slashpb.AttestationHistory, error) {
 	ctx, span := trace.StartSpan(ctx, "Validator.unmarshalAttestationHistory")
 	defer span.End()
+	copiedEnc := make([]byte, len(enc))
+	copy(copiedEnc, enc)
```
Comment (prestonvanloon) [inline validator/db/kv/attestation_history.go:18]: Why?

File: validator/client/attest_protect.go [hunk 2]
```diff
@@ -19,9 +19,9 @@ func (v *validator) preAttSignValidations(ctx context.Context, indexedAtt *ethpb
 	fmtKey := fmt.Sprintf("%#x", pubKey[:])
 	if featureconfig.Get().LocalProtection {
 		v.attesterHistoryByPubKeyLock.RLock()
-		attesterHistory := v.attesterHistoryByPubKey[pubKey]
+		attesterHistory, ok := v.attesterHistoryByPubKey[pubKey]
 		v.attesterHistoryByPubKeyLock.RUnlock()
-		if isNewAttSlashable(attesterHistory, indexedAtt.Data.Source.Epoch, indexedAtt.Data.Target.Epoch) {
+		if ok && isNewAttSlashable(attesterHistory, indexedAtt.Data.Source.Epoch, indexedAtt.Data.Target.Epoch) {
```
Comment (0xKiwi) [inline validator/client/attest_protect.go:24]: Is this way of handling the nil data too silent? Should something be logged?

Comment (prestonvanloon) [reply validator/client/attest_protect.go:24]: maybe at a debug level. It is a bit concerning that it is nil
