### PR TITLE
Fix `checkForChainStart` pre-genesis state and 0 validator

### LINKED ISSUE #6737: Could not determine active validator count from pref genesis stat
The following error happened with `--medalla`

To reproduce, you just have to restart your beacon node once before processing any eth1 deposit. The pre genesis state's validator will be nil and it'll be used for active count

Screen Shot 2020-07-27 at 8 45 47 AM

### PR DESCRIPTION
**Pull request by terencechain**
**What type of PR is this?**
> Bug fix

**What does this PR do? Why is it needed?**
Fixes an edge case where the node has pre-genesis state but there's nil validators in the state. In this such case, the node should exit early in `checkForChainStart`

**Which issues(s) does this PR fix?**

Fixes #6737 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/powchain/log_processing_test.go [hunk 1]
```diff
@@ -622,6 +622,16 @@ func TestConsistentGenesisState(t *testing.T) {
...
 }
 
+func TestCheckForChainstart_NoValidator(t *testing.T) {
+	hook := logTest.NewGlobal()
+	testAcc, err := contracts.Setup()
+	require.NoError(t, err, "Unable to set up simulated backend")
+	beaconDB, _ := testDB.SetupDB(t)
+	s := newPowchainService(t, testAcc, beaconDB)
+	s.checkForChainstart([32]byte{}, nil, 0)
+	testutil.AssertLogsDoNotContain(t, hook, "Could not determine active validator count from pre genesis state")
```
Comment (shayzluf) [inline beacon-chain/powchain/log_processing_test.go:632]: maybe it will also be good to check genesistime wasn't changed
