### PR TITLE
Fix validator export failing when validator.db is in nested directory

### LINKED ISSUE #14954: Slashing protection history export failing
When I try to export the slashing protection history to json I get the following error:

`FATAL historycmd: No slashing protection data was found in your database. This is likely because an older version of Prysm would place your validator database in your wallet directory as a validator.db file. Now, Prysm keeps its validator database inside the direct/ or derived/ folder in your wallet directory. Try running this command again, but add direct/ or derived/ to the path where your wallet directory is in and you should obtain your slashing protection history`

Bit confused with the error, the validator.db file lives in the data folder, not the wallet folder on my system. I am running a different directory for the wallet and the data dir.

I have previously used the same command to perform this task previously. I can't remember the last time I successfully performed the export, perhaps a year ago.

Launch cmd: `validator-v5.2.0-windows-amd64.exe slashing-protection-history export --datadir="G:\prysm\Eth2" --slashing-protection-export-dir="G:\prysm\protection\data"`

### PR DESCRIPTION
**Pull request by rose2221**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

This PR fixes a bug where the `slashing-protection-history export` command fails to locate `validator.db` if it is stored in a nested directory such as `data/direct/`, even when a valid `--datadir` flag is provided.

Previously, the export command would perform a recursive search to locate `validator.db`, but it discarded the actual path where the file was found and later attempted to open it from the root `--datadir`, causing it to miss nested directories. This resulted in errors such as:

```

FATAL historycmd: No slashing protection data was found in your database. \[…]

```

This PR captures the matched path from the recursive search and uses it to open the validator database correctly. This allows the export command to function as expected even when `validator.db` resides deeper in the folder hierarchy (e.g., `/data/direct/validator.db`).

**Which issue(s) does this PR fix?**

Fixes #14954

**Other notes for review**

- Verified end-to-end using a dummy validator initialized with a public beacon endpoint.
- Includes improved logging to indicate the resolved validator DB path.
- Minimal scope and risk: no changes to behavior unless validator.db is nested and previously unreachable.

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

File: cmd/validator/slashing-protection/export.go [hunk 1]
```diff
@@ -74,6 +75,12 @@ func exportSlashingProtectionJSON(cliCtx *cli.Context) error {
 			databaseFileDir = filesystem.DatabaseDirName
 		}
 		return fmt.Errorf("%s (validator database) was not found at path %s, so nothing to export", databaseFileDir, dataDir)
+	} else {
+		if !isDatabaseMinimal {
+			matchPath = filepath.Dir(matchPath) // strip the file name
+		}
+		dataDir = matchPath
+        log.Infof("Found validator database at path %s", dataDir)
```
Comment (prestonvanloon) [inline cmd/validator/slashing-protection/export.go]: I think you may need to run gofmt on this file

**Comment by prestonvanloon** [comment]
Feeling up to adding a test? If not, I can push one for you. There is a good start in `cmd/validator/slashing-protection/import_export_test.go` 

You could refactor that test to run the test twice. Once for the current test and another as a regression test where the validator.db is nested. Refactoring to a table driven test might help!

**Comment by rose2221** [comment]
> Feeling up to adding a test? If not, I can push one for you. There is a good start in `cmd/validator/slashing-protection/import_export_test.go`
> 
> You could refactor that test to run the test twice. Once for the current test and another as a regression test where the validator.db is nested. Refactoring to a table driven test might help!

hey, thanks for reviewing the PR, tests have been added as suggested!

**Review by prestonvanloon — APPROVED** [review]
Thanks!

**Review by prestonvanloon — CHANGES_REQUESTED** [review]
Hmm... actually, when I reviewed the tests more carefully, it doesn't look like you call mutate. so it's testing the flat scenario twice. Could you fix please?

**Comment by rose2221** [comment]
> Hmm... actually, when I reviewed the tests more carefully, it doesn't look like you call mutate. so it's testing the flat scenario twice. Could you fix please?

Ah, sorry about that! I've fixed it now to properly call `mutate` and test both scenarios.

**Comment by prestonvanloon** [comment]
Looks like gofmt needs to be run

**Comment by rose2221** [comment]
> Looks like gofmt needs to be run

fixed, thanks

**Review by prestonvanloon — APPROVED** [review]
