### PR TITLE
only viable head is invalid

### LINKED ISSUE #10777: Wrong justification on init sync nodes
When starting a beacon-node, prysm replays all blocks starting from the finalized node up to the latest known head from the database, repopulating its fork-choice. Prysm assigns as `justified_checkpoint`  the last known justified checkpoint of the branch, which may not coincide with the actual justified checkpoint of the node.

Consider the scneario:

```
  Epoch N-1   |    Epoch N       |   Epoch N+1
              |                  |
A <- B <- C <-  D <- E <- F <- G <- H <- I <- J <- K
```

At the start of epoch N, epoch N-1 has not been justified, block D has enough votes to justify A, and at the start of epoch N+1 block H will have A as `H.justified_checkpoint` while block D will have a lower justified checkpoint in epoch N-2. 

If the node operator decides to restart the beacon, block D will be sent to forkchoice having A and thus epoch N-1 as justified. In normal circumstances this would not affect operations since the head is a descendant of D. However, after Bellatrix, the whole chain `E <- ... <- K` may have been synced optimistically, and be actually invalid. In this case the beacon node will have to revert to `D` as head, but this is impossible, since `D` post-state justified point is in epoch N-2 and forkchoice believes it should be N-1, therefore deadlocking the node. 

This issue requires some design decisions. Teku saves the justified checkpoint of every non-finalized block to dbase and prunes it after finalization.

### LINKED ISSUE #10782: Update justification when pruning INVALID nodes
When the beacon node receives an INVALID reply for an optimistically synced branch, the node removes those nodes from forkchoice. This however may revert the last finalized and justified node even though these may not be invalid. Consider the following situation
```
   Epoch 10    |   Epoch 11    |   Epoch 12    |   Epoch 13    |   Epoch 14
               |               |               |               |
  A <- B <- C <- D < .........<- E <-. .......<- F <- ........<- G <- H
```
Epoch 10 is finalized and 11 is justified, epoch 12 does not justify during its time.  When we sync block `E` in Epoch 12 this block will have 
```
E.justified_checkpoint = { Epoch: 11, Root: D.root }
E.finalized_checkpoint = { Epoch: 10, Root: A.root }
```
At the beginning of epoch 13, block `F`  has enough votes to justify 12(E) and finalize 11 (D).  When we sync block `G` our Forkchoice Store has
```
store.justified_checkpoint = { Epoch: 12, Root: E.root }
store.finalized_checkpoint = { Epoch: 11, Root: D.root }
```
Now suppose that the whole sequence `F<- ... <- H`  was synced optimistically, the EL returns `INVALID` when we sync `H` and `LVH` for block `E`. The node should revert to `E` as head, but  this is not possible since it has contradicting justification information between the block and the store.

### PR DESCRIPTION
**Pull request by potuz**
This PR ensures that in the situation described in the linked issues, where after pruning INVALID blocks, no viable head is possible, we satisfy the following properties

- Stay in optimistic mode https://github.com/ethereum/consensus-specs/pull/2955
- Are able to continue syncing blocks (Reviewers: during Init sync this needs verification)
- Are able to restart the beacon node in these conditions (Reviewers: this needs verification)

This is achieved by allowing `head` to refer to an INVALID block, both in Forkchoice and in `blockchain-service.head`. Even though both store and forkchoice can have an INVALID root as head, the node itself and the blocks/states would have been removed from forkchoice and database. 

Moreover, as a result of this prunning the `blockchain.head` and the forkchoice's cached head may differ, depending on wether the INVALID status was a result of `notifyNewPayload` (no block is inserted to forkchoice) or `notifyForkchoiceUpdated` (the block is inserted in forkchoice and not saved in `blockchain.head`)

Another danger is that any call to `forkchoice.Head()` while on this status will result in an error since there are no viable tips. 

Fixes #10782 
Fixes #10777

### CODE REVIEW

File: beacon-chain/blockchain/process_block_test.go [hunk 1]
```diff
@@ -1800,3 +1801,650 @@ func Test_verifyBlkFinalizedSlot_invalidBlock(t *testing.T) {
 	err = service.verifyBlkFinalizedSlot(wb)
 	require.Equal(t, true, IsInvalidBlock(err))
 }
+
+// See the description in #10777 and #10782 for the full setup
```
Comment (potuz) [inline beacon-chain/blockchain/process_block_test.go:1805]: The tests added here cover the main circumstances of a single branch being pruned and no viable head being available. It checks the behavior when the INVALID return comes from NotifyNewPayload and from FCU. Note however that in order to trigger justification change, at least one INVALID block needs to be imported to forkchoice, so this requires at least one INVALID block to be returned as SYNCING/ACCEPTED by notify_newPayload. 

These tests do not cover initial sync which can be added if requested, but the paths seem to be contained to the execution engine functions, so it should be similar from `onBlock` to `onBlockBatch`.  They also do not cover rebooting from this condition. This is a bit more dangerous since our starting head would be non-existent.

File: testing/util/altair.go [hunk 2]
```diff
@@ -377,6 +377,12 @@ func GenerateFullBlockAltair(
 		}
 	}
 
+	syncCommitteeBits := make(bitfield.Bitvector512, 64)
```
Comment (potuz) [inline testing/util/altair.go:380]: This function prepared a full SyncAggregate, but the signature would fail at the fork. Fixing that perhaps is probable, but since this is not used anywhere on any test, I decided that it was easier to just return the empty participation case.

File: testing/util/altair.go [hunk 3]
```diff
@@ -392,22 +398,17 @@ func GenerateFullBlockAltair(
 		slot = currentSlot + 1
 	}
 
-	syncAgg, err := generateSyncAggregate(bState, privs, parentRoot)
+	stCopy := bState.Copy()
+	stCopy, err = transition.ProcessSlots(context.Background(), stCopy, slot)
```
Comment (potuz) [inline testing/util/altair.go:402]: These functions would increase the slot  temporarily to obtain the block proposer. While this would mostly work, it fails in producing the right signatures at fork transition and most probably epoch boundaries as well. Full process slots are needed. These functions became slower because of this and the extra needed copy.

File: testing/util/bellatrix.go [hunk 4]
```diff
@@ -53,3 +63,176 @@ func BlockSignatureBellatrix(
...
+	if err != nil {
+		return nil, err
+	}
+
+	parentExecution, err := stCopy.LatestExecutionPayloadHeader()
+	if err != nil {
+		return nil, err
+	}
+	blockHash := indexToHash(uint64(slot))
+	newExecutionPayload := &enginev1.ExecutionPayload{
```
Comment (potuz) [inline testing/util/bellatrix.go:119]: This can be improved by including transactions and configuring some of the fields that are hardcoded here.

File: testing/util/block.go [hunk 5]
```diff
@@ -34,6 +34,7 @@ type BlockGenConfig struct {
 	NumAttestations      uint64
 	NumDeposits          uint64
 	NumVoluntaryExits    uint64
+	NumTransactions      uint64 // Only for post Bellatrix blocks
```
Comment (potuz) [inline testing/util/block.go:37]: this is unused now

File: testing/util/bellatrix.go [hunk 6]
```diff
@@ -2,54 +2,195 @@ package util
...
 	"github.com/prysmaticlabs/prysm/crypto/bls"
+	"github.com/prysmaticlabs/prysm/crypto/hash"
+	"github.com/prysmaticlabs/prysm/encoding/bytesutil"
+	enginev1 "github.com/prysmaticlabs/prysm/proto/engine/v1"
 	ethpb "github.com/prysmaticlabs/prysm/proto/prysm/v1alpha1"
+	"github.com/prysmaticlabs/prysm/time/slots"
 )
 
-// BlockSignatureBellatrix calculates the post-state root of the block and returns the signature.
-func BlockSignatureBellatrix(
```
Comment (potuz) [inline testing/util/bellatrix.go:18]: This function is exactly the same as the non-bellatrix version therefore I removed it.

File: testing/util/helpers.go [hunk 7]
```diff
@@ -37,37 +38,78 @@ func RandaoReveal(beaconState state.ReadOnlyBeaconState, epoch types.Epoch, priv
 // BlockSignature calculates the post-state root of the block and returns the signature.
 func BlockSignature(
 	bState state.BeaconState,
-	block *ethpb.BeaconBlock,
+	block interface{},
```
Comment (potuz) [inline testing/util/helpers.go:41]: This is to use this function to sign Altair and Bellatrix blocks as well.

File: testing/util/sync_aggregate.go [hunk 8]
```diff
@@ -1,73 +0,0 @@
...
-	p2pType "github.com/prysmaticlabs/prysm/beacon-chain/p2p/types"
-	"github.com/prysmaticlabs/prysm/beacon-chain/state"
-	"github.com/prysmaticlabs/prysm/config/params"
-	"github.com/prysmaticlabs/prysm/crypto/bls"
-	"github.com/prysmaticlabs/prysm/encoding/bytesutil"
-	ethpb "github.com/prysmaticlabs/prysm/proto/prysm/v1alpha1"
-	"github.com/prysmaticlabs/prysm/time/slots"
-)
-
-func generateSyncAggregate(st state.BeaconState, privs []bls.SecretKey, parentRoot [32]byte) (*ethpb.SyncAggregate, error) {
```
Comment (potuz) [inline testing/util/sync_aggregate.go:16]: This function may be salvaged, the signature here is wrong and is never really used. Perhaps it can be saved in a way that it would sign correctly on fork transition, but since it's not used I figured it was better removed.

File: beacon-chain/blockchain/execution_engine.go [hunk 9]
```diff
@@ -101,8 +101,12 @@ func (s *Service) notifyForkchoiceUpdate(ctx context.Context, arg *notifyForkcho
...
 			r, err := s.cfg.ForkChoiceStore.Head(ctx, s.justifiedBalances.balances)
 			if err != nil {
-				log.WithError(err).Error("Could not get head root")
-				return nil, nil
+				log.WithFields(logrus.Fields{
+					"slot":         headBlk.Slot(),
+					"blockRoot":    fmt.Sprintf("%#x", bytesutil.Trunc(headRoot[:])),
+					"invalidCount": len(invalidRoots),
+				}).Warn("Pruned invalid blocks, could not update head root")
+				return nil, invalidBlock{error: ErrInvalidPayload, root: arg.headRoot, invalidAncestorRoots: invalidRoots}
```
[the remark this answers is not in the document]
Comment (terencechain) [reply beacon-chain/blockchain/execution_engine.go:114]: Here's what is bothering me a little bit. We are returning nil for every `err != nil ` under `ErrInvalidPayloadStatus`. Should we change most of them to `invalidBlock{error: ErrInvalidPayload, root: arg.headRoot, invalidAncestorRoots: invalidRoots}`?  Ok to do this in another PR

File: beacon-chain/core/altair/block.go [hunk 10]
```diff
@@ -47,11 +47,11 @@ import (
 func ProcessSyncAggregate(ctx context.Context, s state.BeaconState, sync *ethpb.SyncAggregate) (state.BeaconState, error) {
 	votedKeys, votedIndices, didntVoteIndices, err := FilterSyncCommitteeVotes(s, sync)
 	if err != nil {
-		return nil, err
+		return nil, errors.Wrap(err, "could not filter sync committee votes")
```
Comment (terencechain) [inline beacon-chain/core/altair/block.go:50]: how is this related to the PR? I don't mind the changes, I'm just curious

Comment (terencechain) [reply beacon-chain/core/altair/block.go:50]: ah I see, you made it better because you had to work through `GenerateFullBlockAltair` for tests

File: beacon-chain/blockchain/chain_info.go [hunk 11]
```diff
@@ -332,7 +334,14 @@ func (s *Service) IsOptimisticForRoot(ctx context.Context, root [32]byte) (bool,
...
 	if ss == nil {
-		return false, errInvalidNilSummary
+		// if the requested root is the headroot we should treat the
+		// node as optimistic. This can happen if we pruned INVALID
+		// nodes and no viable head is available.
+		headRoot, err := s.HeadRoot(ctx)
+		if err == nil && bytes.Equal(headRoot, root[:]) {
+			return true, nil
+		}
+		return true, errInvalidNilSummary
```
Comment (terencechain) [inline beacon-chain/blockchain/chain_info.go:344]: We kinda lose info if `err != nil`. How about?

```suggestion
                 if err != nil {
                         return true, err
                 }
		if bytes.Equal(headRoot, root[:]) {
			return true, nil
		}
		return true, errInvalidNilSummary
```

Comment (terencechain) [reply beacon-chain/blockchain/chain_info.go:344]: Would it be helpful to add a metric counter for `bytes.Equal(headRoot, root[:])` ?

File: beacon-chain/core/altair/block.go (hunk 10 above)
Comment (potuz) [reply beacon-chain/core/altair/block.go:50]: Yeah, things were failing and I didn't know where

File: beacon-chain/blockchain/execution_engine.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (potuz) [reply beacon-chain/blockchain/execution_engine.go:114]: It bothers me too, but we used to return errors on everything and it was bad rendering the node locked with minor things. I feel this situation shouldn't happen often so it's kinda safe to put it here, I haven't thought deeply on the other errors here.

File: testing/util/sync_aggregate.go (hunk 8 above)
Comment (potuz) [reply testing/util/sync_aggregate.go]: I had to reuse it because it turned out to be used by the monitor indirectly in tests

File: testing/util/altair.go (hunk 2 above)
Comment (potuz) [reply testing/util/altair.go]: See below: I had to reuse the previous behavior because of the monitor's test

**Review by terencechain — DISMISSED** [review]

File: beacon-chain/blockchain/chain_info.go [hunk 12]
```diff
@@ -332,7 +334,17 @@ func (s *Service) IsOptimisticForRoot(ctx context.Context, root [32]byte) (bool,
 		return false, err
 	}
 	if ss == nil {
-		return false, errInvalidNilSummary
+		// if the requested root is the headroot we should treat the
+		// node as optimistic. This can happen if we pruned INVALID
+		// nodes and no viable head is available.
+		headRoot, err := s.HeadRoot(ctx)
```
Comment (nisdas) [inline beacon-chain/blockchain/chain_info.go:340]: how does this work, we have a head for which there is no state summary/block in the db ?

File: beacon-chain/blockchain/execution_engine.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (nisdas) [reply beacon-chain/blockchain/execution_engine.go:114]: Is there a reason we only add the invalid block error here ? 
```go
invalidBlock{error: ErrInvalidPayload, root: arg.headRoot, invalidAncestorRoots: invalidRoots}
```
In this whole conditional branch, this is the only location where we return the error.

File: beacon-chain/core/altair/block.go [hunk 13]
```diff
@@ -47,11 +47,11 @@ import (
...
 	}
 
 	if err := VerifySyncCommitteeSig(s, votedKeys, sync.SyncCommitteeSignature); err != nil {
-		return nil, err
+		return nil, errors.Wrap(err, "could not verify Sync Committee signature")
```
Comment (nisdas) [inline beacon-chain/core/altair/block.go:54]:
```suggestion
		return nil, errors.Wrap(err, "could not verify sync committee signature")
```

**Comment by mkalinin** [comment]
> Another danger is that any call to `forkchoice.Head()` while on this status will result in an error since there are no viable tips.

Why will it result in an error? According to the specification, [`get_head`](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/fork-choice.md#get_head) should return `store.justified_checkpoint.root` if no viable tip is available

File: beacon-chain/blockchain/chain_info.go (hunk 12 above)
Comment (potuz) [reply beacon-chain/blockchain/chain_info.go:340]: Yes, and even worse, it can be different than forkchoice's

**Comment by potuz** [comment]
> > Another danger is that any call to `forkchoice.Head()` while on this status will result in an error since there are no viable tips.
> 
> Why will it result in an error? According to the specification, [`get_head`](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/fork-choice.md#get_head) should return `store.justified_checkpoint.root` if no viable tip is available

This is implementation dependant. The specs cannot say what a function does or doesn't do. In this case the computed head will be the justified checkpoint but we return an error because it's not viable for head

**Review by terencechain — APPROVED** [review]

**Comment by terencechain** [comment]
Chatted with @potuz offline. The ideal solution would be:

 Implement this method in fork choice
```go
(f *forkchocice) AreAllTipsInvalid() bool {}
```

Then in IsOptmistic, we add the following breaking:
```go
func (s *Service) IsOptimistic(ctx context.Context) (bool, error) {
   if s.cfg.ForkChoiceStore.AreAllTipsInvalid {
      return true, nil
   }
}
```

That can be done in another PR. For now, I'm going to move forward with this one

**Review by nisdas — APPROVED** [review]
