### PR TITLE
Use passphrase for HD-wallets

### LINKED ISSUE #7213: Passphrase given during HD-wallet creation is not used.  Empty string is used for HD-wallet operations.
# 🐞 Bug Report

If you create a HD wallet, you are asked for a passphrase.  Regardless of what you choose, you can access the wallet using whatever passphrase you please.

### Description

Create HD wallet with passphrase1
Then run accounts-v2 create using passphrase2 <-- No issues
Repeat prior step with a set of random passphrases <-- No issues
List accounts, also no issue.

This stems from the following code in validator/keymanager/v2/derived/derived.go at lines 103 and 134:

```
	if !fileutil.FileExists(filepath.Join(cfg.Wallet.AccountsDir(), EncryptedSeedFileName)) {
		seedConfig, err := initializeWalletSeedFile(cfg.WalletPassword, cfg.SkipMnemonicConfirm)
		if err != nil {
			return nil, errors.Wrap(err, "could not initialize new wallet seed file")
		}
```

```
	decryptor := keystorev4.New()
	seed, err := decryptor.Decrypt(seedConfig.Crypto, cfg.WalletPassword)
	if err != nil {
		return nil, errors.Wrap(err, "could not decrypt seed configuration with password")
	}
```

**cfg.WalletPassword is being passed without being initialized.  The password obtained during startup would actually be in cfg.Wallet.walletPassword** obtainable using a getter method.

### Has this worked before in a previous version?

I don't know.  It might be the first time I have used Prysm HD wallets.

## 🔬 Minimal Reproduction

See above

## 🔥 Error

See above

## 🌍  Your Environment

Bug is in both in Windows 10 as well as Ubuntu running in docker running in Ubuntu VM.  64 bit.

**What version of Prysm are you running? (Which release)**

Current master.  acddb6035a2f07a8d4f38731c89778e7b1813afc

**Anything else relevant (validator index / public key)?**
No

### PR DESCRIPTION
**Pull request by dv8silencer**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**
Currently, the passphrase is ignored for HD wallets.  [Edit:] This bug was included in Alpha 25 (just released) and was not present in Alpha 24.  There is a bug that causes the passwords to be ignored and an empty string (Default val) to be used instead.  This causes HD wallets to be protected by an empty string and HD wallets created prior to Alpha 25 to be difficult to access.  From issue #7213 :

This stems from the following code in validator/keymanager/v2/derived/derived.go at lines 103 and 134:

```
	if !fileutil.FileExists(filepath.Join(cfg.Wallet.AccountsDir(), EncryptedSeedFileName)) {
		seedConfig, err := initializeWalletSeedFile(cfg.WalletPassword, cfg.SkipMnemonicConfirm)
		if err != nil {
			return nil, errors.Wrap(err, "could not initialize new wallet seed file")
		}
```

```
	decryptor := keystorev4.New()
	seed, err := decryptor.Decrypt(seedConfig.Crypto, cfg.WalletPassword)
	if err != nil {
		return nil, errors.Wrap(err, "could not decrypt seed configuration with password")
	}
```

cfg.WalletPassword is being passed without being initialized. The password obtained during startup would actually be in cfg.Wallet.walletPassword obtainable using a getter method.

This PR fixes that issue.  Initially I kept it a draft since I did not know when the bug was introduced and was worried about the repercussions of fixing it.

**Which issues(s) does this PR fix?**

Fixes #7213 

**Other notes for review**

### CODE REVIEW

File: validator/accounts/v2/accounts_create_test.go [hunk 1]
```diff
@@ -28,8 +30,8 @@ func TestCreateAccount_Derived(t *testing.T) {
 
 	// We attempt to open the newly created wallet.
 	ctx := context.Background()
-	wallet, err := OpenWallet(cliCtx.Context, &WalletConfig{
-		WalletDir: walletDir,
+	wallet, err := OpenWalletOrElseCli(cliCtx, func(cliCtx *cli.Context) (*Wallet, error) {
+		return nil, errors.New("failed to open wallet")
 	})
```
Comment (dv8silencer) [inline validator/accounts/v2/accounts_create_test.go:35]: Regarding this change:  cliCtx already has the necessary information, namely, the wallet directory.  (See line 19)

File: validator/accounts/v2/wallet_test.go [hunk 2]
```diff
@@ -142,8 +143,8 @@ func Test_LockUnlockFile(t *testing.T) {
 	require.NoError(t, err)
 
 	// We attempt to open the newly created wallet.
```
Comment (dv8silencer) [inline validator/accounts/v2/wallet_test.go:145]: Regarding this change: cliCtx already has the necessary information, namely, the wallet directory.  (See line 133)

**Comment by dv8silencer** [comment]
This bug may have been released to users in Alpha 25.  So there would be far less concern about introducing this fix as most probably have HD wallets that are indeed protected by a non-empty passphrase they chose in prior releases.

**Review by rauljordan — APPROVED** [review]
