### PR TITLE
Fix Tests in sync/validate_beacon_blocks.go to Pass for the Right Reasons

### LINKED ISSUE #9791: Validate beacon blocks test case passing for wrong reasons
# 🐞 Bug Report

### Description

In the file `validate_beacon-locks-test.go`, few test cases are passing for the wrong reasons.
Ex: `TestValidateBeaconBlockPubSub_InvalidSignature`, the validation check at the end checks for `validationReject`, but it is not checking if the reject is for the right reason, which in this case is Invalid signature. The `validationReject` we are getting is because there is an error in `decodePubsubMessage`.

### Has this worked before in a previous version?

Same from the beginning i think

## 🔬 Minimal Reproduction

Run the test case in debug mode and you will see why it sends a `validationReject`.

## 🔥 Error
No Error is displayed

**Anything else relevant (validator index / public key)?**

In develop, there is an error code that is send  back from `validateBeaconBlockPubSub` along with the libp2p error, we can use that to check if this fails for the right reason.

### PR DESCRIPTION
**Pull request by saolyn**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

In the file `validate_beacon-locks-test.go` there were a number of test cases that were passing for the wrong reasons.
This branch fixes the tests that were passing despite an error in `decodePubsubMessage` and fixes the passing requirements by including the correct expected errors and validation decisions.
This ensures that the tests pass for the right reasons and in the future, if they break, that it is caught early.

Additionally a couple tests were renamed to better describe what they are testing.

**Which issues(s) does this PR fix?**

Fixes #9791

**Other notes for review**

I was unable to fully check whether the tests for valid blocks are passing for the right reasons.

### CODE REVIEW

File: beacon-chain/sync/validate_beacon_blocks.go [hunk 1]
```diff
@@ -168,7 +168,6 @@ func (s *Service) validateBeaconBlockPubSub(ctx context.Context, pid peer.ID, ms
 		}
 		s.pendingQueueLock.Unlock()
 		err := errors.Errorf("unknown parent for block with slot %d and parent root %#x", blk.Block().Slot(), blk.Block().ParentRoot())
-		log.WithError(err).WithFields(getBlockFields(blk)).Debug("Could not process early block")
```
Comment (terencechain) [inline beacon-chain/sync/validate_beacon_blocks.go:171]: Why remove this debug log?

Comment (terencechain) [inline beacon-chain/sync/validate_beacon_blocks.go:171]: Nice!

File: beacon-chain/sync/validate_beacon_blocks_test.go [hunk 2]
```diff
@@ -63,14 +62,21 @@ func TestValidateBeaconBlockPubSub_InvalidSignature(t *testing.T) {
 	msg.Block.ParentRoot = bRoot[:]
 	msg.Block.Slot = 1
 	msg.Block.ProposerIndex = proposerIdx
-	msg.Signature = bytesutil.PadTo([]byte("fake"), fieldparams.BLSSignatureLength)
+	badPrivKeyIdx := proposerIdx - 1 // We generate a valid signature from a wrong private key which fails to verify
+	if badPrivKeyIdx < 0 {
+		badPrivKeyIdx += 2
+	}
```
Comment (terencechain) [inline beacon-chain/sync/validate_beacon_blocks_test.go:68]: `proposerIdx` is deterministic, you could just say `badPrivKeyIdx = proposerIdx +1`  ?

Comment (saolyn) [reply beacon-chain/sync/validate_beacon_blocks_test.go:68]: I wasn't sure if it was deterministic so I added a check just in case. So it can definitely be simplified,

File: beacon-chain/sync/validate_beacon_blocks.go (hunk 1 above)
Comment (saolyn) [reply beacon-chain/sync/validate_beacon_blocks.go:171]: What would you recommend? Something like "Could not identify parent for block"?

Comment (terencechain) [reply beacon-chain/sync/validate_beacon_blocks.go:171]: Sounds good to me

**Review by rauljordan — APPROVED** [review]
awesome job!

**Review by terencechain — APPROVED** [review]
