### PR TITLE
Remove chain not started error

### LINKED ISSUE #6682: Healthz of beacon returns incorrect status before syncing
# 🐞 Bug Report

### Description

When starting the beacon-chain service and querying `/healthz` the endpoint returns no errors, but only `OK`s like this:
```
$ curl localhost:8480/healthz
*gateway.Gateway: OK
*p2p.Service: OK
*powchain.Service: OK
*attestations.Service: OK
*blockchain.Service: OK
*initialsync.Service: OK
*sync.Service: OK
*rpc.Service: OK
*prometheus.Service: OK
```
At the same time it logs something like this:
```
time="2020-07-22 17:14:08" level=info msg="Processing deposits from Ethereum 1 chain" deposits=5632 genesisValidators=5552 prefix=powchain
```

The beacon-chain then enters syncing (connects to peers, loads blocks, ...) and the status change to this:
```
$ curl localhost:8480/healthz
*p2p.Service: OK
*powchain.Service: OK
*attestations.Service: OK
*initialsync.Service: ERROR syncing
*blockchain.Service: OK
*sync.Service: ERROR waiting for initial sync
*rpc.Service: OK
*gateway.Gateway: OK
*prometheus.Service: OK
```

I'd expect seeing `ERROR` when the service isn't started yet. When everything is `OK` one could assume the beacon is ready to serve validators, but in fact it didn't even start syncing.

## 🔬 Minimal Reproduction

Start an empty beacon-chain, query `/healthz` shortly after before syncing starts.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
docker tag `HEAD-62ae22`
  </code>
</pre>

### PR DESCRIPTION
**Pull request by terencechain**
**What type of PR is this?**

> Uncomment one line below and remove others.
>
> Bug fix

**What does this PR do? Why is it needed?**

It's not appropriate for sync to return this error even if chain has not started, instead blockchain chain service should return the error while it is processing deposits to determine the genesis state. After this fix:
```
When processing deposits (before genesis state):
*prometheus.Service: OK
*p2p.Service: OK
*attestations.Service: OK
*initialsync.Service: OK
*sync.Service: OK
*gateway.Gateway: OK
*powchain.Service: OK
*blockchain.Service: ERROR genesis state has not been created
*rpc.Service: OK

After processing deposits (during sync):
*powchain.Service: OK
*blockchain.Service: OK
*p2p.Service: OK
*initialsync.Service: ERROR syncing
*sync.Service: ERROR out of sync
*rpc.Service: OK
*gateway.Gateway: OK
*prometheus.Service: OK
*attestations.Service: OK
```

**Which issues(s) does this PR fix?**

Fixes #6682

**Other notes for review**

### CODE REVIEW

File: beacon-chain/sync/service.go [hunk 1]
```diff
@@ -196,12 +196,6 @@ func (s *Service) Stop() error {
 
 // Status of the currently running regular sync service.
 func (s *Service) Status() error {
-	if s.chainStarted.IsNotSet() {
-		return errors.New("chain not yet started")
-	}
-	if s.initialSync.Syncing() {
```
Comment (terencechain) [inline beacon-chain/sync/service.go:202]: This was duplicated and confusing. Initial sync already projected error here: 
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/sync/initial-sync/service.go#L131

**Review by prestonvanloon — APPROVED** [review]
