### PR TITLE
fix validator loggin timeTillDuty as a negative number

### LINKED ISSUE #11383: `timeTillDuty` log shows a negative number
I turned on my validator after the attestation slot had already passed and this was the duties log:
```
Attestation schedule attesterDutiesAtSlot=1 pubKeys=[0xb6bdb41f87ee] slot=3793913 slotInEpoch=25 timeTillDuty=-1m0s totalAttestersInEpoch=1
```
Notice `timeTillDuty=-1m0s` (there is a `-` at the beginning). We should probably skip the field in such cases.

### PR DESCRIPTION
**Pull request by saolyn**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

If the validator is activated just after the duration of `timeTillDuty`, the log would display a negative number.
With this PR we add a simple check to ensure that the `timeTIllDuty` is only logged when it is above 0.

**Which issues(s) does this PR fix?**

Fixes #11383

**Other notes for review**

### CODE REVIEW

**Review by terencechain — DISMISSED** [review]
lgtm, thank you!

File: validator/client/validator.go [hunk 1]
```diff
@@ -938,20 +939,27 @@ func (v *validator) logDuties(slot types.Slot, duties []*ethpb.DutiesResponse_Du
 	}
 	for i := types.Slot(0); i < params.BeaconConfig().SlotsPerEpoch; i++ {
 		startTime := slots.StartTime(v.genesisTime, slotOffset+i)
-		durationTillDuty := time.Until(startTime) + time.Second
+		durationTillDuty := (time.Until(startTime) + time.Second).Round(time.Second)
```
Comment (saolyn) [inline validator/client/validator.go:942]: Is there a specific reason why we are adding a second here?

Comment (prestonvanloon) [reply validator/client/validator.go:942]: I think it's so that it rounds up more often than rounds down. It seems a bit strange to me as well. 

I think a better pattern would be to add one second then truncate it. Effectively, that would always round up to the next full second.

```suggestion
		durationTillDuty := (time.Until(startTime) + time.Second).Truncate(time.Second) // Round up to next second.
```

**Review by rauljordan — APPROVED** [review]
