### PR TITLE
Fix race on ReceibeBlock

### LINKED ISSUE #15555: Prysm stuck due to invalid optimistic status
### Describe the bug

prysm is stuck due to `invalid optimistic status`, prysm got new block and sent it to geth for execution validation but received and error and roll back the block
```
time="2025-07-30 11:09:07" level=debug msg="Synced new block" block=0x6866eb63... chainServiceProcessedTime=6.913676492s dataAvailabilityWaitedTime=5.984µs deposits=0 epoch=382941 finalizedEpoch=382939 finalizedRoot=0xc73d149f... justifiedEpoch=382940 justifiedRoot=0
x8234dd6f... parentRoot=0xabe112b6... prefix=blockchain sinceSlotStartTime=8.480411182s slot=12254143 slotInEpoch=31 version=electra
time="2025-07-30 11:09:07" level=debug msg="Synced new payload" blockHash=0x135022cb5648 blockNumber=23031546 blsToExecutionChanges=0 gasUtilized=0.54 parentHash=0xc2ff60c9967e prefix=blockchain withdrawals=16
time="2025-07-30 11:09:07" level=info msg="Finished applying state transition" attestations=2 kzgCommitmentCount=4 payloadHash=0x135022cb5648 prefix=blockchain slot=12254143 syncBitsCount=498 txCount=281
time="2025-07-30 11:09:10" level=info msg="Connected peers" inboundQUIC=0 inboundTCP=87 outboundQUIC=3 outboundTCP=16 prefix=p2p total=106
time="2025-07-30 11:09:11" level=error msg="could not remove node" error="invalid optimistic status" prefix=forkchoice-doublylinkedtree
time="2025-07-30 11:09:11" level=warning msg="Rolling back insertion of block with root 0x6866eb63331bee2d26a73841d8b1f4bc677bf75cc22556ec7a5c4450c7e2200a due to processing error" prefix=blockchain
```

then prysm kept requesting same block over and over but because node was not removed due to error whenever we got this block it was discarded due to already sync
```
	if s.InForkchoice(blockRoot) {
		log.WithField("blockRoot", fmt.Sprintf("%#x", blockRoot)).Debug("Ignoring already synced block")
		return nil
	}
```
logs for example
```
time="2025-07-30 11:09:26" level=debug msg="Requesting block by root" blockRoot=0x6866eb63331bee2d26a73841d8b1f4bc677bf75cc22556ec7a5c4450c7e2200a prefix=sync
time="2025-07-30 11:09:26" level=debug msg="Could not send recent block request" error="new stream: failed to negotiate protocol: protocols not supported: [/eth2/beacon_chain/req/beacon_blocks_by_root/2/ssz_snappy]" prefix=sync
time="2025-07-30 11:09:29" level=debug msg="Verified and saved pending attestations to pool" blockRoot=6e22a2d7c687 pendingAttsCount=527 prefix=sync
time="2025-07-30 11:09:30" level=debug msg="Aggregated unaggregated attestations" duration=2.17919ms prefix="pool/attestations"
time="2025-07-30 11:09:30" level=debug msg="Ignoring already synced block" blockRoot=0x6866eb63331bee2d26a73841d8b1f4bc677bf75cc22556ec7a5c4450c7e2200a prefix=blockchain
time="2025-07-30 11:09:30" level=debug msg="Processed pending block and cleared it in cache" blockRoot=6866eb63331b prefix=sync slot=12254143
```
and it keep happening until i restart prysm and geth and then everything works fine for some time and it happen again.

### Has this worked before in a previous version?

```text

```

### 🔬 Minimal Reproduction

_No response_

### Error

```text
https://gist.github.com/leonbiton1/16396205e2d8fb80204bb9ebad8adfdd
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

Prysm/v6.0.4/91b44360fcd74bad41f38b79bb3b05094408a2d0

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by potuz**
In the event two routines for `ReceiveBlock` are triggered with the same block (it may happen if one routine is triggered over gossip and the other in init-sync) it may happen that the second routine believes it's syncing the block for the first time. This is because the cache on `blocksBeingSynced` is not checked to be set and the block may still not be put in forkchoice by the first routine.

In the normal case this would not cause any trouble as the second forkchoice insertion is a noop by design. However, if the second routine times out or has any error in processing (for example the engine will return an error if we try to send FCU to an older head) then the second routine will attempt to remove the inserted block from forkchoice and this bricks the node since forkchoice refuses to remove a valid node, the root is removed inconditionally from db and the node ends up with a root that is not in db and remains in forkchoice.

This PR just prevents the race.

As a followup perhaps we can gate the rollback function from db to nodes that are effectively not in forkchoice, alternatively, force removal from forkchoice when rolling back from db (although this version is complicated due to possible accounting issues on forkchoice).

Fixes #15555

### CODE REVIEW

File: beacon-chain/blockchain/receive_block.go [hunk 1]
```diff
@@ -84,7 +84,11 @@ func (s *Service) ReceiveBlock(ctx context.Context, block interfaces.ReadOnlySig
 	}
 
 	receivedTime := time.Now()
-	s.blockBeingSynced.set(blockRoot)
+	err := s.blockBeingSynced.set(blockRoot)
+	if errors.Is(err, errBlockBeingSynced) {
+		log.WithField("blockRoot", fmt.Sprintf("%#x", blockRoot)).Debug("Ignoring block currently being synced")
```
Comment (kasey) [inline beacon-chain/blockchain/receive_block.go:89]: Consider adding `WithError(err)`. It's a simple unwrapped error for now so perhaps redundant, but if that ever changes, full errors in logs can be helpful in debugging.

**Review by kasey — APPROVED** [review]

File: beacon-chain/blockchain/receive_block.go (hunk 1 above)
Comment (potuz) [reply beacon-chain/blockchain/receive_block.go:89]: I thought about adding it but then realized that anyway this log only happens on this particular error, and the log already includes it. This is invariant even if the error changes in the setter in the future.

**Review by james-prysm — APPROVED** [review]

**Review by terencechain — APPROVED** [review]
