### PR TITLE
Fix #11948 and reduces call to `GetFeeRecipientByPubKey` only in `ListFeeRecipientByPubkey` in nothing is defined in VC

### LINKED ISSUE #11948: If validator client `POST /eth/v1/validator/{pubkey}/gas_limit` is called with `{pubkey}` without any fee recipient registered in validator client configuration, then `{pubkey}` fee recipient is set to `0x00000....`, and any tip earned by a block proposal for this validator will be burned (even if a default fee recipient is set in the beacon node)
# 🐞 Bug Report

### Description

If validator client `POST /eth/v1/validator/{pubkey}/gas_limit` is called with a `{pubkey}` without any fee recipient registered in validator client configuration, then `{pubkey}` fee recipient is set to `0x00000....`, and any tip earned by a block proposal for this validator will be burned (even if a default fee recipient is set in the beacon node).

I suspect it is not the expected behavior.

## 🔬 Minimal Reproduction
1. Run a beacon node with `suggested-fee-recipient`
2. Run a validator client with a given pubkey, (with or without a `default_config` fee recipient, but **without** a `proposer_config` fee recipient for the given `{pubkey}`)
3. At the beginning of the next epoch, no `PrepareBeaconProposer` function will be called for this pubkey ==> At the next block proposal for this pubkey, the used fee recipient will be the default one provided by the beacon node.
4. Call `POST /eth/v1/validator/{pubkey}/gas_limit` for this pubkey.
5. At the beginning of the next epoch,`PrepareBeaconProposer` function will be called for this pubkey, but with `0x0000.....` as fee recipient. ==> At the next block proposal for this pubkey, tips will be burned.

## 🔥 Error
[here](https://github.com/prysmaticlabs/prysm/blob/develop/validator/rpc/standard_api.go#L460) and [here](https://github.com/prysmaticlabs/prysm/blob/develop/validator/rpc/standard_api.go#L467), we have this snippet of code:

```go
GetFeeRecipientByPubKey(ctx, &eth.FeeRecipientByPubKeyRequest{
			PublicKey: []byte(nonExistantPublicKey),
		})
```

No `FeeRecipient` is provided into `eth.FeeRecipientByPubKeyRequest` ==> `FeeRecipient` will default to `common.Address` default value: `0x0000...`

[here](https://github.com/prysmaticlabs/prysm/blob/develop/validator/rpc/standard_api.go#L478), `pOption.FeeRecipient` is set to `params.BeaconConfig().DefaultFeeRecipient,`, which is also `0x0000...`.

## 🌍  Your Environment

**Operating System:**
MacOS Ventura 13.1
Prysm v3.2.0

### PR DESCRIPTION
**Pull request by nalepae**
### What type of PR is this?
Feature and Fix

### Related gitHub issues:
- https://github.com/prysmaticlabs/prysm/issues/11580
- https://github.com/prysmaticlabs/prysm/issues/11948

### What does this PR do? Why is it needed?
This PR introduces two main changes:

#### FeeRecipientconfig

In `ProposerOption`, a new wrapper `FeeRecipientConfig` around `FeeRecipient` is created:

```go
type FeeRecipientConfig struct {
	FeeRecipient common.Address
}

// ProposerOption is a Prysm internal representation of the ProposerOptionPayload on the validator client in bytes format instead of hex.
type ProposerOption struct {
	FeeRecipientConfig *FeeRecipientConfig
	BuilderConfig      *BuilderConfig
}
```

This change enables the fact that `FeeRecipient` could be undefined while `BuilderConfig` is defined.
This fixes https://github.com/prysmaticlabs/prysm/issues/11948.

Important changes are [here](https://github.com/nalepae/prysm/blob/11948/validator/client/validator.go#L1074-L1086) and [here](https://github.com/nalepae/prysm/blob/11948/validator/client/validator.go#L1110): They ensure `PrepareBeaconProposer` and `SubmitValidatorRegistrations` are called only for pubkeys with a (custom or default) fee recipient.

==> We can call [POST setGasLimit](https://ethereum.github.io/keymanager-APIs/#/Gas%20Limit/setGasLimit) on a pubkey without fee recipient without automatically defined the corresponding fee recipient to burn address.

#### GetFeeRecipientByPubKey

Before this PR, `GetFeeRecipientByPubKey` gRPC call is called in:
- `SetGasLimit`,
- `SetFeeRecipientByPubkey`, and
- `ListFeeRecipientByPubkey`

There is no (direct or indirect) equivalent of `GetFeeRecipientByPubKey` in Beacon API.
The idea of this PR is to reduce usage of `GetFeeRecipientByPubKey` gRPC call as low as possible.

After this PR, `GetFeeRecipientByPubKey` gRPC is only used in `ListFeeRecipientByPubkey`.
A next PR will handle this last case in order to be fully Beacon API compatible.

### CODE REVIEW

**Comment by james-prysm** [comment]
I'm ok with the direction of this PR, let me know when it's out of draft mode.

File: hack/update-mockgen.sh [hunk 1]
```diff
@@ -87,3 +87,20 @@ done
 
 goimports -w "$beacon_api_mock_path/."
 gofmt -s -w "$beacon_api_mock_path/."
+
+# github.com/prysmaticlabs/prysm/v3/crypto/bls
+# --------------------------------------------
+crypto_bls_common_mock_path="crypto/bls/common/mock"
+crypto_bls_common_mocks=(
+      "$crypto_bls_common_mock_path/interface_mock.go interface.go"
```
Comment (james-prysm) [inline hack/update-mockgen.sh:96]: are you using this somewhere in the tests right now? having trouble connecting these changes to the rest of the PR.

File: crypto/bls/common/mock/interface_mock.go [hunk 2]
```diff
@@ -0,0 +1,277 @@
...
+
+import (
+	reflect "reflect"
+
+	gomock "github.com/golang/mock/gomock"
+	common "github.com/prysmaticlabs/prysm/v3/crypto/bls/common"
+)
+
+// MockSecretKey is a mock of SecretKey interface.
+type MockSecretKey struct {
```
Comment (james-prysm) [inline crypto/bls/common/mock/interface_mock.go:15]: question related to update-mockgen.sh changes

File: crypto/bls/common/mock/BUILD.bazel [hunk 3]
```diff
@@ -0,0 +1,12 @@
+load("@prysm//tools/go:def.bzl", "go_library")
+
+go_library(
+    name = "go_default_library",
+    srcs = ["interface_mock.go"],
+    importpath = "github.com/prysmaticlabs/prysm/v3/crypto/bls/common/mock",
+    visibility = ["//visibility:public"],
+    deps = [
+        "//crypto/bls/common:go_default_library",
```
Comment (james-prysm) [inline crypto/bls/common/mock/BUILD.bazel:9]: see comment on update-mockgen.sh

File: validator/client/validator_test.go [hunk 4]
```diff
@@ -1943,3 +1974,433 @@ func TestValidator_PushProposerSettings(t *testing.T) {
...
+	feeRecipientTemp, err := hexutil.Decode(stringFeeRecipient)
+	require.NoError(t, err)
+
+	var feeRecipient common.Address
+	copy(feeRecipient[:], feeRecipientTemp)
+
+	return feeRecipient
+}
+
+func TestValidator_buildPrepProposerReqs_WithoutDefaultConfig(t *testing.T) {
```
Comment (james-prysm) [inline validator/client/validator_test.go:2016]: nice great test 👍

File: hack/update-mockgen.sh [hunk 5]
```diff
@@ -88,3 +88,20 @@ done
...
```
Comment (james-prysm) [inline hack/update-mockgen.sh:96]: Nice update on this, found the usage in validator_test.go

**Review by james-prysm — APPROVED** [review]
Thanks for the nice tests and the update to mockgen seems useful for the future as well
This PR as stated will change the default of setting keys without fee recipient settings/defaults from the burn address to not being sent at all in the update. If validators that don't have it set propose it will fall back to whatever the beacon node has set.
