### PR TITLE
Ensure Only Noise And Secio Are Security Transports

### LINKED ISSUE #6032: Use Proper Security Fallback
# 🐞 Bug Report

Currently we have updated our v0.12 branch to the latest libp2p deps to support the new gossipsub. However, it was brought up by the quantstamp team that the security fallback of TLS has been added for the default option.

### Description

This issue is to track the resolution of this to instead only use noise with secio as the fallback.

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction
N.A

**What version of Prysm are you running? (Which release)**

04d6afa356ca666c4677027eeaec539c6b0facc5

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Ensures that for v0.12 only Noise and Secio are used as security transports.

**What does this PR do? Why is it needed?**

Makes sure that we only use the correct security transports instead of something like 
`TLS` which is now the default option along with secio

**Which issues(s) does this PR fix?**

Fixes #6032 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/p2p/options.go [hunk 1]
```diff
@@ -33,7 +34,9 @@ func buildOptions(cfg *Config, ip net.IP, priKey *ecdsa.PrivateKey) []libp2p.Opt
 	}
 	if featureconfig.Get().EnableNoise {
 		// Enable NOISE for the beacon node
```
Comment (terencechain) [inline beacon-chain/p2p/options.go:36]:
```suggestion
		// Enable NOISE for the beacon node.
```
