### PR TITLE
Make external slasher protection fail on load if slasher is not reachable

### LINKED ISSUE #6703: External slasher protection fail silently
# 🐞 Bug Report

### Description

when running a validator with `--enable-external-slasher-protection` and slasher is not reachable attestations are being sent and only warning messages are being emitted

### Has this worked before in a previous version?

not sure

## 🔬 Minimal Reproduction

run `bazel run //validator -- --grpc-headers="api_key=zfB005FncyblbQ2XuF46YOICE3hr4g4P0iKt12xXUl6A43Q8" --beacon-rpc-provider=beacon.prylabs.network:30002 --enable-external-slasher-protection`

### PR DESCRIPTION
**Pull request by shayzluf**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**
if you are choosing to use an external slasher for your validator protection and it is not reachable it is expected to block all your attestations and blocks to fail validation.
This pr make it behave as expected.

**Which issues(s) does this PR fix?**

Fixes #6703

### CODE REVIEW

**Comment by 0xKiwi** [comment]
Shouldn't we query for the slasher like a validator queries for a beacon node? And if the validator can't find it with this flag enabled then fail?

File: validator/slashing-protection/slasher_client.go [hunk 1]
```diff
@@ -142,5 +144,8 @@ func (s *Service) Status() error {
 	if s.conn == nil {
```
Comment (0xKiwi) [inline validator/slashing-protection/slasher_client.go:144]: Comment right above this says WIP, can you update that please?

Comment (shayzluf) [reply validator/slashing-protection/slasher_client.go:144]: sure
