### PR TITLE
Warn Users if Slashing Protection History is Empty

### LINKED ISSUE #9897: Empty `slashing_protection.json` after export
# 🐞 Bug Report

### Description

I have exported in more than 1 prater validator the **slashing protection database** using the CLI. In all cases, the slashing protection database results in a JSON file with empty key values that seems to be wrong, like the following:
```
{
	"metadata": {
		"interchange_format_version": "5",
		"genesis_validators_root": "0x043db0d9a83813551ee2f33450d23797757d430911a9320530ad8a0eabc43efb"
	},
	"data": [
		{
			"pubkey": "0x80b11b83eb8c1858c657dc55936bd4b47d2418c8906777cecae9c14495796f3d52b44652684e25e9ebb3e9efcfea33c6",
			"signed_blocks": [],
			"signed_attestations": []
		}
	]
}
```
### Has this worked before in a previous version?

I have not tried the slashing protection database export before.
## 🔬 Minimal Reproduction
To reproduce the issue just do a normal **export of the validator slashing protection database** with 
```
validator slashing-protection export --datadir=/root/.eth2validators
```
The output logs are
```
validator --prater slashing-protection export --datadir=/root/.eth2validators
[2021-11-12 16:35:02]  WARN flags: Running on the Prater Testnet
[2021-11-12 16:35:02]  INFO slashingprotection: This command exports your validator's attestation and proposal history into a file that can then be imported into any other Prysm setup across computers
Extracting signed blocks by validator public key 100% [================================]  [0s:0s]
Enter your desired output directory for your slashing protection history file:
/root 
[2021-11-12 16:35:13]  INFO slashingprotection: Writing slashing protection export JSON file to /root/slashing_protection.json
[2021-11-12 16:35:13]  INFO slashingprotection: Successfully wrote /root/slashing_protection.json
```

## 🔥 Error
The `slashing_protection.json` JSON file seems to have something wrong, especially the following empty key-values
<pre><code>

"signed_blocks": [],
"signed_attestations": []
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Docker container running on a Debian host
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.0.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
The validator was executed with the following flags
```
validator \
  --prater \
  --datadir=/root/.eth2 \
  --rpc-host 0.0.0.0 \
  --monitoring-host 0.0.0.0 \
  --beacon-rpc-provider=\"$BEACON_RPC_PROVIDER\" \
  --beacon-rpc-gateway-provider=\"$BEACON_RPC_GATEWAY_PROVIDER\" \
  --wallet-dir=/root/.eth2validators \
  --wallet-password-file=/root/.eth2wallets/wallet-password.txt \
  --write-wallet-password-on-web-onboarding \
  --graffiti=\"$GRAFFITI\" \
  --web \
  --grpc-gateway-host=0.0.0.0 \
  --grpc-gateway-port=80 \
  --accept-terms-of-use
```

### PR DESCRIPTION
**Pull request by rauljordan**
Fixes #9897. The dappnode team was running into a curious issue where they were seeing an empty slashing protection history exported, as reported in #9897. They were running their validator with a command like this:

```
validator \
  --prater \
  --datadir=/root/.eth2 \
  --wallet-dir=/root/.eth2validators \
  --rpc-host 0.0.0.0 \
```

and then trying to export their slashing protection history with:
```
validator slashing-protection export --datadir=/root/.eth2validators
```
Note that they set their --datadir as `/root/.eth2` when running, which is different than what they are trying to export. They should have received some kind of warning if this was the case. This PR adds the necessary warning and explanation to users in case this situation happens.

**NOTE TO REVIEWERS**
Currently, if a validator.db is not found in the specified directory when attempting an export, the current code does throw an error. However, seems like it did not in dappnode's case. My belief is that dappnode had an old, probably empty validator.db in their --wallet-dir and their real validator.db in their --datadir, leading to the issue. This is really hard to write a test case for. We will have to confirm this warning is triggered on dappnode's side before merging.

### CODE REVIEW

File: cmd/validator/slashing-protection/export.go [hunk 1]
```diff
@@ -67,6 +67,22 @@ func exportSlashingProtectionJSON(cliCtx *cli.Context) error {
 	if err != nil {
 		return errors.Wrap(err, "could not export slashing protection history")
 	}
+
+	// Check if JSON data is empty and issue a warning about common problems to the user.
+	if eipJSON == nil || len(eipJSON.Data) == 0 {
+		log.Warnf(
```
Comment (terencechain) [inline cmd/validator/slashing-protection/export.go:73]: Wouldn't fatal for (2) be more appropriate here? but i guess it's hard to separate them out

**Comment by rauljordan** [comment]
Ready @terencechain

**Review by terencechain — APPROVED** [review]
