### PR TITLE
Fix Panic When Accessing State Frequently

### LINKED ISSUE #8886: segmentation violation (v1.3.2)
# 🐞 Bug Report

### Description

One of our node crashed with a `SIGSEGV`, this was the first time I have seen a crash like this. The version of the node was `Prysm/v1.3.2/29d1959b81921946f620b8fc745be660c8185d39 `

You can find the logs here: https://gist.github.com/guybrush/c5e1edd181725e6d590cbe6852e7db82

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

- [x] Allocates separately, so as to prevent panics from occurring due to changes in memory mapping. 
- [x] For `HasState`, it inlines the method so as to prevent unnecessary allocation during checking for state 
existence.

**Which issues(s) does this PR fix?**

Fixes #8886

**Other notes for review**

### CODE REVIEW

File: beacon-chain/db/kv/state.go [hunk 1]
```diff
@@ -128,11 +128,20 @@ func (s *Store) SaveStates(ctx context.Context, states []iface.ReadOnlyBeaconSta
...
-	enc, err := s.stateBytes(ctx, blockRoot)
+	hasState := false
+	err := s.db.View(func(tx *bolt.Tx) error {
+		bkt := tx.Bucket(stateBucket)
+		stBytes := bkt.Get(blockRoot[:])
+		if len(stBytes) == 0 {
+			return nil
+		}
+		hasState = true
+		return nil
```
Comment (rkapka) [inline beacon-chain/db/kv/state.go:139]: Can be simplified a little bit to

```
if len(stBytes > 0) {
    hasState = true
}
return nil
```

Comment (rkapka) [inline beacon-chain/db/kv/state.go:139]: Can be simplified a little bit to

```
if len(stBytes) > 0 {
    hasState = true
}
return nil
```

**Review by rkapka — DISMISSED** [review]

**Review by rkapka — APPROVED** [review]
