### PR TITLE
Stop Sync Service More Cleanly

### LINKED ISSUE #7720: sync: Failed to handle p2p RPC error=collector does not exist for topic
# 🐞 Bug Report

### Description

Many debug logs print in rapid succession, process is unable to shutdown gracefully.

### Has this worked before in a previous version?

Yes. Beta.0

## 🔬 Minimal Reproduction

User reported this occurred when trying to shut down a beacon node

Send exit signal to running beacon node.

*Note: I have not reproduced this yet myself.*

## 🔥 Error

```
[2020-11-03 18:26:47] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/ping/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).validateRequest
	beacon-chain/sync/rate_limiter.go:73
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).pingHandler
	beacon-chain/sync/rpc_ping.go:29
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAmRNf9XvmuUSEAgFWCLtp8u5PPfeCL7vRss7jmVJPykcks topic=/eth2/beacon_chain/req/ping/1/ssz_snappy
^C[2020-11-03 18:26:47]  INFO node: Already shutting down, interrupt more to panic times=9
[2020-11-03 18:26:47] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/ping/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).validateRequest
	beacon-chain/sync/rate_limiter.go:73
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).pingHandler
	beacon-chain/sync/rpc_ping.go:29
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAmEjkLHYYtJVLXp4CbrASiq5Je2vH7Wu6hkb7wpMWwrVSN topic=/eth2/beacon_chain/req/ping/1/ssz_snappy
[2020-11-03 18:26:47] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).topicCollector
	beacon-chain/sync/rate_limiter.go:62
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlocksByRangeRPCHandler
	beacon-chain/sync/rpc_beacon_blocks_by_range.go:60
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAm6DVk6e6NAiy6vrRY2CnJqf7GTw7WHPBCmdCe1qvkJrxE topic=/eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
[2020-11-03 18:26:47] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).topicCollector
	beacon-chain/sync/rate_limiter.go:62
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlocksByRangeRPCHandler
	beacon-chain/sync/rpc_beacon_blocks_by_range.go:60
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAm6DVk6e6NAiy6vrRY2CnJqf7GTw7WHPBCmdCe1qvkJrxE topic=/eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
^C[2020-11-03 18:26:47]  INFO node: Already shutting down, interrupt more to panic times=8
^C[2020-11-03 18:26:47]  INFO node: Already shutting down, interrupt more to panic times=7
^C[2020-11-03 18:26:47]  INFO node: Already shutting down, interrupt more to panic times=6
[2020-11-03 18:26:47] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/ping/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).validateRequest
	beacon-chain/sync/rate_limiter.go:73
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).pingHandler
	beacon-chain/sync/rpc_ping.go:29
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAmDozn3ksBmKS83i9KD6QETymzPCTw9ZxszGYvmKxfDmDK topic=/eth2/beacon_chain/req/ping/1/ssz_snappy
[2020-11-03 18:26:47] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/ping/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).validateRequest
	beacon-chain/sync/rate_limiter.go:73
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).pingHandler
	beacon-chain/sync/rpc_ping.go:29
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAky5uUsVC7b9ynQtoGKXjh2EGbHtWP3P3y6CjSKgepTkFz topic=/eth2/beacon_chain/req/ping/1/ssz_snappy
^C[2020-11-03 18:26:47]  INFO node: Already shutting down, interrupt more to panic times=5
[2020-11-03 18:26:47] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/ping/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).validateRequest
	beacon-chain/sync/rate_limiter.go:73
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).pingHandler
	beacon-chain/sync/rpc_ping.go:29
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAmLJvpyjaxRP7yLx926oHseY78KPbzrcyeSb1u2fC9V9zW topic=/eth2/beacon_chain/req/ping/1/ssz_snappy
^C[2020-11-03 18:26:47]  INFO node: Already shutting down, interrupt more to panic times=4
[2020-11-03 18:26:48] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/status/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).validateRequest
	beacon-chain/sync/rate_limiter.go:73
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).statusRPCHandler
	beacon-chain/sync/rpc_status.go:195
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAmERooL3wt6Lyc8U3h8KVabLbsB5LMD8qXqdvtBtLqv9rW topic=/eth2/beacon_chain/req/status/1/ssz_snappy
[2020-11-03 18:26:48] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).topicCollector
	beacon-chain/sync/rate_limiter.go:62
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlocksByRangeRPCHandler
	beacon-chain/sync/rpc_beacon_blocks_by_range.go:60
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAkz28ELWwJ6hdEtbs6kReAzb73rBHT7VogUx8WQsr2ntha topic=/eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
^C[2020-11-03 18:26:48]  INFO node: Already shutting down, interrupt more to panic times=3
^C[2020-11-03 18:26:48]  INFO node: Already shutting down, interrupt more to panic times=2
[2020-11-03 18:26:48] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).topicCollector
	beacon-chain/sync/rate_limiter.go:62
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlocksByRangeRPCHandler
	beacon-chain/sync/rpc_beacon_blocks_by_range.go:60
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAmL5fvbmwwndLiAytX5jRfcGs6ruxGP7kyHBm9GnwpV4ie topic=/eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
[2020-11-03 18:26:48] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).topicCollector
	beacon-chain/sync/rate_limiter.go:62
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlocksByRangeRPCHandler
	beacon-chain/sync/rpc_beacon_blocks_by_range.go:60
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAmL5fvbmwwndLiAytX5jRfcGs6ruxGP7kyHBm9GnwpV4ie topic=/eth2/beacon_chain/req/beacon_blocks_by_range/1/ssz_snappy
[2020-11-03 18:26:48] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/status/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).validateRequest
	beacon-chain/sync/rate_limiter.go:73
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).statusRPCHandler
	beacon-chain/sync/rpc_status.go:195
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAkymN5BX98WV3P2z1kdF8XWCdNeDr7GJLjSvRUF464GqY4 topic=/eth2/beacon_chain/req/status/1/ssz_snappy
^C[2020-11-03 18:26:48]  INFO node: Already shutting down, interrupt more to panic times=1
[2020-11-03 18:26:48] DEBUG sync: Failed to handle p2p RPC error=collector does not exist for topic /eth2/beacon_chain/req/beacon_blocks_by_root/1/ssz_snappy
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).retrieveCollector
	beacon-chain/sync/rate_limiter.go:146
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*limiter).validateRequest
	beacon-chain/sync/rate_limiter.go:73
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlocksRootRPCHandler
	beacon-chain/sync/rpc_beacon_blocks_by_root.go:75
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).registerRPC.func1
	beacon-chain/sync/rpc.go:124
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1
	external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:566
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1373 peer=16Uiu2HAmA2TgVdyTppXQKppnHyZ4LHaGiPn6LvchsdYmCDTqE43Z topic=/eth2/beacon_chain/req/beacon_blocks_by_root/1/ssz_snappy
^Cpanic: Panic closing the beacon node
```

## 🌍  Your Environment

**Operating System:**

**What version of Prysm are you running? (Which release)**

User reports they were running from master

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

- [x] Deregister topic validators properly and cancel subscriptions more appropriately.
- [x] Add simple regression test.

**Which issues(s) does this PR fix?**

Fixes #7720 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/sync/service.go [hunk 1]
```diff
@@ -173,6 +174,16 @@ func (s *Service) Stop() error {
 			s.rateLimiter.free()
 		}
 	}()
+	// Removing RPC Stream handlers.
+	for _, p := range s.p2p.Host().Mux().Protocols() {
```
Comment (shayzluf) [inline beacon-chain/sync/service.go:178]: do we want to check if p2p is not nil?

Comment (nisdas) [reply beacon-chain/sync/service.go:178]: Is there any situation it would be nil ? In the event `p2p` is ever nil we wont be able to start this service up.

Comment (shayzluf) [reply beacon-chain/sync/service.go:178]: was looking for its init but didn't find it

**Review by shayzluf — APPROVED** [review]
lgtm
