### PR TITLE
Builder API: Fix max field check on toProto function

### LINKED ISSUE #13333: Incorrect entry limit for BlobsBundle is used
# 💎 Issue

### Background

Regarding the max number of entries in a `BlobsBundle`...

### Description

https://github.com/prysmaticlabs/prysm/blob/c47c52152b1ee953723d571a3b3ab951230c73dd/api/client/builder/types.go#L1022-L1026

I believe the limit here should be `MaxBlobCommitmentsPerBlock`, not `MaxBlobsPerBlock`.

These are the limits in [`BlobsBundle`](https://github.com/ethereum/builder-specs/blob/main/specs/deneb/builder.md#blobsbundle) in the builder specs.

```python
class BlobsBundle(Container):
  commitments: List[KZGCommitment, MAX_BLOB_COMMITMENTS_PER_BLOCK]
  proofs: List[KZGProof, MAX_BLOB_COMMITMENTS_PER_BLOCK]
  blobs: List[Blob, MAX_BLOB_COMMITMENTS_PER_BLOCK]
```

Also, should `MaxBlobsPerBlock` be in `fieldparams`? This is a spec value and will change in the future. I think it should be in `params.config` instead. I'm guessing it's more practical as a constant?

cc @james-prysm

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

we are using the wrong constant for checking max blobs per blob bundle that was mistaken in a previous PR.
bundle defined here https://github.com/ethereum/builder-specs/blob/main/specs/deneb/builder.md#blobsbundle

**Which issues(s) does this PR fix?**

Fixes #13333

### CODE REVIEW

File: api/client/builder/types_test.go [hunk 1]
```diff
@@ -666,25 +667,21 @@ var testExampleExecutionPayloadDenebTooManyBlobs = fmt.Sprintf(`{
...
-	hexutil.Encode(make([]byte, fieldparams.BlobLength)), // 2
-	hexutil.Encode(make([]byte, fieldparams.BlobLength)), // 3
-	hexutil.Encode(make([]byte, fieldparams.BlobLength)), // 4
-	hexutil.Encode(make([]byte, fieldparams.BlobLength)), // 5
-	hexutil.Encode(make([]byte, fieldparams.BlobLength)), // 6
-	hexutil.Encode(make([]byte, fieldparams.BlobLength)), // 7
-)
+}`, morethanMaxBlobs())
+
+func morethanMaxBlobs() string {
```
Comment (james-prysm) [inline api/client/builder/types_test.go:675]: not sure if this function is worth it... it's pretty slow, wondering if moving to beacon config so i can override might work better

Comment (jtraglia) [reply api/client/builder/types_test.go:675]: Hmm yeah, I imagine that would be quite slow. It's generating a 1 GiB string!

```
128kb per blob * 4096 blobs * 2 bytes per hex value = 1073741824 bytes
```

Comment (james-prysm) [reply api/client/builder/types_test.go:675]: the error should be triggered if it's empty so i'll do that

**Review by terencechain — APPROVED** [review]
