### PR TITLE
Checkpoint sync fixes

### LINKED ISSUE #10617: Checkpoint Sync node version parsing fails on other beacon node API implementations
# 🐞 Bug Report

### Description

Checkpoint Sync needs to fetch a state by slot from the remote beacon node. The previous version of prysm had a bug where it was not running process_slots when retrieving a state by slot, so those older versions are incompatible. We use the beacon node api `/eth/v1/node/version` api to figure out if the remote node is compatible. The problem is, the regex to detect prysm versions is too restrictive and fails to parse version strings for nimbus, teku and lighthouse. We need to loosen it up to ignore everything after the initial client name and semver.

### Has this worked before in a previous version?
no

## 🔬 Minimal Reproduction
attempt to run `go run github.com/prysmaticlabs/prysm/cmd/prysmctl cpt latest --beacon-node-host=<lighthouse|nimbus|teku url>`. Observe an error like ```
unable to proceed with fallback method without confirming node version: could not be parsed: ... ```

## 🔥 Error

:point_up: 

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

`v2.1.1`

### PR DESCRIPTION
**Pull request by kasey**
**What type of PR is this?**
Bug fix

**What does this PR do? Why is it needed?**

This fixes a couple bugs in the checkpoint sync implementation. 
- block file naming
- fix node version regex that only worked for prysm node versions
- fix checkpoint block finalization bug

**Which issues(s) does this PR fix?**

Fixes #10617

**Other notes for review**

Some of these fixes were split off from PR #10387 - that PR will be reduced in scope.

### CODE REVIEW

File: beacon-chain/db/kv/finalized_block_roots.go [hunk 1]
```diff
@@ -105,6 +105,12 @@ func (s *Store) updateFinalizedBlockRoots(ctx context.Context, tx *bolt.Tx, chec
 			return err
 		}
 
+		// breaking here allows the initial checkpoint root to be correctly inserted,
+		// but stops the loop from trying to search for its parent.
+		if bytes.Equal(root, initCheckpointRoot) {
+			break
+		}
```
Comment (kasey) [inline beacon-chain/db/kv/finalized_block_roots.go:112]: this is the fix for the checkpoint block finalization bug

File: beacon-chain/db/kv/wss_test.go [hunk 2]
```diff
@@ -42,4 +42,8 @@ func TestSaveOrigin(t *testing.T) {
 	cbb, err := scb.MarshalSSZ()
 	require.NoError(t, err)
 	require.NoError(t, db.SaveOrigin(ctx, csb, cbb))
+
+	broot, err := scb.Block().HashTreeRoot()
+	require.NoError(t, err)
+	require.Equal(t, true, db.IsFinalizedBlock(ctx, broot))
```
Comment (kasey) [inline beacon-chain/db/kv/wss_test.go:48]: test case for the checkpoint block finalization bug

File: api/client/beacon/client_test.go [hunk 3]
```diff
@@ -28,18 +28,40 @@ func TestParseNodeVersion(t *testing.T) {
...
+				systemInfo:     "linux-x86_64/oracle-java-11",
+			},
+		},
+		{
+			name: "lighthouse version",
+			v:    "Lighthouse/v2.1.1-5f628a7/x86_64-linux",
+			nv: &NodeVersion{
+				implementation: "Lighthouse",
+				semver:         "v2.1.1-5f628a7",
+				systemInfo:     "x86_64-linux",
```
Comment (kasey) [inline api/client/beacon/client_test.go:64]: adding real node version strings from other clients

File: api/client/beacon/client.go [hunk 4]
```diff
@@ -272,7 +272,7 @@ type NodeVersion struct {
 	systemInfo     string
 }
 
-var versionRE = regexp.MustCompile(`^(\w+)\/(v\d+\.\d+\.\d+) \((.*)\)$`)
+var versionRE = regexp.MustCompile(`^(\w+)/(v\d+\.\d+\.\d+[-a-zA-Z0-9]*)\s*/?(.*)$`)
```
Comment (kasey) [inline api/client/beacon/client.go:275]: fix for node version string parsing - adds a alphanumeric + dash character class to the capture before the option space/slash and system info. The old check was too brittle, expecting there to always be a space and parens.

File: api/client/beacon/checkpoint.go [hunk 5]
```diff
@@ -40,15 +40,15 @@ func (od *OriginData) CheckpointString() string {
 // SaveBlock saves the downloaded block to a unique file in the given path.
 // For readability and collision avoidance, the file name includes: type, config name, slot and root
 func (od *OriginData) SaveBlock(dir string) (string, error) {
-	blockPath := path.Join(dir, fname("state", od.cf, od.st.Slot(), od.wsd.BlockRoot))
```
Comment (kasey) [inline api/client/beacon/checkpoint.go:43]: fixes bug where block would be saved to the same file name as state

**Review by terencechain — APPROVED** [review]
