### PR TITLE
Fix Finalized Epoch Checks

### LINKED ISSUE #5827: Mismatch between Finalized Block And Epoch
# 🐞 Bug Report

### Description

Currently there is a mismatch between finalized epochs and their related blocks. The finalized 
epoch does not exactly match the one provided by the slot in the block. 

### Has this worked before in a previous version?

Before #5811 

## 🔬 Minimal Reproduction

Run the node and look at the handshake errors from it from other peers.  

## 🔥 Error

```
[2020-05-12 20:19:13]  WARN sync: Failed to handle p2p RPC error=invalid epoch peer=16Uiu2HAmDstiv2UPX3pRgnTWuVgfoDZvkaUp7jbfoVi43nGsPt6P topic=/eth2/beacon_chain/req/status/1/ssz_snappy
```

**What version of Prysm are you running? (Which release)**

baf9ec60eb3ad308f0d587710209d7f35a8dd985

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

- [x] Feature Addition

**What does this PR do? Why is it needed?**

- [x] We now verify the provided finalized epoch with the finalized root. This involved reading
and finalized blocks and its relevant child blocks and verifying that their respective slots match up.

**Which issues(s) does this PR fix?**

Fixes #5827 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/sync/rpc_status.go [hunk 1]
```diff
@@ -312,7 +312,30 @@ func (s *Service) validateStatusMessage(ctx context.Context, msg *pb.Status) err
 	if blk == nil {
 		return errGeneric
 	}
-	// TODO(#5827) Verify the finalized block with the epoch in the
-	// status message
-	return nil
+	if helpers.SlotToEpoch(blk.Block.Slot) == msg.FinalizedEpoch {
```
Comment (terencechain) [inline beacon-chain/sync/rpc_status.go:315]: Tests for these new chunk of code?

**Review by terencechain — COMMENTED** [review]
Looks good. Just one comment on test

File: beacon-chain/db/kv/finalized_block_roots.go [hunk 2]
```diff
@@ -178,3 +178,37 @@ func (kv *Store) IsFinalizedBlock(ctx context.Context, blockRoot [32]byte) bool
...
+		enc := tx.Bucket(blocksBucket).Get(ctr.ChildRoot)
+		if enc == nil {
+			return nil
+		}
+		blk = &ethpb.SignedBeaconBlock{}
+		return decode(ctx, enc, blk)
+	})
+	if err != nil {
+		traceutil.AnnotateError(span, err)
+	}
```
Comment (prestonvanloon) [inline beacon-chain/db/kv/finalized_block_roots.go:212]:
```suggestion
	traceutil.AnnotateError(span, err)
```
AnnotateError is a no-op if err is nil, no need to check here

**Review by terencechain — APPROVED** [review]
