### PR TITLE
Fix for Proposer Bug

### LINKED ISSUE #277: Proposer Is Creating Collation For Every Received Transaction
This should be batching transactions into a transaction pool.

https://github.com/prysmaticlabs/geth-sharding/blob/b883562e12344c7eeab25b5fb24133fc820b6f05/sharding/proposer/service.go#L80-L101

Please wait for #222 to be merged as there will be some changes to the p2p message types.

### PR DESCRIPTION
**Pull request by nisdas**
This will address and close #277 
### Requirements for Merge
- [x] Batch transactions into a collation, instead of sending out a collation for every Transaction
- [x] Also create collations every period to account for unfull collations and low tx volume shards
- [x] Test for making sure bug is fixed
- [x] Test for making sure a collation is sent every new period

### CODE REVIEW

File: client/proposer/service.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ import (
 // sharding/service.go.
 type Proposer struct {
 	config    *params.Config
-	client    *mainchain.SMCClient
+	client    mainchain.FullClient
```
Comment (terenc3t) [inline client/proposer/service.go]: Is there a reason you are not using `*`?

File: client/proposer/service.go [hunk 2]
```diff
@@ -83,20 +83,35 @@ func (p *Proposer) proposeCollations() {
...
 			if !ok {
 				log.Error("Received incorrect p2p message. Wanted a transaction broadcast message")
 				break
 			}
 			// log.Debugf("Received transaction: %x", tx)
-			if err := p.createCollation(p.ctx, []*gethTypes.Transaction{legacyutil.TransformTransaction(tx)}); err != nil {
-				log.Errorf("Create collation failed: %v", err)
+			gethtx := legacyutil.TransformTransaction(tx)
+
+			if (sizeOfCollation + int64(gethtx.Size())) > types.CollationSizelimit {
```
Comment (terenc3t) [inline client/proposer/service.go]: I'm not sure if this will work. I don't think we are not considering the `indicatorByte` but only the `dataByte`. `CollationSizelimit` is checked after we serialize and pad in first byte as `indicatorByte` right?

File: client/proposer/service_test.go [hunk 3]
```diff
@@ -2,16 +2,79 @@ package proposer
...
+	"github.com/prysmaticlabs/prysm/client/mainchain"
+	"github.com/prysmaticlabs/prysm/client/p2p"
 	"github.com/prysmaticlabs/prysm/client/params"
+	"github.com/prysmaticlabs/prysm/client/txpool"
+	"github.com/prysmaticlabs/prysm/client/types"
+	pb "github.com/prysmaticlabs/prysm/proto/sharding/v1"
+	logTest "github.com/sirupsen/logrus/hooks/test"
 )
 
+func TestProposeCollation(t *testing.T) {
```
Comment (terenc3t) [inline client/proposer/service_test.go]: 2 feedback here:
1.) we are not calling `proposeCollations `, can we make sure we call it and test that using channels? it's similar to what we did in simulator and sync tests
2.) we are not testing `(sizeOfCollation + int64(gethtx.Size())) > types.CollationSizelimit` Can we add a test scenario where the `collation` is right before full?

File: client/proposer/service.go (hunk 1 above)
Comment (rauljordan) [reply client/proposer/service.go]: It's an interface

File: client/types/collation.go [hunk 4]
```diff
@@ -42,7 +42,7 @@ type collationHeaderData struct {
 	ProposerSignature [32]byte        // the proposer's signature for calculating collation hash.
 }
 
-var collationSizelimit = int64(math.Pow(float64(2), float64(20)))
+var CollationSizelimit = int64(math.Pow(float64(2), float64(20)))
```
Comment (rauljordan) [inline client/types/collation.go]: CollationSizeLimit*

File: client/proposer/service.go (hunk 1 above)
Comment (terenc3t) [reply client/proposer/service.go]: Oops. My bad for missing that.

File: client/proposer/service.go (hunk 2 above)
Comment (nisdas) [reply client/proposer/service.go]: Ahh , yeah missed that part. But then in order to carry out the check I would have to serialize the transactions and check the size of the blob. If we have to do it every time a transaction is received , it would be very expensive just to make sure the collation is in the size limit.

Comment (terenc3t) [reply client/proposer/service.go]: I agree. Since this will be replaced by a `tx_pool`let's not spend too much time. Can we please make sure `(sizeOfCollation + int64(gethtx.Size())) > types.CollationSizelimit` doesn't fail e2e? (i.e.: try running a proposer node and a simulator node)

File: client/proposer/service_test.go (hunk 3 above)
Comment (nisdas) [reply client/proposer/service_test.go]: 1) hey so `proposer.Start()` actually spawns off a goroutine which calls `proposeCollations` , so the method is being tested. Maybe TestProposeCollation is not the best name for it since we are proposing, creating and saving collations to the shardDB. Its more like a roundtrip test. 
We can use channels to test the broadacast and subscription of transactions through the p2p feed. 
2) Alright I will add another test scenario for that

File: client/proposer/service.go [hunk 5]
```diff
@@ -87,20 +87,35 @@ func (p *Proposer) proposeCollations() {
...
 	sub := feed.Subscribe(ch)
+	collation := []*gethTypes.Transaction{}
+	sizeOfCollation := int64(0)
+
 	defer sub.Unsubscribe()
 	defer close(ch)
 	for {
 		select {
 		case msg := <-ch:
+			log.Info("tx received")
```
Comment (prestonvanloon) [inline client/proposer/service.go]: debug?

Comment (prestonvanloon) [reply client/proposer/service.go]: This is also on line 104, but commented out.

File: client/proposer/service.go [hunk 6]
```diff
@@ -97,10 +104,29 @@ func (p *Proposer) proposeCollations() {
...
-			if err := p.createCollation(p.ctx, []*gethTypes.Transaction{legacyutil.TransformTransaction(tx)}); err != nil {
-				log.Errorf("Create collation failed: %v", err)
+			log.Debugf("Received transaction: %x", tx)
+			gethtx := legacyutil.TransformTransaction(tx)
+			currentperiod, err := p.currentPeriod(p.ctx)
+			if err != nil {
+				log.Errorf("Unable to get current period: %v", err)
+			}
+
+			if (sizeOfCollation+int64(gethtx.Size())) > types.CollationSizeLimit || period.Cmp(currentperiod) != 0 {
```
Comment (rauljordan) [inline client/proposer/service.go]: Maybe add a quick comment or two explaining why we're doing this - will be very helpful to someone that has no context of this file in the future
