### PR TITLE
Validator-multiple key

### LINKED ISSUE #2025: Validator: performing for multiple keys
The current validator design is rather simple for a single private key: the validator requests assignments, waits for slot to perform task, then performs the appropriate task. In order to optimize resources for a testnet deployment, we could enable a validator to perform tasks for multiple signing keys.

## proto/beacon/rpc/v1/services.proto

The validator RPC service must be updated to support assignment requests for multiple public keys.

```protobuf

 service ValidatorService {
     rpc WaitForActivation(ValidatorActivationRequest) returns (stream ValidatorActivationResponse);
     rpc ValidatorIndex(ValidatorIndexRequest) returns (ValidatorIndexResponse);
-    rpc CommitteeAssignment(ValidatorEpochAssignmentsRequest) returns (CommitteeAssignmentResponse);
+    rpc CommitteeAssignment(CommitteeAssignmentsRequest) returns (CommitteeAssignmentResponse);
     rpc ValidatorStatus(ValidatorIndexRequest) returns (ValidatorStatusResponse);
 }

-message ValidatorEpochAssignmentsRequest {
+message CommitteeAssignmentRequest {
    uint64 epoch_start = 1;
-    bytes public_key = 2;
+    repeated bytes public_key = 2;
}

message CommitteeAssignmentResponse {
-    repeated uint64 committee = 1;
-    uint64 shard = 2;
-    uint64 slot = 3;
-    bool is_proposer = 4;
+    repeated CommitteeAssignment assignment = 1;
+
+    message CommitteeAssignment {
+      repeated uint64 committee = 1;
+      uint64 shard = 2;
+      uint64 slot = 3;
+      bool is_proposer = 4;
+      bytes public_key = 5;
+      ValidatorStatus status = 6;
+   }
 }

```

Example request:
```pbtxt
epoch_start: 960
public_key: pk1
public_key: pk2
public_key: pk3
```

Example response
```pbtxt
assignment {
  committee: 16
  committee: 17
  shard: 143
  slot: 963
  is_proposer: true
  public_key: pk1
  status: ACTIVE
}
assignment {
   public_key: pk2
   status: PENDING_ACTIVE 
}
assignment {
   public_key: pk3
   status: UNKNOWN
}
```

The key differences here are that we also return some information about the status of the validator since they may be in different states. The validator should remove any validator key, from future requests, with status `EXITED` or `EXITED_SLASHED`. 

## validator/accounts/account.go & shared/keystore/keystore.go

The current implementation is that the accounts directory consists of a single set of validator keys (signing key and withdrawal key). We need to adapt new scheme where there may exist multiple key pairs. The most basic scheme would be to have some keystore directory where each valid file present in the directory acts as a signing key or withdrawal key. 

The changes required here are 
- Creating a new account should allow multiple accounts
- Keystore should provide list of keys where the validator key filename is abstracted or not known by the service requesting the key. ([link](https://github.com/prysmaticlabs/prysm/blob/d1b664852f90e968a557ef8fce2b43ce79313741/validator/client/service.go#L45) to current behavior)

## validator/client/service.go

The validator service should use all keys provided by the keystore instead of a single key. This set of keys will be used to request assignments and perform behavior.

## validator/client/validator.go -- WaitForActivation

This method should send a list of public keys where the server will return an activation stream event when any of the keys are activated. This provides a nice user experience when none of the keys have been activated; we wouldn't want to be requesting assignments where the validator client appears to be doing something but it is really waiting for activation. 

```protobuf
message ValidatorActivationRequest {
-    bytes pubkey = 1;
+    repeated bytes public_key = 1;
}
```

Since the response is a no-op for the validator (other than logging for user), we could emit an empty message as a signal that _some_ validator in the list has been activated OR return a list of public_key that we know are activated. 

```protobuf
message ValidatorActivationResponse {
-    ethereum.beacon.p2p.v1.Validator validator = 1;
+    repeated bytes activated_public_key = 1;
}
```

## validator/client/validator.go -- UpdateAssignments

The [validator.assignment](https://github.com/prysmaticlabs/prysm/blob/d1b664852f90e968a557ef8fce2b43ce79313741/validator/client/validator.go#L32) should be changed from a single assignment to a list of assignments for the given epoch. Only active assignments should be assigned to this assignments list. 

## validator/client/runner.go 

With a multiple key design, the first difference in the runner is a change in the validator interface for `RoleAt`, `AttestToBlockHead` and `ProposeBlock`. 

```go
type Validator interface {
	Done()
	WaitForChainStart(ctx context.Context) error
	WaitForActivation(ctx context.Context) error
	NextSlot() <-chan uint64
	UpdateAssignments(ctx context.Context, slot uint64) error
-	RoleAt(slot uint64) pb.ValidatorRole
+	RolesAt(slot uint64) map[uint64]pb.ValidatorRole // validatorIndex -> role
-	AttestToBlockHead(ctx context.Context, slot uint64)
+	AttestToBlockHead(ctx context.Context, validatorIndex uint64, slot uint64)
-	ProposeBlock(ctx context.Context, slot uint64)
+	ProposeBlock(ctx context.Context, validatorIndex uint64, slot uint64)
}
```

Then the main routine of the runner is essentially the same.

```go
for vIdx, role := range roles {
  // same behavior, with additional validator index argument to attest/propose 
  // proposing/attesting should be done in a separate goroutine so not to block performing work
  // for other validator indices
}
```

Given that `RolesAt` returns a map instead of a Role enum value, we can return an empty map when there are no assignments and provide a better user message. 

```go
if len(roles) == 0 {
  log.WithField("slot", slot - params.BeaconConfig().GenesisSlot).Info("No assignments, doing nothing")
}
```

This is much better than the [UNKNOWN enum log](https://github.com/prysmaticlabs/prysm/blob/d1b664852f90e968a557ef8fce2b43ce79313741/validator/client/runner.go#L72-L75), which really shouldn't be exposed to the user. 

## Working on this in parallel

I envision this work being broken up into the following PRs

- [x] Update RPC proto definitions, implement server side and client side to perform the same behavior. I.e. the client should only accept the first response in a list of assignments
- [x] Update validator accounts creation and keystore to support multiple keys
- [ ] Update the validator client to perform the new behavior with multiple roles

The first two tasks can be worked independently, while the third task connects it all together.

### PR DESCRIPTION
**Pull request by shayzluf**
Resolves #2025

---

# Let Validator validate multiple keys as an attester and as a proposer
Merge two preliminary steps : 
- Update RPC proto definitions, implement server side and client side to perform the same behavior. 
   I.e. the client should only accept the first response in a list of assignments
- Update validator accounts creation and keystore to support multiple keys

implement:
Update the validator client to perform the new behavior with multiple roles

### CODE REVIEW

File: beacon-chain/db/validator.go [hunk 1]
```diff
@@ -72,9 +72,29 @@ func (db *BeaconDB) DeleteValidatorIndex(pubKey []byte) error {
 	})
 }
 
+// HasValidators checks if a validator index map exists out of a list of public keys.
+func (db *BeaconDB) HasValidators(pubKeys [][]byte) bool {
```
Comment (nisdas) [inline beacon-chain/db/validator.go]: You do multiple reads here for checking if there are multiple validators, this can be done in a single read.

File: beacon-chain/rpc/validator_server.go [hunk 2]
```diff
@@ -28,36 +28,36 @@ type ValidatorServer struct {
 // beacon state, if not, then it creates a stream which listens for canonical states which contain
 // the validator with the public key as an active validator record.
 func (vs *ValidatorServer) WaitForActivation(req *pb.ValidatorActivationRequest, stream pb.ValidatorService_WaitForActivationServer) error {
-	if vs.beaconDB.HasValidator(req.Pubkey) {
+	if vs.beaconDB.HasValidators(req.PublicKey) {
```
Comment (nisdas) [inline beacon-chain/rpc/validator_server.go]: `req.PublickKeys`

Comment (nisdas) [reply beacon-chain/rpc/validator_server.go]: if one validator doesnt exist, this whole method fails ?

File: beacon-chain/rpc/validator_server.go [hunk 3]
```diff
@@ -208,3 +208,16 @@ func (vs *ValidatorServer) retrieveActiveValidator(beaconState *pbp2p.BeaconStat
 	}
 	return beaconState.ValidatorRegistry[validatorIdx], nil
 }
+
+func (vs *ValidatorServer) retrieveActiveValidators(beaconState *pbp2p.BeaconState, pubkeys [][]byte) ([][]byte, error) {
+	v := [][]byte{}
+	for _, pk := range pubkeys {
+		_, err := vs.beaconDB.ValidatorIndex(pk)
```
Comment (nisdas) [inline beacon-chain/rpc/validator_server.go]: Maybe create a db method to return multiple validators ? That way we only have to do one read

File: proto/beacon/rpc/v1/services.proto [hunk 4]
```diff
@@ -50,11 +50,11 @@ message ValidatorPerformanceResponse {
 }
 
 message ValidatorActivationRequest {
-    bytes pubkey = 1;
+    repeated bytes public_key = 1;
```
Comment (nisdas) [inline proto/beacon/rpc/v1/services.proto]: `public_keys`

File: shared/keystore/keystore.go [hunk 5]
```diff
@@ -80,6 +81,37 @@ func (ks Store) GetKey(filename, password string) (*Key, error) {
...
+	if err != nil {
+		return nil, err
+	}
+	keys := make(map[string]*Key)
+	i := 0
+	for _, f := range files {
+		n := f.Name()
+		filePath := filepath.Join(directory, n)
+		filePath = filepath.Clean(filePath)
+		if f.Mode().IsRegular() && strings.Contains(n, strings.TrimPrefix(fileprefix, "/")) {
```
Comment (nisdas) [inline shared/keystore/keystore.go]: this condition is hard to parse in a read, maybe assign a variable to this `strings.Contains(n, strings.TrimPrefix(fileprefix, "/"))` above

File: shared/keystore/keystore.go [hunk 6]
```diff
@@ -80,6 +81,37 @@ func (ks Store) GetKey(filename, password string) (*Key, error) {
...
+			keyjson, err := ioutil.ReadFile(filePath)
+			if err != nil {
+				return nil, err
+			}
+			key, err := DecryptKey(keyjson, password)
+			if err != nil {
+				return nil, err
+			}
+			keys[hex.EncodeToString(key.PublicKey.Marshal())] = key
+			i++
```
Comment (nisdas) [inline shared/keystore/keystore.go]: what is the point of the i ?

File: validator/accounts/account.go [hunk 7]
```diff
@@ -39,13 +40,10 @@ func VerifyAccountNotExists(directory string, password string) error {
...
-	// one keystore per validator client.
-	if err := VerifyAccountNotExists(directory, password); err != nil {
-		return fmt.Errorf("validator account exists: %v", err)
-	}
-	shardWithdrawalKeyFile := directory + params.BeaconConfig().WithdrawalPrivkeyFileName
-	validatorKeyFile := directory + params.BeaconConfig().ValidatorPrivkeyFileName
+	t := time.Now()
+
+	shardWithdrawalKeyFile := directory + params.BeaconConfig().WithdrawalPrivkeyFileName + t.Format("20060102150405")
+	validatorKeyFile := directory + params.BeaconConfig().ValidatorPrivkeyFileName + t.Format("20060102150405")
```
Comment (nisdas) [inline validator/accounts/account.go]: not sure what is the point of this `t.Format("20060102150405")`

File: validator/client/runner.go [hunk 8]
```diff
@@ -66,24 +67,32 @@ func run(ctx context.Context, v Validator) {
 				handleAssignmentError(err, slot)
 				continue
 			}
-			role := v.RoleAt(slot)
+			var wg sync.WaitGroup
```
Comment (nisdas) [inline validator/client/runner.go]: any reason to use a wait group here  ? after exiting from performing their roles the validators do not do anything else. If one validator is blocked in performing its role then all the validators will be held up and might skip the next slot.

File: validator/client/validator.go [hunk 9]
```diff
@@ -76,14 +76,18 @@ func (v *validator) WaitForChainStart(ctx context.Context) error {
 func (v *validator) WaitForActivation(ctx context.Context) error {
 	ctx, span := trace.StartSpan(ctx, "validator.WaitForActivation")
 	defer span.End()
+	pks := [][]byte{}
+	for _, key := range v.keys {
+		pks = append(pks, key.PublicKey.Marshal())
+	}
 	req := &pb.ValidatorActivationRequest{
-		Pubkey: v.key.PublicKey.Marshal(),
+		PublicKey: pks,
```
Comment (nisdas) [inline validator/client/validator.go]: `PublickKeys`

File: validator/client/validator.go [hunk 10]
```diff
@@ -116,63 +123,73 @@ func (v *validator) NextSlot() <-chan uint64 {
...
 	resp, err := v.validatorClient.CommitteeAssignment(ctx, req)
 	if err != nil {
-		v.assignment = nil // Clear assignments so we know to retry the request.
+		v.assignments = nil // Clear assignments so we know to retry the request.
 		return err
 	}
 
-	v.assignment = resp
+	v.assignments = resp
+	for i := range v.assignments.Assignment {
```
Comment (nisdas) [inline validator/client/validator.go]: why not use this way ?
```go 
for i,assignment := range v.assignments.Assignment {

```
would not need to be so verbose below

File: validator/client/validator.go [hunk 11]
```diff
@@ -116,63 +123,73 @@ func (v *validator) NextSlot() <-chan uint64 {
...
+		var proposerSlot uint64
+		var attesterSlot uint64
+		if v.assignments.Assignment[i].IsProposer && len(v.assignments.Assignment[i].Committee) == 1 {
+			proposerSlot = resp.Assignment[i].Slot
```
Comment (nisdas) [inline validator/client/validator.go]: you can use my suggestion above and do this 
```go
proposerSlot = assingment.Slot
```
same below

File: beacon-chain/db/validator.go (hunk 1 above)
Comment (shayzluf) [reply beacon-chain/db/validator.go]: Thanks

File: beacon-chain/rpc/validator_server.go (hunk 2 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: HasValidators returns true if one validator exists

File: beacon-chain/rpc/validator_server.go (hunk 3 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: done

File: proto/beacon/rpc/v1/services.proto (hunk 4 above)
Comment (shayzluf) [reply proto/beacon/rpc/v1/services.proto]: done

File: shared/keystore/keystore.go (hunk 6 above)
Comment (shayzluf) [reply shared/keystore/keystore.go]: leftover from older code

removed

File: validator/accounts/account.go (hunk 7 above)
Comment (shayzluf) [reply validator/accounts/account.go]: to create multiple validators and withdrawal keys in the same directory while not running over each other and time stamping them

File: validator/client/runner.go (hunk 8 above)
Comment (shayzluf) [reply validator/client/runner.go]: maybe we should have an indicator if the validators task take more than a slot time. I think we should finish all tasks that was assigned before proceeding

File: validator/client/validator.go (hunk 10 above)
Comment (shayzluf) [reply validator/client/validator.go]: done , thanks

File: validator/client/runner.go (hunk 8 above)
Comment (prestonvanloon) [reply validator/client/runner.go]: Please remove the waitgroup

File: validator/client/runner.go [hunk 12]
```diff
@@ -69,22 +70,29 @@ func run(ctx context.Context, v Validator) {
...
+			for idx, role := range v.RolesAt(slot) {
+				wg.Add(1)
+				go func(rol pb.ValidatorRole, id string) {
+					defer wg.Done()
+					switch rol {
```
Comment (prestonvanloon) [inline validator/client/runner.go]:
```suggestion
					switch role {
```

File: validator/client/runner.go [hunk 13]
```diff
@@ -69,22 +70,29 @@ func run(ctx context.Context, v Validator) {
 				handleAssignmentError(err, slot)
 				continue
 			}
-			role := v.RoleAt(slot)
+			var wg sync.WaitGroup
+			for idx, role := range v.RolesAt(slot) {
```
Comment (prestonvanloon) [inline validator/client/runner.go]:
```suggestion
			for id, role := range v.RolesAt(slot) {
```

File: validator/client/runner.go [hunk 14]
```diff
@@ -69,22 +70,29 @@ func run(ctx context.Context, v Validator) {
...
-				v.ProposeBlock(slotCtx, slot)
-				v.AttestToBlockHead(slotCtx, slot)
-			case pb.ValidatorRole_UNKNOWN:
-				log.WithFields(logrus.Fields{
-					"slot": slot - params.BeaconConfig().GenesisSlot,
-					"role": role,
-				}).Info("No active assignment, doing nothing")
-			default:
-				// Do nothing :)
+				}(role, idx)
```
Comment (prestonvanloon) [inline validator/client/runner.go]:
```suggestion
				}(role, id)
```

File: validator/client/validator_test.go [hunk 15]
```diff
@@ -142,21 +150,23 @@ func TestWaitActivation_ContextCanceled(t *testing.T) {
...
+			PublicKeys: publicKeys(v.keys),
 		},
 	).Return(clientStream, nil)
 	clientStream.EXPECT().Recv().Return(
 		&pb.ValidatorActivationResponse{
-			Validator: &pbp2p.Validator{
-				ActivationEpoch: params.BeaconConfig().GenesisEpoch,
-			},
+			ActivatedPublicKeys: publicKeys(v.keys),
+			// Validator: &pbp2p.Validator{
```
Comment (prestonvanloon) [inline validator/client/validator_test.go]: Why comment this out?

File: validator/client/validator_test.go [hunk 16]
```diff
@@ -226,21 +236,54 @@ func TestWaitActivation_LogsActivationEpochOK(t *testing.T) {
...
```
Comment (prestonvanloon) [inline validator/client/validator_test.go]: Why commented this out?

File: validator/client/validator_test.go [hunk 17]
```diff
@@ -226,21 +236,54 @@ func TestWaitActivation_LogsActivationEpochOK(t *testing.T) {
...
+	client.EXPECT().WaitForActivation(
+		gomock.Any(),
+		&pb.ValidatorActivationRequest{
+			PublicKeys: publicKeys(v.keys),
+		},
+	).Return(clientStream, nil)
+	clientStream.EXPECT().Recv().Return(
+		&pb.ValidatorActivationResponse{
+			ActivatedPublicKeys: publicKeys(v.keys),
+			// Validator: &pbp2p.Validator{
```
Comment (prestonvanloon) [inline validator/client/validator_test.go]: Here too

File: validator/client/runner.go (hunk 8 above)
Comment (shayzluf) [reply validator/client/runner.go]: done

File: validator/client/runner.go (hunk 12 above)
Comment (shayzluf) [reply validator/client/runner.go]: done

File: validator/client/runner.go (hunk 13 above)
Comment (shayzluf) [reply validator/client/runner.go]: done

File: validator/client/validator_test.go (hunk 15 above)
Comment (shayzluf) [reply validator/client/validator_test.go]: I wasn't sure it will work with only a list of public keys so i commented it out . forgot to remove it after it all worked out.

Thanks

File: validator/client/runner.go (hunk 14 above)
Comment (shayzluf) [reply validator/client/runner.go]: done

File: validator/client/validator.go [hunk 18]
```diff
@@ -97,53 +129,76 @@ func (v *validator) SlotDeadline(slot uint64) time.Time {
...
+		v.assignments = nil // Clear assignments so we know to retry the request.
 		return err
 	}
 
-	v.assignment = resp
+	v.assignments = resp
+	for _, assignment := range v.assignments.Assignment {
+		var proposerSlot uint64
+		var attesterSlot uint64
+		if assignment.IsProposer && len(assignment.Committee) == 1 {
```
Comment (terenc3t) [inline validator/client/validator.go]: this is no longer relevant, please check the latest `validator/client/validator.go` for reference

File: validator/accounts/account.go [hunk 19]
```diff
@@ -39,13 +40,10 @@ func VerifyAccountNotExists(directory string, password string) error {
...
-	// First, if the keystore already exists, throws an error as there can only be
-	// one keystore per validator client.
-	if err := VerifyAccountNotExists(directory, password); err != nil {
-		return fmt.Errorf("validator account exists: %v", err)
-	}
-	shardWithdrawalKeyFile := directory + params.BeaconConfig().WithdrawalPrivkeyFileName
-	validatorKeyFile := directory + params.BeaconConfig().ValidatorPrivkeyFileName
+	t := time.Now()
+
+	shardWithdrawalKeyFile := directory + params.BeaconConfig().WithdrawalPrivkeyFileName + t.Format("20060102150405")
```
[the remark this answers is not in the document]
Comment (shayzluf) [reply validator/accounts/account.go]: readable and short current time. to be able to create multiple keys with the same prefix 
https://stackoverflow.com/questions/20234104/how-to-format-current-time-using-a-yyyymmddhhmmss-format

File: beacon-chain/db/validator.go [hunk 20]
```diff
@@ -63,6 +63,31 @@ func (db *BeaconDB) ValidatorIndex(pubKey []byte) (uint64, error) {
 	return index, err
 }
 
+// ValidatorsIndexes accepts a slice of public keys and returns the corresponding slice of validators indexs.
```
[the remark this answers is not in the document]
Comment (shayzluf) [reply beacon-chain/db/validator.go]: done

File: beacon-chain/rpc/validator_server.go [hunk 21]
```diff
@@ -163,3 +197,23 @@ func (vs *ValidatorServer) ValidatorStatus(
...
+func (vs *ValidatorServer) retrieveActiveValidator(beaconState *pbp2p.BeaconState, pubkey []byte) (*pbp2p.Validator, error) {
+	validatorIdx, err := vs.beaconDB.ValidatorIndex(pubkey)
+	if err != nil {
+		return nil, fmt.Errorf("could not retrieve validator index: %v", err)
+	}
+	return beaconState.ValidatorRegistry[validatorIdx], nil
+}
+
+func (vs *ValidatorServer) retrieveActiveValidators(pubkeys [][]byte) ([][]byte, error) {
+	m, err := vs.beaconDB.ValidatorsIndexes(pubkeys)
```
[the remark this answers is not in the document]
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: I am trying to get the active validators. as I understand validators has index only if they are active

File: validator/accounts/account_test.go [hunk 22]
```diff
@@ -21,8 +22,15 @@ func TestNewValidatorAccount_AccountExists(t *testing.T) {
...
 		t.Fatalf("Unable to store key %v", err)
 	}
-	if err := NewValidatorAccount(directory, ""); err == nil {
-		t.Error("Expected new validator account to throw error, received nil")
+	if err := NewValidatorAccount(directory, ""); err != nil {
+		t.Errorf("Should support multiple keys: %v", err)
+	}
+	files, _ := ioutil.ReadDir(directory)
+	if len(files) != 3 {
+		t.Errorf("multiple validators wasn't created only: %v files in directory", len(files))
```
[the remark this answers is not in the document]
Comment (shayzluf) [reply validator/accounts/account_test.go]: thanks

File: beacon-chain/rpc/validator_server.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (nisdas) [reply beacon-chain/rpc/validator_server.go]: that is not correct. they may not be activated yet,etc. You have to do another round of filtering to find  the active validators.

File: beacon-chain/db/validator.go [hunk 23]
```diff
@@ -63,6 +63,31 @@ func (db *BeaconDB) ValidatorIndex(pubKey []byte) (uint64, error) {
...
+func (db *BeaconDB) ValidatorsIndexes(pubKeys [][]byte) (map[uint64][]byte, error) {
+	m := make(map[uint64][]byte)
+	if !db.HasValidators(pubKeys) {
```
[the remark this answers is not in the document]
Comment (nisdas) [reply beacon-chain/db/validator.go]: +1

File: beacon-chain/rpc/validator_server.go (hunk 2 above)
Comment (nisdas) [reply beacon-chain/rpc/validator_server.go]: that doesnt sound right, if out of 10 only one existing would be a failure. it should only return true if all the validator exist. If some validators do not exist you could return false and those validators pubkey.

File: validator/accounts/account.go (hunk 7 above)
Comment (nisdas) [reply validator/accounts/account.go]: is there a better way to mark them, maybe use the pubkey as the suffix ? Having the time doesnt help in differentiating them.

File: validator/client/validator.go [hunk 24]
```diff
@@ -74,10 +75,41 @@ func (v *validator) WaitForChainStart(ctx context.Context) error {
...
+		if ctx.Err() == context.Canceled {
+			return head, fmt.Errorf("context has been canceled so shutting down the loop: %v", ctx.Err())
+		}
+		if err != nil {
+			return head, fmt.Errorf("could not receive validator activation from stream: %v", err)
+		}
+		validatorActivatedRecords = res.ActivatedPublicKeys
+		break
+	}
+	for pk := range validatorActivatedRecords {
```
[the remark this answers is not in the document]
Comment (shayzluf) [reply validator/client/validator.go]: my mistake
Fixed

[the remark this answers is not in the document]
Comment (shayzluf) [reply validator/client/validator.go]: thanks

File: beacon-chain/rpc/validator_server.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: done

File: validator/accounts/account.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (shayzluf) [reply validator/accounts/account.go]: changed to 12 first chars of public key hex

File: beacon-chain/rpc/validator_server.go (hunk 2 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: made it to return true only if all the validators exists

File: beacon-chain/db/validator.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (shayzluf) [reply beacon-chain/db/validator.go]: done

File: validator/client/validator.go (hunk 18 above)
Comment (shayzluf) [reply validator/client/validator.go]: done

Comment (prestonvanloon) [reply validator/client/validator.go]: This is still wrong. Please fix. 

A validator should always attest, whether or not they are a proposer.

File: beacon-chain/db/validator.go [hunk 25]
```diff
@@ -72,9 +97,32 @@ func (db *BeaconDB) DeleteValidatorIndex(pubKey []byte) error {
 	})
 }
 
+// HasValidators checks if a validator index map exists out of a list of public keys.
+func (db *BeaconDB) HasValidators(pubKeys [][]byte) (bool, [][]byte) {
```
Comment (prestonvanloon) [inline beacon-chain/db/validator.go]: Why does this return a `[][]byte`?

Comment (shayzluf) [reply beacon-chain/db/validator.go]: It was a suggestion in one of the review comments to return true or false and a list of validators public keys that haven't been found

File: validator/client/validator.go (hunk 18 above)
Comment (shayzluf) [reply validator/client/validator.go]: fixed. Thanks

File: validator/accounts/account_test.go [hunk 26]
```diff
@@ -27,7 +27,7 @@ func TestNewValidatorAccount_AccountExists(t *testing.T) {
 	}
 	files, _ := ioutil.ReadDir(directory)
 	if len(files) != 3 {
-		t.Errorf("multiple validators wasn't created only: %v files in directory", len(files))
+		t.Errorf("multiple validators wasn't created only %v files in directory", len(files))
```
Comment (rauljordan) [inline validator/accounts/account_test.go]:
```suggestion
		t.Errorf("multiple validators were not created created, only %v files in directory", len(files))
```

File: validator/client/validator.go [hunk 27]
```diff
@@ -135,53 +142,74 @@ func (v *validator) SlotDeadline(slot uint64) time.Time {
 // beginning of a new epoch.
 func (v *validator) UpdateAssignments(ctx context.Context, slot uint64) error {
 	// Testing run time for fetching every slot. This is not meant for production!
-	if slot%params.BeaconConfig().SlotsPerEpoch != 0 && v.assignment != nil && false {
+	if slot%params.BeaconConfig().SlotsPerEpoch != 0 && v.assignments != nil {
```
Comment (rauljordan) [inline validator/client/validator.go]: Do not remove the `false` here, we want to request assignments every slot in case of reorgs for now @shayzluf

Comment (shayzluf) [reply validator/client/validator.go]: should i comment TestUpdateAssignments_DoesNothingWhenNotEpochStartAndAlreadyExistingAssignments
as it fails

Comment (shayzluf) [reply validator/client/validator.go]: commented it

File: beacon-chain/db/validator.go (hunk 25 above)
Comment (prestonvanloon) [reply beacon-chain/db/validator.go]: It looks like you never use it and it doesn’t fit with the Boolean name “HasValidators”. Please remove

Comment (shayzluf) [reply beacon-chain/db/validator.go]: removed

File: validator/client/validator.go [hunk 28]
```diff
@@ -135,53 +142,74 @@ func (v *validator) SlotDeadline(slot uint64) time.Time {
...
 			// Note: A proposer also attests to the slot.
-			return pb.ValidatorRole_PROPOSER
+			if assignment.IsProposer {
+				role = pb.ValidatorRole_PROPOSER
+			} else {
+				role = pb.ValidatorRole_ATTESTER
+			}
 		}
-		return pb.ValidatorRole_ATTESTER
+		role = pb.ValidatorRole_UNKNOWN
```
Comment (prestonvanloon) [inline validator/client/validator.go]: This sets the role to be UNKNOWN every time

File: validator/client/validator_test.go [hunk 29]
```diff
@@ -287,16 +293,73 @@ func TestCanonicalHeadSlot_OK(t *testing.T) {
...
+// 		},
+// 	}
+// 	client.EXPECT().CommitteeAssignment(
+// 		gomock.Any(),
+// 		gomock.Any(),
+// 	).Times(0)
+
+// 	if err := v.UpdateAssignments(context.Background(), slot); err != nil {
+// 		t.Errorf("Could not update assignments: %v", err)
+// 	}
```
Comment (prestonvanloon) [inline validator/client/validator_test.go]: Why is this commented out? Please fix

File: beacon-chain/db/validator.go [hunk 30]
```diff
@@ -72,9 +97,29 @@ func (db *BeaconDB) DeleteValidatorIndex(pubKey []byte) error {
 	})
 }
 
+// HasValidators checks if a validator index map exists out of a list of public keys.
```
Comment (prestonvanloon) [inline beacon-chain/db/validator.go]: Please update this comment. This method returns true if any of the pubkeys exist in the database.

File: beacon-chain/db/validator.go [hunk 31]
```diff
@@ -61,6 +61,31 @@ func (db *BeaconDB) ValidatorIndex(pubKey []byte) (uint64, error) {
 	return index, err
 }
 
+// ValidatorIndices accepts a slice of public keys and returns the corresponding map of validators indexes and public keys.
+func (db *BeaconDB) ValidatorIndices(pubKeys [][]byte) (map[uint64][]byte, error) {
+	m := make(map[uint64][]byte)
+	if !db.HasValidators(pubKeys) {
+		return m, fmt.Errorf("one or more of the validators\n%#x\ndoes not exist", pubKeys)
```
Comment (prestonvanloon) [inline beacon-chain/db/validator.go]: Please don't use newlines in error message

File: beacon-chain/rpc/validator_server.go [hunk 32]
```diff
@@ -226,3 +218,23 @@ func (vs *ValidatorServer) retrieveActiveValidator(beaconState *pbp2p.BeaconStat
...
+	m, err := vs.beaconDB.ValidatorIndices(pubkeys)
+	if err != nil {
+		return nil, fmt.Errorf("could not retrieve validators indexes: %v", err)
+	}
+	beaconState, err := vs.beaconDB.State(vs.ctx)
+	if err != nil {
+		return nil, fmt.Errorf("could not retrieve beacon state: %v", err)
+	}
+	activeIndices := helpers.ActiveValidatorIndices(beaconState.ValidatorRegistry, beaconState.Slot)
+	v := make([][]byte, 0, len(m))
```
Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]: Shouldn't this be a map of pubkey -> activeIndex?

File: beacon-chain/rpc/validator_server.go [hunk 33]
```diff
@@ -226,3 +218,23 @@ func (vs *ValidatorServer) retrieveActiveValidator(beaconState *pbp2p.BeaconStat
 	}
 	return beaconState.ValidatorRegistry[validatorIdx], nil
 }
+
+func (vs *ValidatorServer) retrieveActiveValidatorsPublicKeys(pubkeys [][]byte) ([][]byte, error) {
```
Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]: Go method naming preference is to avoid "get" "retrieve" "fetch" verbs, simply call this `activePublicKeys(...) ...`

Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]: Please add a comment to this method since it's a bit hard to explain what it does in the method name. 

This method takes a list of validator public keys, filters the active ones, and returns the list of active public keys. Maybe this method is better named "filterActivePublicKeys"? Up to you, but it isn't intuitive as is

File: beacon-chain/rpc/validator_server.go [hunk 34]
```diff
@@ -30,36 +30,28 @@ type ValidatorServer struct {
...
 // the validator with the public key as an active validator record.
 func (vs *ValidatorServer) WaitForActivation(req *pb.ValidatorActivationRequest, stream pb.ValidatorService_WaitForActivationServer) error {
-	if vs.beaconDB.HasValidator(req.Pubkey) {
-		beaconState, err := vs.beaconDB.State(vs.ctx)
-		if err != nil {
-			return fmt.Errorf("could not retrieve beacon state: %v", err)
-		}
-		activeVal, err := vs.retrieveActiveValidator(beaconState, req.Pubkey)
+	if vs.beaconDB.HasValidators(req.PublicKeys) {
+		activeVals, err := vs.retrieveActiveValidatorsPublicKeys(req.PublicKeys)
```
Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]:
```suggestion
		activeKeys, err := vs.retrieveActiveValidatorsPublicKeys(req.PublicKeys)
```

File: beacon-chain/rpc/validator_server.go [hunk 35]
```diff
@@ -226,3 +218,23 @@ func (vs *ValidatorServer) retrieveActiveValidator(beaconState *pbp2p.BeaconStat
 	}
 	return beaconState.ValidatorRegistry[validatorIdx], nil
 }
+
+func (vs *ValidatorServer) retrieveActiveValidatorsPublicKeys(pubkeys [][]byte) ([][]byte, error) {
+	m, err := vs.beaconDB.ValidatorIndices(pubkeys)
+	if err != nil {
+		return nil, fmt.Errorf("could not retrieve validators indexes: %v", err)
+	}
+	beaconState, err := vs.beaconDB.State(vs.ctx)
```
Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]: Please do not use the service context. Require `ctx` as an argument and pass that to `State`

File: validator/client/validator.go [hunk 36]
```diff
@@ -135,53 +142,74 @@ func (v *validator) SlotDeadline(slot uint64) time.Time {
...
+// RolesAt slot returns the validator roles at the given slot. Returns nil if the
+// validator is known to not have a roles at the at slot. Returns UNKNOWN if the
 // validator assignments are unknown. Otherwise returns a valid ValidatorRole.
-func (v *validator) RoleAt(slot uint64) pb.ValidatorRole {
-	if v.assignment == nil {
-		return pb.ValidatorRole_UNKNOWN
-	}
-	if v.assignment.Assignment[0].Slot == slot {
-		if v.assignment.Assignment[0].IsProposer {
+func (v *validator) RolesAt(slot uint64) map[string]pb.ValidatorRole {
```
Comment (prestonvanloon) [inline validator/client/validator.go]: Please add a test for this to prevent future regressions

File: validator/client/validator.go [hunk 37]
```diff
@@ -98,12 +102,15 @@ func (v *validator) WaitForActivation(ctx context.Context) error {
...
-		validatorActivatedRecord = res.Validator
+		validatorActivatedRecords = res.ActivatedPublicKeys
 		break
 	}
-	log.WithFields(logrus.Fields{
-		"activationEpoch": validatorActivatedRecord.ActivationEpoch - params.BeaconConfig().GenesisEpoch,
-	}).Info("Validator activated")
+	for _, pk := range validatorActivatedRecords {
+		log.WithFields(logrus.Fields{
+			"public key": pk,
```
Comment (prestonvanloon) [inline validator/client/validator.go]:
```suggestion
			"public key": fmt.Sprintf("%#x", pk),
```
Otherwise it looks like
```
time="2019-04-04 17:58:25" level=info msg="Validator activated" prefix=validator public key=[131 3 163 192 108 250 67 155 105 246 122 85 3 169 146 17 236 226 147 86 192 18 90 65 255 39 223 223 43 46 236 39 241 67 48 251 116 56 211 118 23 162 6 94 219 6 216 193 16 183 145 6 255 20 2 173 15 68 75 186 163 116 254 72 11 82 157 27 80 14 44 223 87 171 115 127 96 130 147 178 77 89 177 190 148 138 80 78 212 156 227 66 134 180 244 113]
```

File: validator/client/validator.go [hunk 38]
```diff
@@ -135,53 +142,74 @@ func (v *validator) SlotDeadline(slot uint64) time.Time {
...
+		lFields := logrus.Fields{
+			"attesterSlot": attesterSlot - params.BeaconConfig().GenesisSlot,
+			"proposerSlot": "Not proposing",
+			"shard":        assignment.Shard,
+		}
+		if assignment.IsProposer {
+			lFields["proposerSlot"] = proposerSlot - params.BeaconConfig().GenesisSlot
+		}
+
+		log.WithFields(lFields).Info("Updated validator assignments")
```
Comment (prestonvanloon) [inline validator/client/validator.go]: Is there any way this can be improved? It seems this will log for every assignment when it could log once in some sort of map. 

Imagine we are streaming logs to a database, we don't really want 8 entries for a single update of assignments when running 8 validators.

**Comment by prestonvanloon** [comment]
Please update the assignments. This does not resolve #2025 until the committee assignments returns the assignments for all of the public keys in the request.

https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/rpc/validator_server.go#L116

File: validator/client/validator.go (hunk 28 above)
Comment (shayzluf) [reply validator/client/validator.go]: added it in else

File: validator/client/validator_test.go (hunk 29 above)
Comment (shayzluf) [reply validator/client/validator_test.go]: test fails because of && false

https://github.com/shayzluf/prysm/blob/20717ee7528172fa8e99df0532be71219ad01fb1/validator/client/validator.go#L144-L148

File: beacon-chain/db/validator.go (hunk 30 above)
Comment (shayzluf) [reply beacon-chain/db/validator.go]: this method returns false if any one of the slice element is missing

Comment (shayzluf) [reply beacon-chain/db/validator.go]: // HasValidators returns true if all validator in a list of public keys are in the validator bucket.

File: beacon-chain/db/validator.go (hunk 31 above)
Comment (shayzluf) [reply beacon-chain/db/validator.go]: removed

File: beacon-chain/rpc/validator_server.go (hunk 33 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: thanks

Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: chose the filter naming

File: beacon-chain/rpc/validator_server.go (hunk 34 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: changed

File: validator/client/validator.go (hunk 37 above)
Comment (shayzluf) [reply validator/client/validator.go]: thanks

File: validator/client/validator_test.go (hunk 29 above)
Comment (prestonvanloon) [reply validator/client/validator_test.go]: It isn't failing in master, why does it fail now?

File: validator/client/validator.go (hunk 38 above)
Comment (shayzluf) [reply validator/client/validator.go]: fixed

File: validator/client/validator_test.go (hunk 29 above)
Comment (shayzluf) [reply validator/client/validator_test.go]: what should prevent it from calling update when it gets pass 
```// Testing run time for fetching every slot. This is not meant for production!
	if slot%params.BeaconConfig().SlotsPerEpoch != 0 && v.assignments != nil && false {
		// Do nothing if not epoch start AND assignments already exist.
		return nil
	}
```
then its not doing nothing

Comment (shayzluf) [reply validator/client/validator_test.go]: found the answer on main branch t.Skip()

File: beacon-chain/rpc/validator_server.go (hunk 35 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: done

File: validator/client/validator.go (hunk 36 above)
Comment (shayzluf) [reply validator/client/validator.go]: added

File: beacon-chain/rpc/validator_server.go (hunk 32 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: you defined ```pb.ValidatorActivationResponse{
				ActivatedPublicKeys: activeKeys```
I can change it

File: beacon-chain/db/validator.go [hunk 39]
```diff
@@ -72,9 +97,29 @@ func (db *BeaconDB) DeleteValidatorIndex(pubKey []byte) error {
 	})
 }
 
+// HasValidators returns true if all validator in a list of public keys are in the bucket.
+func (db *BeaconDB) HasValidators(pubKeys [][]byte) bool {
```
Comment (prestonvanloon) [inline beacon-chain/db/validator.go]: Sorry to be pedantic here, but can we rename this to `HasAllValidators` so that it is clear it only returns true if all validators are in the set?

File: beacon-chain/rpc/validator_server.go [hunk 40]
```diff
@@ -30,36 +30,36 @@ type ValidatorServer struct {
...
-			Validator: activeVal,
+			ActivatedPublicKeys: activeKeys,
 		}
 		return stream.Send(res)
 	}
 	for {
 		select {
 		case <-time.After(3 * time.Second):
-			if !vs.beaconDB.HasValidator(req.Pubkey) {
+			if !vs.beaconDB.HasValidators(req.PublicKeys) {
```
Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]: So this is not a good condition, right? If any of the validators doesn't exist, we don't perform anyone's role. Can you improve this logic?

File: beacon-chain/rpc/validator_server.go (hunk 32 above)
Comment (prestonvanloon) [reply beacon-chain/rpc/validator_server.go]: no, this is fine. thanks

File: beacon-chain/db/validator.go (hunk 39 above)
Comment (shayzluf) [reply beacon-chain/db/validator.go]: changed HasValidators to return true if one validator exists

File: beacon-chain/rpc/validator_server.go (hunk 40 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: fixed by changing HasValidators logic

File: beacon-chain/db/validator.go (hunk 39 above)
Comment (shayzluf) [reply beacon-chain/db/validator.go]: changed `HasAllValidators` to return true if one validator exists

File: beacon-chain/db/validator.go (hunk 1 above)
Comment (prestonvanloon) [reply beacon-chain/db/validator.go]: Please change the name to HasAnyValidator

File: beacon-chain/db/validator.go [hunk 41]
```diff
@@ -61,6 +61,31 @@ func (db *BeaconDB) ValidatorIndex(pubKey []byte) (uint64, error) {
 	return index, err
 }
 
+// ValidatorIndices accepts a slice of public keys and returns the corresponding map of validators indexes and public keys.
+func (db *BeaconDB) ValidatorIndices(pubKeys [][]byte) (map[uint64][]byte, error) {
+	m := make(map[uint64][]byte)
+	if !db.HasValidators(pubKeys) {
```
Comment (prestonvanloon) [inline beacon-chain/db/validator.go]: Since this is "has any validator", the lookup for all validators will return an error if any of them do not exist in the database. This is a fatal condition when some validator has not been deposited yet

Comment (shayzluf) [reply beacon-chain/db/validator.go]: changed to hasallvalidators

Comment (shayzluf) [reply beacon-chain/db/validator.go]: it means that if not all validators have performed deposit then the validator client won't run

File: beacon-chain/rpc/validator_server.go [hunk 42]
```diff
@@ -30,36 +30,36 @@ type ValidatorServer struct {
 // beacon state, if not, then it creates a stream which listens for canonical states which contain
 // the validator with the public key as an active validator record.
 func (vs *ValidatorServer) WaitForActivation(req *pb.ValidatorActivationRequest, stream pb.ValidatorService_WaitForActivationServer) error {
-	if vs.beaconDB.HasValidator(req.Pubkey) {
-		beaconState, err := vs.beaconDB.HeadState(vs.ctx)
+	if vs.beaconDB.HasAllValidators(req.PublicKeys) {
```
Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]: This should check `HasAnyValidator(req.PublicKeys)`

File: beacon-chain/rpc/validator_server.go [hunk 43]
```diff
@@ -30,36 +30,36 @@ type ValidatorServer struct {
...
-			Validator: activeVal,
+			ActivatedPublicKeys: activeKeys,
 		}
 		return stream.Send(res)
 	}
 	for {
 		select {
 		case <-time.After(3 * time.Second):
-			if !vs.beaconDB.HasValidator(req.Pubkey) {
+			if !vs.beaconDB.HasAllValidators(req.PublicKeys) {
```
Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]: :+1: this is good

File: validator/client/runner_test.go [hunk 44]
```diff
@@ -143,9 +144,9 @@ func TestProposes_NextSlot(t *testing.T) {
 
 		cancel()
 	}()
-
+	timer := time.NewTimer(time.Duration(200 * time.Millisecond))
```
[the remark this answers is not in the document]
Comment (prestonvanloon) [reply validator/client/runner_test.go]: Please remove these timers, they don't seem necessary

File: beacon-chain/db/validator.go [hunk 45]
```diff
@@ -61,6 +61,31 @@ func (db *BeaconDB) ValidatorIndex(pubKey []byte) (uint64, error) {
 	return index, err
 }
 
+// ValidatorIndices accepts a slice of public keys and returns the corresponding map of validators indexes and public keys.
+func (db *BeaconDB) ValidatorIndices(pubKeys [][]byte) (map[uint64][]byte, error) {
+	m := make(map[uint64][]byte)
+	if !db.HasAllValidators(pubKeys) {
```
Comment (prestonvanloon) [inline beacon-chain/db/validator.go]: This should be `db.HasAnyValidators(pubKeys)`

File: beacon-chain/db/validator.go [hunk 46]
```diff
@@ -61,6 +61,31 @@ func (db *BeaconDB) ValidatorIndex(pubKey []byte) (uint64, error) {
...
+		return m, fmt.Errorf("validators %#x does not exist. make sure that all validators in keystore made a deposit before you run the validator client", pubKeys)
+	}
+
+	err := db.view(func(tx *bolt.Tx) error {
+		bucket := tx.Bucket(validatorBucket)
+		for _, pk := range pubKeys {
+			h := hashutil.Hash(pk)
+			enc := bucket.Get(h[:])
```
Comment (prestonvanloon) [inline beacon-chain/db/validator.go]:
```suggestion
			enc := bucket.Get(h[:])
			if len(enc) == 0 { 
			   // public key is not present in validator bucket
			   continue
			}
```

File: beacon-chain/db/validator.go [hunk 47]
```diff
@@ -72,9 +97,29 @@ func (db *BeaconDB) DeleteValidatorIndex(pubKey []byte) error {
 	})
 }
 
+// HasAllValidators returns true if all validators in a list of public keys are in the bucket.
+func (db *BeaconDB) HasAllValidators(pubKeys [][]byte) bool {
```
Comment (prestonvanloon) [inline beacon-chain/db/validator.go]: Add another method `HasAnyValidator(pubkeys [][]byte) bool`

File: beacon-chain/rpc/validator_server.go [hunk 48]
```diff
@@ -30,36 +30,36 @@ type ValidatorServer struct {
...
 				continue
 			}
 			beaconState, err := vs.beaconDB.HeadState(vs.ctx)
```
Comment (terenc3t) [inline beacon-chain/rpc/validator_server.go]:
```suggestion
			beaconState, err := vs.beaconDB.HeadState(stream.Context())
```

Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: thanks

**Comment by prestonvanloon** [comment]
Update: I pushed a commit to fix wait for activation, and now we have the follow type error
```
time="2019-04-12 22:28:11" level=info msg="Waiting for validator to be activated in the beacon chain" prefix=validator
time="2019-04-12 22:28:11" level=fatal msg="Could not wait for validator activation: could not receive validator activation from stream: rpc error: code = Unknown desc = could not retrieve active validator from state: could not retrieve validators indexes: validators [0x844d0ca2d39500dd433b77942f1e3bb4fc7b99c715d9baca36c7733307fed557c83a3c7aef93ad39c6b11ca67d6a315d0f22f9fe576aa5dc3f04f321fc658fc150969f528a894554e8c4005a26f00d5d507c91c5058e1b57b212f71513e8a228 0x86e2a1f342ec9c63e55ecfd051fa8857c127721b8548831ca532bd6b94ff34f7d44cbc0a7fa554299ca54d3446f3491b0b98ab16194cad179934ccbdd14037af6d5820777f76b9d4f28f619298ad8070499caac4539b336a59e01abaac8659ba 0x8a6e7152eac40a32086a61d2bba6d92e1615893d0ef1a49183c1e098778c31b207231392ce6f6b97e672dfa158f00ecd0624f7500c29a83a645d73227a55755f9b444fa4cad389bfbdabe14c39f35fe83ae0d05a5aa010508939ebe44fae0ed3 0xab69889312a71bde2d03ce219b33d94d4c2341b03e3e3852f931aeefb85f23f0912062177d1e789c16d5922bf0a1aeee04d4a2cd0ded75fef1ebf68f842de96ec488b32a7c2b09cebef0024a0658eba87a70faf1f5bcc00ff6d094f95e2f49d0 0xb40cccc01d85f2d4cd97c2f27aa9cfb5e1ac6564fbe263235984e44d9dfb8b7027bcbf10ba2c1a841f1637a4b5b2f61909d73d45392785fe33ae9b695424da3b00061128b6412a42c5b85696b299a911c48391ffe2dc751c651873b17bf27d2e 0x829e2921cd11e0e0fc0536b0db2c959510993750af6f696abb95ab3c075232d6489745fefa4233c81c337b2898f26dc514e6dfea440ed071e6a5e3494c4b5b06e86a6d7d48cc8c50ce15e33df09cf65585fec352ec5a6dddeb2efd7c94b4b5c2 0x9858105cc75e1cb0c6739a22d07809b5cd24c11dc305fd562f340b30fbc43e5baeb7fa82939ff345bc80575c1802f53103ee04f87a720201d98a543f053185a774fb01949283bdd5a25ce50d424aca1bd76afa978069cf585de05e8540142611 0x98d93b068641ef2f583dfbf206b0061e7695e633069dc79ad12397da3ec72764e4a004baeb415b858474ecd5f3b81ec70843fe1061a01d9a82377049afabd53cab3f75fcd58a33729868bc7a0a1c1e5358e545e46cc9d2e543f88f137b930fb4 0xa88c1a8f7f554446b7002d72d1ccebf698de14507de37eca704b3b744f6526bab4b252e57d9f78ad0963b5b9ddf970d1165e3a69bd69f17202eadf6c4eec61711dd845bc44b97b0c98fa358fc944986f9e0de0368a10a665688a1589a415a627] does not exist. make sure that all validators in keystore made a deposit before you run the validator client" prefix=validator
```

**Comment by prestonvanloon** [comment]
Update: A little farther, assignments fail for the 9th validator.
```
time="2019-04-12 22:44:41" level=error msg="Failed to update assignments" error="rpc error: code = Unknown desc = could not get active validator index: validator 0xa5aa0f7a7ceaf9552ed4e5c5356068b09a92cad4dd97bf53c5f55bcf3649188d391deb8d0d02606e80736d63fb05917a0979e09abb7c920466414d296beed2f021378607c51847de2a46ec71d1023e3883830cd0bf104f1695d1fc65753eea25 does not exist" prefix=validator
```

I'll filter out non-activated keys as part of determining assignments

**Comment by prestonvanloon** [comment]
I got the chain to start with 8 + 1 validators, but then I am getting a failure to verify deposit for the 9th validator.

```
time="2019-04-13 00:03:48" level=error msg="Failed to propose block" error="rpc error: code = Unknown desc = could not process beacon block: could not apply block state transition: could not execute state transition with block could not execute state transition could not process block: could not process block validator deposits: could not verify deposit #0: deposit merkle branch of deposit root did not verify for root: 0xdcd23aa6c54b754cfae0135220c9d74973e599d412290aa73bbc3bcf159b55b3" prefix=validator
```

**Comment by prestonvanloon** [comment]
Trying to split up this PR into smaller pieces

**Comment by prestonvanloon** [comment]
Update; review of #2248 found a much more optimal way to filter out inactive validators. I have added this to the PR and cleaned it up slightly. Still need to review more and try to find ways to split up this PR, if possible.

There is now a failing test since the method for retrieving assignments is now fundamentally different.

**Comment by nisdas** [comment]
Update: 
- [x] To fix issues with postchainstart validators not being activated a new field called activated keys was used in the validator struct. Using this we only request assignments of activated validators
- [x] add a new method to wait for unactivated validators, which calls `WaitForActivation` recursively until we get all the required validators
- [x] Optimize how we get assingments so that we only do state transitions once in each rpc call, instead of repeatedly for each validator

File: beacon-chain/rpc/validator_server.go [hunk 49]
```diff
@@ -6,12 +6,13 @@ import (
 	"fmt"
 	"time"
 
-	"github.com/prysmaticlabs/prysm/beacon-chain/core/helpers"
 	"github.com/prysmaticlabs/prysm/beacon-chain/core/state"
+	"github.com/prysmaticlabs/prysm/shared/hashutil"
+
```
Comment (prestonvanloon) [inline beacon-chain/rpc/validator_server.go]: Remove space

File: validator/client/runner_test.go (hunk 44 above)
[the remark this answers is not in the document]
Comment (prestonvanloon) [reply validator/client/runner_test.go]: Still wondering why this is necessary

**Comment by prestonvanloon** [comment]
I dont see the logic to add the status for non-activated keys.
```
assignment {
  committee: 16
  committee: 17
  shard: 143
  slot: 963
  is_proposer: true
  public_key: pk1
  status: ACTIVE
}
assignment {
   public_key: pk2
   status: PENDING_ACTIVE 
}
assignment {
   public_key: pk3
   status: UNKNOWN
}
```

Please do not merge until we can run in the cluster for a bit.

File: beacon-chain/rpc/validator_server.go (hunk 49 above)
Comment (shayzluf) [reply beacon-chain/rpc/validator_server.go]: removed

**Comment by shayzluf** [comment]
@prestonvanloon about the timer . on multi validator setup run is in a goroutine if we don't wait than the test fails

**Comment by prestonvanloon** [comment]
Timer is OK, i understand it now. It would be better to have a shorter timer but it seems OK.

I had some more feedback that the validator logs are now very hard to understand. 
Assignment update logs look like:
```
time="2019-04-16 23:45:07" level=info msg="Updated validator assignments" b7dc0ffc145d_attesterSlot=4028 b7dc0ffc145d_proposerSlot="Not proposing" b7dc0ffc145d_shard=0 prefix=validator
```
In the above scenario, i had 9 validator keys but only one was activated. I think we need to update the status of all of them with some log like
```
Validator: b7dc0ffc145d
Status: Pending activation

Validator: b7dc0ffc123f
Status: Activated
Attestor slot: 4028
Proposer slot: 4029
...
```

I also see logs like this, but i am not sure what validator is associated with it:
```
time="2019-04-16 23:52:30" level=info msg="No active assignment, doing nothing" prefix=validator role=UNKNOWN slot=4105
```

**Comment by prestonvanloon** [comment]
Also, balance updates may be broken, this is the log i see after running for a few minutes
```
time="2019-04-16 23:56:24" level=info msg="Validator registry information" numActiveValidators=78 prefix=validator totalValidators=83
time="2019-04-16 23:56:24" level=info msg="Generating validator performance report from the previous epoch..." prefix=validator
time="2019-04-16 23:56:24" level=info msg="New validator balance" ethBalance=0.003192077 prefix=validator
time="2019-04-16 23:56:24" level=info msg="Previous validator balance" prefix=validator prevEthBalance=0.012771802
time="2019-04-16 23:56:24" level=info msg="Net gains/losses in eth" eth=-0.009580 percentChange="-75.01%" prefix=validator
```

**Comment by rauljordan** [comment]
PTAL @terenc3t @prestonvanloon

File: validator/client/runner_test.go (hunk 44 above)
[the remark this answers is not in the document]
Comment (prestonvanloon) [reply validator/client/runner_test.go]: Resolved offline, this is needed because the primary logic is run via go routine

**Comment by prestonvanloon** [comment]
Fixing tests, the log format changed so some new test failures
