### PR TITLE
Return consensus block value in Wei

### LINKED ISSUE #13535: v3 blocks endpoint returns consensus value in Gwei
### Describe the bug

The consensus value for the endpoint `/eth/v3/validator/blocks/{slot}` is provided in Gwei.  As per https://github.com/ethereum/beacon-APIs/pull/400 this value should be in Wei.

### Has this worked before in a previous version?

```text
No.
```

### 🔬 Minimal Reproduction

_No response_

### Error

_No response_

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

beacon-chain version Prysm/v4.2.1-rc.2/9c13d47f4c75daffa7d0ceb2f8a578be601e14ad. Built at: 2024-01-26 00:19:59+00:00

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Bug fix

**Which issues(s) does this PR fix?**

Fixes #13535

### CODE REVIEW

File: beacon-chain/rpc/eth/validator/handlers_block.go [hunk 1]
```diff
@@ -298,12 +299,21 @@ func getConsensusBlockValue(ctx context.Context, blockRewardsFetcher rewards.Blo
 		// ignore for phase 0
 		return "", nil
 	}
-	//get consensus payload value which is the same as the total from the block rewards api
+	// Get consensus payload value which is the same as the total from the block rewards api.
+	// The value is in Gwei, but Wei should be returned from the endpoint.
 	blockRewards, httpError := blockRewardsFetcher.GetBlockRewardsData(ctx, bb)
```
Comment (james-prysm) [inline beacon-chain/rpc/eth/validator/handlers_block.go:304]: can you add a comment for GetBlockRewardsData that the rewards are in wei for the public function?

**Review by james-prysm — APPROVED** [review]
