### PR TITLE
Safe Math for ETH1 Batch Headers Request

### LINKED ISSUE #8105: panic: runtime error: makeslice: cap out of range
# 🐞 Bug Report

### Description

Was updating host, running docker, got the panic two times below.

### Has this worked before in a previous version?

Yes

## 🔬 Minimal Reproduction

Don't know, happened only once but two times in a row.

## 🔥 Error

```
prysm_beacon            | time="2020-12-13 19:27:08" level=warning msg="Running on ETH2 Mainnet" prefix=flags
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Using "max_cover" strategy on attestation aggregation" prefix=flags
prysm_beacon            | time="2020-12-13 19:27:08" level=warning msg="Starting beacon chain with max RPC page size of 100000" prefix=node
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Checking DB" database-path="/data/beaconchaindata" prefix=node
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Waiting for state to be initialized" prefix=initial-sync
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Starting beacon node" prefix=node version="Prysm/v1.0.4/b4437e6cecd78257d2699f42073a90a940baf716. Built at: 2020-12-07 18:32:43+00:00"
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Starting JSON-HTTP API" address="0.0.0.0:3500" prefix=gateway
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="gRPC server listening on port" address="0.0.0.0:4000" prefix=rpc
prysm_beacon            | time="2020-12-13 19:27:08" level=warning msg="You are using an insecure gRPC server. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=rpc
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Connected to eth1 proof-of-work chain" endpoint="http://geth:8545" prefix=powchain
prysm_beacon            | time="2020-12-13 19:27:08" level=info msg="Blockchain data already exists in DB, initializing..." prefix=blockchain
prysm_beacon            | panic: runtime error: makeslice: cap out of range
prysm_beacon            |
prysm_beacon            | goroutine 166 [running]:
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).batchRequestHeaders(0xc0002fd7a0, 0xae9616, 0xae9334, 0xae9334, 0xae9616, 0x0, 0x0, 0xc000c21340)
prysm_beacon            |       beacon-chain/powchain/service.go:581 +0x77
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).cacheHeadersForEth1DataVote(0xc0002fd7a0, 0x9a3200, 0xc00220c100, 0x0, 0x0)
prysm_beacon            |       beacon-chain/powchain/service.go:785 +0xa8
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).initPOWService(0xc0002fd7a0)
prysm_beacon            |       beacon-chain/powchain/service.go:695 +0x37a
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).run(0xc0002fd7a0, 0xc006d34360)
prysm_beacon            |       beacon-chain/powchain/service.go:710 +0x89
prysm_beacon            | github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start.func1(0xc0002fd7a0)
prysm_beacon            |       beacon-chain/powchain/service.go:258 +0x50
prysm_beacon            | created by github.com/prysmaticlabs/prysm/beacon-chain/powchain.(*Service).Start
prysm_beacon            |       beacon-chain/powchain/service.go:256 +0x65
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
gcr.io/prysmaticlabs/prysm/beacon-chain:v1.0.4 with https://github.com/stereum-dev/ethereum2-docker-compose
  </code>
</pre>

### PR DESCRIPTION
**Pull request by rauljordan**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

This PR prevents panics at runtime due to underflows in requesting eth1 headers due to invalid ranges by using safer math. The underflow being produced in the first place, however, seems to be a symptom of a problem in the eth1 client the users were using with Prysm. It is safer to not panic.

**Which issues(s) does this PR fix?**

Fixes #8105

### CODE REVIEW

File: beacon-chain/powchain/service.go [hunk 1]
```diff
@@ -616,7 +616,10 @@ func (s *Service) processBlockHeader(header *gethTypes.Header) {
 // batchRequestHeaders requests the block range specified in the arguments. Instead of requesting
 // each block in one call, it batches all requests into a single rpc call.
 func (s *Service) batchRequestHeaders(startBlock, endBlock uint64) ([]*gethTypes.Header, error) {
-	requestRange := (endBlock - startBlock) + 1
+	var requestRange uint64
+	if startBlock < endBlock {
```
Comment (prestonvanloon) [inline beacon-chain/powchain/service.go:620]: What about `startBlock == endBlock`? 

```suggestion
	if startBlock <= endBlock {
```

Comment (nisdas) [inline beacon-chain/powchain/service.go:620]: in the event it is an overflow, we should return an error here. 
so if 
```go
if start > end {
return err
}
```

Comment (rkapka) [reply beacon-chain/powchain/service.go:620]: IIRC, we discussed this during the initial implementation. I wanted to return an empty range in such a case at first, but we agreed that explicitly informing the user that something wrong is happening is better than silently returning an empty range.

**Review by prestonvanloon — APPROVED** [review]

File: beacon-chain/powchain/service.go [hunk 2]
```diff
@@ -616,6 +616,9 @@ func (s *Service) processBlockHeader(header *gethTypes.Header) {
 // batchRequestHeaders requests the block range specified in the arguments. Instead of requesting
 // each block in one call, it batches all requests into a single rpc call.
 func (s *Service) batchRequestHeaders(startBlock, endBlock uint64) ([]*gethTypes.Header, error) {
+	if startBlock >= endBlock {
```
Comment (nisdas) [inline beacon-chain/powchain/service.go:619]:
```suggestion
	if startBlock > endBlock {
```
we should be allowing singular queries too, there might be cases where our batch request is only for 1 header.

**Review by nisdas — CHANGES_REQUESTED** [review]

**Comment by rauljordan** [comment]
Ready again @nisdas

File: beacon-chain/powchain/service.go [hunk 3]
```diff
@@ -616,6 +616,9 @@ func (s *Service) processBlockHeader(header *gethTypes.Header) {
 // batchRequestHeaders requests the block range specified in the arguments. Instead of requesting
 // each block in one call, it batches all requests into a single rpc call.
 func (s *Service) batchRequestHeaders(startBlock, endBlock uint64) ([]*gethTypes.Header, error) {
+	if startBlock > endBlock {
```
Comment (prestonvanloon) [inline beacon-chain/powchain/service.go:619]: I agree with you and @nisdas here. Sorry for suggesting otherwise! I suppose a batch request of 1 block is allowed.

File: beacon-chain/powchain/service.go [hunk 4]
```diff
@@ -616,6 +616,9 @@ func (s *Service) processBlockHeader(header *gethTypes.Header) {
...
+		return nil, fmt.Errorf("start block height %d cannot be >= end block height %d", startBlock, endBlock)
```
Comment (prestonvanloon) [inline beacon-chain/powchain/service.go:620]:
```suggestion
		return nil, fmt.Errorf("start block height %d cannot be > end block height %d", startBlock, endBlock)
```

File: beacon-chain/powchain/service_test.go [hunk 5]
```diff
@@ -571,3 +571,16 @@ func TestDedupEndpoints(t *testing.T) {
 	assert.DeepEqual(t, []string{"A", "B"}, dedupEndpoints([]string{"A", "A", "A", "B"}), "did not dedup correctly")
 	assert.DeepEqual(t, []string{"A", "B"}, dedupEndpoints([]string{"A", "A", "A", "B", "B"}), "did not dedup correctly")
 }
+
+func Test_batchRequestHeaders_UnderflowChecks(t *testing.T) {
+	srv := &Service{}
+	start := uint64(101)
+	end := uint64(100)
+	_, err := srv.batchRequestHeaders(start, end)
+	require.ErrorContains(t, "cannot be >=", err)
```
Comment (prestonvanloon) [inline beacon-chain/powchain/service_test.go:580]:
```suggestion
	require.ErrorContains(t, "cannot be >", err)
```

File: beacon-chain/powchain/service_test.go [hunk 6]
```diff
@@ -571,3 +571,16 @@ func TestDedupEndpoints(t *testing.T) {
...
+
+	start = uint64(200)
+	end = uint64(100)
+	_, err = srv.batchRequestHeaders(start, end)
+	require.ErrorContains(t, "cannot be >=", err)
```
Comment (prestonvanloon) [inline beacon-chain/powchain/service_test.go:585]:
```suggestion
	require.ErrorContains(t, "cannot be >", err)
```

**Review by nisdas — APPROVED** [review]
