### PR TITLE
Fix Gossip Clock Disparity

### LINKED ISSUE #6103: Potential issues due to granularity of timestamps
# 🐞 Bug Report

### Description

 
The following requirement in the P2P specification can be violated:
"The block is not from a future slot (with a `MAXIMUM_GOSSIP_CLOCK_DISPARITY` allowance) -- i.e. validate that `signed_beacon_block.message.slot <= current_slot`"

There is an edge case scenario where this condition would be satisfied for a time that is actually in the future. The following is a code snippet from the `VerifySlotTime` function in `beacon-chain/core/helpers/slot_epoch.go`:
```
	slotTime := 1000 * (genesisTime + slot*params.BeaconConfig().SecondsPerSlot)
	currentTime := 1000 * uint64(roughtime.Now().Unix())
	tolerance := uint64(timeTolerance.Milliseconds()) // 500ms
	if slotTime > currentTime+tolerance { … }
```
Let’s say that `slotTime` is 5000s, and actual time represented by `roughtime.Now()` is 5900 ms. However, since `roughtime.Now().Unix()` returns time in seconds - that is, it returns 5s, and `currentTime` ends up being 5000 (same as `slotTime`). However, an actual current time is 5900s, which is 900ms higher than `slotTime`, but 900ms is bigger than 500ms. Therefore, the time difference is actually higher than `MAXIMUM_GOSSIP_CLOCK_DISPARITY`.

The same pattern is used in the `validateAggregateAttTime` function inside `beacon-chain/sync/validate_aggregate_proof.go` to verify if the attestation slot is within the last `ATTESTATION_PROPAGATION_SLOT_RANGE` slots.

### Recommended fix/mitigation:
If tolerance is less than a second, it makes more sense to do time computations in milliseconds directly, rather than using seconds and then multiplying by 1000. Use [https://golang.org/pkg/time/#Time.UnixNano](https://golang.org/pkg/time/#Time.UnixNano) instead of just `.Unix()`. Same applies to validating other things, e.g., attestations.

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

This fixes a gossip clock disparity, which was allowing old blocks/attestations to be processed
by the beacon node due to how we were casting time based values. This instead enforces that 
we use `time.Time` as the base time type when doing comparisons for timestamps of blocks/attestations. This allows us to accurately compare time values, instead of losing precision due to casting.

Also adds in a regression based test for it.

**Which issues(s) does this PR fix?**

Resolves #6103 

**Other notes for review**

N.A

### CODE REVIEW

File: beacon-chain/sync/validate_aggregate_proof.go [hunk 1]
```diff
@@ -193,18 +194,18 @@ func validateIndexInCommittee(ctx context.Context, s *stateTrie.BeaconState, a *
...
+	currentTime := roughtime.Now()
+	clockDisparity := params.BeaconNetworkConfig().MaximumGossipClockDisparity
 
 	// Verify attestation slot is within the last ATTESTATION_PROPAGATION_SLOT_RANGE slots.
-	currentSlot := (uint64(currentTimeInSec) - genesisTime) / params.BeaconConfig().SecondsPerSlot
-	if attTime-uint64(maximumGossipClockDisparity.Milliseconds()) > uint64(currentTime) ||
-		uint64(currentTime-maximumGossipClockDisparity.Milliseconds()) > attTimeRange {
+	currentSlot := helpers.SlotsSince(genesisTime)
+	if attTime.Add(-clockDisparity).After(currentTime) ||
+		currentTime.Add(-clockDisparity).After(attTimeRange) {
```
Comment (banescusebi) [inline beacon-chain/sync/validate_aggregate_proof.go:208]: Why not use `attTime.Sub(clockDisparity)` instead of `attTime.Add(-clockDisparity)` for the 2 lines above?

Comment (nisdas) [reply beacon-chain/sync/validate_aggregate_proof.go:208]: In the official godoc of the `time` library. https://golang.org/pkg/time/#Time.Sub
```
// Sub returns the duration t-u. If the result exceeds the maximum (or minimum)
// value that can be stored in a Duration, the maximum (or minimum) duration
// will be returned.
// To compute t-d for a duration d, use t.Add(-d).
```
We would use `Sub` to compute the difference between two time instances. Whereas for the code, `clockDisparity` is a `time.Duration` value. So it made sense for me to use `Add` here instead.

Comment (banescusebi) [reply beacon-chain/sync/validate_aggregate_proof.go:208]: got it. thanks
