### PR TITLE
make registerSubscribers idempotent

### LINKED ISSUE #15738: Fix `Provided topic already has an active subscription running` log
### Describe the bug

From time to time, after a BN start, a lot of

```
level=debug msg="Provided topic already has an active subscription running" prefix=sync topic="/eth2/ad532ceb/beacon_attestation_3/ssz_snappy"
```

logs are displayed.

Generally, these logs disappear after a reboot.

We should:
1. Find if there logs are expected, and why.
2. If they are not expected, fix the root cause. If they are expected, reduce the log volume

### PR DESCRIPTION
**Pull request by kasey**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

This is an attempt to make a simple fix to the double topic registration that occurs when the node exits initial-sync, by adding a basic map with a mutex to hold digests of calls to `registerSubscribers` and early exit if the method was previously called with the given digest.

**Which issues(s) does this PR fix?**

Fixes #15738

**Alternative proposals:**
- https://github.com/OffchainLabs/prysm/pull/15769
- https://github.com/OffchainLabs/prysm/pull/15771
- https://github.com/OffchainLabs/prysm/pull/15780

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

File: beacon-chain/sync/subscriber.go [hunk 1]
```diff
@@ -198,8 +198,44 @@ func (s *Service) spawn(f func()) {
...
+	digests map[[4]byte]struct{}
+}
+
+// holdSubscriptionRegistration ensures that only one goroutine can register subscriptions.
+// It returns a boolean indicating whether the caller should proceed with registration,
+// and a callback function to release the lock when done.
+func (s *Service) holdSubscriptionRegistration(digest [4]byte) (bool, func()) {
+	// lazy init
+	if s.subRegs == nil {
+		s.subRegs = &subscriptionRegistrations{digests: make(map[[4]byte]struct{})}
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go:212]: Will panic if `holdSubscriptionRegistration` is called concurrently with ` s.subRegs` unset.

File: beacon-chain/sync/subscriber.go [hunk 2]
```diff
@@ -198,8 +198,44 @@ func (s *Service) spawn(f func()) {
 	}
 }
 
+type subscriptionRegistrations struct {
+	sync.RWMutex
+	digests map[[4]byte]struct{}
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: The `digests` map will only grow in size right?
If so, it's a memory leak, but I think for this specific case is totally harmless, even with a ton of BPO forks.
However, maybe it's worth adding a little comment about this "assumed memory leak".

Comment (nalepae) [reply beacon-chain/sync/subscriber.go]: (Note: It's exactly this kind of grow only map field of struct that used to OOM the slasher, but for sure with a totally different order of magnitude in term of items.)

File: beacon-chain/sync/subscriber.go [hunk 3]
```diff
@@ -198,8 +198,44 @@ func (s *Service) spawn(f func()) {
...
+}
+
+// holdSubscriptionRegistration ensures that only one goroutine can register subscriptions.
+// It returns a boolean indicating whether the caller should proceed with registration,
+// and a callback function to release the lock when done.
+func (s *Service) holdSubscriptionRegistration(digest [4]byte) (bool, func()) {
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: I'm not sure to understand why the `release` process is needed.
Why couldn't we only use a map (with lock to prevent data race) returning `true` if already called with the same digest and `false` otherwise, without having to deal with any `release` on the caller side?

The caller (`registerSubscribers`) would exit early if the returned value is `true`.

Also in this case, I think [sync.Map](https://pkg.go.dev/sync#Map) with `LoadOrStore` can be used instead of defining a map along with a mutex.

**Comment by nalepae** [comment]
In `startDiscoveryAndSubscriptions`, what about testing the return value of `s.registerSubscribers` and log and error if it returns `false`?

File: beacon-chain/sync/subscriber.go (hunk 1 above)
Comment (nalepae) [reply beacon-chain/sync/subscriber.go:212]: EDIT: I delete this comment.

File: beacon-chain/sync/fork_watcher.go [hunk 4]
```diff
@@ -12,20 +12,26 @@ import (
 // Is a background routine that observes for new incoming forks. Depending on the epoch
 // it will be in charge of subscribing/unsubscribing the relevant topics at the fork boundaries.
 func (s *Service) forkWatcher() {
-	<-s.initialSyncComplete
+	// At startup, launch registration and peer discovery loops, and register rpc stream handlers.
+	startEntry := params.GetNetworkScheduleEntry(s.cfg.clock.CurrentEpoch())
+	s.registerSubscribers(startEntry)
+	if err := s.registerRPCHandlers(startEntry); err != nil {
+		log.WithError(err).Error("Could not register rpc handlers at startup")
```
Comment (james-prysm) [inline beacon-chain/sync/fork_watcher.go]: is it safe to continue if we can't register here?

File: beacon-chain/sync/fork_watcher.go [hunk 5]
```diff
@@ -38,22 +44,20 @@ func (s *Service) forkWatcher() {
...
 
 // registerForUpcomingFork registers appropriate gossip and RPC topic if there is a fork in the next epoch.
-func (s *Service) registerForUpcomingFork(currentEpoch primitives.Epoch) error {
-	nextEntry := params.GetNetworkScheduleEntry(currentEpoch + 1)
-	// Check if there is a fork in the next epoch.
-	if nextEntry.ForkDigest == s.registeredNetworkEntry.ForkDigest {
+func (s *Service) registerForUpcomingFork(current primitives.Epoch) error {
+	nextEntry := params.GetNetworkScheduleEntry(current + 1)
+
+	// If nothing new was registered, exit early.
```
Comment (james-prysm) [inline beacon-chain/sync/fork_watcher.go]: small suggestion on rewording to make it easier to read
```
// Early exit when no new subscribers were registered.
//
// Context:
// - registerSubscribers() also runs at service startup (initial sync).
// - On the first call here, it will often return false because startup handled it.
// - RPC registration is performed at startup in that path.
// Therefore, returning early here is expected and safe.
```

File: beacon-chain/startup/clock.go [hunk 6]
```diff
@@ -56,6 +58,17 @@ func (g *Clock) Now() time.Time {
 	return g.now()
 }
 
+// Until returns the duration until the given slot begins, or zero if the slot is in the past.
+func (g *Clock) Until(slot primitives.Slot) time.Duration {
```
Comment (james-prysm) [inline beacon-chain/startup/clock.go]: can you add some tests for this one?

File: beacon-chain/sync/fork_watcher.go (hunk 4 above)
Comment (kasey) [reply beacon-chain/sync/fork_watcher.go]: I think continuing is safer than failing. FWIW this is a somewhat impossible condition, it requires `rpcHandlerByTopicFromFork` to be called with an unrecognized forkIndex.

File: beacon-chain/sync/fork_watcher.go (hunk 5 above)
Comment (kasey) [reply beacon-chain/sync/fork_watcher.go]: This is outdated actually, we no longer call registerSubscribers from a different code path.

File: beacon-chain/sync/subscriber.go [hunk 7]
```diff
@@ -309,35 +313,47 @@ func (s *Service) registerSubscribers(epoch primitives.Epoch, digest [4]byte) {
...
-	if err != nil {
-		// Impossible condition as it would mean digest does not exist.
-		panic(err) // lint:nopanic -- Impossible condition.
+	// Check if this subscribe request is still valid - we may have crossed another fork epoch while waiting for initial sync.
+	if s.subscriptionRequestExpired(nse) {
+		// If we are already past the next fork epoch, do not subscribe to this topic.
+		log.WithFields(logrus.Fields{
+			"topic":        topic,
+			"digest":       nse.ForkDigest,
+			"epoch":        nse.Epoch,
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: Nit: `forkEpoch` instead of `epoch`?

**Comment by james-prysm** [comment]
for other reviewers, we shouldn't approve/merge this until we figure out why we start unsubscribing and getting messages like 
```
Sep 27 22:21:59 eth-consensus beacon-chain_active[1350790]: time="2025-09-27 22:21:59.64" level=error msg="Could not register validator for topic" error="duplicate validator for topic /eth2/ad532ceb/sync_committee_contribution_and_proof/ssz_snappy" prefix=sync topic="/eth2/ad532ceb/sy>
```
in kurtosis starting from fulu fork

File: beacon-chain/sync/fork_watcher.go [hunk 8]
```diff
@@ -38,101 +41,88 @@ func (s *Service) forkWatcher() {
...
 // registerForUpcomingFork registers appropriate gossip and RPC topic if there is a fork in the next epoch.
-func (s *Service) registerForUpcomingFork(currentEpoch primitives.Epoch) error {
-	nextEntry := params.GetNetworkScheduleEntry(currentEpoch + 1)
-	// Check if there is a fork in the next epoch.
-	if nextEntry.ForkDigest == s.registeredNetworkEntry.ForkDigest {
-		return nil
-	}
+func (s *Service) registerForUpcomingFork(epoch primitives.Epoch) error {
+	current := params.GetNetworkScheduleEntry(epoch)
+	s.registerSubscribers(current)
```
Comment (james-prysm) [inline beacon-chain/sync/fork_watcher.go:49]: we need to registerSubscribers for current epoch every slot?

Comment (kasey) [reply beacon-chain/sync/fork_watcher.go:49]: The idea here is it's not `registerForUpcomingFork`'s problem, it just fires off the `registerSubscribers` call. `registerSubscribers` makes sure that it only runs once for each digest, which keeps things simple since there is now just one place to make the check.

File: beacon-chain/sync/subscriber.go [hunk 9]
```diff
@@ -546,30 +555,37 @@ func (s *Service) subscribeToSubnets(t *subnetTracker) error {
...
+				// If we are already past the next fork epoch, do not subscribe to this topic.
+				log.WithFields(logrus.Fields{
+					"topic":        p.shortTopic(),
+					"digest":       p.nse.ForkDigest,
+					"epoch":        p.nse.Epoch,
+					"currentEpoch": s.cfg.clock.CurrentEpoch(),
+				}).Debug("Exiting topic subnet subscription loop")
+				return
+			}
+			go s.ensurePeers(tracker)
```
Comment (james-prysm) [inline beacon-chain/sync/subscriber.go]: this is ok as a separate go routine I think this wasn't for ensureSubnetPeersAndSubscribe?

File: beacon-chain/sync/service.go [hunk 10]
```diff
@@ -377,11 +377,12 @@ func (s *Service) waitForChainStart() {
...
-	err = s.registerRPCHandlers()
-	if err != nil {
-		log.WithError(err).Error("Could not register rpc handlers")
-		return
+	// We need to register RPC handlers ASAP so that we can handle incoming status message
+	// requests from peers.
+	nse := params.GetNetworkScheduleEntry(clock.CurrentEpoch())
+	if err := s.registerRPCHandlers(nse); err != nil {
+		// If we fail here, we won't be able to peer with anyone because we can't handle their status messages.
+		panic(errors.Wrap(err, "Failed to register RPC handlers")) // lint:nopanic
```
Comment (james-prysm) [inline beacon-chain/sync/service.go]: is log.Fatal or panic preferred, i guess niether are preferred ...

Comment (james-prysm) [reply beacon-chain/sync/service.go]: is this change required vs the original code

File: beacon-chain/sync/fork_watcher.go [hunk 11]
```diff
@@ -38,101 +41,88 @@ func (s *Service) forkWatcher() {
...
+			log.WithField("topic", fullTopic).Debug("Removed RPC handler")
+		}
 	}
 
-	topicsToRemove := removedRPCTopics(beforeForkHandlerByTopic, forkHandlerByTopic)
-	for topic := range topicsToRemove {
-		fullTopic := topic + s.cfg.p2p.Encoding().ProtocolSuffix()
-		s.cfg.p2p.Host().RemoveStreamHandler(protocol.ID(fullTopic))
-		log.WithField("topic", fullTopic).Debug("Removed RPC handler")
+	// Unsubscribe from all gossip topics with the previous fork digest.
```
Comment (james-prysm) [inline beacon-chain/sync/fork_watcher.go:118]: this reads a bit strange because the comment reads different from the code I think, so looking at the code if we are registration action complete for registrationActionGossipExit we do **NOT** unsubscribe and return early?

File: beacon-chain/sync/service.go (hunk 10 above)
Comment (kasey) [reply beacon-chain/sync/service.go]: If the node can't register RPC handlers here, it can't answer RPC status messages, which means it can't peer. So it really is a fatal error for the node. I can change it to log.Fatal, I guess the reason to do that would be consistent formatting in logs?

Comment (kasey) [reply beacon-chain/sync/service.go]: But I think the behavior of silently stopping this method while the node starts up is wrong, because this is a fatal condition for the node that requires operator intervention.

File: beacon-chain/sync/subscriber.go (hunk 9 above)
Comment (kasey) [reply beacon-chain/sync/subscriber.go]: It wasn't a goroutine before. Now `ensurePeers` sets a context deadline for itself roughly aligned with the fork watcher interval.

File: beacon-chain/sync/fork_watcher.go (hunk 11 above)
Comment (kasey) [reply beacon-chain/sync/fork_watcher.go:118]: Is this more intuitive?
https://github.com/OffchainLabs/prysm/pull/15779/commits/b80d7546bc849dc3a0d492a90c461232ed1b0e58

File: beacon-chain/sync/once_test.go [hunk 12]
```diff
@@ -0,0 +1,40 @@
...
+						t.Fatal("expected second call to return true")
+					}
+				})
+			}
+		}
+	}
+	testCombos(digests, actions)
+	slices.Reverse(digests)
+	slices.Reverse(actions)
+	testCombos(digests, actions)
```
Comment (nalepae) [inline beacon-chain/sync/once_test.go:39]: What are the benefit of running again tests after reverting the inputs?

File: beacon-chain/sync/subscriber.go [hunk 13]
```diff
@@ -517,20 +533,13 @@ func (s *Service) pruneSubscriptions(t *subnetTracker, wantedSubnets map[uint64]
 // subscribeToSubnets subscribes to needed subnets and unsubscribe from unneeded ones.
 // This functions mutates the `subscriptionBySubnet` map, which is used to keep track of the current subscriptions.
 func (s *Service) subscribeToSubnets(t *subnetTracker) error {
-	// Do not subscribe if not synced.
-	if s.chainStarted.IsSet() && s.cfg.initialSync.Syncing() {
+	select {
+	default:
+		// If initialSyncComplete is not closed, bail out; subscribeWithParameters will keep calling this
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: Couln't we also wait for initial sync to be completed and immediately subscribe to subnets?
It would prevent a potential 12 seconds after initial sync completion without any subscription, and so some avoidable additional Req/Resp calls.

File: beacon-chain/sync/subscriber.go [hunk 14]
```diff
@@ -546,30 +555,37 @@ func (s *Service) subscribeToSubnets(t *subnetTracker) error {
...
 
-func (s *Service) ensureSubnetPeersAndSubscribe(tracker *subnetTracker) {
-	timeout := time.Duration(params.BeaconConfig().SecondsPerSlot) * time.Second
-	minPeers := flags.Get().MinimumPeersPerSubnet
+func (s *Service) trySubscribeSubnets(tracker *subnetTracker) {
 	logFields := tracker.logFields()
-	neededSubnets := computeAllNeededSubnets(s.cfg.clock.CurrentSlot(), tracker.getSubnetsToJoin, tracker.getSubnetsRequiringPeers)
-
 	if err := s.subscribeToSubnets(tracker); err != nil {
 		if errors.Is(err, errInvalidDigest) {
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: Can `subscribeToSubnets` return the `errInvalidDigest` error?

File: beacon-chain/sync/subscriber.go [hunk 15]
```diff
@@ -546,30 +555,37 @@ func (s *Service) subscribeToSubnets(t *subnetTracker) error {
...
 }
 
-func (s *Service) ensureSubnetPeersAndSubscribe(tracker *subnetTracker) {
-	timeout := time.Duration(params.BeaconConfig().SecondsPerSlot) * time.Second
-	minPeers := flags.Get().MinimumPeersPerSubnet
+func (s *Service) trySubscribeSubnets(tracker *subnetTracker) {
 	logFields := tracker.logFields()
-	neededSubnets := computeAllNeededSubnets(s.cfg.clock.CurrentSlot(), tracker.getSubnetsToJoin, tracker.getSubnetsRequiringPeers)
-
 	if err := s.subscribeToSubnets(tracker); err != nil {
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: `subscribeToSubnets` is only used in `trySubscribeSubnets`. Maybe can we merge them?

File: beacon-chain/sync/subscriber.go [hunk 16]
```diff
@@ -314,35 +318,47 @@ func (s *Service) registerSubscribers(epoch primitives.Epoch, digest [4]byte) {
...
+	base := p2p.GossipTopicMappings(topic, nse.Epoch)
 	if base == nil {
 		// Impossible condition as it would mean topic does not exist.
 		panic(fmt.Sprintf("%s is not mapped to any message in GossipTopicMappings", topic)) // lint:nopanic -- Impossible condition.
 	}
-	s.subscribeWithBase(s.addDigestToTopic(topic, digest), validator, handle)
+	s.subscribeWithBase(s.addDigestToTopic(topic, nse.ForkDigest), validator, handle)
 }
 
 func (s *Service) subscribeWithBase(topic string, validator wrappedVal, handle subHandler) *pubsub.Subscription {
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go:371]: `Provided topic already has an active subscription running` should be an error log now right?

File: beacon-chain/sync/subscriber.go [hunk 17]
```diff
@@ -314,35 +318,47 @@ func (s *Service) registerSubscribers(epoch primitives.Epoch, digest [4]byte) {
...
 				getSubnetsRequiringPeers: s.allDataColumnSubnets,
 			})
 		})
 	}
+	return true
+}
+
+func (s *Service) subscriptionRequestExpired(nse params.NetworkScheduleEntry) bool {
+	next := params.NextNetworkScheduleEntry(nse.Epoch)
+	return next.Epoch != nse.Epoch && s.cfg.clock.CurrentEpoch() > next.Epoch
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go:338]: `>` or `>=`?
Do we want to maintain subscription for the first epoch of the fork?

File: beacon-chain/sync/fork_watcher.go [hunk 18]
```diff
@@ -12,20 +12,23 @@ import (
...
 	for {
 		select {
 		// In the event of a node restart, we will still end up subscribing to the correct
 		// topics during/after the fork epoch. This routine is to ensure correct
 		// subscriptions for nodes running before a fork epoch.
-		case currSlot := <-slotTicker.C():
-			currEpoch := slots.ToEpoch(currSlot)
-			if err := s.registerForUpcomingFork(currEpoch); err != nil {
+		case <-slotTicker.C():
+			current := s.cfg.clock.CurrentEpoch()
```
Comment (nalepae) [inline beacon-chain/sync/fork_watcher.go:28]: Why not using the slot given by `<-slotTicker.C()`? It seems more expensive not to use it.

File: beacon-chain/sync/rpc.go [hunk 19]
```diff
@@ -122,38 +120,6 @@ func (s *Service) rpcHandlerByTopicFromFork(forkIndex int) (map[string]rpcHandle
...
-	if epoch >= beaconConfig.AltairForkEpoch {
-		return s.rpcHandlerByTopicFromFork(version.Altair)
-	}
-
-	return s.rpcHandlerByTopicFromFork(version.Phase0)
-}
-
 // addedRPCHandlerByTopic returns the RPC handlers that are added in the new map that are not present in the old map.
 func addedRPCHandlerByTopic(previous, next map[string]rpcHandler) map[string]rpcHandler {
 	added := make(map[string]rpcHandler)
```
Comment (nalepae) [inline beacon-chain/sync/rpc.go]: Maybe adding a hint with the size of `next`?

File: beacon-chain/sync/fork_watcher.go [hunk 20]
```diff
@@ -38,101 +41,88 @@ func (s *Service) forkWatcher() {
 }
 
 // registerForUpcomingFork registers appropriate gossip and RPC topic if there is a fork in the next epoch.
```
Comment (nalepae) [inline beacon-chain/sync/fork_watcher.go]: The name and the godoc of this functions do not describe the function:
Name and godoc talk about the next fork, while the function takes care of the current AND the next fork.

File: beacon-chain/sync/subscriber.go [hunk 21]
```diff
@@ -546,30 +555,37 @@ func (s *Service) subscribeToSubnets(t *subnetTracker) error {
 
 // subscribeWithParameters subscribes to a list of subnets.
 func (s *Service) subscribeWithParameters(p subscribeParameters) {
-	tracker := newSubnetTracker(p)
-	// Try once immediately so we don't have to wait until the next slot.
-	s.ensureSubnetPeersAndSubscribe(tracker)
-
 	go s.logMinimumPeersPerSubnet(p)
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: Does `s.logMinimumPeersPerSubnet` continue to run even after `subscribeWithParameters` exited?

File: beacon-chain/sync/fork_watcher.go [hunk 22]
```diff
@@ -12,20 +12,23 @@ import (
 // Is a background routine that observes for new incoming forks. Depending on the epoch
 // it will be in charge of subscribing/unsubscribing the relevant topics at the fork boundaries.
 func (s *Service) forkWatcher() {
```
Comment (nalepae) [inline beacon-chain/sync/fork_watcher.go]: The name of this function does not represent the fact that it is going to register for for current and upcomming forks and unregister from past forks.

File: beacon-chain/sync/subscriber.go (hunk 17 above)
Comment (nalepae) [reply beacon-chain/sync/subscriber.go:338]: Actually we do.

File: beacon-chain/sync/fork_watcher.go [hunk 23]
```diff
@@ -38,101 +41,88 @@ func (s *Service) forkWatcher() {
...
 	}
-
-	// Get the epoch after the fork epoch.
-	afterForkEpoch := currentFork.Epoch + 1
-
-	// Start de-registering if the current epoch is after the fork epoch.
-	if currentEpoch != afterForkEpoch {
-		return nil
+	if currentEpoch < current.Epoch+1 {
+		return nil // wait until we are 1 epoch into the fork
```
Comment (nalepae) [inline beacon-chain/sync/fork_watcher.go:95]: Not tested.

File: beacon-chain/sync/fork_watcher.go [hunk 24]
```diff
@@ -38,101 +41,88 @@ func (s *Service) forkWatcher() {
...
 	}
 
-	topicsToRemove := removedRPCTopics(beforeForkHandlerByTopic, forkHandlerByTopic)
-	for topic := range topicsToRemove {
-		fullTopic := topic + s.cfg.p2p.Encoding().ProtocolSuffix()
-		s.cfg.p2p.Host().RemoveStreamHandler(protocol.ID(fullTopic))
-		log.WithField("topic", fullTopic).Debug("Removed RPC handler")
+	// Unsubscribe from all gossip topics with the previous fork digest.
+	if s.digestActionDone(previous.ForkDigest, unregisterGossipOnce) {
+		return nil
```
Comment (nalepae) [inline beacon-chain/sync/fork_watcher.go:120]: Not tested.

File: beacon-chain/sync/subscriber.go (hunk 21 above)
Comment (nalepae) [reply beacon-chain/sync/subscriber.go]: Yes it actually does.

File: beacon-chain/sync/once_test.go (hunk 12 above)
Comment (kasey) [reply beacon-chain/sync/once_test.go:39]: Just proving there isn't some bug that manifests when the actions are run in a particular order. We could probably do without it.

File: beacon-chain/sync/fork_watcher.go (hunk 18 above)
Comment (kasey) [reply beacon-chain/sync/fork_watcher.go:28]: `slotTicker` chooses to guarantee that we get a message for every slot at the cost of potentially sending old slots over the channel. As a defensive programming measure I never use the slot value from slot ticker in this kind of situation as I think it's better to always ensure you are acting on the real current slot/epoch. That to me is worth the trivial expense of computing the current slot from the time.Now.

File: beacon-chain/sync/subscriber.go (hunk 17 above)
Comment (kasey) [reply beacon-chain/sync/subscriber.go:338]: Right, so `>` is correct.

File: beacon-chain/sync/subscriber.go (hunk 16 above)
Comment (kasey) [reply beacon-chain/sync/subscriber.go:371]: Yes we should no longer see these logs, so I agree with bumping this to error to flag that something is going wrong.

File: beacon-chain/sync/subscriber.go (hunk 14 above)
Comment (kasey) [reply beacon-chain/sync/subscriber.go]: no, I'm cleaning this up while combining `subscribeToSubnets` with `trySubscribeSubnets`.

File: beacon-chain/sync/service.go (hunk 10 above)
Comment (prestonvanloon) [reply beacon-chain/sync/service.go]: I think panic is not the right approach here. This could interrupt any in progress db transactions and cause other issues potentially. 

If this behavior needs to stop the client, can we surface the error up to the node and do a graceful shutdown ?

Comment (prestonvanloon) [reply beacon-chain/sync/service.go]: If that is too much refactoring for this PR, pls change back to log.Error and resolve in another PR. We shouldn't be panicking imo

Comment (kasey) [reply beacon-chain/sync/service.go]: Will do

File: beacon-chain/sync/rpc.go [hunk 25]
```diff
@@ -181,13 +147,12 @@ func removedRPCTopics(previous, next map[string]rpcHandler) map[string]bool {
...
+func (s *Service) registerRPCHandlers(nse params.NetworkScheduleEntry) error {
+	if s.digestActionDone(nse.ForkDigest, registerRpcOnce) {
+		return nil
+	}
 	// Get the RPC handlers for the current epoch.
-	handlerByTopic, err := s.rpcHandlerByTopicFromEpoch(currentEpoch)
+	handlerByTopic, err := s.rpcHandlerByTopicFromFork(nse.VersionEnum)
 	if err != nil {
 		return errors.Wrap(err, "rpc handler by topic from epoch")
 	}
```
Comment (prestonvanloon) [inline beacon-chain/sync/rpc.go:158]: This could be problematic that we are marking an action as done before it is done? Especially if it fails for some reason?

File: beacon-chain/sync/subscriber.go (hunk 13 above)
Comment (kasey) [reply beacon-chain/sync/subscriber.go]: updated

File: beacon-chain/sync/fork_watcher.go (hunk 24 above)
Comment (kasey) [reply beacon-chain/sync/fork_watcher.go:120]: Do you mean the digestActionDone check is not tested? I thought the unit tests on `digestActionDone` itself should cover this.

File: beacon-chain/sync/fork_watcher.go (hunk 23 above)
Comment (kasey) [reply beacon-chain/sync/fork_watcher.go:95]: Currently we have coverage in `TestService_CheckForNextEpochFork` that exercises the following code by calling `ensureDeregistrationForEpoch` with epoch+1. Will adding this case to show that calling with `== epoch` does not deregister suffice to cover the early return condition?:
```
			require.NoError(t, s.ensureDeregistrationForEpoch(tt.nextForkEpoch))
			assert.Equal(t, true, s.subHandler.digestExists(digest))
````

File: beacon-chain/sync/rpc.go (hunk 25 above)
Comment (kasey) [reply beacon-chain/sync/rpc.go:158]: I believe there was other feedback on this point from James, and there I mentioned that I had an earlier version that behaved more like a transaction, with a callback to commit that the action completed. But in this particular case there is no way for it to fail once and then succeed subsequently, so just marking it done right away is sufficient. I don't mind rebuilding the other "transactional version" and could do that pretty quickly, it's just more cluttered.

File: beacon-chain/sync/subscriber.go [hunk 26]
```diff
@@ -314,35 +318,47 @@ func (s *Service) registerSubscribers(epoch primitives.Epoch, digest [4]byte) {
...
+func (s *Service) subscriptionRequestExpired(nse params.NetworkScheduleEntry) bool {
+	next := params.NextNetworkScheduleEntry(nse.Epoch)
+	return next.Epoch != nse.Epoch && s.cfg.clock.CurrentEpoch() > next.Epoch
 }
 
 // subscribe to a given topic with a given validator and subscription handler.
 // The base protobuf message is used to initialize new messages for decoding.
-func (s *Service) subscribe(topic string, validator wrappedVal, handle subHandler, digest [4]byte) {
+func (s *Service) subscribe(topic string, validator wrappedVal, handle subHandler, nse params.NetworkScheduleEntry) {
 	<-s.initialSyncComplete
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: Shouldn't we add a context to `subscribe` and stop blocking on `<-s.initialSyncComplete` if the node is stopped during the initial sync?
So we ensure a graceful stop of `subscribe`?

File: beacon-chain/sync/subscriber.go [hunk 27]
```diff
@@ -504,89 +520,90 @@ func (s *Service) wrapAndReportValidation(topic string, v wrappedVal) (string, p
...
 	}
-
-	return nil
 }
 
-// subscribeWithParameters subscribes to a list of subnets.
-func (s *Service) subscribeWithParameters(p subscribeParameters) {
-	tracker := newSubnetTracker(p)
+func (s *Service) ensurePeers(ctx context.Context, tracker *subnetTracker) {
+	timeout := (time.Duration(params.BeaconConfig().SecondsPerSlot) * time.Second) - 100*time.Millisecond
```
Comment (nalepae) [inline beacon-chain/sync/subscriber.go]: Could `timeout` be defined in `tryEnsurePeers`?
`tryEnsurePeers` is only called in `ensurePeers`, so not sure we need to define `timeout` in `ensurePeers`.

File: beacon-chain/sync/subscriber.go (hunk 26 above)
Comment (kasey) [reply beacon-chain/sync/subscriber.go]: definitely

File: beacon-chain/sync/subscriber.go (hunk 27 above)
Comment (kasey) [reply beacon-chain/sync/subscriber.go]: can do

File: beacon-chain/sync/subscriber.go (hunk 26 above)
Comment (kasey) [reply beacon-chain/sync/subscriber.go]: Same for `subscribeWithParameters`.

File: beacon-chain/sync/fork_watcher.go (hunk 24 above)
Comment (nalepae) [reply beacon-chain/sync/fork_watcher.go:120]: I mean that the case where `s.digestActionDone` returns true (so specifically line 120) is not tested in `ensureDeregistrationForEpoch`.

**Review by nalepae — APPROVED** [review]

**Review by james-prysm — APPROVED** [review]

**Review by prestonvanloon — APPROVED** [review]
