### PR TITLE
Fix issue : Prevent makeslice panic from invalid Count values

### LINKED ISSUE #16223: Input Validation Missing in SendBeaconBlocksByRangeRequest
## Problem

**This is a robustness issue, not a security vulnerability.** No external trigger path exists that would allow a malicious peer to exploit this issue.

Discovered during in-process mutation/fuzzing: `SendBeaconBlocksByRangeRequest` lacks input validation for `req.Count`, causing a panic (`makeslice: cap out of range`) when creating a slice with an extremely large capacity value.

## Stack Trace

```log
error=runtime error: makeslice: cap out of range
...
github.com/prysmaticlabs/prysm/v5/beacon-chain/sync.SendBeaconBlocksByRangeRequest(...)
	beacon-chain/sync/rpc_send_request.go:65 +0x1a5
```

## Code Location

**File**: `beacon-chain/sync/rpc_send_request.go:65` (Line 81 in latest version)

```go
blocks := make([]interfaces.ReadOnlySignedBeaconBlock, 0, req.Count)  // Panic here
```

## Potential Root Cause

**Upstream risk**: `beacon-chain/sync/backfill/batch.go:127` (Line 151 in latest version)

```go
Count: uint64(b.end - b.begin)  // Potential underflow if b.end < b.begin
```

If `b.end < b.begin`, the subtraction underflows, producing an extremely large `Count` value that causes the panic.

## Suggested Fix

Add validation in `SendBeaconBlocksByRangeRequest`. Also consider defensive check in `blockRequest()` to prevent underflow at source.

### Has this worked before in a previous version?

```text

```

### 🔬 Minimal Reproduction

_No response_

### Error

```text

```

### Platform(s)

_No response_

### What version of Prysm are you running? (Which release)

_No response_

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Add defensive checks to prevent panic from  large Count values that could result from unsigned integer underflow:

1. In batch.blockRequest() and batch.blobRequest(): Return Count=0 when end <= begin, preventing the underflow at the source.

2. In SendBeaconBlocksByRangeRequest(): Cap slice capacity to MaxRequestBlock before allocation to prevent panic even if upstream code produces invalid values.

**Which issues(s) does this PR fix?**

Fixes #16223

**Other notes for review**

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).
- [x] I have added a description with sufficient context for reviewers to understand this PR.
- [x] I have tested that my changes work as expected and I added a testing plan to the PR description (if applicable).

### CODE REVIEW

File: beacon-chain/sync/backfill/batch.go [hunk 1]
```diff
@@ -154,6 +163,14 @@ func (b batch) blockRequest() *eth.BeaconBlocksByRangeRequest {
...
+	// unsigned integer underflow which would produce an astronomically large Count.
+	if b.end <= b.begin {
+		return &eth.BlobSidecarsByRangeRequest{
+			StartSlot: b.begin,
+			Count:     0,
+		}
+	}
 	return &eth.BlobSidecarsByRangeRequest{
 		StartSlot: b.begin,
 		Count:     uint64(b.end - b.begin),
```
Comment (farazdagi) [inline beacon-chain/sync/backfill/batch.go]: `primitives.Slot` has several methods for subtraction: `Sub`, `SafeSub`, `FlooredSubSlot` (basically, an attempt on unchecked/checked/saturating arithmetics). I suppose the original idea of those methods in primitives, was to enforce such and similar invariants. 

So, potentially, instead of defensive check `b.end.FlooredSubSlot(b.begin)` could have been used (and probably should anyway, as manual conversion for types that have their arithmetic defined, seems to defeat the purpose of having separate types).

Comment (prestonvanloon) [reply beacon-chain/sync/backfill/batch.go]: thanks so much!

**Review by james-prysm — APPROVED** [review]
