### PR TITLE
call LogValidatorGainsAndLosses at end of epoch

### LINKED ISSUE #7699: performance aggregates are wrong
# 🐞 Bug Report

### Description
The validator performance aggregates logged in `LogValidatorGainsAndLosses` may miss attestations that are included later

### Has this worked before in a previous version?

No

### The problem:

The performance stats including averages to `InclusionDistance`, `InclusionSlot`, `CorrectlyVotedHead`, `CorrectlyVotedTarget` and `CorrectlyVotedSource` are updated on each call to `LogValidatorGainsAndLosses`. This function is called at the beginning of each epoch. 

This function in turn calls `GetValidatorPerformance` which precomputes the validator performances for the previous epoch. The problem with this latter function is that it treats as missing any attestation that hasn't been included up to this point. Therefore many attestations are counted as missing in the performance summary when they are in fact included later. 

### Possible solutions:

- Call `LogValidatorGainsAndLosses` at the end of the epoch instead of at the beginning to ensure that all attestations that are reported as missing are indeed missing. This is the minimal solution to the above problem. 
- Allow `GetValidatorPerformance` to be given an epoch to compute, so that if it is called with a past epoch it gets the status of the last slot of the previous epoch.  This will allow someone to fetch the performance of a previous epoch knowing returning the right inclusion distance/missing status. Currently, if one calls before 32 slots have passed between the previous attestation, one has no way of knowing for certain if a missing attestation would be missing or if may be included later. In practical terms this means that a user needs to poll this precisely at epoch end to be certain of obtaining the right asnwer. 
- Make `GetValidatorPerformance` return the performance of epoch `CurrentEpoch - 2` so as to avoid the previous problem

### Related issue: 

The api call `/eth/v1alpha1/validators/performance` calls directly `GetValidatorPerformance`, therefore an API user needs to call precisely at epoch ends to avoid the problem mentioned above. 

### Extra Info: 

related discussion in Discord: 
https://discord.com/channels/476244492043812875/730447046930071672/772172731046952989

### PR DESCRIPTION
**Pull request by potuz**
**What type of PR is this?**

 Bug fix

**What does this PR do? Why is it needed?**

Ensures that the reported attestation performances are up-to date, in particular if an attestation is included in the next epoch, the inclusion distance and inclusion slot is reported correctly instead of missing. 

**Which issues(s) does this PR fix?**

Fixes #7699

**Other notes for review**

I've been testing this for about a day and it does not hurt cpu usage having the precompute regenerate the state in the end of the epoch as opposed to the beginning as it is currently.

### CODE REVIEW

File: validator/client/metrics.go [hunk 1]
```diff
@@ -122,8 +122,8 @@ var (
 // and penalties over time, percentage gain/loss, and gives the end user a better idea
 // of how the validator performs with respect to the rest.
 func (v *validator) LogValidatorGainsAndLosses(ctx context.Context, slot uint64) error {
-	if slot%params.BeaconConfig().SlotsPerEpoch != 0 || slot <= params.BeaconConfig().SlotsPerEpoch {
-		// Do nothing unless we are at the start of the epoch, and not in the first epoch.
+	if (slot+1)%params.BeaconConfig().SlotsPerEpoch != 0 || slot <= params.BeaconConfig().SlotsPerEpoch {
```
Comment (terencechain) [inline validator/client/metrics.go:125]: I think this should be at the start of the epoch. 

Example, at slot 64, it logs balances of epoch 1 that is slot 32 to 63. End of the epoch is not exactly accurate by definition

**Review by terencechain — CHANGES_REQUESTED** [review]

File: validator/client/metrics.go (hunk 1 above)
Comment (potuz) [reply validator/client/metrics.go:125]: The thing is the call to `GetValidatorPerformance`, the error if you call it before the attestation is included is a lot: it changes from missing to not missing. This affects the summary logged in the end of that function. 

As for the balances, the error if any is minimal (only for any change in the last slot), and is also irrelevant cause any difference in the balance will be included in the next measurement. But the error in inclusion_distance, voted head, etc. is never corrected since these are not cumulative.

**Comment by prestonvanloon** [comment]
I am not convinced this fixes #7699. You could attest at slot 62 (epoch 2) and it's not included until slot 94 (epoch 3). The participation for epoch 2 would be incorrect when you query it at the last slot of epoch 2.

`ValidatorPerformanceRequest` needs to accept an Epoch parameter and return whether or not the request is still counting participation. The validator client should wait until epoch+1 to query the performance in epoch, otherwise the values are not accurate.

**Comment by potuz** [comment]
> I am not convinced this fixes #7699. You could attest at slot 62 (epoch 2) and it's not included until slot 94 (epoch 3). The participation for epoch 2 would be incorrect when you query it at the last slot of epoch 2.
> 
No because when you call at the end of epoch 2 you will be getting the right answer for epoch 1, when you query at epoch 3 you will be getting the right answer for epoch 2. 

I've checked this on different scenarios on attestations missed, included in the same epoch and in the next one and it works as intended

> `ValidatorPerformanceRequest` needs to accept an Epoch parameter and return whether or not the request is still counting participation. The validator client should wait until epoch+1 to query the performance in epoch, otherwise the values are not accurate.

This is another solution, but as I mentioned in the issue, I have that coded as well, it's a bit more problematic to add tests, and the code on this one is minimal, that's why I chose this,.

**Comment by terencechain** [comment]
In this case, it still can miss one slot. Say we log at slot 95 (end of epoch2), the attestations in block 95 can still include votes from epoch1. But in this implementation, such attestations will be missed

**Comment by potuz** [comment]
> In this case, it still can miss one slot attestation. Say we log at slot 95 (end of epoch3), the attestations in block slot 95 can still include votes from epoch2. But in this implementation, such attestations will be missed

Yes that is true, it misses only attestations of the maximal inclusion delay that happen to be attested in the last slots of an epoch. The solution to this is to report on epoch -2  insteas of epoch -1 in the function `getvalidatorperformace`

I thought that the minimal impact of that unlikely event is less than than the epoch delay in the API call

File: validator/client/runner.go [hunk 2]
```diff
@@ -138,6 +135,9 @@ func run(ctx context.Context, v Validator) {
 
 			// Start fetching domain data for the next epoch.
 			if helpers.IsEpochEnd(slot) {
+				if err := v.LogValidatorGainsAndLosses(slotCtx, slot); err != nil {
```
Comment (terencechain) [inline validator/client/runner.go:138]: Can we revert this change?  The slot time check is within `LogValidatorGainsAndLosses`

File: validator/client/metrics.go (hunk 1 above)
Comment (terencechain) [inline validator/client/metrics.go:125]:
```suggestion
	if helpers.IsEpochEnd(slot) || slot <= params.BeaconConfig().SlotsPerEpoch {
```

File: validator/client/runner.go (hunk 2 above)
Comment (terencechain) [reply validator/client/runner.go:138]: Second thought, let's move this after L178

**Review by terencechain — APPROVED** [review]

**Comment by terencechain** [comment]
Thanks for this. Very useful fix indeed

**Comment by potuz** [comment]
> Thanks for this. Very useful fix indeed

thanks for your patience
