### PR TITLE
Make Sure ChainHeadStream Remains Open

### LINKED ISSUE #4254: panic when using the grpc StreamChainHead
when trying to stream chain head i am getting this error in  the server logs and in the client app
```
time="2019-12-11 06:22:38" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 249030 [running]:
runtime/debug.Stack(0xc0000b6690, 0x1713797, 0x5)
	GOROOT/src/runtime/debug/stack.go:24 +0x9d
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x1aa1200, 0xc004a170e0, 0x150c6e0, 0x251af70, 0xc00359d748, 0xc001dcec64)
	shared/traceutil/recovery_interceptor_option.go:29 +0x155
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x1aa1200, 0xc004a170e0, 0x150c6e0, 0x251af70, 0x18d5430, 0x0, 0xc00359d780)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:52 +0x5a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.StreamServerInterceptor.func1.1(0x1aacf80, 0xc00346c840, 0xc000010540, 0xc00359db20)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:40 +0x9f
panic(0x150c6e0, 0x251af70)
	GOROOT/src/runtime/panic.go:679 +0x1b2
github.com/prysmaticlabs/prysm/beacon-chain/rpc/beacon.(*Server).StreamChainHead(0xc00181e1b0, 0xc0034c5dc0, 0x1aaf8c0, 0xc004f335f0, 0x0, 0x0)
	beacon-chain/rpc/beacon/blocks.go:158 +0x12c
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconChain_StreamChainHead_Handler(0x1689d20, 0xc00181e1b0, 0x1aac560, 0xc0034c5da0, 0xc0034a9a00, 0x32)
	bazel-out/k8-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/beacon_chain.pb.go:3177 +0x10c
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.StreamServerInterceptor.func1(0x1689d20, 0xc00181e1b0, 0x1aac620, 0xc0034c5d40, 0xc0034c5cc0, 0x18d5068, 0xc001c34901, 0xc0034c5d40)
	external/com_github_grpc_ecosystem_go_grpc_middleware/tracing/opentracing/server_interceptors.go:47 +0x144
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x1689d20, 0xc00181e1b0, 0x1aac620, 0xc0034c5d40, 0x32, 0xc00273bb80)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:49 +0x5f
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1(0x1689d20, 0xc00181e1b0, 0x1aacf80, 0xc00346c840, 0xc0034c5cc0, 0xc0034c5ce0, 0x43e686, 0xc0034c5d20)
	external/com_github_grpc_ecosystem_go_grpc_prometheus/server_metrics.go:121 +0xeb
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x1689d20, 0xc00181e1b0, 0x1aacf80, 0xc00346c840, 0x20, 0xc0034c5d20)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:49 +0x5f
github.com/grpc-ecosystem/go-grpc-middleware/recovery.StreamServerInterceptor.func1(0x1689d20, 0xc00181e1b0, 0x1aacf80, 0xc00346c840, 0xc0034c5cc0, 0xc0034c5d00, 0x0, 0x0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:44 +0xd0
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x1689d20, 0xc00181e1b0, 0x1aacf80, 0xc00346c840, 0xc00103fb90, 0x43eef8)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:49 +0x5f
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0x1689d20, 0xc00181e1b0, 0x1aacf80, 0xc00346c840, 0xc0034c5cc0, 0x18d5068, 0x1aa1200, 0xc004a170e0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/chain.go:58 +0xcf
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00185cf00, 0x1ab4360, 0xc002549b00, 0xc0043b6900, 0xc0017c9d10, 0x2524c60, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:1209 +0x45a
google.golang.org/grpc.(*Server).handleStream(0xc00185cf00, 0x1ab4360, 0xc002549b00, 0xc0043b6900, 0x0)
	external/org_golang_google_grpc/server.go:1282 +0xd30
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc003190e60, 0xc00185cf00, 0x1ab4360, 0xc002549b00, 0xc0043b6900)
	external/org_golang_google_grpc/server.go:717 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:715 +0xa1
"
```

cheers

### PR DESCRIPTION
**Pull request by rauljordan**
This resolves #4254 

---

# Description

**Write why you are making the changes in this pull request**

Previously, as soon as we sent a chain head over the `ChainHeadStream` function our `beacon-chain/rpc/beacon/blocks.go` file, we would `return`. Instead, we should keep the stream open as long as the client wants to.

**Write a summary of the changes you are making**

This PR modifies the function so it does not return after a stream send.

**Link anything that would be helpful or relevant to the reviewers**

Having a lot of issues testing this as gomock isn't playing nice. Tried to cancel the context after a `Do` call in gomock, but nothing happens and the test never finishes. @prestonvanloon offered to help.

### CODE REVIEW

File: beacon-chain/rpc/beacon/blocks_test.go [hunk 1]
```diff
@@ -475,12 +476,16 @@ func TestServer_StreamChainHead_OnHeadUpdated(t *testing.T) {
 			PreviousJustifiedEpoch:     3,
 			PreviousJustifiedBlockRoot: pjRoot[:],
 		},
-	).Return(nil)
+	).Do(func(arg0 interface{}) {
+		cancel()
+		exitRoutine <- true
+	})
+	mockStream.EXPECT().Context().Return(ctx)
```
Comment (prestonvanloon) [inline beacon-chain/rpc/beacon/blocks_test.go]: I think you need to add `AnyTimes()`. Test is failing.
