### PR TITLE
Fix Status Messages During Genesis

### LINKED ISSUE #6006: Return ZeroHash Instead of GenesisBlockRoot
# 🐞 Bug Report

Currently in pre-genesis we return the genesis block root instead of a zerohash as the 
finalized root.

### Description

In pregenesis due to how our `chainservice` is structured, we return the genesis block root 
instead of the zerohash as our finalized checkpoint. A workaround was done in witti, to make
a special case for genesis. This issue is to track the resolution of the correct behaviour in master.

### Has this worked before in a previous version?

No

## 🔬 Minimal Reproduction

Peer a Prysm Node With a Lighthouse Node.

## 🔥 Error

```
time="2020-05-26 22:24:21" level=warning msg="Failed to handle p2p RPC" error="invalid finalized root" peer=16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv prefix=sync topic="/eth2/beacon_chain/req/status/1/ssz_snappy"
```

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

During genesis our finalized checkpoints were our genesis blocks whereas the correct behaviour is
to take the finalized checkpoint in the genesis state.

- [x] Set checkpoints correctly
- [x] Validate Genesis Status Messages Correctly
- [x] Unit Test

**Which issues(s) does this PR fix?**

Fixes #6006

**Other notes for review**

### CODE REVIEW

File: beacon-chain/blockchain/service.go [hunk 1]
```diff
@@ -352,9 +352,9 @@ func (s *Service) saveGenesisData(ctx context.Context, genesisState *stateTrie.B
 		return errors.Wrap(err, "could save genesis block root")
 	}
 
-	genesisCheckpoint := &ethpb.Checkpoint{Root: genesisBlkRoot[:]}
+	// finalized checkpoint at genesis is a zero hash.
```
Comment (terencechain) [inline beacon-chain/blockchain/service.go:355]:
```suggestion
	// Finalized checkpoint at genesis is a zero hash.
```
