### PR TITLE
Fix Overflow in Status Check

### LINKED ISSUE #5358: Node reports out of sync to start off in dev cluster v0.11
In dev cluster run, the beacon node doesn't look healthy to start with. This is right after the last deposit before creating the genesis state

```
{"message":"Node is unhealthy!","prefix":"prometheus","severity":"WARNING","statuses":"*p2p.Service: OK\n*powchain.Service: OK\n*attestations.Service: OK\n*blockchain.Service: OK\n*initialsync.Service: OK\n*sync.Service: ERROR out of sync\n*rpc.Service: OK\n*prometheus.Service: OK\n"}
```

### PR DESCRIPTION
**Pull request by nisdas**
Resolves #5358 
- [x] We dont subtract but instead add in the check.
- [x] Add regression test.

### CODE REVIEW

File: beacon-chain/sync/service_test.go [hunk 1]
```diff
@@ -0,0 +1,35 @@
+package sync
+
+import (
+	"testing"
+	"time"
+
+	stateTrie "github.com/prysmaticlabs/prysm/beacon-chain/state"
+	pb "github.com/prysmaticlabs/prysm/proto/beacon/p2p/v1"
+
```
Comment (nisdas) [inline beacon-chain/sync/service_test.go:9]:
```suggestion
```

File: beacon-chain/sync/service_test.go [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+	mockChain "github.com/prysmaticlabs/prysm/beacon-chain/blockchain/testing"
+
```
Comment (nisdas) [inline beacon-chain/sync/service_test.go:11]:
```suggestion
```
