### PR TITLE
Better Handling of Subscriber Errors in Logs Streams

### LINKED ISSUE #8430: Beacon Node Logs Stop Appearing With Web UI
# 🐞 Bug Report

### Description

It has been reported by users that when running with the web-ui beacon node logs eventually stop appearing, and after a few hours the validator attached stops functioning leading to missed attestations.

### Has this worked before in a previous version?

Before v1.2.0

## 🔬 Minimal Reproduction

Run the beacon node and validator with the web ui to trigger the error. This eventually leads to 
the beacon node logs going missing and the validator eventually having missing attestations.

## 🔥 Error

This has been brought up offline and in #8314 .

**What version of Prysm are you running? (Which release)**

v1.2

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by rauljordan**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

Thanks to @nisdas, after doing some investigation of why the beacon node gets into a deadlock when running the web ui, he was able to identify the following offender:

```
#    0x14d760f    reflect.rselect+0x38f                                        GOROOT/src/runtime/select.go:566
#    0x151773b    reflect.Select+0x19b                                        GOROOT/src/reflect/value.go:2260
#    0x1f2ca44    github.com/prysmaticlabs/prysm/shared/event.(*Feed).Send+0x5a4                    shared/event/feed.go:170
#    0x24caab2    github.com/prysmaticlabs/prysm/shared/logutil.(*StreamServer).Write+0x72            shared/logutil/stream.go:69
#    0x152ad66    io.(*multiWriter).Write+0x86
```

Essentially, the subscriber to the event feed where beacon node logs are being sent to is blocked and does not get unblocked at all.

```go
func (ns *Server) StreamBeaconLogs(_ *ptypes.Empty, stream pb.Health_StreamBeaconLogsServer) error {
    ch := make(chan []byte, ns.StreamLogsBufferSize)
    defer close(ch)
    sub := ns.LogsStreamer.LogsFeed().Subscribe(ch)
    defer sub.Unsubscribe()
```

We believe the buffer size is too small, and also, we should not be defer closing a buffered channel this way in a grpc call. Additionally, we were **not handling** a select case for subscriber errors. If there was ever an error in the subscription, we would never exit the function and likely that's where the beacon node logs were getting stuck without our awareness.

**Which issues(s) does this PR fix?**

Fixes #8430

### CODE REVIEW

File: beacon-chain/rpc/node/server.go [hunk 1]
```diff
@@ -224,7 +224,6 @@ func (ns *Server) ListPeers(ctx context.Context, _ *ptypes.Empty) (*ethpb.Peers,
 // StreamBeaconLogs from the beacon node via a gRPC server-side stream.
 func (ns *Server) StreamBeaconLogs(_ *ptypes.Empty, stream pb.Health_StreamBeaconLogsServer) error {
 	ch := make(chan []byte, ns.StreamLogsBufferSize)
-	defer close(ch)
```
Comment (prestonvanloon) [inline beacon-chain/rpc/node/server.go:227]: when is this closed?

**Review by prestonvanloon — APPROVED** [review]
