### PR TITLE
Embedded mainnet genesis state + load genesis.ssz from file

### LINKED ISSUE #8209: Allow running beacon chain node without connecting to Ethereum 1 node
# 💎 Issue

### Background

All other Ethereum 2.0 clients like Teku, Nimbus, and Lighthouse allow running Beacon chain node without connecting to Ethereum 1 JSON RPC endpoint.
Prysm can't start without Ethereum 1 endpoint and panic with error:
```
time="2021-01-05 16:21:58" level=fatal msg="cannot create genesis state: no eth1 http endpoint defined" prefix=powchain
```
### Description
Make `--http-web3provider` optional. So beacon node can start without connecting to Ethereum 1 endpoint and to be compliant with the behavior of other Ethereum 2.0 clients.

@potuz

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

This feature allows users to skip generating the genesis state for mainnet, which often takes several hours of reading eth1 deposit data.

**Which issues(s) does this PR fix?**

Fixes #8209 

**Other notes for review**

Summary of key changes:
- Refactored SaveGenesisData from blockchain and interop to a db method. Added tests for this method as well
- Added functionality to support embedded mainnet state, and future states. Only mainnet is embedded at this time.
- Added support for `--genesis-state=/path/to/genesis.ssz` flag to load a file from genesis. This functionality has some UX features such as checking the genesis state matches the beacon config and acting as a no-op when the user has initialized the genesis state already with the same state. 
- Some test helpers to reduce scope of this PR. With embedded mainnet genesis, many of the mock values would need to change in test so I opted to have tests avoid using embedded state instead of updating all of those values.

Note: github review UI says that ssz files are empty, they are not empty.

### CODE REVIEW

File: beacon-chain/db/iface/errors.go [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package iface
+
+import (
+	"errors"
+)
+
+var (
+	// ErrExistingGenesisState is an error when the user attempts to save a different genesis state
+	// when one already exists in a database.
+	ErrExistingGenesisState = errors.New("genesis state exists already")
```
Comment (rauljordan) [inline beacon-chain/db/iface/errors.go:10]:
```suggestion
	ErrExistingGenesisState = errors.New("genesis state exists already in the DB")
```

Comment (rauljordan) [reply beacon-chain/db/iface/errors.go:10]: More clarity to the user

File: beacon-chain/db/iface/interface.go [hunk 2]
```diff
@@ -99,6 +99,11 @@ type HeadAccessDatabase interface {
 	// Block related methods.
 	HeadBlock(ctx context.Context) (*eth.SignedBeaconBlock, error)
 	SaveHeadBlockRoot(ctx context.Context, blockRoot [32]byte) error
+
+	// Genesis operations.
+	LoadGenesisFromFile(ctx context.Context, filePath string) error
```
Comment (rauljordan) [inline beacon-chain/db/iface/interface.go:104]: use io.Reader here or ReadCloser, makes it more extensible. Imagine in the future someone wants to read the genesis state from some other source that isn't a file

File: beacon-chain/blockchain/service.go [hunk 3]
```diff
@@ -336,38 +334,20 @@ func (s *Service) Status() error {
...
 func (s *Service) saveGenesisData(ctx context.Context, genesisState iface.BeaconState) error {
-	stateRoot, err := genesisState.HashTreeRoot(ctx)
-	if err != nil {
-		return err
+	if err := s.cfg.BeaconDB.SaveGenesisData(ctx, genesisState); err != nil {
+		return errors.Wrap(err, "could not save genesis data")
+	}
+	genesisBlk, err := s.cfg.BeaconDB.GenesisBlock(ctx)
+	if err != nil || genesisBlk == nil {
+		return errors.Wrap(err, "could not load genesis block")
```
Comment (terencechain) [inline beacon-chain/blockchain/service.go:342]: This would just return `nil` if `nil || true`

```go
var err error
require.Equal(t, nil, errors.Wrap(err, "could not load genesis block"))
```

Perhaps it's missing a test case? 🤔

File: beacon-chain/db/kv/genesis.go [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+	}
+
+	if err := s.SaveHeadBlockRoot(ctx, genesisBlkRoot); err != nil {
+		return errors.Wrap(err, "could not save head block root")
+	}
+	if err := s.SaveGenesisBlockRoot(ctx, genesisBlkRoot); err != nil {
+		return errors.Wrap(err, "could not save genesis block root")
+	}
+
+	genesisCheckpoint := &eth.Checkpoint{Root: genesisBlkRoot[:]}
```
Comment (terencechain) [inline beacon-chain/db/kv/genesis.go:50]: We need to be careful here. There's two types of genesis checkpoint:
1. `&eth.Checkpoint{Root: genesisBlkRoot[:]}`
2. `&eth.Checkpoint{Root: params.BeaconConfig().ZeroHash}`

I forgot which is used for peering (i think 2?) 

cc @nisdas for feedback

File: beacon-chain/db/kv/genesis.go [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+	if !bytes.Equal(gs.Fork().CurrentVersion, params.BeaconConfig().GenesisForkVersion) {
+		return fmt.Errorf("loaded genesis fork version (%#x) does not match config genesis "+
+			"fork version (%#x)", gs.Fork().CurrentVersion, params.BeaconConfig().GenesisForkVersion)
+	}
+
+	return s.SaveGenesisData(ctx, gs)
+}
+
+// EnsureEmbeddedGenesis checks that a genesis block has been generated when an embedded genesis
+// state is used. If a genesis block does not exist, but a genesis does, then we should call
```
Comment (terencechain) [inline beacon-chain/db/kv/genesis.go:105]:
```suggestion
// state is used. If a genesis block does not exist, but a genesis state does, then we should call
```

File: beacon-chain/db/kv/state.go [hunk 6]
```diff
@@ -42,8 +45,19 @@ func (s *Store) State(ctx context.Context, blockRoot [32]byte) (iface.BeaconStat
 func (s *Store) GenesisState(ctx context.Context) (iface.BeaconState, error) {
 	ctx, span := trace.StartSpan(ctx, "BeaconDB.GenesisState")
 	defer span.End()
+
+	cached, err := genesis.State(params.BeaconConfig().ConfigName)
+	if err != nil {
+		traceutil.AnnotateError(span, err)
+		return nil, err
+	}
+	span.AddAttributes(trace.BoolAttribute("cache_hit", cached != nil))
```
Comment (terencechain) [inline beacon-chain/db/kv/state.go:54]: Nice use of span attribute!

File: beacon-chain/blockchain/service.go (hunk 3 above)
Comment (prestonvanloon) [reply beacon-chain/blockchain/service.go:342]: Yes, that is fine. Basically would be an error like "could not load genesis block: nil" which would be indicative that it was a nil genesis block. 

I suppose I could expand this if anyone didnt understand that it was nil

Comment (terencechain) [reply beacon-chain/blockchain/service.go:342]: I dont think it would be `could not load genesis block: nil`, the err would literally be `nil`

File: beacon-chain/db/kv/genesis.go (hunk 4 above)
Comment (prestonvanloon) [reply beacon-chain/db/kv/genesis.go:50]: I think this was meant to be genesisState.FinalizedCheckpoint()

https://github.com/prysmaticlabs/prysm/blob/beadec32b8a6260f6c5f91603d159c2d0e22b19e/beacon-chain/blockchain/service.go#L373

Comment (prestonvanloon) [reply beacon-chain/db/kv/genesis.go:50]: This looks like a disparity between interop and blockchain production routine. I will use the production path instead of the interop path.

Comment (prestonvanloon) [reply beacon-chain/db/kv/genesis.go:50]: Actually, looks like i can remove all of this checkpoint stuff. It wasn't used in production, only in interop for some reason

File: beacon-chain/blockchain/service.go (hunk 3 above)
Comment (prestonvanloon) [reply beacon-chain/blockchain/service.go:342]: Got it, i'll use fmt.Errorf, ty

**Review by rauljordan — APPROVED** [review]

**Review by Oleksandr-prog — APPROVED** [review]
