### PR TITLE
Change Log Level of Genesis Time Info Log in RPC

### LINKED ISSUE #6832: Incorrect log level "genesis time notification"
# 🐞 Bug Report

I get a lot of these
```
time=""2020-08-02 17:16:16"" level=info msg=""Sending genesis time notification to connected validator clients"" prefix=""rpc/validator""
```
I guess for every key loaded on the validator there is this logged once.

Beacon log:
[genesis time log.txt](https://github.com/prysmaticlabs/prysm/files/5012564/genesis.time.log.txt)

### Has this worked before in a previous version?

Yes

## 🔬 Minimal Reproduction

Load lots of keys, start validator and beacon

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

https://github.com/stefa2k/prysm-docker-compose docker tag `HEAD-f414cf`

### PR DESCRIPTION
**Pull request by rauljordan**
Resolves #6832, we were logging something at info level that should have been at debug level in rpc/validator: Sending genesis time notification to connected validator clients

### CODE REVIEW

File: beacon-chain/rpc/validator/server_test.go [hunk 1]
```diff
@@ -27,9 +28,15 @@ import (
 	"github.com/prysmaticlabs/prysm/shared/testutil/assert"
 	"github.com/prysmaticlabs/prysm/shared/testutil/require"
 	"github.com/prysmaticlabs/prysm/shared/trieutil"
+	"github.com/sirupsen/logrus"
 	logTest "github.com/sirupsen/logrus/hooks/test"
 )
 
+func init() {
```
Comment (farazdagi) [inline beacon-chain/rpc/validator/server_test.go:35]: I believe a better place for this will be in `validator_test` (where we have `TestMain`, it should actually go into `TestMain` function)

Comment (rauljordan) [reply beacon-chain/rpc/validator/server_test.go:35]: Will do!

Comment (farazdagi) [reply beacon-chain/rpc/validator/server_test.go:35]: To clarify: instead of using `init()`, just put log configuring statements into `validator_test:TestMain()`.

Comment (rauljordan) [reply beacon-chain/rpc/validator/server_test.go]: Fixed
