### PR TITLE
Send correct state root with finalization event

### LINKED ISSUE #13752: `finalized_checkpoint` event returns incorrect data
### Describe the bug

The `finalized_checkpoint` event in the REST API is returning incorrect data for the `state_root` field.   For example we received this event:

```
{"block":"0x211b4dfc8b567ee7d962d7791137fe3e072b98f98cafda94c8c489cc09e41f25","state":"0xcbb0b137bf6f9d4102fe4fda25fa649ec333ae069a3c9e13608b12221c33fdfe","epoch":"270005"}
```

but the state ID provided does not appear to map to any known state.  Also, the provided block ID does not map to the provided state either:

```
curl -s http://localhost:1234/eth/v2/beacon/blocks/0x211b4dfc8b567ee7d962d7791137fe3e072b98f98cafda94c8c489cc09e41f25 | jq -r .data.message.state_root
0x8e238154f30f29ebbdaa2a52ab4b429167a034baac4ed29d43e0222fef1b083f
```

### Has this worked before in a previous version?

_No response_

### 🔬 Minimal Reproduction

_No response_

### Error

_No response_

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

beacon-chain version Prysm/v5.0.0/b7b017f5b607f04d4e9056a1ec8a6851a9c7da29. Built at: 2024-02-22 03:14:13+00:00

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

When sending the finalized event to the event feed we send the root of the _received_ block's state as the finalized state root, but it should be the root of the _finalized_ block's state.

**Which issues(s) does this PR fix?**

Fixes #13752

### CODE REVIEW

File: beacon-chain/blockchain/receive_block_test.go [hunk 1]
```diff
@@ -378,3 +380,38 @@ func TestHandleBlockBLSToExecutionChanges(t *testing.T) {
...
+		Root:  sbbRoot[:],
+	}))
+
+	s.sendNewFinalizedEvent(s.ctx, st)
+
+	require.Equal(t, 1, len(notifier.ReceivedEvents()))
+	e := notifier.ReceivedEvents()[0]
+	assert.Equal(t, statefeed.FinalizedCheckpoint, int(e.Type))
+	fc, ok := e.Data.(*ethpbv1.EventFinalizedCheckpoint)
+	require.Equal(t, true, ok, "event has wrong data type")
```
Comment (saolyn) [inline beacon-chain/blockchain/receive_block_test.go:412]: If it's true then it should be okay, why do you have what seems like an error message here as well?

Comment (nalepae) [reply beacon-chain/blockchain/receive_block_test.go:412]: In the `require.Equal` fails during tests execution, then `"event has wrong data type"` is displayed. It helps for test debugging.
