### PR TITLE
Prevent Exporting False Positive Slashing Event Due to Old Prysm DB Schema Bug

### LINKED ISSUE #8893: Invalid attestations in the slashing protection export
# 🐞 Bug Report

### Description

We had a user trying to migrate their slashing protection database from prysm to lighthouse.  Their JSON export had some entries that would have been slashable but were unsigned, so Lighthouse was unable to import them:

Screen Shot 2021-05-14 at 1 53 12 PM

## 🌍  Your Environment

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.3.9
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by rauljordan**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

A user came across an interesting, corrupted slashing protection history from their Prysm validator database that looked something like this:

```js
"signed_attestations": [
  { source: 0, target: 102122 },
  { source: 1, target: 2},
  ...
]
```
Leading to all attestations in that list appearing as slashable after the first entry. This was identified as a result of an old slashing protection database schema Prysm used and has since deprecated. We estimate this old schema affects users that were attesting with Prysm since December 2020. I personally confirmed the bug happened to me as well as I have been validating since then and received a similar slashing protection export.

As a layer of protection, we add special edge-case handling for that corrupted scenario as we cannot safely account for this bug in a general way without introducing further bug risk or more false positives to Prysm slashing protection. This PR adds a regression test to ensure the bug does not manifest itself again.
  
**Which issues(s) does this PR fix?**

Fixes #8893

### CODE REVIEW

File: validator/slashing-protection/local/standard-protection-format/export.go [hunk 1]
```diff
@@ -120,7 +120,20 @@ func signedAttestationsByPubKey(ctx context.Context, validatorDB db.Database, pu
...
-	for _, att := range history {
+	for i := 0; i < len(history); i++ {
+		att := history[i]
+		// Special edge case due to a bug in Prysm's old slashing protection schema. The bug
+		// manifests itself as the first entry in attester slashing protection history
+		// having a target epoch greater than the next entry in the list. If this manifests,
+		// we skip it to protect users. This check is the best trade-off we can make at
+		// the moment without creating any false positive slashable attestation exports.
+		// More information on the bug can found in https://github.com/prysmaticlabs/prysm/issues/8893.
+		if i == 0 && len(history) > 1 {
```
Comment (nisdas) [inline validator/slashing-protection/local/standard-protection-format/export.go:131]: lets make the check stronger here, if I understand the bug correctly isn't source also 0 ? That way we don't ignore any valid attestations.

Comment (rauljordan) [reply validator/slashing-protection/local/standard-protection-format/export.go:131]: yes, good idea

Comment (terencechain) [reply validator/slashing-protection/local/standard-protection-format/export.go:131]: do we want to add a test for this as well?

**Review by nisdas — APPROVED** [review]
