### PR TITLE
Fix Attestation Aggregation Bitfield

### LINKED ISSUE #1974: Aggregation bitfield is always the same from different attester
This is blocking #1967. 

For the attestations coming from attesters, aggregation bitfield index is always flipped at index 1, but they are not coming from the same attester so something is wrong there. 
fork choice can't work w/o properly tracking attester's latest attestation

```
[2019-03-12 10:37:48]  INFO blockchain: Attestation Store updated attesterIndex=[1] attestationSlot=9223372036854775835
[2019-03-12 10:37:54]  INFO blockchain: Attestation Store updated attesterIndex=[1] attestationSlot=9223372036854775836
[2019-03-12 10:38:00]  INFO blockchain: Attestation Store updated attesterIndex=[1] attestationSlot=9223372036854775837
```

### PR DESCRIPTION
**Pull request by terenc3t**
This fixes #1974 

Verified in run time via different validator instances, they all have different bitfields now:
`aggregation_bitfield:"\004"`
`aggregation_bitfield:"\020"`
`aggregation_bitfield:"\001"`

### CODE REVIEW

File: validator/client/validator_attest_test.go [hunk 1]
```diff
@@ -7,6 +7,8 @@ import (
 	"testing"
 	"time"
 
+	"github.com/prysmaticlabs/prysm/shared/bitutil"
+
```
Comment (prestonvanloon) [inline validator/client/validator_attest_test.go]: Remove space
