### PR TITLE
Organize blobs on disk by epoch

### LINKED ISSUE #13880: Beacon node stops syncing because >64998 subdirectories in blobs folder
### Describe the bug

The Beacon stops syncing at slot 8854183. It has created 64999 directories in the blobs folder and the fs (ext4 in this case) does not allow any more (without setting dir_nlink feature)

A workaround is setting dir_nlink on the ext4 fs:
tune2fs -O dir_nlink <blockdevice>

Maybe the client should try to avoid this by using a deeper directory structure to store hashes?

### Has this worked before in a previous version?

```text
Unknown
```

### 🔬 Minimal Reproduction

1) Put data dir on normally formated ext4 fs
2) Try to sync beacon chain

### Error

```text
Apr 14 10:06:44 eth-consensus beacon-chain_active[72397]: time="2024-04-14 10:06:44" level=warning msg="Skip processing batched blocks" error="could not process block in batch: could not validate blob data availability at slot 8854183: failed to save BlobSidecar index 0 for block 0xe546bfeee9cdfb74664dafded853a707e342b40691863eea6929a4f1eef61fa3: mkdir /mnt/store_0/beacon/blobs/0xe546bfeee9cdfb74664dafded853a707e342b40691863eea6929a4f1eef61fa3: too many links" prefix=initial-sync
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

5.0.3

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by kasey**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

This is an alternative to #13884 which makes more drastic changes in order to store blobs by epoch instead of a flat directory of roots or the single hex byte prefix in 13884. Currently the scheme is a single `blobs` directory which contains a subdir for each unique block root, within which we store blobs by their index number, eg:

```blobs/0xff09895e2ff6232ac1ef6f08b1940e0177aaed5d8b682a30574a1cbd3ec6b487/0.ssz```

The problem with this approach is that it leads to a large directory entry for the `blobs` dir, which can cause issues with older filesystems. In addition, in order to determine the slot for each block root, we currently iterate through the entire blob directory and read a chunk of one of the serialized sidecar files in order to determine their slot. 

With this PR we would instead store the example blob above according to the following scheme:
```
blobs/by-epoch/66/273190/0xff09895e2ff6232ac1ef6f08b1940e0177aaed5d8b682a30574a1cbd3ec6b487/0.ssz
```
Breaking down the reason for each layer:
`by-epoch` outer dir serves as a version signifier. If we need to change the scheme again we can use this directory name to understand the version of the scheme within.
`66` is the "period" the blob falls under. It is derived from the blob epoch as:
`period = <epoch> // MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS`
This ensures that the top level directory listing is always small, so we can most efficiently list epoch directories.
`273190` is the epoch number of all roots within.
`0xff09895e2ff6232ac1ef6f08b1940e0177aaed5d8b682a30574a1cbd3ec6b487` is the block root of the contained sidecars.
`0.ssz` indicates that this is an ssz-encoded BlobSidecar (and not a `.part` file) for index 0.

This path can be constructed when looking up blobs by root+index using a cache that contains the following structures:
```
cache  map[[32]byte]BlobStorageSummary // keyed by block root

type BlobStorageSummary struct {
        epoch primitives.Epoch
        mask  blobIndexMask
}

// blobIndexMask represents which blob indices are present on disk
type blobIndexMask [fieldparams.MaxBlobsPerBlock]bool
```

Note that all data in the cache can be derived from traversing the blob directories. Local testing has shown that using this approach results in order of magnitude faster cache warm up time (which delays the start of the beacon node) and sub-ms pruning times.

***Using the feature***

A new flag has been introduced:
```
   --blob-storage-layout value                                         Dictates how to organize the blob directory structure on disk. Available options are: flat, by-epoch (default: "flat")
```
The default option `flat` maintains the current behavior of organizing all blobs in folders named after their block root, with all block folders in a single directory. `by-epoch` uses the new scheme described above. This branch includes a migration which will automatically move any blobs stored under the other layout scheme to the specified scheme, meaning to upgrade to the by-epoch scheme, you can simply set `--blob-storage-layout=by-epoch` and any files stored according to the "flat" scheme will be moved at startup. You can also "downgrade" via the flag; if the node is started with `--blob-storage-layout=flat` (or run with the default setting), any files organized according to the `by-epoch` layout will be automatically moved to the flat scheme at startup.

**Which issues(s) does this PR fix?**

Fixes #13880

**Other notes for review**
- **Important** This branch makes a hard tradeoff in order to get rid of complicated async startup code. We allow the rest of the node to assume the cache is always populated by turning cache warmup into a blocking operation. After the first startup on this code, cache warmup is very fast (10s-100s ms) but on the first startup this can take seconds, maybe over a minute depending on the number of blobs that need to move. The first startup could be rough on archival (L2) nodes. If that is an unacceptable compromise we'll have to reintroduce some complexity around node initialization, or think through how to make cache misses acceptable.
- Thanks to `verification.VerifiedROBlobFromDisk` this PR eliminates non-test code breaking the rules when it comes to using noop blob verification code paths.
- Everything in the pruning path uses epochs instead of converting between slots, which has greatly simplified pruning code.
- The organization on disk is abstracted by a new `runtimeLayout` interface. `blobNamer` has been simplified to `blobIdent` and its job of constructing paths has been moved to the layout. `BlobStorage` no longer interacts with `pruner`, it now notifies the layout of new files and layout is responsible for triggering pruning. `Remove` is likewise delegated to the layout.
- `BlobStorage` now directly implements/satisfies `BlobStorageSummarizer`.
- ~~`Indices` is served straight out of the cache without touching disk.~~ `Indices` is no longer supported, it has been replaced by the safer `Summary`, which returns a `BlobStorageSummary` value with a `HasIndex` method that can be used to more safely check the existence of an index. `Summary` is does come straight from the cache.

### CODE REVIEW

File: beacon-chain/db/filesystem/blob.go [hunk 1]
```diff
@@ -1,42 +1,29 @@
...
 	"github.com/prysmaticlabs/prysm/v5/consensus-types/primitives"
-	"github.com/prysmaticlabs/prysm/v5/encoding/bytesutil"
 	"github.com/prysmaticlabs/prysm/v5/io/file"
-	ethpb "github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1"
 	"github.com/prysmaticlabs/prysm/v5/runtime/logging"
 	"github.com/sirupsen/logrus"
 	"github.com/spf13/afero"
 )
 
+const directoryPermissions = 0700
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/blob.go:20]: I feel like we have this set differently for different files in the code base, should we standardize the permissions somewhere? ( need to double check)

File: beacon-chain/db/filesystem/blob.go [hunk 2]
```diff
@@ -76,138 +80,152 @@ func NewBlobStorage(opts ...BlobStorageOption) (*BlobStorage, error) {
...
+		}
+		b.fs = afero.NewBasePathFs(afero.NewOsFs(), b.base)
 	}
-	b.base = path.Clean(b.base)
-	if err := file.MkdirAll(b.base); err != nil {
-		return nil, errors.Wrapf(err, "failed to create blob storage at %s", b.base)
+	b.cache = newBlobStorageCache()
+	pruner := newBlobPruner(b.retentionEpochs)
+	if b.layoutName == "" {
+		b.layoutName = LayoutNameFlat
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/blob.go:97]: I thought we wanted to migrate to the new one ? ( or is this set this way to be opt in)

File: beacon-chain/db/filesystem/blob.go [hunk 3]
```diff
@@ -76,138 +80,152 @@ func NewBlobStorage(opts ...BlobStorageOption) (*BlobStorage, error) {
...
-			return closeErr
+			return partPath, closeErr
 		}
-		return errors.Wrap(err, "failed to write to partial file")
+		return partPath, errors.Wrap(err, "failed to write to partial file")
 	}
 	if bs.fsync {
 		if err := partialFile.Sync(); err != nil {
-			return err
+			return partPath, err
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/blob.go:179]: do we need to close partial File here?

File: beacon-chain/db/filesystem/pruner.go [hunk 4]
```diff
@@ -1,320 +1,67 @@
...
-
-func listDir(fs afero.Fs, dir string) ([]string, error) {
-	top, err := fs.Open(dir)
-	if err != nil {
-		return nil, errors.Wrap(err, "failed to open directory descriptor")
-	}
-	defer func() {
-		if err := top.Close(); err != nil {
-			log.WithError(err).Errorf("Could not close file %s", dir)
+			log.WithError(err).WithFields(sum.LogFields()).Warn("Encountered errors during blob pruning.")
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/pruner.go:49]: do you need to also close done here?

File: beacon-chain/db/filesystem/layout_flat.go [hunk 5]
```diff
@@ -0,0 +1,212 @@
...
+		return false
+	}
+	return ident.epoch < l.before
+}
+
+// isFlatCachedAndBefore tries to filter out any roots that it knows are not before the given epoch
+// based on the cache. It's an opportunistic filter; if the cache is not populated, it will not attempt to populate it.
+// isSSZAndBefore on the other hand, is a strict filter that will only return true if the file is an SSZ file and
+// the epoch can be determined.
+func isFlatCachedAndBefore(cache *blobStorageCache, before primitives.Epoch) func(string) bool {
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/layout_flat.go:193]: nitpick, reading the function i assume i'm getting a bool into a function that returns bool

File: beacon-chain/db/filesystem/layout_flat.go [hunk 6]
```diff
@@ -0,0 +1,212 @@
...
+}
+
+var _ fsLayout = &flatLayout{}
+
+func newFlatLayout(fs afero.Fs, cache *blobStorageCache, pruner *blobPruner) fsLayout {
+	l := &flatLayout{fs: fs, cache: cache, pruner: pruner}
+	return l
+}
+
+// iterateIdents for flatLayout is tricky because
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/layout_flat.go:28]: feels like this comment got cut off

File: cmd/beacon-chain/storage/options.go [hunk 7]
```diff
@@ -24,8 +25,28 @@ var (
...
+	}
 )
 
+func layoutFlagUsage() string {
+	return "Dictates how to organize the blob directory structure on disk. " +
+		"Available options are: " + strings.Join(filesystem.LayoutNames, ", ")
+}
+
+func validateLayoutFlag(_ *cli.Context, v string) error {
+	for _, l := range filesystem.LayoutNames {
```
Comment (nalepae) [inline cmd/beacon-chain/storage/options.go:42]: Why not using a set (`map[string]bool`) instead?

It could avoid the usage of the  `O(n)` range/if and replace it by a single `O(1)` operation.
(I agree here we won't gain much time since there is 2 items in the list, but in general `O(1)` is better than `O(n)`).

File: beacon-chain/db/filesystem/blob.go (hunk 1 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go:20]: Looks like we've got [this](https://github.com/prysmaticlabs/prysm/blob/develop/config/params/io_config.go#L18) dusty old helper, I can use it.

File: beacon-chain/db/filesystem/blob.go (hunk 2 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go:97]: Yep this is keeping the default to flat for now, see PR description and flag helptext.

I actually meant to convert this to a proper feature flag, will make sure to do that before this is merged.

File: beacon-chain/db/filesystem/blob.go (hunk 3 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go:179]: Yes - apparently a bug we had before (this func is basically a copy/paste to reduce cyclomatic complexity complaint on `Save`). Will deal with Close in a defer.

File: beacon-chain/db/filesystem/layout_flat.go (hunk 5 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_flat.go:193]: I don't understand what you mean by "i'm getting a bool into a function that returns a bool"?

File: cmd/beacon-chain/storage/options.go (hunk 7 above)
Comment (kasey) [reply cmd/beacon-chain/storage/options.go:42]: I considered this, but there are only 2 values, and this is just used once at option processing, so I thought readability for the win here - plus I suspect iterating over a 2 item list may be faster than a map lookup (especially in all the cases where the first item is a match haha).

Comment (kasey) [reply cmd/beacon-chain/storage/options.go:42]: (oh yeah and the list let me use `strings.Join` in the help text...)

File: beacon-chain/db/filesystem/layout.go [hunk 8]
```diff
@@ -0,0 +1,230 @@
...
+	LayoutNameByEpoch = "by-epoch"
+)
+
+var LayoutNames = []string{LayoutNameFlat, LayoutNameByEpoch}
+
+var (
+	errMigrationFailure       = errors.New("unable to migrate blob directory between old and new layout")
+	errCacheWarmFailed        = errors.New("failed to warm blob filesystem cache")
+	errPruneFailed            = errors.New("failed to prune root")
+	errInvalidRootString      = errors.New("Could not parse hex string as a [32]byte")
```
Comment (nalepae) [inline beacon-chain/db/filesystem/layout.go:38]: Some error messages start with a capital letter, some don't. Is it intended?

File: beacon-chain/db/filesystem/layout_flat.go [hunk 9]
```diff
@@ -0,0 +1,212 @@
...
+func (l *flatLayout) iterateIdents(before primitives.Epoch) (*identIterator, error) {
+	_, err := l.fs.Stat(".")
+	if err != nil {
+		if os.IsNotExist(err) {
+			return &identIterator{eof: true}, nil // The directory is non-existent, which is fine; stop iteration.
+		}
+		return nil, errors.Wrapf(err, "error reading path %s", periodicEpochBaseDir)
+	}
```
Comment (nalepae) [inline beacon-chain/db/filesystem/layout_flat.go:36]:
```suggestion
	if _, err := l.fs.Stat("."); err != nil {
		if os.IsNotExist(err) {
			return &identIterator{eof: true}, nil // The directory is non-existent, which is fine; stop iteration.
		}
		return nil, errors.Wrapf(err, "error reading path %s", periodicEpochBaseDir)
	}
```

File: beacon-chain/db/filesystem/blob.go (hunk 3 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go:179]: @prestonvanloon since I'm cleaning this up - I noticed that we check:
1. that the sidecar data len is not equal to zero
2. that the number of bytes written is equal to the sidecar data len
3. that the number of bytes written is not equal to zero

But 3 is impossible if 1 and 2 checks don't fail. So I'm going to delete 3.

File: beacon-chain/db/filesystem/blob.go (hunk 1 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go]: updated

File: beacon-chain/db/filesystem/blob.go (hunk 3 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go]: updated

File: beacon-chain/db/filesystem/layout_flat.go (hunk 6 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_flat.go]: updated

File: beacon-chain/db/filesystem/cache.go [hunk 10]
```diff
@@ -55,7 +57,7 @@ var _ BlobStorageSummarizer = &blobStorageCache{}
 
 func newBlobStorageCache() *blobStorageCache {
 	return &blobStorageCache{
-		cache: make(map[[32]byte]BlobStorageSummary, params.BeaconConfig().MinEpochsForBlobsSidecarsRequest*fieldparams.SlotsPerEpoch),
+		cache: make(map[[32]byte]BlobStorageSummary),
```
Comment (nalepae) [inline beacon-chain/db/filesystem/cache.go:60]: Why removing the capacity of the map?

File: beacon-chain/db/filesystem/iteration_test.go [hunk 11]
```diff
@@ -0,0 +1,296 @@
...
+			require.NoError(t, err)
+			require.Equal(t, c.slot, slot)
+		})
+	}
+}
+
+func TestIterationComplete(t *testing.T) {
+	targets := []migrationTestTarget{
+		{
+			ident: ezIdent(t, "0x0125e54c64c925018c9296965a5b622d9f5ab626c10917860dcfb6aa09a0a00b", 1234, 0),
```
Comment (nalepae) [inline beacon-chain/db/filesystem/iteration_test.go:248]: `ezIdent` is defined in `migration_test.go` but both used in `migration_test.go` and `iteration_test.go`.
As a common resource between 2 tests files, would'nt be useful to create a common test utils files? (Or to put this function in `mock.go`, even if it's not really a mock...)

File: beacon-chain/db/filesystem/iteration_test.go [hunk 12]
```diff
@@ -0,0 +1,296 @@
...
+		{
+			ident: ezIdent(t, "0x666cea5034e22bd3b849cb33914cad59afd88ee08e4d5bc0e997411c945fbc1d", 11235, 1),
+		},
+	}
+	fs := afero.NewMemMapFs()
+	cache := newBlobStorageCache()
+	byEpoch, err := newLayout(LayoutNameByEpoch, fs, cache, nil)
+	require.NoError(t, err)
+	for _, tar := range targets {
+		setupTestBlobFile(t, tar.ident, tar.slotOffset, fs, byEpoch)
```
Comment (nalepae) [inline beacon-chain/db/filesystem/iteration_test.go:279]: `setupTestBlobFile` is defined in `migration_test.go` and is both used in `migration_test.go` and `iteration_test.go`.

File: beacon-chain/db/filesystem/layout_flat.go (hunk 5 above)
Comment (nalepae) [reply beacon-chain/db/filesystem/layout_flat.go:191]: @james-prysm written like this it could help?
```go
func isFlatCachedAndBefore(cache *blobStorageCache, before primitives.Epoch) (func(string) bool)
```

Comment (nalepae) [reply beacon-chain/db/filesystem/layout_flat.go:191]: IMO the documentation is a little bit misleading:
> isFlatCachedAndBefore tries to filter out any roots that it know
==>
> isFlatCachedAndBefore returns a function that tries to filter out any roots that it know

File: beacon-chain/db/filesystem/layout_flat.go [hunk 13]
```diff
@@ -0,0 +1,210 @@
...
+	return ident, l.cache.ensure(ident)
+}
+
+func (l *flatSlotReader) isSSZAndBefore(fname string) bool {
+	if !isSszFile(fname) {
+		return false
+	}
+	// If 'before' != 0, assuming isSSZAndBefore is used as a filter on the same level with populateEpoch, this will typically
+	// call popualteEpoch before the iteration code calls it. So we can guarantee that the cache gets populated
```
Comment (nalepae) [inline beacon-chain/db/filesystem/layout_flat.go:168]: typo: `popualteEpoch`

File: beacon-chain/db/filesystem/layout_flat.go [hunk 14]
```diff
@@ -0,0 +1,210 @@
...
+func (l *flatLayout) pruneBefore(before primitives.Epoch) (*pruneSummary, error) {
+	sums, err := pruneBefore(before, l)
+	if err != nil {
+		return nil, err
+	}
+
+	// Roll up summaries and clean up per-epoch directories.
+	rollup := &pruneSummary{}
+	for _, sum := range sums {
+		rollup.blobsPruned += sum.blobsPruned
```
Comment (nalepae) [inline beacon-chain/db/filesystem/layout_flat.go:98]: This is not tested.

File: beacon-chain/db/filesystem/layout_by_epoch.go [hunk 15]
```diff
@@ -0,0 +1,193 @@
...
+
+func (l *periodicEpochLayout) notify(ident blobIdent) error {
+	if err := l.cache.ensure(ident); err != nil {
+		return err
+	}
+	l.pruner.notify(ident.epoch, l)
+	return nil
+}
+
+// If before == 0, it won't be used as a filter and all idents will be returned.
```
Comment (nalepae) [inline beacon-chain/db/filesystem/layout_by_epoch.go:37]: Why this comment?
IMO this comment applies for `isBeforePeriod` and `isBeforeEpoch`, not to `isRootDir` nor `isSszFile`.

File: beacon-chain/db/filesystem/iteration.go [hunk 16]
```diff
@@ -0,0 +1,230 @@
...
+			return next, nil
+		}
+		if err != io.EOF {
+			return blobIdent{}, err
+		}
+	}
+	return iter.advanceChild()
+}
+
+// advanceChild is used to move to the next directory at each level of the tree, either when
```
Comment (nalepae) [inline beacon-chain/db/filesystem/iteration.go:111]: I feel confused about the words level and tree.
I'm not sure if we are talking about level (and leaves) of the tree represented by the filesystem, or about levels composed of filters and populate (`identIteratoor.levels`)

File: beacon-chain/db/filesystem/iteration.go [hunk 17]
```diff
@@ -0,0 +1,230 @@
...
+		nextPath := filepath.Join(iter.path, iter.entries[iter.offset])
+		nextLevel := iter.levels[0]
+		if !nextLevel.filter(nextPath) {
+			continue
+		}
+		ident, err := nextLevel.populateIdent(iter.ident, nextPath)
+		if err != nil {
+			return ident, newIdentificationError(nextPath, ident, err)
+		}
+		// if we're at the leaf level, we can return the updated ident.
```
Comment (nalepae) [inline beacon-chain/db/filesystem/iteration.go:128]: leaf level means last level here?

File: beacon-chain/db/filesystem/blob.go [hunk 18]
```diff
@@ -66,6 +56,23 @@ func WithSaveFsync(fsync bool) BlobStorageOption {
...
+// WithFs allows the afero.Fs implementation to be customized. Used by tests
+// to substitute an in-memory filesystem.
+func WithFs(fs afero.Fs) BlobStorageOption {
+	return func(b *BlobStorage) error {
+		b.fs = fs
+		return nil
+	}
+}
+
+// WithLayout enables the user to specify a runtimeLayout which dictates how blob files are stored on disk.
```
Comment (nalepae) [inline beacon-chain/db/filesystem/blob.go:68]: The object `runtimeLayout` does not exist in the code base.

File: beacon-chain/db/filesystem/iteration_test.go (hunk 11 above)
Comment (nalepae) [reply beacon-chain/db/filesystem/iteration_test.go:248]:
```suggestion
func TestIterationComplete(t *testing.T) {
	/*
by-epoch
├── 0
│   └── 1234
│       └── 0x0125e54c64c925018c9296965a5b622d9f5ab626c10917860dcfb6aa09a0a00b
│           └── 0.ssz
├── 1
│   └── 5330
│       └── 0x0127dba6fd30fdbb47e73e861d5c6e602b38ac3ddc945bb6a2fc4e10761e9a86
│           ├── 0.ss
│           └── 1.ssz
├── 2
│   └── 11235
│       └── 0x666cea5034e22bd3b849cb33914cad59afd88ee08e4d5bc0e997411c945fbc1d
│           └── 1.ssz
└── 4096
    ├── 16777216
    │   └── 0x0232521756a0b965eab2c2245d7ad85feaeaf5f427cd14d1a7531f9d555b415c
    │       ├── 0.ssz
    │       └── 1.ssz
    └── 16777217
        └── 0x42eabe3d2c125410cd226de6f2825fb7575ab896c3f52e43de1fa29e4c809aba
            └── 0.ssz
	*/

Comment (nalepae) [reply beacon-chain/db/filesystem/iteration_test.go:248]: (So it's easier to understand the test.)

File: beacon-chain/db/filesystem/iteration_test.go [hunk 19]
```diff
@@ -0,0 +1,296 @@
...
+			enc, err := sc.MarshalSSZ()
+			require.NoError(t, err)
+			slot, err := slotFromBlob(bytes.NewReader(enc))
+			require.NoError(t, err)
+			require.Equal(t, c.slot, slot)
+		})
+	}
+}
+
+func TestIterationComplete(t *testing.T) {
```
Comment (nalepae) [inline beacon-chain/db/filesystem/iteration_test.go:245]:
```suggestion
func TestIterationComplete(t *testing.T) {
	/*
by-epoch
├── 0
│   └── 1234
│       └── 0x0125e54c64c925018c9296965a5b622d9f5ab626c10917860dcfb6aa09a0a00b
│           └── 0.ssz
├── 1
│   └── 5330
│       └── 0x0127dba6fd30fdbb47e73e861d5c6e602b38ac3ddc945bb6a2fc4e10761e9a86
│           ├── 0.ss
│           └── 1.ssz
├── 2
│   └── 11235
│       └── 0x666cea5034e22bd3b849cb33914cad59afd88ee08e4d5bc0e997411c945fbc1d
│           └── 1.ssz
└── 4096
    ├── 16777216
    │   └── 0x0232521756a0b965eab2c2245d7ad85feaeaf5f427cd14d1a7531f9d555b415c
    │       ├── 0.ssz
    │       └── 1.ssz
    └── 16777217
        └── 0x42eabe3d2c125410cd226de6f2825fb7575ab896c3f52e43de1fa29e4c809aba
            └── 0.ssz
	*/
```

Comment (nalepae) [reply beacon-chain/db/filesystem/iteration_test.go:245]: So it's easier to understand the test.

File: beacon-chain/db/filesystem/layout_by_epoch.go [hunk 20]
```diff
@@ -0,0 +1,193 @@
...
+	// iterate root, which should have directories named by "period"
+	entries, err := listDir(l.fs, periodicEpochBaseDir)
+	if err != nil {
+		return nil, errors.Wrapf(err, "failed to list %s", periodicEpochBaseDir)
+	}
+
+	return &identIterator{
+		fs:   l.fs,
+		path: periodicEpochBaseDir,
+		levels: []layoutLevel{
```
Comment (nalepae) [inline beacon-chain/db/filesystem/layout_by_epoch.go:55]: OK I understand now.
It was not clear to me at all that:
- the first item of the slice corresponds to the `period` level of the path
- the seconde one corresponds to the `epoch` level of the path
- ...


Maybe it's just me.
But I guess adding a comment explaining this could give a nice tip to a potential future reader.

(I had to run tests in debug mode to understand actually.)

File: beacon-chain/db/filesystem/layout.go [hunk 21]
```diff
@@ -0,0 +1,230 @@
...
+			return errors.Wrapf(errCacheWarmFailed, "failed to populate blob data cache err=%s", err.Error())
+		}
+		if err := cache.ensure(ident); err != nil {
+			return errors.Wrapf(errCacheWarmFailed, "failed to write cache entry for %s, err=%s", l.sszPath(ident), err.Error())
+		}
+	}
+	return nil
+}
+
+func migrateLayout(fs afero.Fs, from, to fsLayout, cache *blobStorageCache) error {
```
Comment (nalepae) [inline beacon-chain/db/filesystem/layout.go:120]: Blob migration cab take a lot of time.

On my computer (mac M2), a 17GB database needed > 10 seconds to migrate.
If we take `4096 (epochs) * 32 (slots/epoch) * 6 (blobs/slot) * 128 kB = 96 GB`, the migration could need more than a minute.

I think it would be useful to add a log when the migration starts (a log warning the user that it can takes several minutes), so the user knows why there is no more logs at all.

**Comment by nalepae** [comment]
If we brutally stops the migration (for example from flat to by-epoch), then the database ends up in a in-between state:

image

Is this safe?

File: beacon-chain/verification/error.go [hunk 22]
```diff
@@ -36,3 +39,12 @@ func (ve VerificationMultiError) Failures() map[Requirement]error {
 func newVerificationMultiError(r *results, err error) VerificationMultiError {
 	return VerificationMultiError{r: r, err: err}
 }
+
+// VerifiedROBlobError can be used by methods that have a VerifiedROBlob return type but do not have permission to
+// create a value of that type in order to generate an error return value.
+func VerifiedROBlobError(err error) (blocks.VerifiedROBlob, error) {
+	if err == nil {
+		panic("VerifiedROBlobError used to create a VerifiedROBlob without a checkable error.")
```
Comment (prestonvanloon) [inline beacon-chain/verification/error.go:47]: :scream: do we have to panic?? :scream:

File: beacon-chain/verification/filesystem.go [hunk 23]
```diff
@@ -0,0 +1,23 @@
+package verification
+
+import (
+	"github.com/prysmaticlabs/prysm/v5/consensus-types/blocks"
+	ethpb "github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1"
+	"github.com/spf13/afero"
+)
+
+func VerifiedROBlobFromDisk(fs afero.Fs, root [32]byte, path string) (blocks.VerifiedROBlob, error) {
```
[the remark this answers is not in the document]
Comment (kasey) [reply beacon-chain/verification/filesystem.go:9]: sure, is there a particular test case you'd like to see? it's a pretty trivial func, i could see maybe making sure we get errors when readfile or unmarshalssz fail, and if NewROBlobWithRoot can't compute the HTR?

File: beacon-chain/verification/error.go (hunk 22 above)
Comment (kasey) [reply beacon-chain/verification/error.go:47]: My reasoning was that we should only call this function when there's an error, because we want to make sure that this isn't accidentally used to get an empty VerifiedROBlob that gets used somehow, and that a panic would make a test fail... But you're right to flag this, because I suppose some code could be written that uses this incorrectly, and somehow doesn't fall under test coverage, which would be quite dangerous! A better alternative is to turn this into a custom error:

```
var errVerifiedROBlobErrorNil = errors.New(VerifiedROBlobError used to create a VerifiedROBlob without a checkable error.")

func VerifiedROBlobError(err error) (blocks.VerifiedROBlob, error) {
	if err == nil {
	    return ..., errVerifiedROBlobErrorNil
	    ...
```

File: beacon-chain/db/filesystem/layout_by_epoch.go (hunk 20 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_by_epoch.go:55]: Out of curiosity, did you see the commentary on `identIterator` about how the levels work? I assumed readers would look at that, and that the naming of the populate/filter funcs in the levels would be intuitive. But I agree that adding comments on the levels here is helpful too!

**Comment by kasey** [comment]
> If we brutally stops the migration (for example from flat to by-epoch), then the database ends up in a in-between state:
> 
> image
> 
> Is this safe?

Can you think of a failure mode there? I think that if this happens, the migration should pick up on the next restart. Each step is an atomic filesystem rename of the leaf directory (holding the blob files), so I think it's safe?

File: beacon-chain/db/filesystem/iteration_test.go (hunk 19 above)
Comment (kasey) [reply beacon-chain/db/filesystem/iteration_test.go:245]: Hmm, this seems a little hard to keep updated if test cases are added. What if I added a field to the test case that holds the string of the full path of each ident (in each direction) which can be asserted in the test?
```
{
    ident: ezIdent(t, "0x0125e54c64c925018c9296965a5b622d9f5ab626c10917860dcfb6aa09a0a00b", 1234, 0),
    flatPath: "0x0125e54c64c925018c9296965a5b622d9f5ab626c10917860dcfb6aa09a0a00b/0.ssz",
    byEpochPath: "by-epoch/0/1234/0x0125e54c64c925018c9296965a5b622d9f5ab626c10917860dcfb6aa09a0a00b/0.ssz",
}
```

File: beacon-chain/db/filesystem/iteration_test.go (hunk 11 above)
Comment (kasey) [reply beacon-chain/db/filesystem/iteration_test.go:248]: Generally I don't see a problem with this? If you imagine a rule where any type or func that is shared across 2 files needs to be defined in some special common file, that would require a lot of vigilance, decision fatigue and inconvenient separation. It's simple enough to go from a usage in one source to find it's definition in another. Don't feel super strongly about it but to me it feels like an uncomfortable convention to enforce.

File: beacon-chain/db/filesystem/iteration_test.go (hunk 12 above)
Comment (kasey) [reply beacon-chain/db/filesystem/iteration_test.go:279]: same response as https://github.com/prysmaticlabs/prysm/pull/14023/files/b6ef6b47e258ee85e4113cb0033b3ee2f2d18ac3#r1635219191

File: beacon-chain/db/filesystem/layout.go (hunk 8 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout.go:38]: nope, will fix! they should always be lower.

File: beacon-chain/db/filesystem/layout_by_epoch.go (hunk 15 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_by_epoch.go:37]: It applies to how the returned iterator behaves, overall. My thought was that since this is a method on the layout, it is more likely for someone touching the higher level storage code to see this method in the methodset and make an assumption that `before` would behave a certain way, so I wanted to make that explicit.

File: beacon-chain/db/filesystem/blob.go (hunk 18 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go:68]: refactor artifact, will fix!

File: beacon-chain/db/filesystem/cache.go (hunk 10 above)
Comment (kasey) [reply beacon-chain/db/filesystem/cache.go:60]: I was thinking that due to the way map expansion works (more heuristic than lists, based on bin averages), even with this hint it may usually wind up needing to expand anyway. But the hint won't hurt anything, might as well keep it.

File: beacon-chain/db/filesystem/layout_flat.go (hunk 14 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_flat.go:98]: will add a test!

File: beacon-chain/db/filesystem/cache.go [hunk 24]
```diff
@@ -67,48 +69,70 @@ func (s *blobStorageCache) Summary(root [32]byte) BlobStorageSummary {
...
 	}
-	v.mask[idx] = true
-	s.cache[key] = v
+	v.mask[ident.index] = true
+	s.cache[ident.root] = v
 	return nil
 }
 
-func (s *blobStorageCache) slot(key [32]byte) (primitives.Slot, bool) {
+func (s *blobStorageCache) get(key [32]byte) (BlobStorageSummary, bool) {
```
Comment (saolyn) [inline beacon-chain/db/filesystem/cache.go:88]: Would this not be better named `summary` since it returns the `BlobStorageSummary`?
```suggestion
func (s *blobStorageCache) summary(key [32]byte) (BlobStorageSummary, bool) {
```

File: beacon-chain/db/filesystem/iteration.go [hunk 25]
```diff
@@ -0,0 +1,230 @@
...
+
+	"github.com/ethereum/go-ethereum/common/hexutil"
+	"github.com/pkg/errors"
+	fieldparams "github.com/prysmaticlabs/prysm/v5/config/fieldparams"
+	"github.com/prysmaticlabs/prysm/v5/encoding/bytesutil"
+	"github.com/sirupsen/logrus"
+	"github.com/spf13/afero"
+)
+
+var errIdentFailure = errors.New("failed to determine blob metadata, ignoring all sub-path.")
```
Comment (saolyn) [inline beacon-chain/db/filesystem/iteration.go:19]:
```suggestion
var errIdentFailure = errors.New("failed to determine blob metadata, ignoring all sub-paths.")
```

File: beacon-chain/db/filesystem/iteration.go [hunk 26]
```diff
@@ -0,0 +1,230 @@
...
+	child   *identIterator
+	ident   blobIdent
+	levels  []layoutLevel
+	entries []string
+	offset  int
+	eof     bool
+}
+
+// next is the only method that a user of the identIterator needs to call.
+// identIterator will blobIdents in a breadth-first fashion,
```
Comment (saolyn) [inline beacon-chain/db/filesystem/iteration.go:93]:
```suggestion
// identIterator will traverse blobIdents in a breadth-first fashion,
```

File: beacon-chain/db/filesystem/layout_by_epoch.go [hunk 27]
```diff
@@ -0,0 +1,193 @@
...
+}
+
+// Funcs below this line are iteration support methods that are specific to the epoch layout.
+
+func isBeforePeriod(before primitives.Epoch) func(string) bool {
+	if before == 0 {
+		return filterNoop
+	}
+	beforePeriod := periodForEpoch(before)
+	if before%4096 != 0 {
```
Comment (saolyn) [inline beacon-chain/db/filesystem/layout_by_epoch.go:139]: Should we not have a const for `4096`?

File: beacon-chain/db/filesystem/iteration.go [hunk 28]
```diff
@@ -0,0 +1,230 @@
...
+	return fmt.Sprintf("%s path=%s, err=%s", errIdentFailure.Error(), ide.path, ide.err.Error())
+}
+
+func (ide *identificationError) Unwrap() error {
+	return ide.err
+}
+
+func (*identificationError) Is(err error) bool {
+	return err == errIdentFailure
+}
```
Comment (saolyn) [inline beacon-chain/db/filesystem/iteration.go:37]: These two functions appear to be unused, are they here just to "complete" `identificationError`?

File: beacon-chain/db/filesystem/layout_flat.go [hunk 29]
```diff
@@ -0,0 +1,210 @@
...
+		slot, err := slotFromFile(fname, l.fs)
+		if err != nil {
+			return ident, err
+		}
+		ident.epoch = slots.ToEpoch(slot)
+	}
+	return ident, l.cache.ensure(ident)
+}
+
+func (l *flatSlotReader) isSSZAndBefore(fname string) bool {
```
Comment (saolyn) [inline beacon-chain/db/filesystem/layout_flat.go:163]: It seems weird that before `isFlatCachedAndBefore` below we describe both `isSSZAndBefore` and `isFlatCachedAndBefore` filters but here have no description. If we want there to be some comparison between the filters then why not add the reverse comment here too
```suggestion
// isSSZAndBefore is a strict filter that will only return true if the file is an SSZ file and the epoch can 
// be determined.
// isFlatCachedAndBefore on the other hand tries to filter out any roots that it knows are not before the 
// given epoch based on the cache.

func (l *flatSlotReader) isSSZAndBefore(fname string) bool {
```

File: beacon-chain/db/filesystem/iteration.go (hunk 28 above)
Comment (kasey) [reply beacon-chain/db/filesystem/iteration.go:37]: Implementing `Is`, `As` and `Unwrap` on a custom error allows you to control how the stdlib [errors](https://pkg.go.dev/errors) package deals with the error:
- [errors.As](https://pkg.go.dev/errors#As) `An error type might provide an As method so it can be treated as if it were a different error type. `
- [errors.Is](https://pkg.go.dev/errors#Is) `An error type might provide an Is method so it can be treated as equivalent to an existing error.`
- [errors.Unwrap](https://pkg.go.dev/errors#Unwrap)`Unwrap returns the result of calling the Unwrap method on err, if err's type contains an Unwrap method returning error.`

`errors.Is` and `errors.As` are directly used in this PR. `Unwrap` is used under the hood by `errors.As` and `errors.Is`, eg within `errors.Is` in the case where custom `Is` returns false, the error will be further unwrapped, so for instance if some code wanted to check whether the error was of the wrapped error's type, the custom `Unwrap` is needed for that check to operate correctly (if `Is` is defined, `Unwrap` is only called when the custom `Is` returns false to continue recursively unwrapping and checking [[src](https://cs.opensource.google/go/go/+/refs/tags/go1.22.4:src/errors/wrap.go;l=53-78)]).

File: beacon-chain/db/filesystem/layout_flat.go (hunk 29 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_flat.go:163]: My reasoning was that the behavior of `isFlatCachedAndBefore` is potentially surprising (cache dependent) whereas the other method always works. When I write a comment like that I'm putting myself in the mindset of a developer who is looking at `isFlatCachedAndBefore` because they are thinking about changing how it's used or using it somewhere new. At that point I want them to notice the subtlety and think about whether that works for their use case. `isSSZAndBefore` on the other hand I think doesn't need the distraction of talking about `isFlatCachedAndBefore` because it's behavior is more intuitive. What do you think?

File: beacon-chain/db/filesystem/iteration_test.go (hunk 11 above)
Comment (nalepae) [reply beacon-chain/db/filesystem/iteration_test.go:248]: Yeah actually this is possible in golang, since all files in the same package are gathered into the same translation unit. In other languages, not having this kind of "tooling hygiene" could rapidly cause some circular import issues.

But that's fine to me!

File: beacon-chain/db/filesystem/iteration_test.go (hunk 19 above)
Comment (nalepae) [reply beacon-chain/db/filesystem/iteration_test.go:245]: Oh yeah that's a good solution!

File: beacon-chain/db/filesystem/layout_by_epoch.go (hunk 20 above)
Comment (nalepae) [reply beacon-chain/db/filesystem/layout_by_epoch.go:55]: Yes I read it. But I was still confused about the role of `levels`. By again, it's maybe just me.

File: beacon-chain/db/filesystem/cache.go (hunk 24 above)
Comment (kasey) [reply beacon-chain/db/filesystem/cache.go:109]: `get` is an internal method that also indicates if the value is present in the cache for initialization purposes, whereas the public `Summary` always returns a `BlobStorageSummary` that can be used by code outside the storage package.

File: beacon-chain/db/filesystem/layout_by_epoch.go (hunk 20 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_by_epoch.go]: I added some extra commentary and also renamed `levels` to `layers` in hopes of making this more clear.

File: beacon-chain/db/filesystem/iteration_test.go (hunk 19 above)
Comment (kasey) [reply beacon-chain/db/filesystem/iteration_test.go:245]: added this :+1:

File: beacon-chain/db/filesystem/blob.go (hunk 2 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go:99]: Instead of defining this as a feature flag, once we have some confidence in this feature through internal testing I'm going to make a branch that does the following:
- If a layout is explicitly defined by the feature flag (`IsSet` is true on the flag), use that (and perform migration if needed, which this branch currently handles).
- If no layout is specified, check for an existing blobs directory. If the blobs dir is empty, default to the new `by-epoch` layout.
- If no layout is specified and there are blob directories in an existing layout, detect which layout it is (can be determined by the existence of a by-epoch folder) and proceed with that layout.
- If no layout is specified and both layouts are detected, set the default to by-epoch and perform a flat->by-epoch migration.

File: beacon-chain/verification/filesystem.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (kasey) [reply beacon-chain/verification/filesystem.go:9]: @prestonvanloon LMK if you do have specific tests you'd like to see on this func. IMO this func is just a short and sweet string of constructors, so it's not clear to me what kind of test would be useful.

File: beacon-chain/db/filesystem/blob.go [hunk 30]
```diff
@@ -1,42 +1,31 @@
...
 	"github.com/prysmaticlabs/prysm/v5/consensus-types/primitives"
-	"github.com/prysmaticlabs/prysm/v5/encoding/bytesutil"
 	"github.com/prysmaticlabs/prysm/v5/io/file"
-	ethpb "github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1"
 	"github.com/prysmaticlabs/prysm/v5/runtime/logging"
 	"github.com/sirupsen/logrus"
 	"github.com/spf13/afero"
 )
 
+func directoryPermissions() os.FileMode {
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/blob.go:21]: is there some benefit in having this function ( readability maybe) instead of just using the params.BeaconIoConfig() directly?

Comment (kasey) [reply beacon-chain/db/filesystem/blob.go:21]: Yeah it's more concise.

**Comment by nalepae** [comment]
If running with a a non valid option (ex: `by-epochs` instead of`by-epoch`), then the following messages are printed:

```
[2025-01-28 18:43:54] ERROR main: invalid layout flag value by-epochs
[2025-01-28 18:43:55] ERROR main: invalid layout flag value by-epochs
[2025-01-28 18:43:56] ERROR main: invalid layout flag value by-epochs
[2025-01-28 18:43:57] ERROR main: invalid layout flag value by-epochs
[2025-01-28 18:43:58] ERROR main: invalid layout flag value by-epochs
[2025-01-28 18:44:00] ERROR main: invalid layout flag value by-epochs
[2025-01-28 18:44:04] ERROR main: invalid layout flag value by-epochs
[2025-01-28 18:44:11] ERROR main: invalid layout flag value by-epochs
```

- No need to print it multiple time, one is enough, and
- The error message does not help the user to know that it is the `--blob-storage-layout` value which is invalid, and
- Optionally, the error message could remind the valid options.

**Comment by nalepae** [comment]
```
[2025-01-28 18:58:59]  INFO filesystem: Migrating blob filesystem layout. This one-time operation can take extra time (up to a few minutes for systems with extended blob storage and a cold disk cache). from_layout=flat to_layout=by-epoch
```
In the rest of the codebase, log fields are `camelCased` not `snake_cased`.
==> `fromLayout` and `toLayout`.

**Comment by nalepae** [comment]
When migrating from `by-epoch` to `flat`, all by-epoch (empty) directories remain.

File: beacon-chain/db/filesystem/iteration.go [hunk 31]
```diff
@@ -0,0 +1,238 @@
...
+// advanceChild is used to move to the next directory at each layer of the tree, either when
+// the nodes are first being initialized at a layer, or when a sub-branch has been exhausted.
+func (iter *identIterator) advanceChild() (blobIdent, error) {
+	defer func() {
+		iter.offset += 1
+	}()
+	for i := iter.offset; i < len(iter.entries); i++ {
+		iter.offset = i
+		nextPath := filepath.Join(iter.path, iter.entries[iter.offset])
+		nextLayer := iter.layers[0]
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/iteration.go:125]: caught by cyberframe:
Suggestion: Add a check ensuring that nextPath cannot escape the intended base directory (e.g., via '../'), preventing unauthorized file traversal. [security, importance: 9]
```suggestion
                nextLayer := iter.layers[0]
                cleanedPath := filepath.Clean(nextPath)
                basePath := filepath.Clean(iter.path)
                if !strings.HasPrefix(cleanedPath, basePath+string(filepath.Separator)) {
                    continue
                }
```

File: beacon-chain/db/filesystem/layout.go [hunk 32]
```diff
@@ -0,0 +1,232 @@
...
+	// Skip pruning the n-1 ident if we're on the first real ident (lastIdent will be zero value).
+	if ident.root == params.BeaconConfig().ZeroHash {
+		return
+	}
+	_, ok := sums[ident.epoch]
+	if !ok {
+		sums[ident.epoch] = &pruneSummary{}
+	}
+	s := sums[ident.epoch]
+	removed, err := l.remove(ident)
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/layout.go:226]: do we need a safety check on l.dir(ident) before removal?

File: beacon-chain/db/filesystem/layout_by_epoch.go [hunk 33]
```diff
@@ -0,0 +1,200 @@
...
+	return rollup, nil
+}
+
+func (l *periodicEpochLayout) remove(ident blobIdent) (int, error) {
+	removed := l.cache.evict(ident.root)
+	// Skip the syscall if there are no blobs to remove.
+	if removed == 0 {
+		return 0, nil
+	}
+	if err := l.fs.RemoveAll(l.dir(ident)); err != nil {
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/layout_by_epoch.go:133]: Another cyber frame suggestion: Add a path check to ensure l.dir(ident) remains inside the intended base directory before removing it, preventing potential path traversal. [security, importance: 9]

File: beacon-chain/db/filesystem/layout_flat.go [hunk 34]
```diff
@@ -0,0 +1,215 @@
...
+	f, err := fs.Open(name)
+	if err != nil {
+		return 0, err
+	}
+	defer func() {
+		if err := f.Close(); err != nil {
+			log.WithError(err).Errorf("Could not close blob file")
+		}
+	}()
+	return slotFromBlob(f)
```
Comment (james-prysm) [inline beacon-chain/db/filesystem/layout_flat.go:123]: Another Cyberframe Suggestion: Add a file size check before reading at offset 131176 to avoid partial reads when handling untrusted files. [security, importance: 8]

File: beacon-chain/verification/filesystem.go [hunk 35]
```diff
@@ -0,0 +1,23 @@
...
+	encoded, err := afero.ReadFile(fs, path)
```
Comment (james-prysm) [inline beacon-chain/verification/filesystem.go:10]: Cyberframe Suggestion: Validate the path parameter for directory traversal before calling ReadFile, ensuring it cannot escape the intended directory structure. [security, importance: 8]

File: beacon-chain/db/filesystem/layout.go (hunk 32 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout.go:281]: No, this directory structure is managed by the program.

File: beacon-chain/db/filesystem/layout_by_epoch.go (hunk 33 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_by_epoch.go:141]: No, this path is not from an untrusted input, it's from a different part of the same program. Also the afero base path fs is being used so relative paths outside that aren't possible.

File: beacon-chain/db/filesystem/layout_flat.go (hunk 34 above)
Comment (kasey) [reply beacon-chain/db/filesystem/layout_flat.go:127]: That's a bad suggestion, because it would add a syscall in the happy path and be of little help in the path where the file is truncated. If the file is truncated, ReadAt will simply return an error.

File: beacon-chain/verification/filesystem.go (hunk 35 above)
Comment (kasey) [reply beacon-chain/verification/filesystem.go:10]: Not an issue.

**Review by nalepae — DISMISSED** [review]

File: beacon-chain/verification/error.go [hunk 36]
```diff
@@ -35,6 +38,10 @@ var (
 
 	// ErrMissingVerification indicates that the given verification function was never performed on the value.
 	ErrMissingVerification = errors.New("verification was not performed for requirement")
+
+	// errVerificationImplementationFault indicates that a code path yielding VerifiedROBlobs has an implementation
+	// error, leading it to call VerifiedROBlobError with a nil error.
+	errVerificationImplementationFault = errors.New("could not verify blob data or create a valid VerifiedROBlob.")
```
Comment (prestonvanloon) [inline beacon-chain/verification/error.go:44]:
```suggestion
	errVerificationImplementationFault = errors.New("could not verify blob data or create a valid VerifiedROBlob")
```

File: beacon-chain/sync/subscriber_beacon_blocks.go [hunk 37]
```diff
@@ -81,19 +81,19 @@ func (s *Service) reconstructAndBroadcastBlobs(ctx context.Context, block interf
 	if s.cfg.blobStorage == nil {
 		return
 	}
-	indices, err := s.cfg.blobStorage.Indices(blockRoot, block.Block().Slot())
+	summary := s.cfg.blobStorage.Summary(blockRoot)
+	cmts, err := block.Block().Body().BlobKzgCommitments()
 	if err != nil {
-		log.WithError(err).Error("Failed to retrieve indices for block")
-		return
+		log.WithError(err).Error("Failed to read commitments from block")
```
Comment (prestonvanloon) [inline beacon-chain/sync/subscriber_beacon_blocks.go:87]:
```suggestion
		log.WithError(err).Error("Failed to read commitments from block")
		return
```

Seems like a logic change? Why proceed when there is an error?

File: beacon-chain/sync/rpc_blob_sidecars_by_range.go [hunk 38]
```diff
@@ -27,14 +27,10 @@ func (s *Service) streamBlobBatch(ctx context.Context, batch blockBatch, wQuota
...
 	for _, b := range batch.canonical() {
 		root := b.Root()
-		idxs, err := s.cfg.blobStorage.Indices(b.Root(), b.Block().Slot())
-		if err != nil {
-			s.writeErrorResponseToStream(responseCodeServerError, p2ptypes.ErrGeneric.Error(), stream)
-			return wQuota, errors.Wrapf(err, "could not retrieve sidecars for block root %#x", root)
-		}
-		for i, l := uint64(0), uint64(len(idxs)); i < l; i++ {
+		idxs := s.cfg.blobStorage.Summary(root)
+		for i := uint64(0); i < idxs.MaxBlobsForEpoch(); i++ {
```
Comment (prestonvanloon) [inline beacon-chain/sync/rpc_blob_sidecars_by_range.go:31]:
```suggestion
		for i := range idxs.MaxBlobsForEpoch() {
```

Since go 1.23, i think?

File: beacon-chain/db/filesystem/iteration.go [hunk 39]
```diff
@@ -0,0 +1,238 @@
...
+	idx, err := strconv.ParseUint(parts[0], 10, 64)
+	if err != nil {
+		return 0, err
+	}
+	/*
+		// we can no longer check this here, we need to read the epoch/slot from the blob / cache first
+		if idx >= fieldparams.MaxBlobsPerBlock {
+			return 0, errors.Wrapf(errIndexOutOfBounds, "index=%d", idx)
+		}
+	*/
```
Comment (prestonvanloon) [inline beacon-chain/db/filesystem/iteration.go:208]: Delete?

Where is this handled now?

File: beacon-chain/db/filesystem/blob.go [hunk 40]
```diff
@@ -228,35 +253,57 @@ func (bs *BlobStorage) Save(sidecar blocks.VerifiedROBlob) error {
...
+		// If there is an overflow, then the retention period was set to an extremely large number.
+		return true
+	}
+	return requested+bs.retentionEpochs >= current
 }
 
-// Indices generates a bitmap representing which BlobSidecar.Index values are present on disk for a given root.
-// This value can be compared to the commitments observed in a block to determine which indices need to be found
-// on the network to confirm data availability.
+// TODO: double check this rebase conflicted code
```
Comment (prestonvanloon) [inline beacon-chain/db/filesystem/blob.go:305]: Please do this before merging and clean up the comments.

**Review by prestonvanloon — CHANGES_REQUESTED** [review]
Partial review -- will resume later

File: beacon-chain/db/filesystem/blob.go (hunk 40 above)
Comment (kasey) [reply beacon-chain/db/filesystem/blob.go:305]: derp ty

File: beacon-chain/db/filesystem/iteration.go (hunk 39 above)
Comment (kasey) [reply beacon-chain/db/filesystem/iteration.go:208]: This func is in `populateIndex` in the iterator, which is used for cache warming and layout migrations. In both cases we insert the value that is read through this code path into the cache. The cache now handles validation of the blob indices upon insertion.

File: beacon-chain/sync/subscriber_beacon_blocks.go (hunk 37 above)
Comment (kasey) [reply beacon-chain/sync/subscriber_beacon_blocks.go:87]: This change was a little odd because the function you are commenting on no longer needs to check commitments, except for the purpose of incrementing this log. If retrieving `cmts` generates an error here, it will also fail when calling `ReconstructBlobSidecars` and failing there will result in an error that makes the most sense to me rolled up with the other errors from that function `Failed to reconstruct blob sidecars`. So the behavior is 2 logs instead of 1, but otherwise same logic. 

But I agree with your suggestion, it's weird to not short circuit here and could be a footgun if code is inserted in between those calls. I'll change it.

**Review by prestonvanloon — APPROVED** [review]
I have run this locally and found it to work well! Thanks so much
