### PR TITLE
Don't show stack trace for certain voluntary exit failure scenarios

### LINKED ISSUE #7534: Duplicate Exit Throws Error
# 🐞 Bug Report

### Description

Running 5 validators on Zinken, and I wanted to attempt an exit. Using prysm.sh I ran the command to exit and select 1 validator to exit. After seeing that my validator appeared on the exit queue, I ran prysm.sh again to exit my remaining validators. I selected the "all" option to exit all validators, not realizing that my previously exited validator is still in the list. 

Output seems to indicate that the four new exits were processed correctly, but the error message around the previously-exited validator is not pretty.

### Has this worked before in a previous version?

Never tried it before.

## 🔬 Minimal Reproduction

Exit one key, then exit that same key and more.

## 🔥 Error

<pre><code>
If you still want to continue with the voluntary exit, please input the passphrase from the above URL:
Exit my validator
[2020-10-14 17:20:58]  WARN validator: You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc
[2020-10-14 17:20:58] ERROR accounts-v2: voluntary exit failed for account 0xXXXXXXXXXXXX error=rpc error: code = InvalidArgument desc = validator has already submitted an exit, which will take place at epoch: 561
failed to propose voluntary exit
github.com/prysmaticlabs/prysm/validator/client.ProposeExit
        validator/client/propose.go:157
github.com/prysmaticlabs/prysm/validator/accounts/v2.performExit
        validator/accounts/v2/accounts_exit.go:196
github.com/prysmaticlabs/prysm/validator/accounts/v2.ExitAccountsCli
        validator/accounts/v2/accounts_exit.go:61
github.com/prysmaticlabs/prysm/validator/accounts/v2.glob..func6
        validator/accounts/v2/cmd_accounts.go:160
github.com/urfave/cli/v2.(*Command).Run
        external/com_github_urfave_cli_v2/command.go:164
github.com/urfave/cli/v2.(*App).RunAsSubcommand
        external/com_github_urfave_cli_v2/app.go:427
github.com/urfave/cli/v2.(*Command).startApp
        external/com_github_urfave_cli_v2/command.go:279
github.com/urfave/cli/v2.(*Command).Run
        external/com_github_urfave_cli_v2/command.go:94
github.com/urfave/cli/v2.(*App).RunContext
        external/com_github_urfave_cli_v2/app.go:306
github.com/urfave/cli/v2.(*App).Run
        external/com_github_urfave_cli_v2/app.go:215
main.main
        validator/main.go:354
runtime.main
        GOROOT/src/runtime/proc.go:203
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1373
[2020-10-14 17:20:58]  INFO accounts-v2: Voluntary exit was successful for the accounts listed publicKeys=0xXXXXXXXXXXXX, 0xXXXXXXXXXXXX, 0xXXXXXXXXXXXX, 0xXXXXXXXXXXXX
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha.29
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Stack trace will not be displayed if validator could not be exited because of the following non-fatal reasons:
- validator has already exited
- validator has not been active long enough to exit

**Which issues(s) does this PR fix?**

Fixes #7534

**Other notes for review**

N/A

### CODE REVIEW

**Review by rauljordan — APPROVED** [review]

File: validator/accounts/cmd_accounts.go [hunk 1]
```diff
@@ -171,6 +173,11 @@ this command outputs a deposit data string which is required to become a validat
 			Action: func(cliCtx *cli.Context) error {
 				featureconfig.ConfigureValidator(cliCtx)
 				if err := ExitAccountsCli(cliCtx, os.Stdin); err != nil {
+					msg := err.Error()
```
Comment (rauljordan) [inline validator/accounts/cmd_accounts.go:176]: @rkapka let's use `errors.Is` instead of doing string comparisons

Comment (rkapka) [reply validator/accounts/cmd_accounts.go:176]: I don't think `errors.Is` can be used here as I am not comparing errors. The exported messages are plain strings.
