### PR TITLE
Fix LC versioning bug

### LINKED ISSUE #15393: Inconsistent `version` Field in Prysm `/eth/v1/light_client/optimistic_update` Endpoint
### Overview

Hello developers,

I am conducting API testing on an Electra PoS devnet chain and noticed inconsistencies in the Beacon-API responses across Prysm, Lighthouse, Nimbus, and Lodestar. 

In particular, Prysm returns the `version` field as `"deneb"`, while the other clients correctly return `"electra"` for the same request. All other fields in the response are identical. The network has been configured to activate Electra at `epoch 0`. Notably, other Electra-introduced endpoints in Prysm are functional, indicating that the fork configuration is generally applied.

Would like to know whether this is a bug or a misconfiguration. Thanks in advance!

### Details

Results

```
# prysm
{"data": {"attested_header": {"beacon": {"body_root": "0xca6437b6f542a5d929477a0b30d4e5eae1db4cdcff381f1ecb6af73db076f3fa", "parent_root": "0x8f13ea3670f0cf473a2202d1e76e62e2ae1ad09eace1181616cff2fb20833426", "proposer_index": "1", "slot": "71", "state_root": "0x8121a0a2675c4f96e6a9725b929ff86fc7ee0f7974caa6e9688e0a59431f8e5c"}, "execution": {"base_fee_per_gas": "470244", "blob_gas_used": "0", "block_hash": "0x8c4ec9e18a0116ecf083c6a5b6e6bfcc18cca89b2417b58e18cddbea281f0828", "block_number": "69", "excess_blob_gas": "0", "extra_data": "0xd883010f0c846765746888676f312e32342e33856c696e7578", "fee_recipient": "0x8943545177806ed17b9f23f0a21ee5948ecaa776", "gas_limit": "32089985", "gas_used": "4963979", "logs_bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "parent_hash": "0x1c3451648e7e4b71b09f810c62f65a2ed0c24d49330966e8fbdbcff421ee5f3b", "prev_randao": "0x446ad7df850cbfcf7912aac4ed35c44a49623da441a73b7e323f824334e0984a", "receipts_root": "0x63791db3b21e1e21036229a74715ee2ef83c8788ed630d2c1b9e11857df0ce85", "state_root": "0x670f839f1dfa710a672623c1eb157210ea2d77efea86a7834a240ae2c40e9586", "timestamp": "1749481073", "transactions_root": "0xa3233eadcefdca5469203061f0bffd008cb89d5b7822c4968fdc1005cebff120", "withdrawals_root": "0x792930bbd5baac43bcc798ee49aa8185ef76bb3b44ba62b91d86ae569e4bb535"}, "execution_branch": ["0x6dd3b9955d892d92338b19976fd07084bfe88a76c3063482b7f30ee60feb2a58", "0x9741e25b7d473381e5c816556af40a143692823fe515923db27e4ce0084f829f", "0xac980dfdca2902748b1bf18e77216a2fce6b3c718aa505f6a70dddeb0eabec7b", "0xb46f0c01805fe212e15907981b757e6c496b0cb06664224655613dcec82505bb"]}, "signature_slot": "72", "sync_aggregate": {"sync_committee_bits": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "sync_committee_signature": "0x86b45247696bb99f3acb930f9302a3138bd26948b5632f2bd9eb4e289ff644261674298ff90c43528fa85bb53edab64e157ebc10a402be3b8bd5bd497d1634b2fb4700bdbd7ba8a82c2a98da435e6d0db325b516f29466e199ef8bf01f65289f"}}, "version": "deneb"}
# Lighthouse
{"data": {"attested_header": {"beacon": {"body_root": "0xca6437b6f542a5d929477a0b30d4e5eae1db4cdcff381f1ecb6af73db076f3fa", "parent_root": "0x8f13ea3670f0cf473a2202d1e76e62e2ae1ad09eace1181616cff2fb20833426", "proposer_index": "1", "slot": "71", "state_root": "0x8121a0a2675c4f96e6a9725b929ff86fc7ee0f7974caa6e9688e0a59431f8e5c"}, "execution": {"base_fee_per_gas": "470244", "blob_gas_used": "0", "block_hash": "0x8c4ec9e18a0116ecf083c6a5b6e6bfcc18cca89b2417b58e18cddbea281f0828", "block_number": "69", "excess_blob_gas": "0", "extra_data": "0xd883010f0c846765746888676f312e32342e33856c696e7578", "fee_recipient": "0x8943545177806ed17b9f23f0a21ee5948ecaa776", "gas_limit": "32089985", "gas_used": "4963979", "logs_bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "parent_hash": "0x1c3451648e7e4b71b09f810c62f65a2ed0c24d49330966e8fbdbcff421ee5f3b", "prev_randao": "0x446ad7df850cbfcf7912aac4ed35c44a49623da441a73b7e323f824334e0984a", "receipts_root": "0x63791db3b21e1e21036229a74715ee2ef83c8788ed630d2c1b9e11857df0ce85", "state_root": "0x670f839f1dfa710a672623c1eb157210ea2d77efea86a7834a240ae2c40e9586", "timestamp": "1749481073", "transactions_root": "0xa3233eadcefdca5469203061f0bffd008cb89d5b7822c4968fdc1005cebff120", "withdrawals_root": "0x792930bbd5baac43bcc798ee49aa8185ef76bb3b44ba62b91d86ae569e4bb535"}, "execution_branch": ["0x6dd3b9955d892d92338b19976fd07084bfe88a76c3063482b7f30ee60feb2a58", "0x9741e25b7d473381e5c816556af40a143692823fe515923db27e4ce0084f829f", "0xac980dfdca2902748b1bf18e77216a2fce6b3c718aa505f6a70dddeb0eabec7b", "0xb46f0c01805fe212e15907981b757e6c496b0cb06664224655613dcec82505bb"]}, "signature_slot": "72", "sync_aggregate": {"sync_committee_bits": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "sync_committee_signature": "0x86b45247696bb99f3acb930f9302a3138bd26948b5632f2bd9eb4e289ff644261674298ff90c43528fa85bb53edab64e157ebc10a402be3b8bd5bd497d1634b2fb4700bdbd7ba8a82c2a98da435e6d0db325b516f29466e199ef8bf01f65289f"}}, "version": "electra"}
# nimbus
{"data": {"attested_header": {"beacon": {"body_root": "0xca6437b6f542a5d929477a0b30d4e5eae1db4cdcff381f1ecb6af73db076f3fa", "parent_root": "0x8f13ea3670f0cf473a2202d1e76e62e2ae1ad09eace1181616cff2fb20833426", "proposer_index": "1", "slot": "71", "state_root": "0x8121a0a2675c4f96e6a9725b929ff86fc7ee0f7974caa6e9688e0a59431f8e5c"}, "execution": {"base_fee_per_gas": "470244", "blob_gas_used": "0", "block_hash": "0x8c4ec9e18a0116ecf083c6a5b6e6bfcc18cca89b2417b58e18cddbea281f0828", "block_number": "69", "excess_blob_gas": "0", "extra_data": "0xd883010f0c846765746888676f312e32342e33856c696e7578", "fee_recipient": "0x8943545177806ed17b9f23f0a21ee5948ecaa776", "gas_limit": "32089985", "gas_used": "4963979", "logs_bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "parent_hash": "0x1c3451648e7e4b71b09f810c62f65a2ed0c24d49330966e8fbdbcff421ee5f3b", "prev_randao": "0x446ad7df850cbfcf7912aac4ed35c44a49623da441a73b7e323f824334e0984a", "receipts_root": "0x63791db3b21e1e21036229a74715ee2ef83c8788ed630d2c1b9e11857df0ce85", "state_root": "0x670f839f1dfa710a672623c1eb157210ea2d77efea86a7834a240ae2c40e9586", "timestamp": "1749481073", "transactions_root": "0xa3233eadcefdca5469203061f0bffd008cb89d5b7822c4968fdc1005cebff120", "withdrawals_root": "0x792930bbd5baac43bcc798ee49aa8185ef76bb3b44ba62b91d86ae569e4bb535"}, "execution_branch": ["0x6dd3b9955d892d92338b19976fd07084bfe88a76c3063482b7f30ee60feb2a58", "0x9741e25b7d473381e5c816556af40a143692823fe515923db27e4ce0084f829f", "0xac980dfdca2902748b1bf18e77216a2fce6b3c718aa505f6a70dddeb0eabec7b", "0xb46f0c01805fe212e15907981b757e6c496b0cb06664224655613dcec82505bb"]}, "signature_slot": "72", "sync_aggregate": {"sync_committee_bits": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "sync_committee_signature": "0x86b45247696bb99f3acb930f9302a3138bd26948b5632f2bd9eb4e289ff644261674298ff90c43528fa85bb53edab64e157ebc10a402be3b8bd5bd497d1634b2fb4700bdbd7ba8a82c2a98da435e6d0db325b516f29466e199ef8bf01f65289f"}}, "version": "electra"}
# lodestar
{"data": {"attested_header": {"beacon": {"body_root": "0xca6437b6f542a5d929477a0b30d4e5eae1db4cdcff381f1ecb6af73db076f3fa", "parent_root": "0x8f13ea3670f0cf473a2202d1e76e62e2ae1ad09eace1181616cff2fb20833426", "proposer_index": "1", "slot": "71", "state_root": "0x8121a0a2675c4f96e6a9725b929ff86fc7ee0f7974caa6e9688e0a59431f8e5c"}, "execution": {"base_fee_per_gas": "470244", "blob_gas_used": "0", "block_hash": "0x8c4ec9e18a0116ecf083c6a5b6e6bfcc18cca89b2417b58e18cddbea281f0828", "block_number": "69", "excess_blob_gas": "0", "extra_data": "0xd883010f0c846765746888676f312e32342e33856c696e7578", "fee_recipient": "0x8943545177806ED17B9F23F0a21ee5948eCaa776", "gas_limit": "32089985", "gas_used": "4963979", "logs_bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "parent_hash": "0x1c3451648e7e4b71b09f810c62f65a2ed0c24d49330966e8fbdbcff421ee5f3b", "prev_randao": "0x446ad7df850cbfcf7912aac4ed35c44a49623da441a73b7e323f824334e0984a", "receipts_root": "0x63791db3b21e1e21036229a74715ee2ef83c8788ed630d2c1b9e11857df0ce85", "state_root": "0x670f839f1dfa710a672623c1eb157210ea2d77efea86a7834a240ae2c40e9586", "timestamp": "1749481073", "transactions_root": "0xa3233eadcefdca5469203061f0bffd008cb89d5b7822c4968fdc1005cebff120", "withdrawals_root": "0x792930bbd5baac43bcc798ee49aa8185ef76bb3b44ba62b91d86ae569e4bb535"}, "execution_branch": ["0x6dd3b9955d892d92338b19976fd07084bfe88a76c3063482b7f30ee60feb2a58", "0x9741e25b7d473381e5c816556af40a143692823fe515923db27e4ce0084f829f", "0xac980dfdca2902748b1bf18e77216a2fce6b3c718aa505f6a70dddeb0eabec7b", "0xb46f0c01805fe212e15907981b757e6c496b0cb06664224655613dcec82505bb"]}, "signature_slot": "72", "sync_aggregate": {"sync_committee_bits": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "sync_committee_signature": "0x86b45247696bb99f3acb930f9302a3138bd26948b5632f2bd9eb4e289ff644261674298ff90c43528fa85bb53edab64e157ebc10a402be3b8bd5bd497d1634b2fb4700bdbd7ba8a82c2a98da435e6d0db325b516f29466e199ef8bf01f65289f"}}, "version": "electra"}
```

Related implementation:
https://github.com/OffchainLabs/prysm/blob/f5a9394c77daf4950f8437fed795e17d30295397/beacon-chain/blockchain/process_block_helpers.go#L316-L367

Electra is enabled in epoch 0. This is the response of `/eth/v1/config/spec`:
```json
{"data": {"ALTAIR_FORK_EPOCH": "0", "ALTAIR_FORK_VERSION": "0x20000038", "ATTESTATION_PROPAGATION_SLOT_RANGE": "32", "ATTESTATION_SUBNET_COUNT": "64", "ATTESTATION_SUBNET_EXTRA_BITS": "0", "ATTESTATION_SUBNET_PREFIX_BITS": "6", "BALANCE_PER_ADDITIONAL_CUSTODY_GROUP": "32000000000", "BASE_REWARD_FACTOR": "64", "BELLATRIX_FORK_EPOCH": "0", "BELLATRIX_FORK_VERSION": "0x30000038", "BLOB_SIDECAR_SUBNET_COUNT": "6", "BLOB_SIDECAR_SUBNET_COUNT_ELECTRA": "9", "BLS_WITHDRAWAL_PREFIX": "0x00", "BYTES_PER_LOGS_BLOOM": "256", "CAPELLA_FORK_EPOCH": "0", "CAPELLA_FORK_VERSION": "0x40000038", "CHURN_LIMIT_QUOTIENT": "65536", "COMPOUNDING_WITHDRAWAL_PREFIX": "0x02", "CONFIG_NAME": "testnet", "CUSTODY_REQUIREMENT": "4", "DATA_COLUMN_SIDECAR_SUBNET_COUNT": "128", "DENEB_FORK_EPOCH": "0", "DENEB_FORK_VERSION": "0x50000038", "DEPOSIT_CHAIN_ID": "946253", "DEPOSIT_CONTRACT_ADDRESS": "0x00000000219ab540356cBB839Cbe05303d7705Fa", "DEPOSIT_NETWORK_ID": "946253", "DOMAIN_AGGREGATE_AND_PROOF": "0x06000000", "DOMAIN_APPLICATION_BUILDER": "0x00000001", "DOMAIN_APPLICATION_MASK": "0x00000001", "DOMAIN_BEACON_ATTESTER": "0x01000000", "DOMAIN_BEACON_PROPOSER": "0x00000000", "DOMAIN_BLS_TO_EXECUTION_CHANGE": "0x0a000000", "DOMAIN_CONTRIBUTION_AND_PROOF": "0x09000000", "DOMAIN_DEPOSIT": "0x03000000", "DOMAIN_RANDAO": "0x02000000", "DOMAIN_SELECTION_PROOF": "0x05000000", "DOMAIN_SYNC_COMMITTEE": "0x07000000", "DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF": "0x08000000", "DOMAIN_VOLUNTARY_EXIT": "0x04000000", "EFFECTIVE_BALANCE_INCREMENT": "1000000000", "EJECTION_BALANCE": "16000000000", "ELECTRA_FORK_EPOCH": "0", "ELECTRA_FORK_VERSION": "0x60000038", "EPOCHS_PER_ETH1_VOTING_PERIOD": "64", "EPOCHS_PER_HISTORICAL_VECTOR": "65536", "EPOCHS_PER_RANDOM_SUBNET_SUBSCRIPTION": "256", "EPOCHS_PER_SLASHINGS_VECTOR": "8192", "EPOCHS_PER_SUBNET_SUBSCRIPTION": "256", "EPOCHS_PER_SYNC_COMMITTEE_PERIOD": "256", "ETH1_ADDRESS_WITHDRAWAL_PREFIX": "0x01", "ETH1_FOLLOW_DISTANCE": "2048", "FIELD_ELEMENTS_PER_BLOB": "4096", "FULL_EXIT_REQUEST_AMOUNT": "0", "FULU_FORK_EPOCH": "18446744073709551615", "FULU_FORK_VERSION": "0x70000038", "GENESIS_DELAY": "0", "GENESIS_FORK_VERSION": "0x10000038", "HISTORICAL_ROOTS_LIMIT": "16777216", "HYSTERESIS_DOWNWARD_MULTIPLIER": "1", "HYSTERESIS_QUOTIENT": "4", "HYSTERESIS_UPWARD_MULTIPLIER": "5", "INACTIVITY_PENALTY_QUOTIENT": "67108864", "INACTIVITY_PENALTY_QUOTIENT_ALTAIR": "50331648", "INACTIVITY_PENALTY_QUOTIENT_BELLATRIX": "16777216", "INACTIVITY_SCORE_BIAS": "4", "INACTIVITY_SCORE_RECOVERY_RATE": "16", "INTERVALS_PER_SLOT": "3", "KZG_COMMITMENT_INCLUSION_PROOF_DEPTH": "17", "MAXIMUM_GOSSIP_CLOCK_DISPARITY": "500", "MAX_ATTESTATIONS": "128", "MAX_ATTESTATIONS_ELECTRA": "8", "MAX_ATTESTER_SLASHINGS": "2", "MAX_ATTESTER_SLASHINGS_ELECTRA": "1", "MAX_BLOBS_PER_BLOCK": "6", "MAX_BLOBS_PER_BLOCK_ELECTRA": "9", "MAX_BLOBS_PER_BLOCK_FULU": "12", "MAX_BLOB_COMMITMENTS_PER_BLOCK": "4096", "MAX_BLS_TO_EXECUTION_CHANGES": "16", "MAX_BYTES_PER_TRANSACTION": "1073741824", "MAX_COMMITTEES_PER_SLOT": "64", "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD": "2", "MAX_DEPOSITS": "16", "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD": "8192", "MAX_EFFECTIVE_BALANCE": "32000000000", "MAX_EFFECTIVE_BALANCE_ELECTRA": "2048000000000", "MAX_EXTRA_DATA_BYTES": "32", "MAX_PARTIAL_WITHDRAWALS_PER_PAYLOAD": "0", "MAX_PAYLOAD_SIZE": "10485760", "MAX_PENDING_DEPOSITS_PER_EPOCH": "16", "MAX_PENDING_PARTIALS_PER_WITHDRAWALS_SWEEP": "8", "MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT": "8", "MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT": "256000000000", "MAX_PROPOSER_SLASHINGS": "16", "MAX_REQUEST_BLOB_SIDECARS": "768", "MAX_REQUEST_BLOB_SIDECARS_ELECTRA": "1152", "MAX_REQUEST_BLOCKS": "1024", "MAX_REQUEST_BLOCKS_DENEB": "128", "MAX_REQUEST_DATA_COLUMN_SIDECARS": "16384", "MAX_REQUEST_LIGHT_CLIENT_UPDATES": "128", "MAX_SEED_LOOKAHEAD": "4", "MAX_TRANSACTIONS_PER_PAYLOAD": "1048576", "MAX_VALIDATORS_PER_COMMITTEE": "2048", "MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP": "16384", "MAX_VOLUNTARY_EXITS": "16", "MAX_WITHDRAWALS_PER_PAYLOAD": "16", "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD": "16", "MESSAGE_DOMAIN_INVALID_SNAPPY": "0x00000000", "MESSAGE_DOMAIN_VALID_SNAPPY": "0x01000000", "MIN_ACTIVATION_BALANCE": "32000000000", "MIN_ATTESTATION_INCLUSION_DELAY": "1", "MIN_DEPOSIT_AMOUNT": "1000000000", "MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS": "4096", "MIN_EPOCHS_FOR_BLOCK_REQUESTS": "33024", "MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS": "4096", "MIN_EPOCHS_TO_INACTIVITY_PENALTY": "4", "MIN_GENESIS_ACTIVE_VALIDATOR_COUNT": "66", "MIN_GENESIS_TIME": "1749520534", "MIN_PER_EPOCH_CHURN_LIMIT": "4", "MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA": "128000000000", "MIN_SEED_LOOKAHEAD": "1", "MIN_SLASHING_PENALTY_QUOTIENT": "128", "MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR": "64", "MIN_SLASHING_PENALTY_QUOTIENT_BELLATRIX": "32", "MIN_SLASHING_PENALTY_QUOTIENT_ELECTRA": "4096", "MIN_SYNC_COMMITTEE_PARTICIPANTS": "1", "MIN_VALIDATOR_WITHDRAWABILITY_DELAY": "256", "NODE_ID_BITS": "256", "NUMBER_OF_COLUMNS": "128", "NUMBER_OF_CUSTODY_GROUPS": "128", "PENDING_CONSOLIDATIONS_LIMIT": "262144", "PENDING_DEPOSITS_LIMIT": "134217728", "PENDING_PARTIAL_WITHDRAWALS_LIMIT": "134217728", "PRESET_BASE": "mainnet", "PROPORTIONAL_SLASHING_MULTIPLIER": "1", "PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR": "2", "PROPORTIONAL_SLASHING_MULTIPLIER_BELLATRIX": "3", "PROPOSER_REWARD_QUOTIENT": "8", "PROPOSER_SCORE_BOOST": "40", "PROPOSER_WEIGHT": "8", "RANDOM_SUBNETS_PER_VALIDATOR": "1", "REORG_HEAD_WEIGHT_THRESHOLD": "20", "REORG_MAX_EPOCHS_SINCE_FINALIZATION": "2", "REORG_PARENT_WEIGHT_THRESHOLD": "160", "RESP_TIMEOUT": "10", "SAMPLES_PER_SLOT": "8", "SECONDS_PER_ETH1_BLOCK": "12", "SECONDS_PER_SLOT": "12", "SHARD_COMMITTEE_PERIOD": "256", "SHUFFLE_ROUND_COUNT": "90", "SLOTS_PER_EPOCH": "32", "SLOTS_PER_HISTORICAL_ROOT": "8192", "SUBNETS_PER_NODE": "2", "SYNC_COMMITTEE_SIZE": "512", "SYNC_COMMITTEE_SUBNET_COUNT": "4", "SYNC_REWARD_WEIGHT": "2", "TARGET_AGGREGATORS_PER_COMMITTEE": "16", "TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE": "16", "TARGET_BLOBS_PER_BLOCK_ELECTRA": "6", "TARGET_COMMITTEE_SIZE": "128", "TERMINAL_BLOCK_HASH": "0x0000000000000000000000000000000000000000000000000000000000000000", "TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH": "18446744073709551615", "TERMINAL_TOTAL_DIFFICULTY": "0", "TIMELY_HEAD_FLAG_INDEX": "0x02", "TIMELY_HEAD_WEIGHT": "14", "TIMELY_SOURCE_FLAG_INDEX": "0x00", "TIMELY_SOURCE_WEIGHT": "14", "TIMELY_TARGET_FLAG_INDEX": "0x01", "TIMELY_TARGET_WEIGHT": "26", "TTFB_TIMEOUT": "5", "UNSET_DEPOSIT_REQUESTS_START_INDEX": "18446744073709551615", "VALIDATOR_CUSTODY_REQUIREMENT": "8", "VALIDATOR_REGISTRY_LIMIT": "1099511627776", "WEIGHT_DENOMINATOR": "64", "WHISTLEBLOWER_REWARD_QUOTIENT": "512", "WHISTLEBLOWER_REWARD_QUOTIENT_ELECTRA": "4096"}}
```

Prysm version: `Prysm/v6.0.4 (linux amd64)`

Noticed that certain light-client methods were reorganized in #15383, don't know whether this still occurs :)

### PR DESCRIPTION
**Pull request by Inspector-Butters**
**What type of PR is this?**
Bug fix

**What does this PR do? Why is it needed?**
This PR addresses the versioning bug in our lc APIs. previously when we served the lc data with a "version" field, we used the version of the struct, which was not correct since some versions share the same underlying struct. Now the version comes from the slot of the attested header of a light client data type.

**Which issues(s) does this PR fix?**
Fixes #15393

### CODE REVIEW

**Review by terencechain — DISMISSED** [review]

File: beacon-chain/core/light-client/lightclient.go [hunk 1]
```diff
@@ -163,13 +163,13 @@ func NewLightClientUpdateFromBeaconState(
 	updateAttestedPeriod := slots.SyncCommitteePeriod(slots.ToEpoch(attestedBlock.Block().Slot()))
 
 	// update = LightClientUpdate()
-	result, err := CreateDefaultLightClientUpdate(currentSlot, attestedState)
```
Comment (rkapka) [inline beacon-chain/core/light-client/lightclient.go:166]: To make things more aligned with the spec and within Prysm, I think it would be cleaner to pass the attested block here instead of the attested state.

File: testing/spectest/shared/common/light_client/update_ranking.go [hunk 2]
```diff
@@ -20,6 +21,21 @@ import (
...
+	}
+	if v >= 3 {
+		params.BeaconConfig().CapellaForkEpoch = 0
+	}
+	if v >= 4 {
+		params.BeaconConfig().DenebForkEpoch = 0
+	}
+	if v >= 5 {
+		params.BeaconConfig().ElectraForkEpoch = 0
+	}
```
Comment (prestonvanloon) [inline testing/spectest/shared/common/light_client/update_ranking.go]: I know this is test code, but we can avoid these "magic numbers" by using the version enum.

```suggestion
	if v >= version.Altair {
		params.BeaconConfig().AltairForkEpoch = 0
	}
	if v >= version.Bellatrix {
		params.BeaconConfig().BellatrixForkEpoch = 0
	}
	if v >= version.Capella {
		params.BeaconConfig().CapellaForkEpoch = 0
	}
	if v >= version.Deneb {
		params.BeaconConfig().DenebForkEpoch = 0
	}
	if v >= version.Electra {
		params.BeaconConfig().ElectraForkEpoch = 0
	}
```
Do you want to handle Fulu while you are here? It's coming soon...

Comment (Inspector-Butters) [reply testing/spectest/shared/common/light_client/update_ranking.go]: thanks. will do.

File: beacon-chain/core/light-client/lightclient.go [hunk 3]
```diff
@@ -575,190 +520,57 @@ func ComputeWithdrawalsRoot(payload interfaces.ExecutionData) ([]byte, error) {
 
 func BlockToLightClientHeader(
 	ctx context.Context,
-	currentSlot primitives.Slot,
+	v int,
```
Comment (rkapka) [inline beacon-chain/core/light-client/lightclient.go]: Can you rename this to `attestedBlockVersion`? Because `v` doesn't mean much

File: beacon-chain/core/light-client/lightclient.go [hunk 4]
```diff
@@ -575,190 +520,57 @@ func ComputeWithdrawalsRoot(payload interfaces.ExecutionData) ([]byte, error) {
...
 	block interfaces.ReadOnlySignedBeaconBlock,
 ) (interfaces.LightClientHeader, error) {
-	var m proto.Message
-	currentEpoch := slots.ToEpoch(currentSlot)
-	blockEpoch := slots.ToEpoch(block.Block().Slot())
-	parentRoot := block.Block().ParentRoot()
-	stateRoot := block.Block().StateRoot()
-	bodyRoot, err := block.Block().Body().HashTreeRoot()
+	if block.Version() > v {
+		return nil, errors.Errorf("invalid block version %s for %s header", version.String(block.Version()), version.String(v))
```
Comment (rkapka) [inline beacon-chain/core/light-client/lightclient.go]:
```suggestion
		return nil, errors.Errorf("block version %s is greater than attested block version %s", version.String(block.Version()), version.String(v))
```
What do you think?

File: beacon-chain/core/light-client/lightclient.go [hunk 5]
```diff
@@ -575,190 +520,57 @@ func ComputeWithdrawalsRoot(payload interfaces.ExecutionData) ([]byte, error) {
...
-				ParentRoot:    parentRoot[:],
-				StateRoot:     stateRoot[:],
-				BodyRoot:      bodyRoot[:],
-			},
+			Beacon:          beacon,
 			Execution:       payloadHeader,
 			ExecutionBranch: payloadProof,
 		}
+	default:
+		return nil, fmt.Errorf("unsupported light client header version %s", version.String(v))
```
Comment (rkapka) [inline beacon-chain/core/light-client/lightclient.go]:
```suggestion
		return nil, fmt.Errorf("unsupported attested block version %s", version.String(v))
```

File: beacon-chain/core/light-client/helpers.go [hunk 6]
```diff
@@ -0,0 +1,243 @@
...
+			},
+			CurrentSyncCommittee:       currentSyncCommittee,
+			CurrentSyncCommitteeBranch: currentSyncCommitteeBranch,
+		}
+	}
+
+	return light_client.NewWrappedBootstrap(m)
+}
+
+func makeExecutionAndBranchDeneb(ctx context.Context, blk interfaces.ReadOnlySignedBeaconBlock) (*enginev1.ExecutionPayloadHeaderDeneb, [][]byte, error) {
```
Comment (rkapka) [inline beacon-chain/core/light-client/helpers.go]: I would change `Branch` to `Proof`. After all you return a variable called `payloadProof`

File: beacon-chain/core/light-client/lightclient.go [hunk 7]
```diff
@@ -575,190 +520,57 @@ func ComputeWithdrawalsRoot(payload interfaces.ExecutionData) ([]byte, error) {
...
-			}
-
-			payloadProof, err = blocks.PayloadProof(ctx, block.Block())
-			if err != nil {
-				return nil, errors.Wrap(err, "could not get execution payload proof")
-			}
+	case version.Capella:
+		payloadHeader, payloadProof, err := makeExecutionAndBranchCapella(ctx, block)
+		if err != nil {
+			return nil, errors.Wrap(err, "could not make execution payload header and branch")
```
Comment (rkapka) [inline beacon-chain/core/light-client/lightclient.go]:
```suggestion
			return nil, errors.Wrap(err, "could not make execution payload header and proof")
```
In case you rename this in the function name

File: beacon-chain/core/light-client/lightclient.go [hunk 8]
```diff
@@ -575,190 +520,57 @@ func ComputeWithdrawalsRoot(payload interfaces.ExecutionData) ([]byte, error) {
...
-			}
-
-			payloadProof, err = blocks.PayloadProof(ctx, block.Block())
-			if err != nil {
-				return nil, errors.Wrap(err, "could not get execution payload proof")
-			}
+	case version.Deneb, version.Electra, version.Fulu:
+		payloadHeader, payloadProof, err := makeExecutionAndBranchDeneb(ctx, block)
+		if err != nil {
+			return nil, errors.Wrap(err, "could not make execution payload header and branch")
```
Comment (rkapka) [inline beacon-chain/core/light-client/lightclient.go]:
```suggestion
			return nil, errors.Wrap(err, "could not make execution payload header and proof")
```
In case you rename this in the function name

File: beacon-chain/core/light-client/lightclient.go [hunk 9]
```diff
@@ -575,190 +520,57 @@ func ComputeWithdrawalsRoot(payload interfaces.ExecutionData) ([]byte, error) {
...
-		proof[i] = b[:]
-	}
-	return proof
-}
-
 func HasRelevantSyncCommittee(update interfaces.LightClientUpdate) (bool, error) {
+	fmt.Println(update.Version())
+	fmt.Println(update.AttestedHeader().Beacon().Slot)
+	fmt.Println(update.SignatureSlot())
+	fmt.Println(update.FinalizedHeader().Beacon().Slot)
```
Comment (rkapka) [inline beacon-chain/core/light-client/lightclient.go]: remove

File: consensus-types/light-client/finality_update.go [hunk 10]
```diff
@@ -174,7 +175,7 @@ func (u *finalityUpdateAltair) Proto() proto.Message {
 }
 
 func (u *finalityUpdateAltair) Version() int {
-	return version.Altair
+	return slots.ToForkVersion(u.attestedHeader.Beacon().Slot)
```
Comment (rkapka) [inline consensus-types/light-client/finality_update.go:177]: I am not strongly against using the same pattern for all types, but it's only Altair updates that can have a variable version, either `altair` or `bellatrix`. Versions for all other types will match these types.

File: beacon-chain/db/kv/lightclient.go [hunk 11]
```diff
@@ -297,6 +310,8 @@ func keyForLightClientUpdate(v int) ([]byte, error) {
 		return denebKey, nil
 	case version.Capella:
 		return capellaKey, nil
+	case version.Bellatrix:
+		return bellatrixKey, nil
 	case version.Altair:
 		return altairKey, nil
```
Comment (rkapka) [inline beacon-chain/db/kv/lightclient.go:316]:
```suggestion
	case version.Altair, version.Bellatrix:
		return altairKey, nil
```
This would also work, right? Not sure which one I like better

File: consensus-types/light-client/finality_update.go (hunk 10 above)
Comment (Inspector-Butters) [reply consensus-types/light-client/finality_update.go:177]: not exactly. for optimistic updates, it's (Altair, Bellatrix), Capella, (Deneb, Electra, Fulu).
for finality updates and normal updates, it's (Altair, Bellatrix), Capella, Deneb, (Electra, Fulu).

File: beacon-chain/db/kv/lightclient.go (hunk 11 above)
Comment (Inspector-Butters) [reply beacon-chain/db/kv/lightclient.go:316]: I think separating them is cleaner. but I'm not sure either.

File: consensus-types/light-client/update.go [hunk 12]
```diff
@@ -3,6 +3,8 @@ package light_client
 import (
 	"fmt"
 
+	"github.com/OffchainLabs/prysm/v6/time/slots"
+
```
Comment (prestonvanloon) [inline consensus-types/light-client/update.go]:
```suggestion
```

Probably will need to run goimports too.

File: consensus-types/light-client/optimistic_update.go [hunk 13]
```diff
@@ -3,11 +3,12 @@ package light_client
 import (
 	"fmt"
 
+	"github.com/OffchainLabs/prysm/v6/time/slots"
+
```
Comment (prestonvanloon) [inline consensus-types/light-client/optimistic_update.go]:
```suggestion
```

Probably will need to run goimports too.

File: consensus-types/light-client/finality_update.go [hunk 14]
```diff
@@ -3,12 +3,13 @@ package light_client
 import (
 	"fmt"
 
+	"github.com/OffchainLabs/prysm/v6/time/slots"
+
```
Comment (prestonvanloon) [inline consensus-types/light-client/finality_update.go]:
```suggestion
```
Probably will need to run goimports too.

File: consensus-types/light-client/bootstrap.go [hunk 15]
```diff
@@ -3,6 +3,8 @@ package light_client
 import (
 	"fmt"
 
+	"github.com/OffchainLabs/prysm/v6/time/slots"
+
```
Comment (prestonvanloon) [inline consensus-types/light-client/bootstrap.go]:
```suggestion
```
Probably will need to run goimports too.

File: beacon-chain/db/kv/lightclient_test.go [hunk 16]
```diff
@@ -213,19 +228,20 @@ func TestStore_LightClientUpdate_CanSaveRetrieve(t *testing.T) {
 		require.NoError(t, err)
 		require.DeepEqual(t, update, retrievedUpdate, "retrieved update does not match saved update")
 	})
-	t.Run("Capella", func(t *testing.T) {
-		update, err := createUpdate(t, version.Capella)
+	t.Run("Bellatrix", func(t *testing.T) {
```
Comment (prestonvanloon) [inline beacon-chain/db/kv/lightclient_test.go:231]: Looks like a great opportunity to make this iterative...

```
for _, v := range version.All() {
  t.Run(version.String(v), func(t *testing.T) {
    update, err := createUpdate(t, v)
   // the rest of the code...
  }
}
```

Then you can delete all of these individual code blocks since it's all identical besides the version argument in createUpdate

Comment (Inspector-Butters) [reply beacon-chain/db/kv/lightclient_test.go:231]: will do this in a follow up PR.

**Review by prestonvanloon — APPROVED** [review]
