### PR TITLE
Fix multiple deposits to the same pubkey pre-chain-start

### LINKED ISSUE #1973: Same Pub Key Can Deposit Multiple Times
Same public key could be used to deposit multiple times and start the chain. Seen below `0xabb76586a66e0124938baff7be419ac67bdb78b003fbd362c6dba9ad09bb1ad9778495bd83b0d03f3abd12270fbf43b6088d190e37eea2cb3107ec042dec3369f025b566602befb3c4f33f265ea54c23fe42df698e8be8ca9fd9ad75b192897f` deposited 7 times and then the chain started 

```
[2019-03-12 10:20:01]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=0 publicKey=0xabb76586a66e0124938baff7be419ac67bdb78b003fbd362c6dba9ad09bb1ad9778495bd83b0d03f3abd12270fbf43b6088d190e37eea2cb3107ec042dec3369f025b566602befb3c4f33f265ea54c23fe42df698e8be8ca9fd9ad75b192897f
[2019-03-12 10:22:01]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=1 publicKey=0xabb76586a66e0124938baff7be419ac67bdb78b003fbd362c6dba9ad09bb1ad9778495bd83b0d03f3abd12270fbf43b6088d190e37eea2cb3107ec042dec3369f025b566602befb3c4f33f265ea54c23fe42df698e8be8ca9fd9ad75b192897f
[2019-03-12 10:22:16]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=2 publicKey=0xabb76586a66e0124938baff7be419ac67bdb78b003fbd362c6dba9ad09bb1ad9778495bd83b0d03f3abd12270fbf43b6088d190e37eea2cb3107ec042dec3369f025b566602befb3c4f33f265ea54c23fe42df698e8be8ca9fd9ad75b192897f
[2019-03-12 10:22:46]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=3 publicKey=0xabb76586a66e0124938baff7be419ac67bdb78b003fbd362c6dba9ad09bb1ad9778495bd83b0d03f3abd12270fbf43b6088d190e37eea2cb3107ec042dec3369f025b566602befb3c4f33f265ea54c23fe42df698e8be8ca9fd9ad75b192897f
[2019-03-12 10:23:01]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=4 publicKey=0xabb76586a66e0124938baff7be419ac67bdb78b003fbd362c6dba9ad09bb1ad9778495bd83b0d03f3abd12270fbf43b6088d190e37eea2cb3107ec042dec3369f025b566602befb3c4f33f265ea54c23fe42df698e8be8ca9fd9ad75b192897f
[2019-03-12 10:24:16]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=5 publicKey=0xabb76586a66e0124938baff7be419ac67bdb78b003fbd362c6dba9ad09bb1ad9778495bd83b0d03f3abd12270fbf43b6088d190e37eea2cb3107ec042dec3369f025b566602befb3c4f33f265ea54c23fe42df698e8be8ca9fd9ad75b192897f
[2019-03-12 10:24:31]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=6 publicKey=0xabb76586a66e0124938baff7be419ac67bdb78b003fbd362c6dba9ad09bb1ad9778495bd83b0d03f3abd12270fbf43b6088d190e37eea2cb3107ec042dec3369f025b566602befb3c4f33f265ea54c23fe42df698e8be8ca9fd9ad75b192897f
[2019-03-12 10:24:31]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=7 publicKey=0xa0db0d3b7e1e63abb8fa5041e58c825477671a15b58bdf18282fcc6f34a6f55e9675ecebcb19b52286345a3deb687aa2097e78d568b1a58684a668255aa336ab5a8f35ad6ba7d637bc36a9dcad9e8dd0db30da0d5edb4fb4aa8f20cbc06a997f
[2019-03-12 10:24:31]  INFO powchain: Minimum number of validators reached for beacon-chain to start ChainStartTime=2019-03-12 10:25:00 -0700 PDT
[2019-03-12 10:24:31]  INFO blockchain: ChainStart time reached, starting the beacon chain!
```

### PR DESCRIPTION
**Pull request by IvanTheGreatDev**
This resolves #1973 but handles it in a different way the issue intended, public keys are always able to make multiple deposits, but our previous behavior for duplicate deposits was buggy.

Each duplicate validator was added to a new index
```
[2019-03-19 00:19:06]  INFO core/state: Current Epoch Boundary Attesting Balance: 0
[2019-03-19 00:19:06]  INFO core/state: Balance after FFG src calculation: [0 0 0 0 0 0 0 25460368]
[2019-03-19 00:19:06]  INFO core/state: Balance after FFG target calculation: [0 0 0 0 0 0 0 25448732]
[2019-03-19 00:19:06]  INFO core/state: Balance after chain head calculation: [0 0 0 0 0 0 0 25437096]
[2019-03-19 00:19:06]  INFO core/state: Balance after inclusion distance calculation: [0 0 0 0 0 0 0 25437096]
[2019-03-19 00:19:06]  INFO core/state: Previous justified epoch PreviousJustifiedEpoch=0
[2019-03-19 00:19:06]  INFO core/state: Justified epoch JustifiedEpoch=0
[2019-03-19 00:19:06]  INFO core/state: Finalized epoch FinalizedEpoch=0
[2019-03-19 00:19:06]  INFO core/state: Validator Registry Update Epoch ValidatorRegistryUpdateEpoch=0
[2019-03-19 00:19:06]  INFO core/state: Validator registry length NumValidators=8
```

This has now become: 
```
[2019-03-19 14:24:42]  INFO core/state: Previous epoch boundary attester indices: []
[2019-03-19 14:24:42]  INFO core/state: Processing Total Balance: 3200000
[2019-03-19 14:24:42]  INFO core/state: Previous Epoch Boundary Attesting Balance: 0
[2019-03-19 14:24:42]  INFO core/state: Current Epoch Boundary Attesting Balance: 0
[2019-03-19 14:24:42]  INFO core/state: Balance after FFG src calculation: [3188364]
[2019-03-19 14:24:42]  INFO core/state: Balance after FFG target calculation: [3176770]
[2019-03-19 14:24:42]  INFO core/state: Balance after chain head calculation: [3165219]
[2019-03-19 14:24:42]  INFO core/state: Balance after inclusion distance calculation: [3165219]
[2019-03-19 14:24:42]  INFO core/state: Previous justified epoch PreviousJustifiedEpoch=0
[2019-03-19 14:24:42]  INFO core/state: Justified epoch JustifiedEpoch=0
[2019-03-19 14:24:42]  INFO core/state: Finalized epoch FinalizedEpoch=0
[2019-03-19 14:24:42]  INFO core/state: Validator Registry Update Epoch ValidatorRegistryUpdateEpoch=0
[2019-03-19 14:24:42]  INFO core/state: Validator registry length NumValidators=1
```

### CODE REVIEW

File: beacon-chain/core/state/state.go [hunk 1]
```diff
@@ -78,9 +77,9 @@ func GenesisBeaconState(
 		}
 
 		validatorRegistry[i] = validator
-
 	}
 
+	latestBalances := make([]uint64, len(genesisValidatorDeposits))
```
Comment (IvanTheGreatDev) [inline beacon-chain/core/state/state.go]: I made this change for readability since seeing latestBalances next to the for loop made me think its being used there when it's not.

File: beacon-chain/powchain/log_processing.go [hunk 2]
```diff
@@ -72,32 +72,57 @@ func (w *Web3Service) ProcessDepositLog(depositLog gethTypes.Log) {
...
+		validData = false
 	}
+
 	deposit := &pb.Deposit{
 		DepositData:     depositData,
 		MerkleTreeIndex: index,
 	}
+
+	// Make sure duplicates are rejected pre-chainstart.
+	allDeps := w.beaconDB.AllDeposits(w.ctx, nil)
```
Comment (IvanTheGreatDev) [inline beacon-chain/powchain/log_processing.go]: Getting all deposits from the DB is going to be very expensive if we do this on every deposit. Is there a better option?

File: beacon-chain/powchain/log_processing.go [hunk 3]
```diff
@@ -72,32 +72,57 @@ func (w *Web3Service) ProcessDepositLog(depositLog gethTypes.Log) {
...
-		w.beaconDB.InsertPendingDeposit(w.ctx, deposit, big.NewInt(int64(depositLog.BlockNumber)))
+		for _, dep := range allDeps {
+			depInput, err := helpers.DecodeDepositInput(dep.DepositData)
+			if err != nil {
+				log.Errorf("Could not decode deposit input %v", err)
+				validData = false
+				break
+			}
+
+			if bytes.Equal(depositInput.Pubkey, depInput.Pubkey) {
```
Comment (IvanTheGreatDev) [inline beacon-chain/powchain/log_processing.go]: I know I can check the depositData instead of decoding it for the public keys, but for some reason it wasn't consistent. I'll toy with it again.

File: beacon-chain/powchain/log_processing.go [hunk 4]
```diff
@@ -72,32 +72,56 @@ func (w *Web3Service) ProcessDepositLog(depositLog gethTypes.Log) {
...
+
+	validData := true
+
+	// Make sure duplicates are rejected pre-chainstart.
 	if !w.chainStarted {
-		w.chainStartDeposits = append(w.chainStartDeposits, depositData)
-	} else {
-		w.beaconDB.InsertPendingDeposit(w.ctx, deposit, big.NewInt(int64(depositLog.BlockNumber)))
+		allDeps := w.beaconDB.AllDeposits(w.ctx, nil)
+		for _, dep := range allDeps {
```
Comment (prestonvanloon) [inline beacon-chain/powchain/log_processing.go]: Is there a better way to do this with O(1) lookup time? 
Otherwise this method is going to take longer as more deposits are added since this is linear time checking the entire list of all deposits.

Comment (IvanTheGreatDev) [reply beacon-chain/powchain/log_processing.go]: Not sure what can be done around this, I changed it to read from web3service chain starts deposits so it's a bit better now. Only faster way I can think of would be to maintain a mapping of bytes -> bool and marking the pubkey as entered by setting the key to true.

File: beacon-chain/powchain/log_processing.go [hunk 5]
```diff
@@ -72,32 +72,55 @@ func (w *Web3Service) ProcessDepositLog(depositLog gethTypes.Log) {
...
 	}
+
+	validData := true
+
+	// Make sure duplicates are rejected pre-chainstart.
 	if !w.chainStarted {
-		w.chainStartDeposits = append(w.chainStartDeposits, depositData)
-	} else {
-		w.beaconDB.InsertPendingDeposit(w.ctx, deposit, big.NewInt(int64(depositLog.BlockNumber)))
+		for _, dep := range w.chainStartDeposits {
```
Comment (prestonvanloon) [inline beacon-chain/powchain/log_processing.go]: This is going to cause O(n^2) insertion time. Please consider a better algorithm
