### PR TITLE
Fixes race condition at genesis

### LINKED ISSUE #5015: Fix Critical Race Condition Bug at Genesis
Hi all,

Currently in our blockchain service, we have two important goroutines that happen when the node first kicks off. One begins listening for incoming attestations, and the other begins listening for the genesis state to be initialized. The former depends on a **one time event** fired by the latter. Given the two are launched as goroutines at the same time, there's a high likelihood (reproducible 3/5 times locally) that the latter goroutine will fire before the former, preventing our node from listening to incoming attestations at all.

The offending code is here:

```go
		go func() {
			stateChannel := make(chan *feed.Event, 1)
			stateSub := s.stateNotifier.StateFeed().Subscribe(stateChannel)
			defer stateSub.Unsubscribe()
			for {
				select {
				case event := <-stateChannel:
					if event.Type == statefeed.ChainStarted {
						data := event.Data.(*statefeed.ChainStartedData)
						log.WithField("starttime", data.StartTime).Debug("Received chain start event")
						s.processChainStartTime(ctx, data.StartTime)
						return
					}
				case <-s.ctx.Done():
					log.Debug("Context closed, exiting goroutine")
					return
				case err := <-stateSub.Err():
					log.WithError(err).Error("Subscription to state notifier failed")
					return
				}
			}
		}()
	}

	go s.processAttestation()
```

In line https://github.com/prysmaticlabs/prysm/blob/aebc883a0da22e1d27cb9b10e4f9ffb24785d58e/beacon-chain/blockchain/service.go#L182 of our blockchain service, we fire a goroutine that has a race condition with `go s.processAttestations()`. We need to ensure this is deterministic, otherwise many prysm nodes can stall at mainnet genesis.

### PR DESCRIPTION
**Pull request by farazdagi**
Resolves #5015 

---

Fixes race condition by synchronising order of execution.

### CODE REVIEW

File: beacon-chain/blockchain/service.go [hunk 1]
```diff
@@ -137,6 +137,9 @@ func (s *Service) Start() {
 		}
 	}
 
+	// Make sure that attestation processor is subscribed and ready for state initializing event.
+	attestationProcessorSubscribed := make(chan struct{}, 1)
```
Comment (rauljordan) [inline beacon-chain/blockchain/service.go]: Do we need to make sure it is unbuffered so that it will block?

Comment (farazdagi) [reply beacon-chain/blockchain/service.go]: Well,  it will block on reader's side (which is what we need). And on writer, we can just write w/o blocking.

**Comment by farazdagi** [comment]
ping
