### PR TITLE
Fix slice out of bounds error in validator db migration

### LINKED ISSUE #8509: Validator Unable to Migrate to v1.3
# 🐞 Bug Report

### Description

A user has reported that their validator was unable to migrate upwards to v1.3 on the discord server. They also mentioned that 
they had pending validators coming online soon with already active validators which might have triggered the particular error seen below.

### Has this worked before in a previous version?

Before v1.3 

## 🔬 Minimal Reproduction

Run a Validator with both active/pending keys in v1.3 from v1.2.x onwards. 

## 🔥 Error

image

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Prevents an out of bounds error on line 138.

**Which issues(s) does this PR fix?**

Fixes  #8509

**Other notes for review**

### CODE REVIEW

**Review by nisdas — DISMISSED** [review]

**Review by terencechain — DISMISSED** [review]

**Review by nisdas — APPROVED** [review]

**Review by terencechain — APPROVED** [review]

File: validator/db/kv/migration_source_target_epochs_bucket_test.go [hunk 1]
```diff
@@ -14,7 +14,9 @@ import (
 
 func TestStore_migrateSourceTargetEpochsBucketUp(t *testing.T) {
 	numEpochs := uint64(100)
-	numKeys := 50
+	// numKeys should be more than batch size for testing.
```
Comment (Zolmeister) [inline validator/db/kv/migration_source_target_epochs_bucket_test.go:17]: Technically also shouldn't be a multiple of publicKeyMigrationBatchSize

Comment (nisdas) [reply validator/db/kv/migration_source_target_epochs_bucket_test.go:17]: Thanks for the spot ! #8523 has been opened to update the test case.
