### PR TITLE
Vendored github.com/tyler-smith/go-bip39

### LINKED ISSUE #15997: Cannot build validator: github.com/tyler-smith/go-bip39 is gone
# 💎 Issue

### Background

I tried to build prysm's validator as per instructions at https://prysm.offchainlabs.com/docs/install-prysm/install-with-bazel/.  In particular, I cloned the latest version of the `develop` branch (commit de0825f880f5f7c76ded5364fe6b28142f9294a0) and ran `bazel build //cmd/validator:validator --config=release`.

### Description

The validator depends on the github.com/tyler-smith/go-bip39 package, which appears to be deleted.  The build errors out as follows:

```
$ bazel build //cmd/validator:validator --config=release
INFO: Repository com_github_tyler_smith_go_bip39 instantiated at:
  /home/nickolai/refsrc/prysm/WORKSPACE:396:11: in <toplevel>
  /home/nickolai/refsrc/prysm/deps.bzl:3408:18: in prysm_deps
  /home/nickolai/refsrc/prysm/tools/go/def.bzl:70:10: in go_repository
  /home/nickolai/refsrc/prysm/tools/go/def.bzl:58:18: in maybe
Repository rule go_repository defined at:
  /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle/internal/go_repository.bzl:340:32: in <toplevel>
ERROR: /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle/internal/go_repository.bzl:256:17: An error occurred during the fetch of repository 'com_github_tyler_smith_go_bip39':
   Traceback (most recent call last):
	File "/home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle/internal/go_repository.bzl", line 256, column 17, in _go_repository_impl
		fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
ERROR: no such package '@@com_github_tyler_smith_go_bip39//': failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
ERROR: no such package '@@com_github_tyler_smith_go_bip39//wordlists': failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
ERROR: /home/nickolai/refsrc/prysm/validator/keymanager/derived/BUILD.bazel:3:11: //validator/keymanager/derived:go_default_library depends on @@com_github_tyler_smith_go_bip39//:go_default_library in repository @@com_github_tyler_smith_go_bip39 which failed to fetch. no such package '@@com_github_tyler_smith_go_bip39//': failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
ERROR: /home/nickolai/refsrc/prysm/validator/keymanager/derived/BUILD.bazel:3:11: //validator/keymanager/derived:go_default_library depends on @@com_github_tyler_smith_go_bip39//wordlists:go_default_library in repository @@com_github_tyler_smith_go_bip39 which failed to fetch. no such package '@@com_github_tyler_smith_go_bip39//wordlists': failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
ERROR: /home/nickolai/refsrc/prysm/cmd/validator/wallet/BUILD.bazel:3:11: //cmd/validator/wallet:go_default_library depends on @@com_github_tyler_smith_go_bip39//:go_default_library in repository @@com_github_tyler_smith_go_bip39 which failed to fetch. no such package '@@com_github_tyler_smith_go_bip39//': failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
ERROR: /home/nickolai/refsrc/prysm/cmd/validator/wallet/BUILD.bazel:3:11: //cmd/validator/wallet:go_default_library depends on @@com_github_tyler_smith_go_bip39//wordlists:go_default_library in repository @@com_github_tyler_smith_go_bip39 which failed to fetch. no such package '@@com_github_tyler_smith_go_bip39//wordlists': failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
ERROR: /home/nickolai/refsrc/prysm/validator/rpc/BUILD.bazel:3:11: //validator/rpc:go_default_library depends on @@com_github_tyler_smith_go_bip39//:go_default_library in repository @@com_github_tyler_smith_go_bip39 which failed to fetch. no such package '@@com_github_tyler_smith_go_bip39//': failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
ERROR: /home/nickolai/refsrc/prysm/validator/rpc/BUILD.bazel:3:11: //validator/rpc:go_default_library depends on @@com_github_tyler_smith_go_bip39//wordlists:go_default_library in repository @@com_github_tyler_smith_go_bip39 which failed to fetch. no such package '@@com_github_tyler_smith_go_bip39//wordlists': failed to fetch com_github_tyler_smith_go_bip39: fetch_repo: github.com/tyler-smith/go-bip39@v1.1.0: invalid version: git ls-remote -q origin in /home/nickolai/.cache/bazel/_bazel_nickolai/07c5abc4df5865a4f8dd6102bfba90f8/external/bazel_gazelle_go_repository_cache/pkg/mod/cache/vcs/b924af8be9f1a02719f734cdd61d6132b8922be229357d4ca54b11f018d9ce77: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
INFO: Analyzed target //cmd/validator:validator (0 packages loaded, 0 targets configured).
WARNING: errors encountered while analyzing target '//cmd/validator:validator', it will not be built.
Analysis failed
INFO: Found 0 targets...
ERROR: command succeeded, but there were loading phase errors
INFO: Elapsed time: 1.045s, Critical Path: 0.05s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Copied the code, as is, from the go mod cache. This repo was deleted from github at some point.

**Which issues(s) does this PR fix?**

Fixes #15997

**Other notes for review**

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
~Need to figure out the go mod / gazelle issue. Converting back to draft for now~

File: third_party/go-bip39/wordlists/japanese.go [hunk 1]
```diff
@@ -0,0 +1,2071 @@
...
+	"strings"
+)
+
+func init() {
+	// Ensure word list is correct
+	// $ wget https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/japanese.txt
+	// $ crc32 japanese.txt
+	// 0acc1419
+	checksum := crc32.ChecksumIEEE([]byte(japanese))
+	if fmt.Sprintf("%x", checksum) != "acc1419" {
```
Comment (prestonvanloon) [inline third_party/go-bip39/wordlists/japanese.go:15]: Why are these checksums different? I got the `0acc1419` but the code verifies something else!

Comment (kasey) [reply third_party/go-bip39/wordlists/japanese.go:15]: I wonder if it could be the trailing newline. Try moving the closing backtick to the end of the previous line?

Comment (kasey) [reply third_party/go-bip39/wordlists/japanese.go:15]: Actually I see this is using `TrimSpace`, which I think should drop that trailing newline, hmm.

Comment (prestonvanloon) [reply third_party/go-bip39/wordlists/japanese.go:15]: They aren't different, just a leading zero is missed in the string.

**Review by kasey — APPROVED** [review]
