### PR TITLE
Don't hard shutdown if mev-boost / relay is not available

### LINKED ISSUE #11379: Uncontactable builder results in process exit
# 🐞 Bug Report

### Description

If a builder is configured for the beacon node but it is unavailable at startup then prysm shuts down.  Other beacon nodes note that the builder is unavailable and continue with local execution payloads (they also appear to check periodically if the builder is back up, and allow blinded block production if so).

### Has this worked before in a previous version?

N/A

## 🔬 Minimal Reproduction

Run the beacon node with `--builder=http://localhost:18550` but without anything listening on that port.

## 🔥 Error

<pre><code>
{"level":"error","msg":"could not connect to builder: Get \"http://localhost:18550/eth/v1/builder/status\": dial tcp [::1]:18550: connect: connection refused","prefix":"main","time":"2022-08-31T20:40:56Z"}
</code></pre>

## 🌍  Your Environment
Prysm 3.0.0

### PR DESCRIPTION
**Pull request by terencechain**
Fixes #11379

### CODE REVIEW

File: beacon-chain/builder/service.go [hunk 1]
```diff
@@ -66,7 +65,7 @@ func NewService(ctx context.Context, opts ...Option) (*Service, error) {
 
 		// Is the builder up?
 		if err := s.c.Status(ctx); err != nil {
-			return nil, fmt.Errorf("could not connect to builder: %v", err)
+			log.WithError(err).Error("Failed to check builder status")
```
Comment (james-prysm) [inline beacon-chain/builder/service.go:68]: the next line says "builder has been configured" maybe we should put this in an else statement or return early here.

Comment (rauljordan) [reply beacon-chain/builder/service.go:68]: +1, thats my only feedback as well

**Review by james-prysm — APPROVED** [review]
