### PR TITLE
Fix ListValidatorBalances RPC API

### LINKED ISSUE #3844: ListValidatorBalances Not Working
The ListValidatorBalances RPC call returns nothing, given it expects indices or public keys to function. We should return all balances paginated by default.

### PR DESCRIPTION
**Pull request by rauljordan**
Resolves #3844 

---

# Description

**Write why you are making the changes in this pull request**

This PR allows for `ListValidatorBalances` to retrieve the latest balances with pagination properly if default parameters are passed in. It modifies the protobuf request/response to accommodate for this functionality and adds appropriate tests.

**Diff large due to protobuf regen**

### CODE REVIEW

File: beacon-chain/rpc/beacon_chain_server.go [hunk 1]
```diff
@@ -319,7 +325,28 @@ func (bs *BeaconChainServer) ListValidatorBalances(
 			})
 		}
 	}
-	return &ethpb.ValidatorBalances{Balances: res}, nil
+
+	if len(res) == 0 {
```
Comment (prestonvanloon) [inline beacon-chain/rpc/beacon_chain_server.go]: This the intended behavior? This reads, "if no balances matched the filter, return everything". 

So if I asked for a balance for an index that wasn't present in the state, i would get back all balances?

What about doing something like 
```go
if proto.Equal(req, &ethpb.GetValidatorBalancesRequest) {
   // return everything
}
```

hmm I guess you still need pagination though. In any case, I suggest to reconsider this approach.

Comment (rauljordan) [reply beacon-chain/rpc/beacon_chain_server.go]: Great point, I added this logic to check if no indices or pubkeys were passed in, return everything, but forgot the case where nothing matched the filter. That approach seems best.

**Comment by rauljordan** [comment]
PTAL @prestonvanloon
