### PR TITLE
Fix Stream Duties Server + Get Duties Before ChainStart

### LINKED ISSUE #5450: Display in Validator Client if Deposit Was Processed Before Chainstart
Would be very nice to get the feedback that the validator deposit has been processed and that the validator is ready to validate.

### PR DESCRIPTION
**Pull request by rauljordan**
**What does this PR do? Why is it needed?**

This PR is a precursor to #5814 as it includes several important server-side fixes. It also resolves #5450

- [x] It allows for validators to receive duties before chainstart if a genesis time / genesis state exists. 
- [x] It computes and sends next epoch duties over a stream to validator clients

### CODE REVIEW

File: beacon-chain/rpc/validator/assignments.go [hunk 1]
```diff
@@ -96,60 +110,83 @@ func (vs *Server) StreamDuties(req *ethpb.DutiesRequest, stream ethpb.BeaconNode
...
 			return nil, status.Errorf(codes.Internal, "Could not process slots up to %d: %v", epochStartSlot, err)
 		}
 	}
-	committeeAssignments, proposerIndexToSlots, err := helpers.CommitteeAssignments(s, req.Epoch)
+	committeeAssignments, proposerIndexToSlots, err := helpers.CommitteeAssignments(s, epoch)
 	if err != nil {
 		return nil, status.Errorf(codes.Internal, "Could not compute committee assignments: %v", err)
 	}
+	// Query the next epoch assignments for committee subnet subscriptions.
+	nextCommitteeAssignments, nextProposerIndexToSlots, err := helpers.CommitteeAssignments(s, epoch+1)
```
Comment (rauljordan) [inline beacon-chain/rpc/validator/assignments.go:131]: We make use of the next epoch assignments

File: beacon-chain/sync/initial-sync/service.go [hunk 2]
```diff
@@ -111,12 +111,16 @@ func (s *Service) Start() {
 	}
 
 	if genesis.After(roughtime.Now()) {
-		log.WithField(
-			"genesis time", genesis,
-		).Warn("Genesis time is in the future - waiting to start sync...")
-		time.Sleep(roughtime.Until(genesis))
```
Comment (rauljordan) [inline beacon-chain/sync/initial-sync/service.go:117]: This was not needed - it was preventing validators from getting duties before chainstart if a genesis time exists

File: beacon-chain/sync/initial-sync/service.go [hunk 3]
```diff
@@ -9,6 +9,8 @@ import (
 
 	"github.com/kevinms/leakybucket-go"
 	"github.com/pkg/errors"
+	"github.com/sirupsen/logrus"
+
```
Comment (rauljordan) [inline beacon-chain/sync/initial-sync/service.go:13]:
```suggestion
```

File: beacon-chain/sync/initial-sync/service.go (hunk 2 above)
Comment (0xKiwi) [reply beacon-chain/sync/initial-sync/service.go:117]: Great change!

File: beacon-chain/rpc/validator/assignments.go [hunk 4]
```diff
@@ -96,60 +110,84 @@ func (vs *Server) StreamDuties(req *ethpb.DutiesRequest, stream ethpb.BeaconNode
...
+		nextValidatorAssignments = append(nextValidatorAssignments, nextAssignment)
 		// Assign relevant validator to subnet.
 		assignValidatorToSubnet(pubKey, assignment.Status)
+		assignValidatorToSubnet(pubKey, nextAssignment.Status)
 	}
 
 	return &ethpb.DutiesResponse{
-		Duties: validatorAssignments,
+		Duties:             validatorAssignments,
+		CurrentEpochDuties: validatorAssignments,
```
[the remark this answers is not in the document]
Comment (rauljordan) [reply beacon-chain/rpc/validator/assignments.go:189]: Because we still have to support validators running on old images, otherwise it would be a breaking change for everyone talking to these beacon nodes. Once almost everyone is running the new duties code, we can remove that line and deduplicate.

**Comment by terencechain** [comment]
Currently testing this with my local validators. Will report back on some findings
