### PR TITLE
function to merge and validate saved/new blobs

### LINKED ISSUE #12785: Duplicated blobs can get saved in DB
Duplicated blobs can get saved in the DB. The DB should filter out the duplication and have it as no-op. Here is a unit test to reproduce this fault:
```go
t.Run("saving same blob twice", func(t *testing.T) {
		scs := generateBlobSidecars(t, 1)
		require.Equal(t, 1, len(scs))
		db := setupDB(t)
		require.NoError(t, db.SaveBlobSidecar(ctx, scs))

		saved, err := db.BlobSidecarsByRoot(ctx, bytesutil.ToBytes32(scs[0].BlockRoot))
		require.NoError(t, err)
		require.NoError(t, equalBlobSlices(scs, saved))

		require.NoError(t, db.SaveBlobSidecar(ctx, scs))
		saved, err = db.BlobSidecarsByRoot(ctx, bytesutil.ToBytes32(scs[0].BlockRoot))
		require.NoError(t, err)
		require.NoError(t, equalBlobSlices(scs, saved))
	})
```

### LINKED ISSUE #12848: db: save blob sidecar does not distinguish different blobs per call
Save blob sidecar takes in a list of blob sidecars. It is built in a dangerous assumption that all blob sidecars are from the same slot and root. There are no additional validations for this assumption
If a caller saves sidecars: `[{slot:100, index: 0},{slot:101, index: 1},{slot:102, index: 3},{slot:103, index: 5}]`
The sidecar will save the blobs as they are all under slot 100 and use the same key for everything

### PR DESCRIPTION
**Pull request by kasey**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Streamlines the logic in `SaveBlobSidecar` ensuring that all blobs in the db value are unique, belong to the same block, and are sorted.

**Which issues(s) does this PR fix?**

Fixes #12848 
Fixes #12785

**Other notes for review**

### CODE REVIEW

File: beacon-chain/db/kv/blob.go [hunk 1]
```diff
@@ -80,61 +75,95 @@ func (s *Store) SaveBlobSidecar(ctx context.Context, scs []*ethpb.BlobSidecar) e
...
+		return nil, errors.Wrapf(errBlobSidecarLimit, "%d > %d", didx, fieldparams.MaxBlobsPerBlock)
+	}
+	return scs[0:didx], nil
 }
 
 // sortSideCars sorts the sidecars by their index.
-func sortSideCars(scs []*ethpb.BlobSidecar) {
-	sort.Slice(scs, func(i, j int) bool {
-		return scs[i].Index < scs[j].Index
+func sortSideCars(sc []*ethpb.BlobSidecar) {
```
Comment (james-prysm) [inline beacon-chain/db/kv/blob.go:164]: small comment, any reason for changing the name here? just shorter?

File: beacon-chain/db/kv/blob.go [hunk 2]
```diff
@@ -80,61 +75,95 @@ func (s *Store) SaveBlobSidecar(ctx context.Context, scs []*ethpb.BlobSidecar) e
...
 		}
-		if !bytes.Equal(sc.BlockRoot, r) {
-			return fmt.Errorf("sidecar root mismatch: %x != %x", sc.BlockRoot, r)
+		// skip duplicate
+		if sc.Index == prev.Index {
+			continue
 		}
-		if sc.ProposerIndex != p {
-			return fmt.Errorf("sidecar proposer index mismatch: %d != %d", sc.ProposerIndex, p)
+		if didx != i {
```
Comment (james-prysm) [inline beacon-chain/db/kv/blob.go:150]: I liked this approach.

File: beacon-chain/db/kv/blob.go [hunk 3]
```diff
@@ -80,61 +75,95 @@ func (s *Store) SaveBlobSidecar(ctx context.Context, scs []*ethpb.BlobSidecar) e
...
+				if err := decode(ctx, existing, sc); err != nil {
 					return err
 				}
 			}
 		}
-		return bkt.Put(newKey, encodedBlobSidecar)
+
+		sc.Sidecars = append(sc.Sidecars, scs...)
+		sortSideCars(sc.Sidecars)
+		var err error
```
Comment (james-prysm) [inline beacon-chain/db/kv/blob.go:91]: why do we need this var?

Comment (kasey) [reply beacon-chain/db/kv/blob.go:91]: because on the next line we assign to the struct field directly, so err needs to be defined in this scope.

File: beacon-chain/db/kv/blob.go (hunk 1 above)
Comment (kasey) [reply beacon-chain/db/kv/blob.go:164]: oh wait, I had some changes to this func that I wound up reverting but this bit lingered. I meant to also change the capitalization of the func. But actually this is just unrelated cruft. 

The change I had for a bit was to take the BlobSidecars container. That changed the argument from a list of sidecars to a single sidecars value. So plural -> singular.

I'll go ahead and change the capitalization since we've already talked about it and undo the variable name change :)

Comment (kasey) [reply beacon-chain/db/kv/blob.go]: updated to revert that variable name change and change the func name, please take another look.

**Review by james-prysm — APPROVED** [review]
lgtm
