### PR TITLE
Moved delay att inclusion to fork choice service

### LINKED ISSUE #3336: error: could not process attestation until delay
Set up: 2 nodes with 32 validators each

Saw this earlier in my run time set up, not entirely sure how to reproduce, but wanted to open an issue first so we don't lose track.

```
[2019-08-27 16:04:47] ERROR rpc: could not receive attestation in chain service error=could not process attestation for fork choice until inclusion delay, time 1566947088 > time 1566947087
could not process block from fork choice service
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).ReceiveAttestationNoPubsub
	beacon-chain/blockchain/receive_attestation.go:75
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).ReceiveAttestation
	beacon-chain/blockchain/receive_attestation.go:50
github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*AttesterServer).SubmitAttestation.func1
	beacon-chain/rpc/attester_server.go:51
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1337
```

### LINKED ISSUE #3340: error: sync failed to handle p2p pubsub error epoch x can't be greater than y
Set up: 2 nodes with 32 validators each

Saw this earlier in run time not entirely sure how to reproduce, but wanted to open an issue first so we don't lose track.

```
[2019-08-28 10:10:18] ERROR sync: Failed to handle p2p pubsub error=epoch 12 can't be greater than 5
could not determine epoch start shard
github.com/prysmaticlabs/prysm/beacon-chain/core/helpers.AttestationDataSlot
        beacon-chain/core/helpers/attestation.go:45
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).waitForAttInclDelay
        beacon-chain/blockchain/receive_attestation.go:125
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).ReceiveAttestationNoPubsub
        beacon-chain/blockchain/receive_attestation.go:68
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconAttestationSubscriber
        beacon-chain/sync/subscriber_beacon_attestation.go:17
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1
        beacon-chain/sync/subscriber.go:114
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1337
could not get attestation slot
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).waitForAttInclDelay
        beacon-chain/blockchain/receive_attestation.go:127
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).ReceiveAttestationNoPubsub
        beacon-chain/blockchain/receive_attestation.go:68
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconAttestationSubscriber
        beacon-chain/sync/subscriber_beacon_attestation.go:17
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1
        beacon-chain/sync/subscriber.go:114
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1337
could not delay attestation inclusion
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).ReceiveAttestationNoPubsub
        beacon-chain/blockchain/receive_attestation.go:70
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).beaconAttestationSubscriber
        beacon-chain/sync/subscriber_beacon_attestation.go:17
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*RegularSync).subscribe.func1
        beacon-chain/sync/subscriber.go:114
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1337 topic=/eth2/beacon_attestation/ssz
```

### PR DESCRIPTION
**Pull request by terencechain**
This resolves #3336 and resolves #3340

When we calculated attestation data for slot we were using base state. That's wrong, we should be using target state and the best place to get target state (without having to recalculate) is from fork choice service package. There we can use checkpoint to state cache. This PR moves attestation inclusion delay logic to fork choice service's `OnAttestation`. This also aligns more with the spec order. I feel much better about this than before

### CODE REVIEW

File: beacon-chain/blockchain/forkchoice/process_attestation.go [hunk 1]
```diff
@@ -60,44 +60,49 @@ func (s *Store) OnAttestation(ctx context.Context, a *ethpb.Attestation) error {
...
 	// Verify attestation target has had a valid pre state produced by the target block.
 	baseState, err := s.verifyAttPreState(ctx, tgt)
 	if err != nil {
-		return err
+		return 0, err
 	}
 
 	// Verify Attestations cannot be from future epochs.
 	slotTime := baseState.GenesisTime + tgtSlot*params.BeaconConfig().SecondsPerSlot
 	currentTime := uint64(time.Now().Unix())
```
Comment (skillful-alex) [inline beacon-chain/blockchain/forkchoice/process_attestation.go]: Need to use roughtime

File: beacon-chain/blockchain/forkchoice/process_attestation.go [hunk 2]
```diff
@@ -138,6 +143,26 @@ func (s *Store) saveCheckpointState(ctx context.Context, baseState *pb.BeaconSta
...
+	slot, err := helpers.AttestationDataSlot(targetState, a.Data)
+	if err != nil {
+		return errors.Wrap(err, "could not get attestation slot")
+	}
+
+	nextSlot := slot + 1
+	duration := time.Duration(nextSlot*params.BeaconConfig().SecondsPerSlot)*time.Second + time.Millisecond
+	timeToInclude := time.Unix(int64(targetState.GenesisTime), 0).Add(duration)
+
+	time.Sleep(time.Until(timeToInclude))
```
Comment (skillful-alex) [inline beacon-chain/blockchain/forkchoice/process_attestation.go]: Also roughtime
