### PR TITLE
Make TLS mandatory by default when unmarshalling remote wallet options

### LINKED ISSUE #8091: Remote signer wallets in 1.0.4 break backwards compatibility with older wallets
# 🐞 Bug Report

### Description

Remote wallets created before 1.0.4 do not have 
```
"require_tls": true,
```
Causing an error when trying to start a validator that used tls with remote signer previously.
Adding require_tls fixes the issue.

### Has this worked before in a previous version?

There was no issues in versions before 1.0.4

## 🔬 Minimal Reproduction

Start a validator on version 1.0.3 or lower and use a keymanageropts.json with the form of 
 
```
{
	"remote_cert": {
		"crt_path":
		"key_path": 
		"ca_crt_path":
	},
	"remote_address": 
}
```
And connect to a remote-signer with tls. The above format was the format keymanageropts.json was created in older versions. In 1.0.4 it has the "require_tls": true, field.
## 🔥 Error

<pre><code>
level=fatal msg="Could not wait for validator activation: could not fetch validating keys: could not list accounts from remote server: rpc error: code = Unavailable desc = connection closed" prefix=validator
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
ubuntu
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
1.0.4
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

#7953 added a new flag to disable TLS with a remote wallet. Because no explicit default value was specified when unmarshalling options, this broke backward compatibility. A missing configuration field defaults to `RequireTls: false` when unmarshalling the options file, which results in skipping TLS. All remote wallets created before the new flag was introduced require TLS, but don't have the `RequireTls` field.

This PR provides a default value of `RequireTls: true` for backward compatibility.

**Which issues(s) does this PR fix?**

Fixes #8091

**Other notes for review**

N/A

### CODE REVIEW

File: validator/keymanager/remote/keymanager.go [hunk 1]
```diff
@@ -137,7 +137,9 @@ func UnmarshalOptionsFile(r io.ReadCloser) (*KeymanagerOpts, error) {
 			log.Errorf("Could not close keymanager config file: %v", err)
 		}
 	}()
-	opts := &KeymanagerOpts{}
+	opts := &KeymanagerOpts{
+		RemoteCertificate: &CertificateConfig{RequireTls: true},
```
Comment (nisdas) [inline validator/keymanager/remote/keymanager.go:141]: Wont this still fail ? All the older remote wallets will not have tls configured for

**Review by nisdas — APPROVED** [review]

File: validator/keymanager/remote/keymanager.go (hunk 1 above)
Comment (nisdas) [reply validator/keymanager/remote/keymanager.go:141]: Discussed offline, this should unblock our older users.
