### PR TITLE
fix: Multiple network flags should prevent the BN to start

### LINKED ISSUE #13801: Multiple network flags should prevent the BN to start.
### Describe the bug

Let's run the BN with both `--sepolia` and `--holesky` flags, like:

```
bazel run //cmd/beacon-chain --config=release -- --execution-endpoint=http://localhost:8551 --sepolia --jwt-secret /Users/manu/OffchainLabs/ethereum/jwt.hex --checkpoint-sync-url https://sepolia.beaconstate.info --genesis-beacon-api-url https://sepolia.beaconstate.info --accept-terms-of-use --holesky --force-clear-db
```

The BN starts. It should exit on error immediately.

### Has this worked before in a previous version?

Probably not.

Related to: https://github.com/prysmaticlabs/prysm/issues/13799

### PR DESCRIPTION
**Pull request by shyam-patel-kira**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**
This will prevent BN from starting if there are multiple network flags

**Which issues(s) does this PR fix?**

Fixes #13801 

**Other notes for review**
Let me know if I need to add comments to change any part of the code

### CODE REVIEW

File: cmd/flags_test.go [hunk 1]
```diff
@@ -237,3 +237,53 @@ func TestValidateNoArgs_SubcommandFlags(t *testing.T) {
...
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			app := &cli.App{
+				Before: ValidateNetworkFlags,
+				Action: func(c *cli.Context) error {
+					return nil
+				},
+				Flags: append([]cli.Flag{
```
Comment (nalepae) [inline cmd/flags_test.go:276]: Why using `append` here?

File: cmd/flags.go [hunk 2]
```diff
@@ -328,6 +351,21 @@ func ValidateNoArgs(ctx *cli.Context) error {
 	return nil
 }
 
+func ValidateNetworkFlags(ctx *cli.Context) error {
```
Comment (nalepae) [inline cmd/flags.go:354]: If you move this function into `prysm/config/features`, then you don't need to duplicate `SepoliaTestnet`, `HoleskyTestnet`, `Mainnet` and `NetworkFlags`.

Comment (nalepae) [reply cmd/flags.go:354]: `ValidateNetworkFlags` is a public function. Please as a documentation
```
// ValidateNetworkFlags ...
func ValidateNetworkFlags(...
```

File: cmd/flags.go [hunk 3]
```diff
@@ -328,6 +351,21 @@ func ValidateNoArgs(ctx *cli.Context) error {
...
+
+	networkFlagsCount := 0
+	for _, flag := range NetworkFlags {
+		if ctx.IsSet(flag.Names()[0]) {
+			networkFlagsCount++
```
Comment (nalepae) [inline cmd/flags.go:359]: Nit: You can already exit here if `networkFlagsCount > 1`. No need to iterate over all network flags then test the value out of the loop.

File: cmd/flags.go [hunk 4]
```diff
@@ -328,6 +351,21 @@ func ValidateNoArgs(ctx *cli.Context) error {
...
+		}
+	}
+
+	if networkFlagsCount > 1 {
+		return fmt.Errorf("cannot use more than one network flag at the same time")
```
Comment (nalepae) [inline cmd/flags.go:364]: No need to use `Errorf` since there is no variable in the error message.

However, it is not obvious to the user to know what "network flag" mean.
A good idea would be to list in the error message all possible network flags and indicate to the user they can use only one of them.

**Comment by nalepae** [comment]
I know the GH issue is only for the beacon node.
However, other binaries have the same issue (validator client and some other CLIs).

Could you handle them as well?

File: cmd/flags.go [hunk 5]
```diff
@@ -328,6 +351,21 @@ func ValidateNoArgs(ctx *cli.Context) error {
 	return nil
 }
 
+func ValidateNetworkFlags(ctx *cli.Context) error {
+
```
Comment (nalepae) [inline cmd/flags.go:355]: Unnecessary leading newline (the CI fails because of this).

Comment (shyam-patel-kira) [reply cmd/flags.go:355]: resolved this in the next commit

File: cmd/flags.go (hunk 4 above)
Comment (shyam-patel-kira) [reply cmd/flags.go:364]: alright, take a look at changes

File: cmd/flags.go (hunk 3 above)
Comment (shyam-patel-kira) [reply cmd/flags.go:359]: makes sense

File: cmd/flags.go (hunk 2 above)
Comment (shyam-patel-kira) [reply cmd/flags.go:354]: resolved this in the next commit

File: cmd/flags_test.go (hunk 1 above)
Comment (shyam-patel-kira) [reply cmd/flags_test.go:276]: removed this completely

**Comment by shyam-patel-kira** [comment]
> Other binaries have the same issue (validator client and some other CLIs).

I added it to the validator client, can you point out which other cli needs to be changes?

File: config/features/config.go [hunk 6]
```diff
@@ -337,3 +339,24 @@ func logDisabled(flag cli.DocGenerationFlag) {
 	}
 	log.WithField(name, flag.GetUsage()).Warn(disabledFeatureFlag)
 }
+
+// ValidateNetworkFlags validates and prevents beacon node
```
Comment (nalepae) [inline config/features/config.go:343]: Not only beacon node.

**Comment by nalepae** [comment]
> I added it to the validator client, can you point out which other cli needs to be changed?

The only other place I see these flags are:
```
prysmctl validator exit
```

File: config/features/config.go (hunk 6 above)
Comment (shyam-patel-kira) [reply config/features/config.go]: Updated the comment

**Comment by shyam-patel-kira** [comment]
> ```
> prysmctl validator exit
> ```
added it here

**Comment by nalepae** [comment]
Thanks!

**Review by nalepae — APPROVED** [review]
