### PR TITLE
Fee recipient: checksum log

### LINKED ISSUE #10631: Checksum to fee recipient address
It might be useful to validate the fee recipient address for checksum as defined in eip55. The client should warn or error out if the checksum fails 

Reference: https://eips.ethereum.org/EIPS/eip-55

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

Reopening PR for checksum check for fee recipient.

Users should be aware when they use a non checksummed fee recipient. This new validation will warn users that they are using the non checksummed version but using the correct address with all lower case(invalid checksum) would still go to the same destination ( correct checksum address)

**Which issues(s) does this PR fix?**

Fixes #10631

### CODE REVIEW

File: beacon-chain/node/config.go [hunk 1]
```diff
@@ -117,7 +118,15 @@ func configureExecutionSetting(cliCtx *cli.Context) error {
...
 		return fmt.Errorf("%s is not a valid fee recipient address", ha)
 	}
-	c.DefaultFeeRecipient = common.HexToAddress(ha)
+	mixedcaseAddress, err := common.NewMixedcaseAddressFromString(ha)
+	if err != nil {
+		return errors.Wrapf(err, "could not decode fee recipient %s", ha)
+	}
+	checksumAddress := common.HexToAddress(ha)
+	if !mixedcaseAddress.ValidChecksum() {
+		log.Warnf("fee recipient %s is not a valid checksum address. The checksummed address is %s and this will be used as the fee recipient", ha, checksumAddress.Hex())
```
Comment (rauljordan) [inline beacon-chain/node/config.go:127]: Let's consider this log from the user's perspective. Many do not know what a checksum is, so we should instead warn them that a checksummed address is safer to prevent against spelling mistakes in Ethereum addresses. The provided address was not checksummed and will be used as is when setting transaction fee recipients

Comment (james-prysm) [reply beacon-chain/node/config.go:127]: i'll go ahead and update this

Comment (rauljordan) [reply beacon-chain/node/config.go:127]: Maybe something about how we recommend using a mixed-case address to prevent against spelling mistakes in your fee recipient Ethereum address. The provided address is not a valid checksum (mixed-case) address. Not sure if we should link people to a specific place, but something worth thinking about

File: beacon-chain/node/config.go [hunk 2]
```diff
@@ -117,7 +118,15 @@ func configureExecutionSetting(cliCtx *cli.Context) error {
...
 		return fmt.Errorf("%s is not a valid fee recipient address", ha)
 	}
-	c.DefaultFeeRecipient = common.HexToAddress(ha)
+	mixedcaseAddress, err := common.NewMixedcaseAddressFromString(ha)
+	if err != nil {
+		return errors.Wrapf(err, "could not decode fee recipient %s", ha)
+	}
+	checksumAddress := common.HexToAddress(ha)
+	if !mixedcaseAddress.ValidChecksum() {
+		log.Warnf("fee recipient %s is not a valid checksum address. The checksummed address is %s and this will be used as the fee recipient. We recommend using a mixed-case address ( checksummed address ) to prevent spelling mistakes in your fee recipient Ethereum address", ha, checksumAddress.Hex())
```
Comment (rauljordan) [inline beacon-chain/node/config.go:127]:
```suggestion
		log.Warnf("fee recipient %s is not a checksum Ethereum address. The checksummed address is %s and will be used as the fee recipient. We recommend using a mixed-case address (checksum) to prevent spelling mistakes in your fee recipient Ethereum address", ha, checksumAddress.Hex())
```

File: validator/node/node.go [hunk 3]
```diff
@@ -539,8 +539,16 @@ func feeRecipientConfig(cliCtx *cli.Context) (*validatorServiceConfig.FeeRecipie
 			if !common.IsHexAddress(option.FeeRecipient) {
 				return nil, errors.New("fee recipient is not a valid eth1 address")
 			}
+			mixedcaseAddress, err := common.NewMixedcaseAddressFromString(option.FeeRecipient)
+			if err != nil {
+				return nil, errors.Wrapf(err, "could not decode fee recipient %s", option.FeeRecipient)
+			}
+			checksumAddress := common.BytesToAddress(feebytes)
+			if !mixedcaseAddress.ValidChecksum() {
+				log.Warnf("fee recipient %s is not a valid checksum address. The checksummed address is %s and this will be used as the fee recipient. We recommend using a mixed-case address (checksummed address) to prevent spelling mistakes in your fee recipient Ethereum address.", option.FeeRecipient, checksumAddress.Hex())
```
Comment (rauljordan) [inline validator/node/node.go:548]:
```suggestion
				log.Warnf("Fee recipient %s is not a checksum Ethereum address. The checksummed address is %s and will be used as the fee recipient. We recommend using a mixed-case address (checksum) to prevent spelling mistakes in your fee recipient Ethereum address", option.FeeRecipient, checksumAddress.Hex())
```

File: beacon-chain/node/config.go [hunk 4]
```diff
@@ -117,7 +118,15 @@ func configureExecutionSetting(cliCtx *cli.Context) error {
...
 		return fmt.Errorf("%s is not a valid fee recipient address", ha)
 	}
-	c.DefaultFeeRecipient = common.HexToAddress(ha)
+	mixedcaseAddress, err := common.NewMixedcaseAddressFromString(ha)
+	if err != nil {
+		return errors.Wrapf(err, "could not decode fee recipient %s", ha)
+	}
+	checksumAddress := common.HexToAddress(ha)
+	if !mixedcaseAddress.ValidChecksum() {
+		log.Warnf("fee recipient %s is not a checksum Ethereum address. The checksummed address is %s and will be used as the fee recipient. We recommend using a mixed-case address (checksum) to prevent spelling mistakes in your fee recipient Ethereum address", ha, checksumAddress.Hex())
```
Comment (rauljordan) [inline beacon-chain/node/config.go:127]:
```suggestion
		log.Warnf("Fee recipient %s is not a checksum Ethereum address. The checksummed address is %s and will be used as the fee recipient. We recommend using a mixed-case address (checksum) to prevent spelling mistakes in your fee recipient Ethereum address", ha, checksumAddress.Hex())
```

**Review by rauljordan — APPROVED** [review]

**Review by rauljordan — APPROVED** [review]

**Review by rauljordan — APPROVED** [review]
