### PR TITLE
Warn rather than fail on incorrect keystore password

### LINKED ISSUE #4955: One validator key with an incorrect password causes all to fail
When launching the validator client with three validator keys, one had a password that was not provided correctly and the validator failed with:

`ERROR main: could not get private key: could not decrypt key with given passphrase`

The ideal behavior is that the validator would continue to validate for keys with the correct passphrase while aggressively reporting the warning for the key(s) with incorrect passwords. One bad key should not stop the whole show.

### PR DESCRIPTION
**Pull request by mcdee**
This fixes an issue on validator startup where any failure to decrypt a keystore would cause the validator to exit.  It now provides a warning about the failure, and continues.

Resolves #4955

### CODE REVIEW

File: shared/keystore/keystore.go [hunk 1]
```diff
@@ -104,7 +105,10 @@ func (ks Store) GetKeys(directory, fileprefix, password string) (map[string]*Key
 			}
 			key, err := DecryptKey(keyjson, password)
 			if err != nil {
-				return nil, err
+				if warnOnFail {
```
Comment (0xKiwi) [inline shared/keystore/keystore.go]: Why is this a toggleable action?

Comment (mcdee) [reply shared/keystore/keystore.go]: `GetKeys` is called in various places, including to check if certain keys exist, so this flag stops spurious errors from showing up in the logs.
