### PR TITLE
Prevent Usage of Stdlib File/Dir Writing With Static Analysis

### LINKED ISSUE #7410: Trail of Bits audit tracking
This tracks the progress on audit resolutions, we will update this through out the duration of the audit:

- [x] 1. Failure to propagate errors in beacon-chain #7246
- [x] 2. Data race in featureconfig #7406
- [x] 3. Context leak in validator client #7405
- [x] 4. Variable shadowing in beacon-chain history regeneration code #7308
- [x] 5. Data race in beacon-chain syncing code #7682
- [x] 6. Failure to error check could cause undefined behavior #7398 #7403
- [x] 7. Improvements needed to Bazel end-to-end testing documentation
- [x] 8. Raw password logged #7404 
- [x] 9. Dependencies are out of date #7646
- [x] 10. Code relies on two dependencies with OSS advisories #7646
- [x] 11. Overwrite of powchain.Service.preGenesisState even when deposits cannot be processed #7681
- [x] 12. Excessive memory usage by snappy.Decode _(Invalid, see reason below)_
- [x] 13. Improper use of recover in hashutil.HashProto #7683
- [x] 14. Improper use of recover in powchain.Service #7435
- [x] 15. Premature loop exit causes validator deposits to be missed #7678
- [x] 16. Proposer indices cannot be retrieved from cache #7442
- [x] 17. Shuffled list is not added to cache if proposer indices are present #7442
- [x] 18. Inefficiencies surrounding use of cache #7442
- [x] 19. Wrong domain used in helpers.SlotSignature #7447
- [x] 20. Wrong loop exit condition in store.ForkChoice.AncestorRoot #7226
- [x] 21. Handler on_tick unimplemented (we dont have a ticker, the slot advances as block comes in)
- [x] 22. Hardcoded contract bytecode
- [x] 23. Files and directories created with os.MkdirAll and ioutil.WriteFile are not ensured to have correct permissions #7685
- [x] 24. Response body not closed in tests #7450
- [x] 25. Password guesses should be limited to prevent brute force
- [x] 26. Premature exit under certain conditions in blockchain.Service.ancestor

### PR DESCRIPTION
**Pull request by rauljordan**
**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

This PR prevents usage of ioutil.WriteFile and os.MkdirAll in our repository, as those are unsafe when it comes to checking permissions. For example, an attacker could create a directory `p` with 777 permissions, and `os.MkdirAll(p)` will fail silently, without overriding the permissions of the attacker. Instead, we enforce Prysm to use our own `shared/fileutil` package that properly checks for permissions errors compared to the Go standard library. We enforce this using a static analyzer that prevents `os.MkdirAll` and `ioutil.WriteFile`.

**Which issues(s) does this PR fix?**

Part of #7410 and fixes #7410

### CODE REVIEW

File: shared/fileutil/fileutil.go [hunk 1]
```diff
@@ -28,6 +27,51 @@ func ExpandPath(p string) (string, error) {
...
+// permissions of every directory along the path, ensuring we are not attempting
+// to overwrite any existing permissions. Finally, creates the directory accordingly
+// with standardized, Prysm project permissions. This is the static-analysis enforced
+// method for creating a directory programmatically in Prysm.
+func MkdirAll(pth string) error {
+	expanded, err := ExpandPath(pth)
+	if err != nil {
+		return err
+	}
+	exists, err := HasDir(pth)
```
Comment (rkapka) [inline shared/fileutil/fileutil.go:40]: Shouldn't it be `HasDir(expanded)`?

File: shared/fileutil/fileutil.go [hunk 2]
```diff
@@ -28,6 +27,51 @@ func ExpandPath(p string) (string, error) {
...
+	if err != nil {
+		return err
+	}
+	if exists {
+		info, err := os.Stat(expanded)
+		if err != nil {
+			return err
+		}
+		if info.Mode().Perm() != params.BeaconIoConfig().ReadWriteExecutePermissions {
+			return errors.New("dir already exists with wrong permissions")
```
Comment (rkapka) [inline shared/fileutil/fileutil.go:50]: Are you sure that `wrong` is the correct wording here? Maybe the permissions are correct and the new dir should be placed somewhere else.

File: shared/fileutil/fileutil.go [hunk 3]
```diff
@@ -28,6 +27,51 @@ func ExpandPath(p string) (string, error) {
...
+	if err != nil {
+		return err
+	}
+	if FileExists(expanded) {
+		info, err := os.Stat(expanded)
+		if err != nil {
+			return err
+		}
+		if info.Mode() != params.BeaconIoConfig().ReadWritePermissions {
+			return errors.New("file already exists with wrong permissions")
```
Comment (rkapka) [inline shared/fileutil/fileutil.go:69]: Same comment about `wrong`.

File: shared/fileutil/fileutil_test.go [hunk 4]
```diff
@@ -47,6 +48,30 @@ func TestPathExpansion(t *testing.T) {
...
 
+func TestMkdirAll(t *testing.T) {
+	dirName := testutil.TempDir() + "somedir"
+	err := os.MkdirAll(dirName, os.ModePerm)
+	require.NoError(t, err)
+	defer func() {
+		assert.NoError(t, os.RemoveAll(dirName))
+	}()
+	err = fileutil.MkdirAll(dirName)
+	assert.ErrorContains(t, "already exists with wrong permissions", err)
```
Comment (rkapka) [inline shared/fileutil/fileutil_test.go:59]: You should also test the happy path - when `fileutil` does not return an error.

File: shared/fileutil/fileutil_test.go [hunk 5]
```diff
@@ -47,6 +48,30 @@ func TestPathExpansion(t *testing.T) {
...
+	dirName := testutil.TempDir() + "somedir"
+	err := os.MkdirAll(dirName, os.ModePerm)
+	require.NoError(t, err)
+	defer func() {
+		assert.NoError(t, os.RemoveAll(dirName))
+	}()
+	someFileName := filepath.Join(dirName, "somefile.txt")
+	require.NoError(t, ioutil.WriteFile(someFileName, []byte("hi"), os.ModePerm))
+	err = fileutil.WriteFile(someFileName, []byte("hi"))
+	assert.ErrorContains(t, "already exists with wrong permissions", err)
```
Comment (rkapka) [inline shared/fileutil/fileutil_test.go:72]: You should also test the happy path - when `fileutil` does not return an error.

File: slasher/db/kv/kv.go [hunk 6]
```diff
@@ -87,9 +88,16 @@ func createBuckets(tx *bolt.Tx, buckets ...[]byte) error {
...
 		return nil, err
 	}
+	if !hasDir {
+		if err := fileutil.MkdirAll(dirPath); err != nil {
+			return nil, err
+		}
+	}
+
 	datafile := path.Join(dirPath, databaseFileName)
 	boltDB, err := bolt.Open(datafile, params.BeaconIoConfig().ReadWritePermissions, &bolt.Options{Timeout: params.BeaconIoConfig().BoltTimeout})
```
Comment (rkapka) [inline slasher/db/kv/kv.go:102]: Same comment as in `beacon-chain/db/kv/kv.go`

File: tools/analyzers/writefile/analyzer.go [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+	"fmt"
+	"go/ast"
+
+	"golang.org/x/tools/go/analysis"
+	"golang.org/x/tools/go/analysis/passes/inspect"
+	"golang.org/x/tools/go/ast/inspector"
+)
+
+// Doc explaining the tool.
+const Doc = "Tool to enforce usage of Prysm's internal file-writing utils instead of os.MkdirAll or ioutil.WriteFile"
```
Comment (rkapka) [inline tools/analyzers/writefile/analyzer.go:17]: Package/function names are mixed up either here or in the package-level comment.

File: tools/analyzers/writefile/analyzer.go [hunk 8]
```diff
@@ -0,0 +1,101 @@
+// Package writefile implements a static analyzer to ensure that Prysm does not
+// use ioutil.MkdirAll or os.WriteFile as they are unsafe when it comes to guaranteeing
+// file permissions and not overriding existing permissions.
+package writefile
```
Comment (rkapka) [inline tools/analyzers/writefile/analyzer.go:4]: The analyzer also checks directories. Can you think of a broader name?

File: tools/analyzers/writefile/analyzer.go [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+// Doc explaining the tool.
+const Doc = "Tool to enforce usage of Prysm's internal file-writing utils instead of os.MkdirAll or ioutil.WriteFile"
+
+var errUnsafePackage = errors.New(
+	"os and ioutil dir and file writing functions are not permissions-safe, use shared/fileutil",
+)
+
+// Analyzer runs static analysis.
+var Analyzer = &analysis.Analyzer{
+	Name:     "writefile",
```
Comment (rkapka) [inline tools/analyzers/writefile/analyzer.go:25]: Don't forget about this name in case you change the package name :)

File: validator/db/kv/db.go [hunk 10]
```diff
@@ -61,9 +62,15 @@ func createBuckets(tx *bolt.Tx, buckets ...[]byte) error {
...
+	if err != nil {
 		return nil, err
 	}
+	if !hasDir {
+		if err := fileutil.MkdirAll(dirPath); err != nil {
+			return nil, err
+		}
+	}
 	datafile := filepath.Join(dirPath, ProtectionDbFileName)
 	boltDB, err := bolt.Open(datafile, params.BeaconIoConfig().ReadWritePermissions, &bolt.Options{Timeout: params.BeaconIoConfig().BoltTimeout})
```
Comment (rkapka) [inline validator/db/kv/db.go:75]: Same comment as in `beacon-chain/db/kv/kv.go`

File: beacon-chain/db/kv/kv.go [hunk 11]
```diff
@@ -46,9 +47,15 @@ type Store struct {
...
-	if err := os.MkdirAll(dirPath, params.BeaconIoConfig().ReadWriteExecutePermissions); err != nil {
+	hasDir, err := fileutil.HasDir(dirPath)
+	if err != nil {
 		return nil, err
 	}
+	if !hasDir {
+		if err := fileutil.MkdirAll(dirPath); err != nil {
+			return nil, err
+		}
+	}
```
Comment (rkapka) [inline beacon-chain/db/kv/kv.go:58]: Can you please write some tests?

File: slasher/db/kv/kv.go [hunk 12]
```diff
@@ -87,9 +88,16 @@ func createBuckets(tx *bolt.Tx, buckets ...[]byte) error {
...
+	hasDir, err := fileutil.HasDir(dirPath)
+	if err != nil {
 		return nil, err
 	}
+	if !hasDir {
+		if err := fileutil.MkdirAll(dirPath); err != nil {
+			return nil, err
+		}
+	}
+
```
Comment (rkapka) [inline slasher/db/kv/kv.go:100]: Can you please write some tests?

File: validator/db/kv/db.go [hunk 13]
```diff
@@ -61,9 +62,15 @@ func createBuckets(tx *bolt.Tx, buckets ...[]byte) error {
...
-	if err := os.MkdirAll(dirPath, params.BeaconIoConfig().ReadWriteExecutePermissions); err != nil {
+	hasDir, err := fileutil.HasDir(dirPath)
+	if err != nil {
 		return nil, err
 	}
+	if !hasDir {
+		if err := fileutil.MkdirAll(dirPath); err != nil {
+			return nil, err
+		}
+	}
```
Comment (rkapka) [inline validator/db/kv/db.go:73]: Can you please write some tests?

File: tools/analyzers/writefile/analyzer.go [hunk 14]
```diff
@@ -0,0 +1,101 @@
...
+		switch stmt := node.(type) {
+		case *ast.File:
+			// Reset aliases (per file).
+			aliases = make(map[string]string)
+		case *ast.ImportSpec:
+			// Collect aliases.
+			pkg := stmt.Path.Value
+			if pkg == "\"os\"" {
+				if stmt.Name != nil {
+					aliases[stmt.Name.Name] = stmt.Path.Value
```
Comment (rkapka) [inline tools/analyzers/writefile/analyzer.go:56]: You can replace `stmt.Path.Value` with `pkg` everywhere inside both conditionals.

File: tools/analyzers/writefile/analyzer.go [hunk 15]
```diff
@@ -0,0 +1,101 @@
...
+			if pkg == "\"io/ioutil\"" {
+				if stmt.Name != nil {
+					aliases[stmt.Name.Name] = stmt.Path.Value
+				} else {
+					aliases["ioutil"] = stmt.Path.Value
+				}
+			}
+		case *ast.CallExpr:
+			// Check if any of disallowed functions have been used.
+			for pkg, path := range aliases {
```
Comment (rkapka) [inline tools/analyzers/writefile/analyzer.go:70]: Earlier you use the variable `pkg` (actually the equivalent `stmt.Path.Value`) to populate the map's value, and here you use the name `pkg` for the key. This is a bit confusing. Wouldn't `for alias, pkg := range aliases {` be more in line with what the map contains?

File: tools/analyzers/writefile/analyzer.go [hunk 16]
```diff
@@ -0,0 +1,101 @@
...
+				for _, fn := range disallowedFns {
```
Comment (rkapka) [inline tools/analyzers/writefile/analyzer.go:71]: This is not that big of a deal, but since you have a nested loop you check `MkdirAll` and `WriteFile` for both packages.

**Review by rkapka — CHANGES_REQUESTED** [review]
Please add more tests.

File: beacon-chain/db/kv/kv.go [hunk 17]
```diff
@@ -46,9 +47,15 @@ type Store struct {
...
 	datafile := path.Join(dirPath, databaseFileName)
 	boltDB, err := bolt.Open(datafile, params.BeaconIoConfig().ReadWritePermissions, &bolt.Options{Timeout: 1 * time.Second, InitialMmapSize: 10e6})
```
[the remark this answers is not in the document]
Comment (rauljordan) [reply beacon-chain/db/kv/kv.go:60]: If it already exists that means you already have a database and we should open it normally to start your beacon node

File: tools/analyzers/writefile/analyzer.go (hunk 16 above)
Comment (rauljordan) [reply tools/analyzers/writefile/analyzer.go]: this is ok because it's better if it's extensible. In the future we can easily add more functions we want to check against near the top of the file

**Review by rkapka — DISMISSED** [review]

**Review by 0xKiwi — APPROVED** [review]
