### PR TITLE
Avoid Panic Retrieving Validator Public Key 

### LINKED ISSUE #2561: beacon - panic: runtime error: index out of range
beacon-chain crash on docker.

```
panic: runtime error: index out of range

goroutine 1329 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).saveValidatorIdx(0xc0007ac300, 0xc0001a6e00, 0xc002d7a998, 0x1)
	beacon-chain/blockchain/block_processing.go:323 +0x220
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).runStateTransition(0xc0007ac300, 0x16186e0, 0xc0000820c0, 0x8f4eaf734d5f4844, 0x5a406f5c9ebac0a5, 0x7cebd57a54902030, 0x82b8c587855f4ea4, 0x0, 0xc0001a6e00, 0xc0001a6e00, ...)
	beacon-chain/blockchain/block_processing.go:299 +0x341
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*ChainService).ApplyBlockStateTransition(0xc0007ac300, 0x16186e0, 0xc0000820c0, 0xc0018a6320, 0xc0001a6e00, 0x0, 0x0, 0x82b8c587855f4ea4)
	beacon-chain/blockchain/block_processing.go:169 +0x1dc
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).exitInitialSync(0xc0005caaa0, 0x16186e0, 0xc0000820c0, 0xc0018a6320, 0xc000f1ae10, 0x0, 0x0)
	beacon-chain/sync/initial-sync/service.go:183 +0x51b
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).processBlock(0xc0005caaa0, 0x16187a0, 0xc00292c1e0, 0xc0018a6320, 0xc000f1ae10, 0x0, 0x0)
	beacon-chain/sync/initial-sync/sync_blocks.go:28 +0x111
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).processBatchedBlocks(0xc0005caaa0, 0x16187a0, 0xc001802660, 0xc001b24780, 0x22, 0x1610d60, 0xc001a6fb00, 0xc000f1ae10, 0x0, 0x0)
	beacon-chain/sync/initial-sync/sync_blocks.go:63 +0x361
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).syncToPeer(0xc0005caaa0, 0x1618760, 0xc00153efc0, 0xc000f1ae10, 0xc001428c60, 0x22, 0x0, 0x0)
	beacon-chain/sync/initial-sync/service.go:291 +0x6c7
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).run(0xc0005caaa0, 0xc00049fe90)
	beacon-chain/sync/initial-sync/service.go:249 +0x3f4
created by github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*InitialSync).Start
	beacon-chain/sync/initial-sync/service.go:138 +0x49
```

### PR DESCRIPTION
**Pull request by terencechain**
This fixes #2561 

If for some reason, a validator is not yet included in state, and we try to save the its index to public key to the DB, it will result in a panic and shut down beacon node.
This implements a protection by checking validator length in state before retrieving its public key, if the validator is not in state yet, beacon node will again next epoch by placing index into the right queue

### CODE REVIEW

File: beacon-chain/blockchain/block_processing.go [hunk 1]
```diff
@@ -323,13 +323,22 @@ func (c *ChainService) runStateTransition(
...
+		if int(idx) >= len(state.ValidatorRegistry) {
+			idxNotInState = append(idxNotInState, idx)
+			continue
+		}
 		pubKey := state.ValidatorRegistry[idx].Pubkey
 		if err := c.beaconDB.SaveValidatorIndex(pubKey, int(idx)); err != nil {
 			return fmt.Errorf("could not save validator index: %v", err)
 		}
 	}
+	validators.InsertActivatedIndices(nextEpoch+1, idxNotInState)
```
Comment (nisdas) [inline beacon-chain/blockchain/block_processing.go]: why is this nextEpoch+1 ?

File: beacon-chain/blockchain/block_processing.go [hunk 2]
```diff
@@ -323,13 +323,22 @@ func (c *ChainService) runStateTransition(
 // validators were activated from current epoch. After it saves, current epoch key
 // is deleted from ActivatedValidators mapping.
 func (c *ChainService) saveValidatorIdx(state *pb.BeaconState) error {
-	activatedValidators := validators.ActivatedValFromEpoch(helpers.CurrentEpoch(state) + 1)
+	nextEpoch := helpers.CurrentEpoch(state) + 1
```
Comment (nisdas) [inline beacon-chain/blockchain/block_processing.go]: lets use the `NextEpoch` helper here

File: beacon-chain/blockchain/block_processing.go (hunk 1 above)
Comment (terencechain) [reply beacon-chain/blockchain/block_processing.go]: Because we are processing `nextEpoch` already, if we can't process certain validator indices during `nextEpoch`, we'll save it for the next one which is `nextEpoch + 1`. I'll add a comment for clarity

File: beacon-chain/blockchain/block_processing.go (hunk 2 above)
Comment (terencechain) [reply beacon-chain/blockchain/block_processing.go]: There's no more `NextEpoch` in the 0.6 spec, it needs to be deleted hence I try to avoid using it. Not a big fan of `NextEpoch`, it doesn't add much value, it's just `CurrentEpoch + 1` and we barely use it
