### PR TITLE
Handles issue with empty dirs on validator accounts create

### LINKED ISSUE #5882: command "validator account create" gives error when the key store path directory is empty
# 🐞 Bug Report

### Description

It looks like the `validator account create` command will not create any new accounts if the target directory is empty.

`mkdir empty-keystore-dir`

` ./validator accounts create --keystore-path=./empty-keystore-dir --password=ok`

output:

[2020-05-17 12:39:32] FATAL main: Could not create validator at path: ./keystore error=path "./keystore" does not exist

Expecting:
INFO accounts: Account creation complete!  ....

### Has this worked before in a previous version?

Not tested on any previous version

## 🔥 Error

<code>
[2020-05-17 12:39:32] FATAL main: Could not create validator at path: ./keystore error=path "./keystore" does not exist
</code>

## 🌍  Your Environment

<pre>
  <code>
 x86_64 GNU/Linux 5.4
  go1.14.3
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
The latest pulled from master just the other day
  </code>
</pre>

**Further info**

It looks like the bug is in validator/accounts/account.go:124 in the `Exists` func

```// Exists checks if a validator account at a given keystore path exists.
func Exists(keystorePath string) (bool, error) {
	/* #nosec */
	f, err := os.Open(keystorePath)
	if err != nil {
		return false, nil
	}
	defer func() {
		if err := f.Close(); err != nil {
			log.Fatal(err)
		}
	}()

	_, err = f.Readdirnames(1) // Or f.Readdir(1)
	if err == io.EOF {
		return false, nil
	}
	return true, err
}
```

***Additional comment

It seems like `Exists` function expects at least one file or sub-directory to be present, and it will return an error if the keystore dir is empty even if it exists. 

I could gladly submit a PR with the following proposed fixes:

1. remove the following code from account.go

<code>
        _, err = f.Readdirnames(1) // Or f.Readdir(1)
	if err == io.EOF {
		return false, nil
	}
</code>

2. add a test case

Thanks

Edit: formatting

### PR DESCRIPTION
**Pull request by farazdagi**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**
- Fixes issue when empty directory was causing issues on `validator accounts create`

**Which issues(s) does this PR fix?**

Fixes #5882

**Other notes for review**
N/A

### CODE REVIEW

File: validator/accounts/account.go [hunk 1]
```diff
@@ -118,7 +118,7 @@ func NewValidatorAccount(directory string, password string) error {
 }
 
 // Exists checks if a validator account at a given keystore path exists.
-func Exists(keystorePath string) (bool, error) {
+func Exists(keystorePath string, assertNonEmpty bool) (bool, error) {
```
Comment (terencechain) [inline validator/accounts/account.go:121]: Since `Exists` is exported. Can we please add a comment on what `assertNonEmpty` is?
