### PR TITLE
run e2e for 12 epochs

### LINKED ISSUE #10716: e2e flakiness higher with extra epochs
### Description

In order to demonstrate the fix for the committee cache e2e bug, a change was made to the minimal e2e test to run for additional epochs. This change also seems to have caused increased flakiness in e2e runs.

### Has this worked before in a previous version?

yes prior to https://github.com/prysmaticlabs/prysm/pull/10639 being merged

## 🔥 Error

<pre><code>
--- FAIL: TestEndToEnd_MinimalConfigV/all_nodes_have_samehead%d#01 (0.19s)
  assertions.go:86: endtoend_test.go:379 Evaluation failed for sync node: received conflicting head epochs on node 1, expected 13, received 12
</code></pre>

## 🌍  Your Environment

buildkite ci

**What version of Prysm are you running? (Which release)**

development branch

### PR DESCRIPTION
**Pull request by kasey**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Reverts a change to run for extra epochs in e2e tests.

**Which issues(s) does this PR fix?**

Fixes #10716

### CODE REVIEW

**Review by nisdas — APPROVED** [review]

**Review by prestonvanloon — DISMISSED** [review]

File: testing/endtoend/minimal_e2e_test.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ func e2eMinimal(t *testing.T, useWeb3RemoteSigner bool, extraEpochs uint64) {
 
 	// Run for 12 epochs if not in long-running to confirm long-running has no issues.
 	var err error
-	epochsToRun := 10
+	epochsToRun := 12
```
Comment (nisdas) [inline testing/endtoend/minimal_e2e_test.go:30]:
```suggestion
	epochsToRun := 10
```

File: testing/endtoend/minimal_e2e_test.go [hunk 2]
```diff
@@ -14,7 +14,7 @@ import (
 )
 
 func TestEndToEnd_MinimalConfig(t *testing.T) {
-	e2eMinimal(t, false, 3)
+	e2eMinimal(t, false, 0)
```
Comment (nisdas) [inline testing/endtoend/minimal_e2e_test.go:17]:
```suggestion
	e2eMinimal(t, false, 3)
```

**Review by nisdas — APPROVED** [review]
