### PR TITLE
Use validator protection datadir

### LINKED ISSUE #7331: Cannot initialize validator.db: permission denied
# 🐞 Bug Report

### Description

Hi, I can't upgrade my validators as version `v1.0.0-alpha.25` introduced a breaking change of moving `validator.db` from `data` directory to the `wallet` directory. In the Kubernetes environment where these two directories are separated (one is mounted as `rw` and is PV and another is mounted as `ro` and is Kubernetes secret), there is no way to combine those two under the same path.

Please provide a way to separate `validator.db` and `wallet` directories.

### Has this worked before in a previous version?

Yes, it has stopped working after introducing the following change: https://github.com/prysmaticlabs/prysm/pull/7176

### PR DESCRIPTION
**Pull request by shayzluf**
**What type of PR is this?**

Bug fix

why?
two reasons:
- extra protection layer
missing db file is a slashing protection problem. warn users and allow them to copy the db file if its empty
- allowing users to define their custom protection db location
some users reported they don't have write permissions to wallet dir and need to configure a different location for it

**What does this PR do? Why is it needed?**
- use wallet dir flag as default protection db dir
- if datadir flag is set use it for protection db (we introduced a breaking change)
- if file doesn't exist warn user and ask him to give the path to the latest copy
- Copy existing db from old path to datadir

**Which issues(s) does this PR fix?**

Fixes #7331

### CODE REVIEW

**Review by nisdas — CHANGES_REQUESTED** [review]
lets reuse our old flag, adding a new flag would just be confusing

**Comment by shayzluf** [comment]
@nisdas reused the same flag

File: validator/node/node.go [hunk 1]
```diff
@@ -246,21 +248,23 @@ func (s *ValidatorClient) initializeFromCLI(cliCtx *cli.Context) error {
 }
 
 func moveDb(cliCtx *cli.Context, accountsDir string) string {
-	dataDir := cliCtx.String(cmd.DataDirFlag.Name)
+	dataDir := cmd.DefaultDataDir()
```
Comment (prestonvanloon) [inline validator/node/node.go:251]: Why doesn't this read the flag?

Comment (shayzluf) [reply validator/node/node.go:251]: i think reading the flag is indeed the right thing to do. wanted to check the default location in case there is a db there.
fixing

Comment (shayzluf) [reply validator/node/node.go:251]: @prestonvanloon i am worried about the case were db already moved to accounts dir and now the user resets it to diff location. adding handling for that case as well

**Review by nisdas — COMMENTED** [review]
There are many large conditionals in one line and it is opaque on how they work, is it possible to refactor them into variables and then compare them, that way it is easier to understand.

**Comment by shayzluf** [comment]
@nisdas sure
doing it now

File: validator/node/node.go [hunk 2]
```diff
@@ -249,22 +251,50 @@ func (s *ValidatorClient) initializeFromCLI(cliCtx *cli.Context) error {
...
 			if err != nil {
 				log.Fatal(err)
 			}
+			log.WithFields(logrus.Fields{
+				"oldDbFile": dataFile,
+			}).Info("Deleting validator db in folder")
+			if err := os.Remove(accountsDirDbFile); err != nil {
+				log.Info(errors.Wrap(err, "could not delete old db file"))
+			}
+		} else if dataDirDBExistsAndDifferent && accountsDirDBDoesntExist { //move files to account dir.
```
Comment (nisdas) [inline validator/node/node.go:282]: hmm no, it means the user wants to use a db from that directory. Copying and removing it isnt correct

File: validator/node/node.go [hunk 3]
```diff
@@ -168,7 +168,7 @@ func (s *ValidatorClient) initializeFromCLI(cliCtx *cli.Context) error {
 			if err != nil {
 				return errors.Wrap(err, "could not generate interop keys")
 			}
-			accountsDir = cliCtx.String(flags.KeystorePathFlag.Name)
+			dbDir = cliCtx.String(flags.KeystorePathFlag.Name)
```
Comment (nisdas) [inline validator/node/node.go:171]: this is still the accounts directory. I dont think we should assign this as the db dir, this will confuse any new reader.

Comment (shayzluf) [reply validator/node/node.go:171]: same db dir as here
`dbDir = cliCtx.String(cmd.DataDirFlag.Name)`

**Review by prestonvanloon — CHANGES_REQUESTED** [review]
Please add tests for this new logic

File: validator/node/node.go [hunk 4]
```diff
@@ -242,24 +258,35 @@ func (s *ValidatorClient) initializeFromCLI(cliCtx *cli.Context) error {
...
-			log.WithFields(logrus.Fields{
-				"oldDbPath": dataDir,
-				"walletDir": accountsDir,
-			}).Info("Moving validator protection db to wallet dir")
-			err := fileutil.CopyFile(dataFile, newDataFile)
-			if err != nil {
-				log.Fatal(err)
-			}
+func moveDb(cliCtx *cli.Context, defaultDir *cli.StringFlag) {
+	log.Infof("starting move db: %s", defaultDir.Name)
```
Comment (rauljordan) [inline validator/node/node.go:262]:
```suggestion
	log.Infof("Starting move db: %s", defaultDir.Name)
```

File: validator/node/node.go [hunk 5]
```diff
@@ -242,24 +258,35 @@ func (s *ValidatorClient) initializeFromCLI(cliCtx *cli.Context) error {
...
-		if fileutil.FileExists(dataFile) && !fileutil.FileExists(newDataFile) {
-			log.WithFields(logrus.Fields{
-				"oldDbPath": dataDir,
-				"walletDir": accountsDir,
-			}).Info("Moving validator protection db to wallet dir")
-			err := fileutil.CopyFile(dataFile, newDataFile)
-			if err != nil {
-				log.Fatal(err)
-			}
+func moveDb(cliCtx *cli.Context, defaultDir *cli.StringFlag) {
```
Comment (rauljordan) [inline validator/node/node.go:261]: Not a fan of this function name, it needs to be a lot more descriptive. Perhaps let's call it `moveSlashingProtectionDatabase`

File: validator/node/node_test.go [hunk 6]
```diff
@@ -73,3 +76,80 @@ func TestClearDB(t *testing.T) {
 	require.NoError(t, err)
 	require.LogsContain(t, hook, "Removing database")
 }
+
+func Test_MoveDb(t *testing.T) {
```
Comment (rauljordan) [inline validator/node/node_test.go:80]: Let's also fix the test names if we change the function namme

**Comment by rauljordan** [comment]
PTAL @prestonvanloon and @nisdas

File: validator/node/node.go [hunk 7]
```diff
@@ -242,24 +258,35 @@ func (s *ValidatorClient) initializeFromCLI(cliCtx *cli.Context) error {
...
-			log.WithFields(logrus.Fields{
-				"oldDbPath": dataDir,
-				"walletDir": accountsDir,
-			}).Info("Moving validator protection db to wallet dir")
-			err := fileutil.CopyFile(dataFile, newDataFile)
-			if err != nil {
-				log.Fatal(err)
-			}
+func moveSlashingProtectionDatabase(cliCtx *cli.Context, defaultDir *cli.StringFlag) {
+	log.Infof("starting move db: %s", defaultDir.Name)
```
Comment (nisdas) [inline validator/node/node.go:262]: lets move all the user logging into the scope of the if conditional, so that normal users aren't confused if they haven't used the flag.

**Review by nisdas — COMMENTED** [review]
PR looks good, had some minor cosmetic comments

File: validator/node/node.go (hunk 7 above)
Comment (shayzluf) [reply validator/node/node.go:262]: left out from debugging . thanks

**Review by nisdas — COMMENTED** [review]
Please remove the checked in site data

**Review by nisdas — APPROVED** [review]

**Comment by rauljordan** [comment]
PTAL @prestonvanloon

**Review by prestonvanloon — APPROVED** [review]
