### PR TITLE
Validate Deposit Transactions

### LINKED ISSUE #3985: Key manager should wait for transactions to be mined to confirm success
https://github.com/prysmaticlabs/prysm/blob/81c53c26fb97c179f80c5d77e1719cfd83ac329e/tools/cluster-pk-manager/server/server.go#L71-L75

We noticed some behavior where private keys were allocated with failed deposits yesterday. This should not be allowed to be a successful response.

### PR DESCRIPTION
**Pull request by nisdas**
This validates the deposit transactions before assigning them to a pod. If a transaction failed then it doesn't assign the specific key to a pod and ignores it.

This resolves #3985

### CODE REVIEW

File: tools/cluster-pk-manager/server/server.go [hunk 1]
```diff
@@ -147,16 +152,51 @@ func (s *server) allocateNewKeys(ctx context.Context, podName string, numKeys in
...
 	return &pb.PrivateKeys{PrivateKeys: pks}, nil
 }
+
+func (s *server) checkDepositTxs(ctx context.Context, txMap map[*keystore.Key]*types.Transaction) ([][]byte,
+	error) {
+	pks := make([][]byte, 0, len(txMap))
+	for k, tx := range txMap {
+		receipt, err := s.client.TransactionReceipt(ctx, tx.Hash())
+		if err == ethereum.NotFound {
+			// tx still not processed yet
```
Comment (rauljordan) [inline tools/cluster-pk-manager/server/server.go]:
```suggestion
			// tx still not processed yet.
```

File: tools/cluster-pk-manager/server/server.go [hunk 2]
```diff
@@ -147,16 +152,51 @@ func (s *server) allocateNewKeys(ctx context.Context, podName string, numKeys in
...
+			continue
+		}
+		if err != nil {
+			return nil, err
+		}
+		if receipt.Status == types.ReceiptStatusFailed {
+			delete(txMap, k)
+			continue
+		}
+		// append key if tx succeeded
```
Comment (rauljordan) [inline tools/cluster-pk-manager/server/server.go]:
```suggestion
		// append key if tx succeeded.
```
