### PR TITLE
Use justified hash as safe block hash when passing attribute

### LINKED ISSUE #12195: Incorrect safeBlockHash in fcU with payload attributes
# 🐞 Bug Report

### Description

While testing Prysm with my execution multiplexer ([eleel](https://github.com/michaelsproul/eleel)) I noticed that some of Prysm's forkchoiceUpdated messages were not matching Lighthouse.

I tracked it down to Prysm sometimes setting the `safeBlockHash` to the `finalizedBlockHash` rather than the `justifiedBlockHash`. I noticed that this seems to happen only for fork choice updates that include payload attributes, which at a glance makes sense given the code here:

https://github.com/prysmaticlabs/prysm/blob/f5bfb8e9eb8c00adb7e72396183e4e14d41abb25/beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go#L139-L143

This isn't a critical bug, and I think the impact is minimal. For now I'll work around it in `eleel`.

### Has this worked before in a previous version?

Not sure. I noticed it on v3.2.2 and upgrading to v4.0.0 didn't fix it.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 22.04 x86_64
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v4.0.0
  </code>
</pre>

### PR DESCRIPTION
**Pull request by terencechain**
Fixes #12195

This PR uses the justified hash as safe block hash when calling FCU with payload attribute
This PR also attempts a clean-up to retrieve `FinalizedBlockHash` from `FinalizationFetcher` instead from getting it from the block in DB

### CODE REVIEW

File: beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go [hunk 1]
```diff
@@ -508,6 +508,17 @@ func (f *ForkChoice) JustifiedPayloadBlockHash() [32]byte {
 	return node.payloadHash
 }
 
+// UnrealizedJustifiedPayloadBlockHash returns the hash of the payload at the unrealized justified checkpoint
+func (f *ForkChoice) UnrealizedJustifiedPayloadBlockHash() [32]byte {
```
Comment (potuz) [inline beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go:512]: I think this should return an error rather than 0 root

File: beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go [hunk 2]
```diff
@@ -508,6 +508,17 @@ func (f *ForkChoice) JustifiedPayloadBlockHash() [32]byte {
...
+	root := f.store.unrealizedJustifiedCheckpoint.Root
+	node, ok := f.store.nodeByRoot[root]
+	if !ok || node == nil {
+		// This should not happen
+		return [32]byte{}
+	}
+	return node.payloadHash
```
Comment (potuz) [inline beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go:519]: This is the only function that needs a test

File: beacon-chain/blockchain/chain_info_test.go [hunk 3]
```diff
@@ -119,6 +119,50 @@ func TestCurrentJustifiedCheckpt_CanRetrieve(t *testing.T) {
...
+	require.NoError(t, err)
+
+	jroot := [32]byte{'j'}
+	cp := &forkchoicetypes.Checkpoint{Epoch: 6, Root: jroot}
+	bState, _ := util.DeterministicGenesisState(t, 10)
+	require.NoError(t, beaconDB.SaveState(ctx, bState, jroot))
+
+	require.NoError(t, fcs.UpdateFinalizedCheckpoint(cp))
+	jp := service.FinalizedBlockHash()
+	require.Equal(t, params.BeaconConfig().ZeroHash, jp)
```
Comment (potuz) [inline beacon-chain/blockchain/chain_info_test.go:141]: Why are you setting in this test jroot for justified root if this is not tested at all? I think the easiest thing is to add a check that the justified checkpoint is being picked `require.Equal(t, jroot, fcs.JustifiedCheckpoint().Root)` or even better use `prepareForkChoiceState()` to set up the node with root `jroot` so that it has the right payload hash. Same applies to other tests in this suite.

File: beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go [hunk 4]
```diff
@@ -742,3 +742,21 @@ func TestForkchoice_UpdateJustifiedBalances(t *testing.T) {
...
+	f := setup(0, 0)
+
+	st, blkRoot, err := prepareForkchoiceState(ctx, 0, [32]byte{'a'}, params.BeaconConfig().ZeroHash, [32]byte{'A'}, 1, 1)
+	require.NoError(t, err)
+	require.NoError(t, f.InsertNode(ctx, st, blkRoot))
+
+	f.store.unrealizedJustifiedCheckpoint.Root = [32]byte{'a'}
+	got, err := f.UnrealizedJustifiedPayloadBlockHash()
+	require.NoError(t, err)
+	require.DeepEqual(t, [32]byte{'A'}, got)
```
Comment (potuz) [inline beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go:757]: Question here, isn't `Equal` enough for slices?

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go [hunk 5]
```diff
@@ -115,31 +115,23 @@ func (vs *Server) getExecutionPayload(ctx context.Context, slot primitives.Slot,
...
+			justifiedBlockHash = finalizedBlockHash // Don't fail block proposal if we can't get the justified block hash.
 		}
 	}
 
 	f := &enginev1.ForkchoiceState{
 		HeadBlockHash:      parentHash,
-		SafeBlockHash:      finalizedBlockHash,
-		FinalizedBlockHash: finalizedBlockHash,
+		SafeBlockHash:      finalizedBlockHash[:],
+		FinalizedBlockHash: justifiedBlockHash[:],
```
Comment (potuz) [inline beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go:134]: these are mixed

**Review by potuz — CHANGES_REQUESTED** [review]

File: beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go (hunk 5 above)
Comment (terencechain) [reply beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go:134]: Wow. Nice catch

File: beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go (hunk 4 above)
Comment (terencechain) [reply beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go]: It is. Updated to `Equal`

File: beacon-chain/blockchain/chain_info_test.go (hunk 3 above)
Comment (terencechain) [reply beacon-chain/blockchain/chain_info_test.go:141]: Gotcha. I'll add the check `require.Equal(t, jroot, fcs.JustifiedCheckpoint().Root)`

**Review by potuz — APPROVED** [review]
