### PR TITLE
Fix aggregated attestation pool grows large in size

### LINKED ISSUE #4929: Attestation pool grows to large size
Screenshot from 2020-02-22 18-38-29

Some nodes are reporting as high as 300k+ attestations in the pool. This is causing instability issues in the testnet over the last few days.

### PR DESCRIPTION
**Pull request by terencechain**
This fixes #4929 

Please review and merge #4930 first

Attestation pool were growing large in size because we **reset** an item's expiration time upon new update. Say a new attestation with `dataA` and bits 0x01 comes in, the expires time of the attestation is set to `time.Now + N`. 

One slot later another attestation with `dataA` but different bits came in. Here we should not touch the expire time, but instead the node reset the expire time to `time.Now + N` **again**. That's why some attestations would never expire because we keep on **re aggregating** itself here:
https://github.com/prysmaticlabs/prysm/compare/fix-exp-time?expand=1#diff-45a8f7c8f90ae232acabd3f59fdea76cL27

Change list:
* Update attestation with correct expire time
* Delete attestation with correct expire time
* Don't aggregate itself since aggregated attestation is already in an aggregated form
* Update aggregation from 3 times per slot to 2 times per slot. 3 was too much with a lot of wasted computations
* Tests

Live testing update:
[2020-02-23 14:05:36 PST]: Ran it for 10+ epochs, the attestations pool count is steadily below 500 versus 2000.. before

### CODE REVIEW

**Comment by terencechain** [comment]
Don't merge yet, I'm testing proposer is passing

File: beacon-chain/operations/attestations/aggregate.go [hunk 1]
```diff
@@ -24,8 +24,7 @@ func (s *Service) aggregateRoutine() {
 		case <-s.ctx.Done():
 			return
 		case <-ticker.C:
-			attsToBeAggregated := append(s.pool.UnaggregatedAttestations(), s.pool.AggregatedAttestations()...)
-			if err := s.aggregateAttestations(ctx, attsToBeAggregated); err != nil {
+			if err := s.aggregateAttestations(ctx, s.pool.UnaggregatedAttestations()); err != nil {
```
Comment (prestonvanloon) [inline beacon-chain/operations/attestations/aggregate.go]: Why wouldn't we use the aggregated ones too?

Comment (terencechain) [reply beacon-chain/operations/attestations/aggregate.go]: Agree that's a problem. Reverted
