### PR TITLE
Fix test setup and change participation min back to 100% 

### LINKED ISSUE #5572: E2E flakes with subpar participation
This issue is tracking issue to ensure we look into the root cause of E2E flaking failures.

The test that fails is participation, with it usually being between 87.5% and 95% when it fails.

### PR DESCRIPTION
**Pull request by 0xKiwi**
This PR is me trying to improve consistency for E2E testing, by making sure the setup conditions are consistent and reporting accurately. 
Also changes the min participation back to what it should be, since reducing it was making test failures less likely. Certain metrics have also been modified as previous values were too low for 64 validators. 

Reduces node count to 2 as 4 beacon nodes might be too many for 64 validators.

Fixes #5572

### CODE REVIEW

File: endtoend/evaluators/metrics.go [hunk 1]
```diff
@@ -58,13 +58,13 @@ var metricComparisonTests = []comparisonTest{
 		name:               "committee index 0 beacon attestation",
 		topic1:             "p2p_message_failed_validation_total{topic=\"/eth2/%x/committee_index0_beacon_attestation/ssz_snappy\"}",
 		topic2:             "p2p_message_received_total{topic=\"/eth2/%x/committee_index0_beacon_attestation/ssz_snappy\"}",
-		expectedComparison: 0.1,
```
Comment (terencechain) [inline endtoend/evaluators/metrics.go:61]: this was not mentioned in the description, what's the reason for loosening this requirement?

Comment (0xKiwi) [reply endtoend/evaluators/metrics.go:61]: > this was not mentioned in the description, what's the reason for loosening this requirement?

I feel as if it's currently at the boundary, sometimes it flakes with 0.11 > 0.10, so I've increased it to allow for a bit more room. Low validator count might mean this ratio is a bit off of what it should be.

Comment (terencechain) [reply endtoend/evaluators/metrics.go:61]: Sounds good. Let's put that in the description then it's good to go
