### PR TITLE
Fix Metadata Sequence Checks

### LINKED ISSUE #6665: Req/Respone: Ping/Metadata - Verify that metadata.seq_nr is strictly increasing
# 🐞 Bug Report

### Description

Hey guys, just stumbled upon this and wanted to make sure you are aware of it. 
Prism does not seem to enforce that the sequence_nr is strictly increasing when updating the metadata of a node.

[Spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/phase0/p2p-interface.md#metadata)
> seq_number is a uint64 starting at 0 used to version the node's metadata. If any other field in the local MetaData changes, the node MUST increment seq_number by 1.

The spec states that nodes must increment the sequence nr. If for whatever reason a seq_nr is seen to decrement this should raise an alarm.

https://github.com/prysmaticlabs/prysm/blob/c2615168d9af98c6c1a348b943b43dc158d57fbf/beacon-chain/sync/rpc_ping.go#L55-L72

https://github.com/prysmaticlabs/prysm/blob/c2615168d9af98c6c1a348b943b43dc158d57fbf/beacon-chain/sync/rpc_ping.go#L115-L123

validation:
https://github.com/prysmaticlabs/prysm/blob/c2615168d9af98c6c1a348b943b43dc158d57fbf/beacon-chain/sync/rpc_ping.go#L126-L139

- ping response: check ping sequence nr > cached sequence nr
- get metadata: check ping sequence nr > cached sequence nr 
- discuss whether this should be a reason to decrement the score of a node

## 🔬 Minimal Reproduction

* hint a seq_nr that is lower than the one cached for the peer
* code validates that `ping_sequence_nr != cached_sequence_nr` 
* metadata is updated w/o checking if seqnr is strictly increasing (or the one provided in the getMetadata call is actually > the one that is cached).

cheers,

tin / consensys diligence

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

- [x] Descore a peer for giving us an invalid sequence number, if we already do have a higher sequence number cached.
- [x] Add a regression test to make sure peer is penalised for providing bad data.
- [x] Adds a `NotEqual` test method for our assertions library.

**Which issues(s) does this PR fix?**

Resolves #6665 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/sync/rpc_test.go [hunk 1]
```diff
@@ -7,6 +7,8 @@ import (
 	"testing"
 	"time"
 
+	"github.com/prysmaticlabs/prysm/shared/testutil/require"
+
```
Comment (nisdas) [inline beacon-chain/sync/rpc_test.go:11]:
```suggestion
```

**Comment by prestonvanloon** [comment]
Tests fail
```
=== RUN   TestPingRPCHandler_ReceivesPing
    TestPingRPCHandler_ReceivesPing: assertions.go:51: rpc_ping_test.go:65 Unexpected error: invalid sequence number provided
    TestPingRPCHandler_ReceivesPing: assertions.go:24: rpc_test.go:29 Received non-zero response code, want: 0 (uint8), got: 1 (uint8)
--- FAIL: TestPingRPCHandler_ReceivesPing (0.01s)
```

**Comment by nisdas** [comment]
> LGTM. Are the testutil changes part of this PR?

Yeap they are included in the PR
