### PR TITLE
Benchmark and Optimize ListValidatorBalances

### LINKED ISSUE #4531: RPC Tests Broken on Master
Running `bazel test //beacon-chain/rpc/beacon:go_default_test` on master passes, but running:
```
bazel test //beacon-chain/rpc/beacon:go_default_test --test_output=streamed
```
shows a panicking test of the form:

```
--- FAIL: TestServer_ListAssignments_Pagination_DefaultPageSize_NoArchive (14.87s)
panic: runtime error: slice bounds out of range [:250] with capacity 0 [recovered]
        panic: runtime error: slice bounds out of range [:250] with capacity 0
```
This is blocking development of new features / optimizations in that package.

### PR DESCRIPTION
**Pull request by rauljordan**
Resolves #4531

---

# Description

**Write why you are making the changes in this pull request**

Currently, fetching validator balances via the `ListValidatorBalances` call takes more than 1 minute to complete! After looking into it, it turns out that while we do have pagination, it does the work to compute all 30k validator balances in the state and _then_ filters/paginates that list. Instead, we should be only performing as much work as the `PageSize` in the request, up to `MaxPageSize`.

Additionally, we were using `ssz.Marshal` for marshaling validator balances into the archive, which ended up being super slow. Instead, we can have a simple, custom marshaling method for that type and get almost a 10x improvement.

**Link anything that would be helpful or relevant to the reviewers**

Old implementation
```
BenchmarkListValidatorBalances-4                   18540             62207 ns/op           96474 B/op       1012 allocs/op
BenchmarkListValidatorBalances_FromArchive-4       62989             28187 ns/op           17936 B/op        170 allocs/op
```

New implementation only doing as much computational work as the MAX_PAGE_SIZE possible on each request:
```
BenchmarkListValidatorBalances-4                   96092             10719 ns/op           10136 B/op        109 allocs/op
BenchmarkListValidatorBalances_FromArchive-4      133644              8016 ns/op            6168 B/op         70 allocs/op
```
This PR also clears caching in a broken RPC test that was not manifesting due to test sharding, thereby resolving #4531

### CODE REVIEW

File: beacon-chain/db/kv/prune_states.go [hunk 1]
```diff
@@ -26,8 +25,8 @@ func (k *Store) pruneStates(ctx context.Context) error {
 		return nil
 	}
 
-	log := logrus.WithField("prefix", "kv")
-	log.Info("Pruning states before last finalized check point. This might take a while...")
+	//log := logrus.WithField("prefix", "kv")
```
Comment (nisdas) [inline beacon-chain/db/kv/prune_states.go]: revert this, the same below

File: beacon-chain/rpc/beacon/validators.go [hunk 2]
```diff
@@ -8,13 +8,14 @@ import (
 
 	ptypes "github.com/gogo/protobuf/types"
 	ethpb "github.com/prysmaticlabs/ethereumapis/eth/v1alpha1"
+	"google.golang.org/grpc/codes"
+	"google.golang.org/grpc/status"
+
```
Comment (rauljordan) [inline beacon-chain/rpc/beacon/validators.go]:
```suggestion
```
