### PR TITLE
Future slot check for state end point

### LINKED ISSUE #5753: Endpoint /eth/v1alpha1/beacon/state does not address future slot request
# 🐞 Bug Report

### Description

The debug end point `/eth/v1alpha1/beacon/state` does not account for fault case where request slot exceeds current slot:
`
{"error":"could not compute state by slot: could not process slot: unknown state","code":13,"message":"could not compute state by slot: could not process slot: unknown state","details":[]}
`

### PR DESCRIPTION
**Pull request by terencechain**
This fixes #5753

Returns proper error if user requests `future` slot

### CODE REVIEW

File: beacon-chain/rpc/beacon/state.go [hunk 1]
```diff
@@ -20,8 +20,20 @@ func (bs *Server) GetBeaconState(
...
 	}
+
 	switch q := req.QueryFilter.(type) {
 	case *pbrpc.BeaconStateRequest_Slot:
+		currentSlot := bs.GenesisTimeFetcher.CurrentSlot()
+		requestedSlot := q.Slot
+		if requestedSlot > currentSlot {
+			return nil, status.Errorf(
+				codes.InvalidArgument,
+				"Cannot retrieve information about an slot in the future, current slot %d, slot %d",
```
Comment (0xKiwi) [inline beacon-chain/rpc/beacon/state.go:31]:
```suggestion
				"Cannot retrieve information about a slot in the future, current slot %d, requested slot %d",
```

File: beacon-chain/rpc/beacon/state_test.go [hunk 2]
```diff
@@ -76,3 +79,19 @@ func TestServer_GetBeaconState(t *testing.T) {
...
+	resetCfg := featureconfig.InitWithReset(&featureconfig.Flags{NewStateMgmt: true})
+	defer resetCfg()
+
+	bs := &Server{GenesisTimeFetcher: &mock.ChainService{}}
+	req := &pbrpc.BeaconStateRequest{
+		QueryFilter: &pbrpc.BeaconStateRequest_Slot{
+			Slot: bs.GenesisTimeFetcher.CurrentSlot() + 1,
+		},
+	}
+	wanted := "Cannot retrieve information about an slot in the future"
```
Comment (0xKiwi) [inline beacon-chain/rpc/beacon/state_test.go:93]:
```suggestion
	wanted := "Cannot retrieve information about a slot in the future"
```
