### PR TITLE
Listen to all Network Interfaces for discovery

### LINKED ISSUE #7220: Dynamic IP address: Peers drop without recovery after IP-reset
# 🐞 Bug Report

### Description
My ISP resets my IP every day (it only provides dynamic IP V4 addresses). Im running my beacon with --p2p-host-dns=xxx
The host-dns instantly resolves to the new ip.

However after this ip-change, my peers drop to only a few (<5) and the beacon does not recover from the change anymore back to the expected max-peer value (=30).

What is somewhat strange that the peer drop does not happen every day, although the ip address changes every day. On Sept 6,7 and 9 the reset did not cause a drop in peers.
The only way to recover is to restart the beacon.
Below is a Grafana picture from the last 7 days. On most days I have to restart.
Today I have not restarted yet. Therefore current peer count is still 3.
So last 3 days it happened every day.

Having only very few peers left after the IP-reset obviously has a very bad impact on the validator performance of the validators using this beacon.

### Has this worked before in a previous version?
I have no exact information, but I think it was ok in the past (before discV5), so before medalla.

## 🔬 Minimal Reproduction
Run beacon with parameter `--p2p-host-dns` and change/reset the IP address the beacon is using, more commonly called having a "dynamic IP"

## 🔥 Error
Peer drops to only a few

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Docker
  </code>
</pre>

**What version of Prysm are you running? (Which release)**
latest. release 24
<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**
For reference, my **eth1 geth** node (which is using the same ip) handles the IP reset without issue. It drops its peers, but after that its discovery gets it back to where it was. Im expecting the same behaviour from my beacon.

Detailed trace logs regarding this issue already have been sent to @nisdas

### LINKED ISSUE #7383: Beacon does not reacquire peers after network disruption
# 🐞 Bug Report

### Description

- Prysm 1.0.0-alpha.27
- Ubuntu 20.04
- Dockerized
- Behind many-to-one NAT
- Beacon ports forwarded on firewall

After network connectivity was lost and restored, Prysm did not reacquire peers. Log excerpt

```
beacon_1            | time="2020-09-29 23:13:12" level=info msg="Connected to eth1 proof-of-work chain" endpoint="https://goerli.infura.io/v3/USERID" prefix=powchain
beacon_1            | time="2020-09-29 23:13:28" level=info msg="Peer disconnected" activePeers=3 multiAddr="/ip4/159.89.195.24/tcp/9000/p2p/16Uiu2HAkzxm5LRR4agVpFCqfVkuLE6BvGaHbyzZYgY7jsX1WRTiC" prefix=p2p
beacon_1            | time="2020-09-29 23:13:59" level=info msg="Peer disconnected" activePeers=2 multiAddr="/ip4/37.187.150.105/tcp/9000/p2p/16Uiu2HAm298dJNNVgKwF4PmGFnibaURGJedX2GnjSaCXJ2pMxKgE" prefix=p2p
beacon_1            | time="2020-09-29 23:14:11" level=info msg="Peer disconnected" activePeers=1 multiAddr="/ip4/87.123.98.49/tcp/9000/p2p/16Uiu2HAmK6MuJEG8naYrFeCctwv5g3mdG5PhkM3ACP2JYUGJmKoi" prefix=p2p
beacon_1            | time="2020-09-29 23:15:11" level=info msg="Peer disconnected" activePeers=0 multiAddr="/ip4/51.15.70.7/tcp/9500/p2p/16Uiu2HAmTxXKUd1DFdsudodJostmWRpDVj77e48JKCxUdGm1RLaA" prefix=p2p
beacon_1            | time="2020-09-30 00:04:08" level=info msg="Connected to eth1 proof-of-work chain" endpoint="https://goerli.infura.io/v3/USERID" prefix=powchain
beacon_1            | time="2020-09-30 08:06:06" level=info msg="Connected to eth1 proof-of-work chain" endpoint="https://goerli.infura.io/v3/USERID" prefix=powchain
```

Expected behavior: Prysm beacon will reacquire peers, even when it lost all of them, without a restart of the beacon.

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Feature Improvement

**What does this PR do? Why is it needed?**

This PR defaults to listening to all network interfaces for discovery. Previously we would only bind to a single 
interface however that caused issues with virtual networks where that was less straightforward. So a solution 
there was to instead determine which network interface a node would bind to when sending out an outbound
packet using UDP as the transport.  This however lead to issues with nodes running with dynamic IPs, as 
on each IP reset the network interface to bind to would also have changed. This PR instead simply 
binds to all interfaces so as to solve issues with network disconnections/resets. 

**Which issues(s) does this PR fix?**

Fixes #7383 , Resolves #7220 

**Other notes for review**

### CODE REVIEW

**Review by farazdagi — APPROVED** [review]

**Review by farazdagi — APPROVED** [review]

**Review by farazdagi — DISMISSED** [review]

**Review by prestonvanloon — APPROVED** [review]

**Comment by prestonvanloon** [comment]
I think this is failing e2e tests.

File: beacon-chain/p2p/discovery.go [hunk 1]
```diff
@@ -98,25 +97,31 @@ func (s *Service) createListener(
 	ipAddr net.IP,
 	privKey *ecdsa.PrivateKey,
 ) (*discover.UDPv5, error) {
-	// assume ip is either ipv4 or ipv6
+	// Listen to all network interfaces
+	// for both ip protocols.
 	networkVersion := ""
```
Comment (farazdagi) [inline beacon-chain/p2p/discovery.go:102]:
```suggestion
	var networkVersion string
```
Just for consistency with `createListener()` code + it kind of manifests that value will be set somewhere down the road (with assignment it is more like empty string "" is a valid value).

**Review by farazdagi — APPROVED** [review]
Hopefully it will pass the e2e tests!
