### PR TITLE
Increase regen historical state cache size

### LINKED ISSUE #5611: Could not generate historical state, pre state can't be nil
# 🐞 Bug Report

### Description
Reported by Peter from Bitfly:
```
time="2020-04-24 15:30:08" level=error msg="could not regenerate historical states, please retry: pre state can't be nil" prefix=main
```

### PR DESCRIPTION
**Pull request by terencechain**
This PR fixes #5611.  It has no impact to beacon node run time, it only impacts the duration when beacon node is generating and saving historical states. It's 8 mins given current chain length

Change list:
 * Increased cache size from 64 to 80 with rationale
 * Garbage collect at the end of `regenHistoricalStates`

### CODE REVIEW

File: beacon-chain/db/kv/regen_historical_states.go [hunk 1]
```diff
@@ -125,6 +129,9 @@ func (kv *Store) regenHistoricalStates(ctx context.Context) error {
 	// Flush the cache, the cached states never be used again.
 	cacheState.Purge()
 
+	// Manually garbage collect as previous cache will never be used again..
```
Comment (terencechain) [inline beacon-chain/db/kv/regen_historical_states.go:132]:
```suggestion
	// Manually garbage collect as previous cache will never be used again.
```

File: beacon-chain/db/kv/regen_historical_states.go [hunk 2]
```diff
@@ -56,7 +57,10 @@ func (kv *Store) regenHistoricalStates(ctx context.Context) error {
 	if err != nil {
 		return err
 	}
-	cacheState, err := lru.New(int(params.BeaconConfig().SlotsPerEpoch) * 2)
+	// Using max possible size to avoid using DB to save and retrieve pre state (slow)
+	// The size is 80 because block at slot 43772 built on top of block at slot 43693.
+	// That is the worst case.
+	cacheState, err := lru.New(80)
```
Comment (0xKiwi) [inline beacon-chain/db/kv/regen_historical_states.go:63]: Should this be a global constant? Just so its not hardcoded into a parameter.

Comment (terencechain) [reply beacon-chain/db/kv/regen_historical_states.go:63]: Yep! Done
