### PR TITLE
Do not fail production when consensus block value is unavailable

### LINKED ISSUE #13910: Could not get sync aggregate rewards
### Describe the bug

in mev scence. my vc call getHeader request to prysm failed. it return "Could not get sync aggregate rewards" and the httpcode is 500.

{
	"message": "Could not get sync aggregate rewards: could not verify sync committee signature: invalid sync committee signature",
	"code": 500
}

I don't know why that is. Can someone explain this to me?

### Has this worked before in a previous version?

```text
ok
```

### 🔬 Minimal Reproduction

_No response_

### Error

```text
the prysm logs:

time="2024-04-22 21:05:49" level=info msg="Finished applying state transition" attestations=128 deposits=16 kzgCommitmentCount=6 payloadHash=0x49ac12dc54f2 prefix=blockchain slot=8913927 syncBitsCount=502 txCount=48
time="2024-04-22 21:05:49" level=info msg="Synced new block" block=0x2376c22a... epoch=278560 finalizedEpoch=278558 finalizedRoot=0x3f222d39... prefix=blockchain slot=8913927
time="2024-04-22 21:05:37" level=info msg="Finished applying state transition" attestations=128 deposits=16 kzgCommitmentCount=2 payloadHash=0x2d587397aeaf prefix=blockchain slot=8913926 syncBitsCount=365 txCount=135
time="2024-04-22 21:05:37" level=info msg="Synced new block" block=0xd36f7a10... epoch=278560 finalizedEpoch=278558 finalizedRoot=0x3f222d39... prefix=blockchain slot=8913926
time="2024-04-22 21:05:30" level=info msg="Peer summary" activePeers=9 inbound=3 outbound=6 prefix=p2p
time="2024-04-22 21:05:25" level=info msg="Finished applying state transition" attestations=128 deposits=16 kzgCommitmentCount=6 payloadHash=0xda8d0654c2c3 prefix=blockchain slot=8913925 syncBitsCount=507 txCount=276
time="2024-04-22 21:05:25" level=info msg="Synced new block" block=0xe6e26595... epoch=278560 finalizedEpoch=278558 finalizedRoot=0x3f222d39... prefix=blockchain slot=8913925
time="2024-04-22 21:05:21" level=info msg="Attempted late block reorg aborted due to attestations at 10 seconds" prefix=blockchain root=0xc1663a7dca530c3d0c5c1cabdade381057dd7d5b00efaa23277e9500b93ac5b8 weight=989499000000000
time="2024-04-22 21:05:13" level=info msg="Finished building block" prefix="rpc/validator" sinceSlotStartTime=2.012987948s slot=8913924 validator=1331977
time="2024-04-22 21:05:12" level=info msg="Finished building block" prefix="rpc/validator" sinceSlotStartTime=1.911513981s slot=8913924 validator=1331977
time="2024-04-22 21:05:12" level=info msg="Received header with bid" blockHash=0x2692bcea8235e96230ca79b53fe24b0a84cb526c4b84cb6494751328a5d3923a builderPubKey=0xb0b07cd0abef743db4260b0ed50619cf6ad4d82064cb4fbec9d3ec530f7c5e6793d9f286c4e082c0244ffb9f2658fe88 gweiValue=20000000 kzgCommitmentCount=6 prefix="rpc/validator" sinceSlotStartTime=1.809671128s slot=8913924 validator=1331977
time="2024-04-22 21:05:12" level=info msg="Received header with bid" blockHash=0x2692bcea8235e96230ca79b53fe24b0a84cb526c4b84cb6494751328a5d3923a builderPubKey=0xb0b07cd0abef743db4260b0ed50619cf6ad4d82064cb4fbec9d3ec530f7c5e6793d9f286c4e082c0244ffb9f2658fe88 gweiValue=20000000 kzgCommitmentCount=6 prefix="rpc/validator" sinceSlotStartTime=1.77134669s slot=8913924 validator=1331977
time="2024-04-22 21:05:11" level=info msg="Begin building block" prefix="rpc/validator" sinceSlotStartTime=715.442665ms slot=8913924
time="2024-04-22 21:05:11" level=info msg="Begin building block" prefix="rpc/validator" sinceSlotStartTime=653.504794ms slot=8913924
time="2024-04-22 21:05:03" level=info msg="Finished applying state transition" attestations=128 deposits=16 kzgCommitmentCount=6 payloadHash=0x5606a17ff159 prefix=blockchain slot=8913923 syncBitsCount=505 txCount=111
time="2024-04-22 21:05:03" level=info msg="Synced new block" block=0xc1663a7d... epoch=278560 finalizedEpoch=278558 finalizedRoot=0x3f222d39... prefix=blockchain slot=8913923
time="2024-04-22 21:05:03" level=info msg="Forkchoice updated with payload attributes for proposal" blockRoot=0xa2de56b57a11 headSlot=8913922 payloadID=0x03d012c3a21e prefix=blockchain
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v5.0.2

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

We sometimes see sync committee signature verification failures when trying to get sync committee rewards for a given block. The reason for this bug is still unknown, but failing block production because of such a non-critical thing is too radical.

**Which issues(s) does this PR fix?**

Fixes #13910

**Other notes for review**

I modified the comment for Phase 0 to explain why we ignore it.

### CODE REVIEW

File: beacon-chain/rpc/eth/validator/handlers_block.go [hunk 1]
```diff
@@ -297,8 +297,8 @@ func getConsensusBlockValue(ctx context.Context, blockRewardsFetcher rewards.Blo
 		}
 	}
 	if bb.Version() == version.Phase0 {
-		// ignore for phase 0
-		return "", nil
+		// Getting the block value for Phase 0 is very hard, so we ignore it
```
Comment (james-prysm) [inline beacon-chain/rpc/eth/validator/handlers_block.go:300]: should we at least add a debug log or something

**Review by james-prysm — APPROVED** [review]

**Review by saolyn — APPROVED** [review]
