### PR TITLE
bugfix: submitPoolSyncCommitteeSignatures response inconsistent

### LINKED ISSUE #15424: Inconsistent response of beacon-api endpoint `submitPoolSyncCommitteeSignatures`
### Describe the bug

Hello developers,

I am conducting API testing on an Electra PoS devnet chain and noticed inconsistencies in the Beacon-API responses across Prysm, Lighthouse, Nimbus, Lodestar and Grandine. 

Specifically, prysm and nimbus return the `200` while other CL clients return `400` when calling `/eth/v1/beacon/pool/sync_committees` with invalid signatures. However, the [beacon-api](https://ethereum.github.io/beacon-APIs/#/Beacon/submitPoolSyncCommitteeSignatures) defines that

> If one or more sync committee signatures fail validation the node MUST return a 400 error with details of which sync committee signatures have failed, and why.

Results:

```
# prysm
{"code": 200}
# lighthouse
{"code": 400, "message": "BAD_REQUEST: body deserialize error: Error(\"BlstError(BLST_BAD_ENCODING)\", line: 1, column: 343)", "stacktraces": []}
# teku
{"code": 400, "failures": [{"index": "0", "message": "Rejecting sync committee message because the signature is invalid"}, {"index": "1", "message": "Rejecting sync committee message because the signature is invalid"}], "message": "Some items failed to publish, refer to errors for details"}
# nimbus
{"code": 200, "message": "Sync committee message(s) was broadcast"}
# lodestar
{"code": 400, "failures": [{"index": 0, "message": "SYNC_COMMITTEE_INVALID_SIGNATURE"}, {"index": 1, "message": "SYNC_COMMITTEE_INVALID_SIGNATURE"}], "message": "Error processing sync committee signatures"}
# grandine
{"code": 400, "failures": [{"index": 0, "message": "invalid signature"}, {"index": 0, "message": "invalid signature"}, {"index": 0, "message": "invalid signature"}, {"index": 0, "message": "invalid signature"}, {"index": 1, "message": "invalid signature"}, {"index": 1, "message": "invalid signature"}, {"index": 1, "message": "invalid signature"}, {"index": 1, "message": "invalid signature"}], "message": "invalid sync committee messages"}
```

Thanks!

### Has this worked before in a previous version?

```text
N/A
```

### 🔬 Minimal Reproduction

For prysm
```
curl -i -X POST http://127.0.0.1:10783/eth/v1/beacon/pool/sync_committees \
  -H "Content-Type: application/json" \
  -d '[
    {
      "slot": "1121",
      "beacon_block_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
      "validator_index": "1",
      "signature": "0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505"
    },
    {
      "slot": "1121",
      "beacon_block_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
      "validator_index": "2",
      "signature": "0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505"
    }
  ]' 
```
The status code is `200`

```
HTTP/1.1 200 OK
```
For nimbus,
```
curl -X POST http://127.0.0.1:10826/eth/v1/beacon/pool/sync_committees \
  -H "Content-Type: application/json" \
  -d '[
    {
      "slot": "1121",
      "beacon_block_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
      "validator_index": "1",
      "signature": "0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505"
    },
    {
      "slot": "1121",
      "beacon_block_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
      "validator_index": "2",
      "signature": "0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505"
    }
  ]' \
| jq
```
nimbus return 
```
{
  "code": 200,
  "message": "Sync committee message(s) was broadcast"
}
```

### Error

```text

```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

Prysm/v6.0.4 (linux amd64)

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by Muzry**
**What type of PR is this?**
 Bug fix

**What does this PR do? Why is it needed?**

fix: align submitPoolSyncCommitteeSignatures response with Beacon API specification

**Which issues(s) does this PR fix?**

Fixes #15424

**Other notes for review**
- This is my first PR for the Prysm, so I may be using some wrong functions.
- I referred to other CL repos, and I used the `bls.SignatureFromBytes(sig)` function to verify the signature is valid after `bytesutil.DecodeHexWithLength(m.Signature, fieldparams.BLSSignatureLength)`
- Then if the signature is invalid, response 400 status code and error

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

**Comment by james-prysm** [comment]
@Muzry thanks please add a [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd)

did you test this change? there is an issue


nogo: missing strict dependencies:
--
  | api/server/structs/conversions.go: import of "github.com/OffchainLabs/prysm/v6/crypto/bls"

**Comment by Muzry** [comment]
> @Muzry thanks please add a [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd)
> 
> did you test this change? there is an issue
> 
> ## nogo: missing strict dependencies:
>   | api/server/structs/conversions.go: import of "github.com/OffchainLabs/prysm/v6/crypto/bls"

@james-prysm Thanks for your reply. I apologize for only testing with unit tests so far, and not yet testing using Bazel. I will follow the Contribution Guidelines to fix the issue.

**Comment by james-prysm** [comment]
unit tests seem to be failing TestSubmitSyncCommitteeSignatures

**Comment by Muzry** [comment]
The issue has been fixed; It seems the original unit test case was using incorrect data. I’m still new to Prysm and the Consensus Layer, so please let me know if I misunderstood anything.

File: api/server/structs/conversions.go [hunk 1]
```diff
@@ -699,6 +700,11 @@ func (m *SyncCommitteeMessage) ToConsensus() (*eth.SyncCommitteeMessage, error)
 	if err != nil {
 		return nil, server.NewDecodeError(err, "Signature")
 	}
+	// Add validation to check if the signature is valid BLS format
+	_, err = bls.SignatureFromBytes(sig)
+	if err != nil {
+		return nil, server.NewDecodeError(errors.New("Invalid Signature"), "Signature")
```
Comment (rkapka) [inline api/server/structs/conversions.go]:
```suggestion
		return nil, server.NewDecodeError(err, "Signature")
```
The second parameter is used to add the field name to the final error message, no need to add it for the second time

File: beacon-chain/rpc/eth/beacon/handlers_pool_test.go [hunk 2]
```diff
@@ -2523,6 +2523,18 @@ var (
...
+	"slot": "1121",
+	"beacon_block_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
+	"validator_index": "1",
+	"signature": "0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505"
+  },
+  {
+	"slot": "1121",
+	"beacon_block_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
+	"validator_index": "2",
+	"signature": "0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505"
```
Comment (rkapka) [inline beacon-chain/rpc/eth/beacon/handlers_pool_test.go:2537]: why add these?

Comment (Muzry) [reply beacon-chain/rpc/eth/beacon/handlers_pool_test.go:2537]: The test cases from Issue #15424 revealed a mismatch that was not covered by the current unit tests. I added them  to the unit tests

File: api/server/structs/conversions.go (hunk 1 above)
Comment (Muzry) [reply api/server/structs/conversions.go]: I updated the format

**Review by james-prysm — APPROVED** [review]
thanks for this, waiting for radek too

**Review by rkapka — APPROVED** [review]
