### PR TITLE
Make DB Backup More Efficient

### LINKED ISSUE #8486: Database Backups Leads To High Memory Usage
# 🐞 Bug Report

### Description

Database backups in the beacon node, lead to a very large increase in memory usage. This eventually kills the node
and host machine due to Bolt iterating through all the buckets and keys and trying to copy them.

### Has this worked before in a previous version?

Yes

## 🔬 Minimal Reproduction

Backup a live beacon node in mainnet.

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

- [x] Allows a beacon node to take a live backup without killing the main node. 
- [x] Breaks up the backup process to multiple writes for each key in a bucket, allowing a node
to have a lower memory footprint at the cost of making backups longer. This prevents long running read
transactions which Bolt doesn't handle well.

**Which issues(s) does this PR fix?**

Resolves #8486 partially

**Other notes for review**

### CODE REVIEW

File: beacon-chain/db/kv/backup_test.go [hunk 1]
```diff
@@ -7,6 +7,8 @@ import (
 	"path/filepath"
 	"testing"
 
+	types "github.com/prysmaticlabs/eth2-types"
+
```
Comment (rauljordan) [inline beacon-chain/db/kv/backup_test.go:11]:
```suggestion
```

**Review by rauljordan — APPROVED** [review]
