### PR TITLE
Fixes: Accounts-V2: listing accounts produces incorrect output

### LINKED ISSUE #6976: Accounts-V2: listing accounts produces incorrect output mixing up "validating public key" entries
# 🐞 Bug Report

### Description

When listing V2 validator accounts, the output is incorrect, the "validating public key" entries are mixed up, showing as belonging to different accounts than they really do.

An example can be seen in ##6918, copied below:

<pre>
  <code>
Account 0 | constantly-popular-wasp
[validating public key] 0xb692725fe769d79863eefe4752fac00f878072b8c898a8fbfca32189692ceb0bdb77212d82d9ee8a199b48a60461263b

Account 1 | cheaply-summary-gull
[validating public key] 0x8329d8e9aa7da5f6b8300a22e55fd5657d6fa42d30408c83218da10136db06936e1bd7025574718e4283a1adf6c1ab71

Account 2 | carefully-wondrous-terrapin
[validating public key] 0x99cc6a756b0492b2790903a175351d1e153b513e1cfb95db7a56a33cd811c5f7c859d94cea46b67b8e7e6481f09eb5f5

Account 3 | repeatedly-prime-stinkbug
[validating public key] 0xa9e8ab052e4e80670ecf54a3bec7f43a08a1b146063221348a5c735e42ef16db1c0c9685f29192502526f91272b80a96
  </code>
</pre>

<pre>
  <code>
Account 0 | constantly-popular-wasp
[withdrawal public key] 0xa387211380b13ab47d59a00f3eaa7a6edffd1f1b9745231aa607eb7480c42e403dba11d00a8e4f5d7c80627677c3c050
[derivation path] m/12381/3600/0/0
[validating public key] 0xa9e8ab052e4e80670ecf54a3bec7f43a08a1b146063221348a5c735e42ef16db1c0c9685f29192502526f91272b80a96
[derivation path] m/12381/3600/0/0/0

Account 1 | cheaply-summary-gull
[withdrawal public key] 0xb8ac604b685fd322c21ce1e2f263934c7e272cb6d3e60052430d6975d2666c2f142ba042213101c48c333df95a40abf4
[derivation path] m/12381/3600/1/0
[validating public key] 0x9958265fbd2577270ad8fda3745bd804ff77fb50fe02b781f203cd571204178e60686f4052803f7ceb5334ac197c2dd8
[derivation path] m/12381/3600/1/0/0

Account 2 | carefully-wondrous-terrapin
[withdrawal public key] 0xaf0f953920a8203b1d0a96f59e1cbfb80961086f10931c2ddaa8250d4d952dc38482847da15816842de56417f8273ab5
[derivation path] m/12381/3600/2/0
[validating public key] 0xb692725fe769d79863eefe4752fac00f878072b8c898a8fbfca32189692ceb0bdb77212d82d9ee8a199b48a60461263b
[derivation path] m/12381/3600/2/0/0

Account 3 | repeatedly-prime-stinkbug
[withdrawal public key] 0x87b9ebcd8af91ad43485aa311888f1622a2c41ce1614c24d205e9f52506c28c0543628c3eff8db18845925236421fc91
[derivation path] m/12381/3600/3/0
[validating public key] 0x8329d8e9aa7da5f6b8300a22e55fd5657d6fa42d30408c83218da10136db06936e1bd7025574718e4283a1adf6c1ab71
[derivation path] m/12381/3600/3/0/0
  </code>
</pre>

For example the key `0xb692725fe769d79863eefe4752fac00f878072b8c898a8fbfca32189692ceb0bdb77212d82d9ee8a199b48a60461263b` is in the first listing show as belonging to the account `constantly-popular-wasp`, in the second listing it is shown to belong to the account `carefully-wondrous-terrapin`.

### Has this worked before in a previous version?

No.

## 🔬 Minimal Reproduction

Generate multiple accounts, note the validator public keys, then invoke validator again listing the accounts and observe that the `[validating public key]` entries are mixed up.

## 🔥 Error

No error.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Distribution:      Clear Linux OS
Installed version: 33620

Docker version 19.03.8, build afacb8b7f0d8d4f9d2a8e8736e9c993e672b41f3
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
gcr.io/prysmaticlabs/prysm/validator:v1.0.0-alpha.19
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

The methods producing the output are calling the respective `keymanager.FetchValidatingPublicKeys` functions to retrieve the list of validator public keys. The direct and derived keymanagers both use the key collection of a hashmap to in the `FetchValidatingPublicKeys` function to produce the lis. Because of how a hashmap is implemented, that list is produced in a different order than the order in which the accounts are stored and listed, resulting in a mixup.

Here is the relevant code:

https://github.com/prysmaticlabs/prysm/blob/399dc85737639df62f3dc2f7d95478307812440f/validator/keymanager/v2/direct/direct.go#L311-L318

https://github.com/prysmaticlabs/prysm/blob/399dc85737639df62f3dc2f7d95478307812440f/validator/keymanager/v2/derived/derived.go#L346-L353

### PR DESCRIPTION
**Pull request by RoBiK75**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

This PR is needed because the output produced by the account list functionality was incorrect, validator public keys were mixed up between the listed account. See #6976 for an example.
This PR changes the way in which the public and private key caching is implemented in the direct and derived keymanagers.
The implementations of the FetchValidatingPublicKeys fuctions for the direct and derived keymanagers was changed to produce correctly ordered output using the reimplemented key caching.
The tests for the keymanagers were improved to assert that the function FetchValidatingPublicKeys produces correct output.
The test for the account list functionality was improved to assert that the output is listing the relevant fields in correct possitions.
The backup and backup_test files for the derived keymanager were changed to reflect the change in the  secret key cache variable name.

**Which issues(s) does this PR fix?**

Fixes #6976

**Other notes for review**

### CODE REVIEW

File: validator/keymanager/v2/derived/derived.go [hunk 1]
```diff
@@ -310,6 +313,15 @@ func (dr *Keymanager) CreateAccount(ctx context.Context, logAccountInfo bool) (s
 			"validatingKeyPath":   path.Join(dr.wallet.AccountsDir(), validatingKeyPath),
 		}).Info("Successfully created new validator account")
 	}
+
+	dr.lock.Lock()
+	defer dr.lock.Unlock()
+	// Append the new acount keyes to the account keys caches
```
Comment (rauljordan) [inline validator/keymanager/v2/derived/derived.go:319]:
```suggestion
	// Append the new account keys to the account keys caches.
```

File: validator/keymanager/v2/derived/derived.go [hunk 2]
```diff
@@ -310,6 +313,15 @@ func (dr *Keymanager) CreateAccount(ctx context.Context, logAccountInfo bool) (s
...
+	err = dr.appendKeyesToCaches(blsValidatingKey)
+	if err != nil {
+		return "", errors.Wrapf(err, "failed to append account number %d to acount keys caches", newAccountNumber)
```
Comment (rauljordan) [inline validator/keymanager/v2/derived/derived.go:322]:
```suggestion
		return "", errors.Wrapf(err, "failed to append account number %d to account keys caches", newAccountNumber)
```

File: validator/keymanager/v2/derived/derived.go [hunk 3]
```diff
@@ -406,27 +402,38 @@ func (dr *Keymanager) DepositDataForAccount(accountIndex uint64) ([]byte, error)
 	return tx.Data(), nil
 }
 
-func (dr *Keymanager) initializeSecretKeysCache() error {
-	dr.lock.Lock()
-	defer dr.lock.Unlock()
-	for i := uint64(0); i < dr.seedCfg.NextAccount; i++ {
+// Append public and secret keys for a given account index to their respective caches
+func (dr *Keymanager) appendKeyesToCaches(secretKey bls.SecretKey) error {
```
Comment (rauljordan) [inline validator/keymanager/v2/derived/derived.go:406]:
```suggestion
func (dr *Keymanager) appendKeysToCaches(secretKey bls.SecretKey) error {
```

Comment (rauljordan) [inline validator/keymanager/v2/derived/derived.go:406]: No mutex here? Would be easy to abuse this function since it is not thread safe. Can we move the mutex locking inside if possible?

File: validator/keymanager/v2/derived/derived.go [hunk 4]
```diff
@@ -182,14 +183,16 @@ func NewKeymanager(
...
 	}
-	// We initialize a cache of public key -> secret keys
-	// used to retrieve secrets keys for the accounts via the unlocked wallet.
-	// This cache is needed to process Sign requests using a validating public key.
-	if err := k.initializeSecretKeysCache(); err != nil {
-		return nil, errors.Wrap(err, "could not initialize secret keys cache")
+	// Initialize public and secret key caches that are used to speed up the functions
+	// FetchValidatingPublicKeys and Sign
+	k.lock.Lock()
+	err = k.initializeKeysCaches()
```
Comment (rauljordan) [inline validator/keymanager/v2/derived/derived.go:190]: Would rather this initialize keys caches function hold on to the mutex inside of its function body

File: validator/keymanager/v2/derived/derived.go (hunk 3 above)
Comment (rauljordan) [reply validator/keymanager/v2/derived/derived.go:406]: if this is not reasonable, we should at least add a warning or comment that this function isn't thread safe

File: validator/keymanager/v2/derived/derived.go [hunk 5]
```diff
@@ -406,27 +402,38 @@ func (dr *Keymanager) DepositDataForAccount(accountIndex uint64) ([]byte, error)
...
+	publicKey := bytesutil.ToBytes48(secretKey.PublicKey().Marshal())
+	dr.publicKeysCache = append(dr.publicKeysCache, publicKey)
+	dr.secretKeysCache[publicKey] = secretKey
+	return nil
+}
+
+// Initialize public and secret key caches used to speed up the functions
+// FetchValidatingPublicKeys and Sign
+func (dr *Keymanager) initializeKeysCaches() error {
+	count := dr.seedCfg.NextAccount
```
Comment (rauljordan) [inline validator/keymanager/v2/derived/derived.go:416]: It definitely feels like this function should be the one to hold to the lock

File: validator/keymanager/v2/derived/derived.go (hunk 3 above)
Comment (RoBiK75) [reply validator/keymanager/v2/derived/derived.go:406]: Sorry about all the typos. i need to install a spellchecker into my VS Code

File: validator/keymanager/v2/derived/derived.go (hunk 4 above)
Comment (RoBiK75) [reply validator/keymanager/v2/derived/derived.go:190]: Thinking about it, the initializeKeysCaches function is used only during the initialization of the keymanager. I think it is safe to assume that nobody will try to use the keymanager from a different thread before it is initialized. Therefore the lock around initializeKeysCaches in not really necessary and could be removed.

File: validator/keymanager/v2/derived/derived.go (hunk 5 above)
Comment (RoBiK75) [reply validator/keymanager/v2/derived/derived.go:416]: As mentioned in the above comment, it is only called during the initialization of the keymanager, there is no real need to protect it from race conditions.

File: validator/keymanager/v2/derived/derived.go (hunk 3 above)
Comment (RoBiK75) [reply validator/keymanager/v2/derived/derived.go:406]: If we remove the mutex lock around initializeKeysCaches then we can place the mutex lock inside the appendKeyesToCaches, if we don't rremove the lock around or inside initializeKeysCaches , we would get a deadlock because initializeKeysCaches is calling appendKeyesToCaches.

File: validator/keymanager/v2/derived/derived.go (hunk 1 above)
Comment (RoBiK75) [reply validator/keymanager/v2/derived/derived.go:319]: Sorry for the spelling errors, i need a spellchecker in my development UI :)

File: validator/keymanager/v2/derived/derived.go (hunk 3 above)
Comment (RoBiK75) [reply validator/keymanager/v2/derived/derived.go:406]: Should i go ahead and remove the lock around initializeKeysCaches and put a lock inside appendKeyesToCaches?

File: validator/keymanager/v2/derived/derived.go [hunk 6]
```diff
@@ -406,27 +398,42 @@ func (dr *Keymanager) DepositDataForAccount(accountIndex uint64) ([]byte, error)
...
+	dr.publicKeysCache = append(dr.publicKeysCache, publicKey)
+	dr.secretKeysCache[publicKey] = secretKey
+	dr.lock.Unlock()
+	return nil
+}
+
+// Initialize public and secret key caches used to speed up the functions
+// FetchValidatingPublicKeys and Sign as part of the Keymanager instance initialization
+// Should be only called as part of the initialization of a new Keymanager instance
+// This function is not thread safe
```
Comment (rauljordan) [inline validator/keymanager/v2/derived/derived.go:414]:
```suggestion
// This function is not thread safe.
```

**Comment by rauljordan** [comment]
Hi @RoBiK75 some conflicts to fix
