### PR TITLE
Faster ancestor root look up via fork choice store

### LINKED ISSUE #6750: ancestor via db cause resource exhaustion
# 🐞 Bug Report

### Description

As reported in the Discord channel and observed in clusters. The current Onyx testnet nodes have been using significantly more resources and that's due to long duration of epochs since finality. At this time of writing this, there's ~200 epochs since finality. https://beaconcha.in/. 

The biggest bottleneck is retrieving ancestors for block via DB

Screen Shot 2020-07-28 at 9 40 14 AM

### Has this worked before in a previous version?

No

## 🔬 Minimal Reproduction

Sync to head on Onyx testnet

## 🔥 Error

N/A

### PR DESCRIPTION
**Pull request by terencechain**
**What type of PR is this?**
> Feature

**What does this PR do? Why is it needed?**

Added a more performant way to retrieve ancestor root for a given block slot. This utilizes fork choice store's DAG  structure in memory for look back.  Before it was using recursive DB look up and it became a bottleneck at 200 epochs no finality.

Before:
Screen Shot 2020-07-28 at 12 17 42 PM

After:
Screen Shot 2020-07-28 at 1 12 54 PM

**Which issues(s) does this PR fix?**

Fixes #6750 

**Other notes for review**

Tested run time

### CODE REVIEW

File: beacon-chain/forkchoice/protoarray/store.go [hunk 1]
```diff
@@ -138,3 +138,44 @@ func (f *ForkChoice) HasNode(root [32]byte) bool {
...
 }
+
+// HasParent returns true if the node parent exists in fork choice store,
+// false else wise.
+func (f *ForkChoice) HasParent(root [32]byte) bool {
+	f.store.nodeIndicesLock.RLock()
+	defer f.store.nodeIndicesLock.RUnlock()
+
+	i, ok := f.store.NodeIndices[root]
+	if !ok {
```
Comment (rauljordan) [inline beacon-chain/forkchoice/protoarray/store.go:149]:
```go
if !ok || i >= uint64(len(f.store.Nodes)) {
```
