### PR TITLE
Modify the algorithm of `updateFinalizedBlockRoots`

### LINKED ISSUE #13408: Error on finalized flag for `/eth/v2/beacon/blocks/{block_id}`
### Describe the bug

I run several nodes behind a node balancer. I query for the checkpoint and when I receive a new one I query `/eth/v1/beacon/headers/{block_id}` with the `block_id = finalized_root` from the checkpoint payload. Then, I query for all the slots between the previous finalized slot and the current finalized slot.

When I queried slot `8118490` (endpoint = `/eth/v2/beacon/blocks/8118490`) after having seen a new checkpoint (not necessarily from the node that I was quering), I received the payload for the block with the flag `finalized: true` which is not what I was expecting since the slot has been forked/uncled.

I was expecting either a 404 (block not found) or `finalized: false`. 

Is this an expected behaviour?

[Here](https://github.com/prysmaticlabs/prysm/files/13818624/slot_response_8118490.json) is the payload that I received for slot `8118490` that shows the finalized flag = true. 

### Has this worked before in a previous version?

```text
Not sure
```

### 🔬 Minimal Reproduction

Below are the prism flags and environment used for all of the nodes behind the node balancer.
```
[Service]

Environment=USE_PRYSM_MODERN=true
Environment=USE_PRYSM_VERSION=v4.0.8

ExecStart=/data/prysm/prysm.sh beacon-chain \
--slots-per-archive-point 2048 \
--execution-endpoint=http://localhost:8551/ \
--mainnet \
--jwt-secret=/path/to/jwt.hex \
--datadir /path/to/datadir \
--monitoring-host 0.0.0.0 \
--grpc-gateway-host 0.0.0.0 \
--grpc-gateway-corsdomain 127.0.0.1 \
--accept-terms-of-use \
--enable-debug-rpc-endpoints
```

### Error

_No response_

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

4.0.8

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

The motivation for this PR is the following note from `IsFinalizedBlock`:
> // Note: beacon blocks from the latest finalized epoch return true, whether or not they are
// considered canonical in the "head view" of the beacon node.

This means that an orphaned block can be viewed as finalized, as was reported in #13408. To fix this, I redesigned the algorithm so that it traverses parent->child block relationships in the `blockParentRootIndicesBucket` bucket to find the path between the last finalized checkpoint and the current finalized checkpoint.

`TestStore_OrphanedBlockIsNotFinalized` is the test covering the main improvement. I completely removed `TestStore_IsFinalized_ForkEdgeCase` because it tested that a finalized checkpoint is reverted.

The new algorithm shaves off a staggering 10ms from epoch processing time :laughing: 

**Which issues(s) does this PR fix?**

Fixes #13408

### CODE REVIEW

File: beacon-chain/state/stategen/replay_test.go [hunk 1]
```diff
@@ -374,63 +374,63 @@ func TestLoadBlocks_BadStart(t *testing.T) {
 //	                 \- B7
 func tree1(t *testing.T, beaconDB db.Database, genesisRoot []byte) ([][32]byte, []*ethpb.SignedBeaconBlock, error) {
 	b0 := util.NewBeaconBlock()
-	b0.Block.Slot = 0
+	b0.Block.Slot = 1
```
Comment (rkapka) [inline beacon-chain/state/stategen/replay_test.go:377]: Incrementing slot everywhere because genesis block has slot 0

File: beacon-chain/state/stategen/replay_test.go [hunk 2]
```diff
@@ -697,17 +697,17 @@ func TestLoadFinalizedBlocks(t *testing.T) {
...
-	require.Equal(t, 0, len(filteredBlocks))
+	require.Equal(t, 1, len(filteredBlocks))
 	require.NoError(t, beaconDB.SaveStateSummary(ctx, &ethpb.StateSummary{Root: roots[8][:]}))
 
 	require.NoError(t, s.beaconDB.SaveFinalizedCheckpoint(ctx, &ethpb.Checkpoint{Root: roots[8][:]}))
-	filteredBlocks, err = s.loadFinalizedBlocks(ctx, 0, 8)
+	filteredBlocks, err = s.loadFinalizedBlocks(ctx, 0, 9)
 	require.NoError(t, err)
-	require.Equal(t, 10, len(filteredBlocks))
+	require.Equal(t, 7, len(filteredBlocks))
```
Comment (rkapka) [inline beacon-chain/state/stategen/replay_test.go:712]: This also manifests the purpose of the new algorithm. The tree constructed in `tree1` has orphaned blocks, but they were expected to be finalized.

File: beacon-chain/db/kv/finalized_block_roots.go [hunk 3]
```diff
@@ -29,139 +28,77 @@ var containerFinalizedButNotCanonical = []byte("recent block needs reindexing to
...
 		}
+		_, finalized = pathToFinalizedCheckpoint(ctx, [][]byte{previousFinalizedCheckpoint.Root}, checkpoint.Root, tx)
+	}
 
+	for i, r := range finalized {
+		var container *ethpb.FinalizedBlockRootContainer
+		if i == len(finalized)-1 {
+			// We don't know the finalized child of the new finalized checkpoint.
+			// It will be filled out in the next function call.
+			container = &ethpb.FinalizedBlockRootContainer{}
```
Comment (nisdas) [inline beacon-chain/db/kv/finalized_block_roots.go:84]: This completely misses adding in `ParentRoot` for the container. In fact it appears this PR has completely removed it.

File: beacon-chain/db/kv/finalized_block_roots.go [hunk 4]
```diff
@@ -297,3 +232,50 @@ func (s *Store) FinalizedChildBlock(ctx context.Context, blockRoot [32]byte) (in
...
+func pathToFinalizedCheckpoint(ctx context.Context, roots [][]byte, checkpointRoot []byte, tx *bolt.Tx) (bool, [][]byte) {
+	if len(roots) == 1 && roots[0] == nil {
+		return false, nil
+	}
+
+	for _, r := range roots {
+		if bytes.Equal(r, checkpointRoot) {
+			return true, [][]byte{r}
+		}
+		children := lookupValuesForIndices(ctx, map[string][]byte{string(blockParentRootIndicesBucket): r}, tx)[0]
```
[the remark this answers is not in the document]
Comment (rkapka) [reply beacon-chain/db/kv/finalized_block_roots.go:245]: I added a condition for it although it is not strictly necessary. Since the passed in map contains one key, the resulting slice will have one item.

File: beacon-chain/db/kv/finalized_block_roots.go [hunk 5]
```diff
@@ -81,10 +81,18 @@ func (s *Store) updateFinalizedBlockRoots(ctx context.Context, tx *bolt.Tx, chec
 		if i == len(finalized)-1 {
 			// We don't know the finalized child of the new finalized checkpoint.
 			// It will be filled out in the next function call.
-			container = &ethpb.FinalizedBlockRootContainer{}
+			container = &ethpb.FinalizedBlockRootContainer{
+				ParentRoot: finalized[i-1],
+			}
+		} else if i == 0 {
```
Comment (nisdas) [inline beacon-chain/db/kv/finalized_block_roots.go:88]: might be better to use a switch statement ? If not handling `i` in a progressive order is reads better
```
if i == 0 {
// do something
else if i == len(finalized) -1 {
// do something
} else {
// ...
}
```

**Review by nisdas — APPROVED** [review]

**Review by prestonvanloon — APPROVED** [review]
