### PR TITLE
Fixes server ignores request to gzip data 

### LINKED ISSUE #14593: server ignores request to gzip data
### Describe the bug

version: beacon-chain:v5.0.4

was checking tcpdump as we had some issues and found following

````
(GET /eth/v1/beacon/blob_sidecars/10252744?indices=0&indices=1&indices=2&indices=3&indices=4 HTTP/1.1
Host: beacon:7028
User-Agent: Go-http-client/1.1
Accept: application/json
Accept-Encoding: gzip
````
response
````
Content-Type: application/json
Vary: Origin
Vary: Origin
Date: Tue, 29 Oct 2024 17:06:42 GMT
Transfer-Encoding: chunked

142720
{"data":[{"index":"0","blob":"0x3e0001fbfc...
````

so it ignored Accept-Encoding header and sending only plain json. Would be great if beacon can handle this correctly.

### Has this worked before in a previous version?

_No response_

### 🔬 Minimal Reproduction

_No response_

### Error

_No response_

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

5.0.4

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by rose2221**
### **What type of PR is this?**
Bug fix  

### **What does this PR do? Why is it needed?**
This PR fixes an issue where the Prysm beacon chain server **ignores the `Accept-Encoding: gzip` header** in HTTP requests and always returns uncompressed JSON responses.

#### **Fix Details:**
- Updated middleware to properly **respect the `Accept-Encoding` header**.
- Ensured that responses are **compressed when requested**.
- Added **error handling** to prevent silent failures.

### **Which issue(s) does this PR fix?**
Fixes #14593

### **Acknowledgements**
- [✅] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).  
- [✅] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).  
- [✅] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

File: api/server/middleware/middleware.go [hunk 1]
```diff
@@ -112,6 +114,40 @@ func AcceptHeaderHandler(serverAcceptedTypes []string) Middleware {
...
+				return
+		}
+
+		w.Header().Set("Content-Encoding", "gzip")
+
+		gz := gzip.NewWriter(w)
+		// defer gz.Close()
+		defer func(){
+			if err:= gz.Close(); err != nil {
+				log.WithError(err).Error("failed to close gzip writer")
```
Comment (rkapka) [inline api/server/middleware/middleware.go]:
```suggestion
				log.WithError(err).Error("Failed to close gzip writer")
```
We use upper casing for logs

File: api/server/middleware/middleware.go [hunk 2]
```diff
@@ -112,6 +114,40 @@ func AcceptHeaderHandler(serverAcceptedTypes []string) Middleware {
 	}
 }
 
+func GzipMiddleware() Middleware {
```
Comment (rkapka) [inline api/server/middleware/middleware.go]: Can you rename this to `AcceptEncodingHeaderHandler` because we already have `AcceptHeaderHandler`?

**Comment by rkapka** [comment]
Hey @rose2221 , thanks for the contribution! This PR only adds gzip to the blobs endpoint, but it would make much more sense to have support on all endpoints that return data. Which means all endpoint that use `middleware.AcceptHeaderHandler`.

Before merging the PR you will also have to sign [the Contributor License Agreement](https://github.com/prysmaticlabs/prysm/pull/14982#issuecomment-2677955298) and add a [changelog file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).

**Comment by rose2221** [comment]
Thank you, @rkapka, for your suggestions! I've implemented the requested changes. Let me know if there's anything else that needs adjustment. Also, should I add tests for this as well?

File: changelog/rose2221-develop.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+### Bug Fixes
```
Comment (rkapka) [inline changelog/rose2221-develop.md]:
```suggestion
### Added
```

**Comment by rkapka** [comment]
> Also, should I add tests for this as well?

That would be very helpful. Perhaps you could write a unit test where you:
- have a dummy handler that returns some value
- register the gzip middleware for this handler
- execute the handler and check that the returned data is NOT equal to the value that the handler returns (meaning that it got zipped - this is to prevent a scenario where nothing gets zipped and the next step does nothing, but the whole test passes)
- unzip the returned data and see that it's equal to the value returned from the handler

**Comment by rose2221** [comment]
> > Also, should I add tests for this as well?
> 
> That would be very helpful. Perhaps you could write a unit test where you:
> 
> * have a dummy handler that returns some value
> * register the gzip middleware for this handler
> * execute the handler and check that the returned data is NOT equal to the value that the handler returns (meaning that it got zipped - this is to prevent a scenario where nothing gets zipped and the next step does nothing, but the whole test passes)
> * unzip the returned data and see that it's equal to the value returned from the handler

Thank you, I've implemented the test as suggested and I'm open to any further feedback. @rkapka

**Comment by james-prysm** [comment]
please fix linting `bazel run //:gazelle -- fix`

File: api/server/middleware/middleware.go [hunk 4]
```diff
@@ -112,6 +114,39 @@ func AcceptHeaderHandler(serverAcceptedTypes []string) Middleware {
...
 }
 
+// AcceptEncodingHeaderHandler compresses the response before sending it back to the client, if gzip is supported.
+func AcceptEncodingHeaderHandler() Middleware {
+	return func(next http.Handler) http.Handler {
+		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request){
+			if !strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
+				next.ServeHTTP(w, r)
+				return
+		}
```
Comment (james-prysm) [inline api/server/middleware/middleware.go]: There's something wrong with this formatting when I first read it I thought it was on the return above

File: beacon-chain/rpc/endpoints.go [hunk 5]
```diff
@@ -124,6 +124,7 @@ func (s *Service) rewardsEndpoints(blocker lookup.Blocker, stater lookup.Stater,
 			name:     namespace + ".BlockRewards",
 			middleware: []middleware.Middleware{
 				middleware.AcceptHeaderHandler([]string{api.JsonMediaType}),
+				middleware.AcceptEncodingHeaderHandler(),
```
Comment (james-prysm) [inline beacon-chain/rpc/endpoints.go:133]: I'm not sure if this actually makes sense to be added on all of these endpoints...

Comment (james-prysm) [reply beacon-chain/rpc/endpoints.go:133]: If i remember correctly it was just a request on blobs

File: api/server/middleware/middleware.go [hunk 6]
```diff
@@ -112,6 +114,39 @@ func AcceptHeaderHandler(serverAcceptedTypes []string) Middleware {
...
+
+		w.Header().Set("Content-Encoding", "gzip")
+
+		gz := gzip.NewWriter(w)
```
Comment (james-prysm) [inline api/server/middleware/middleware.go]: I'm a little worried about the usage of this will need to read up more on this

File: beacon-chain/rpc/endpoints.go (hunk 5 above)
Comment (rkapka) [reply beacon-chain/rpc/endpoints.go:133]: What's the downside of being able to receive zipped data?

File: api/server/middleware/middleware_test.go [hunk 7]
```diff
@@ -124,6 +127,77 @@ func TestContentTypeHandler(t *testing.T) {
...
+				require.Equal(t, "gzip", rr.Header().Get("Content-Encoding"), "Expected Content-Encoding header to be 'gzip'")
+
+				compressedBody := rr.Body.Bytes()
+				require.NotEqual(t, dummyContent, string(compressedBody), "Response body should be compressed and differ from the original")
+
+				gzReader, err := gzip.NewReader(bytes.NewReader(compressedBody))
+				require.NoError(t, err, "Failed to create gzipReader")
+				defer func() {
+					if err := gzReader.Close(); err != nil {
+						log.WithError(err).Error("Failed to close gzip writer")
```
Comment (rkapka) [inline api/server/middleware/middleware_test.go]:
```suggestion
						log.WithError(err).Error("Failed to close gzip reader")
```

**Comment by rkapka** [comment]
@rose2221 Thanks for the test. I would like to approve the PR, but you need to run `bazel run //:gazelle -- fix` to fix dependencies before this can be merged.

**Comment by rose2221** [comment]
> @rose2221 Thanks for the test. I would like to approve the PR, but you need to run `bazel run //:gazelle -- fix` to fix dependencies before this can be merged.

done! thanks!

**Review by rkapka — DISMISSED** [review]

**Comment by rkapka** [comment]
Merging the PR @rose2221 , thanks a lot for the contribution!

**Comment by rkapka** [comment]
@rose2221 For some reason our end-to-end tests fail with this PR. I can debug this myself but if you'd like to do it yourself you can run
```
bazel test //testing/endtoend:go_default_test --test_filter=TestEndToEnd_MinimalConfig --test_env=E2E_EPOCHS=4 --test_timeout=10000 --test_output=streamed --sandbox_debug
```

**Comment by rose2221** [comment]
> @rose2221 For some reason our end-to-end tests fail with this PR. I can debug this myself but if you'd like to do it yourself you can run
> 
> ```
> bazel test //testing/endtoend:go_default_test --test_filter=TestEndToEnd_MinimalConfig --test_env=E2E_EPOCHS=4 --test_timeout=10000 --test_output=streamed --sandbox_debug
> ```

hey yes i would like to work on it

**Comment by rkapka** [comment]
Great! When the test fails, it outputs a path where all logs are stored. These are logs from the e2e run as well as beacon node logs (and some other as well but looking at beacon node logs should be enough)

**Comment by rose2221** [comment]
> @rose2221 For some reason our end-to-end tests fail with this PR. I can debug this myself but if you'd like to do it yourself you can run

Hey, I'm unable to deal with the error. Could you help me out or guide me for debugging? @rkapka

**Comment by rose2221** [comment]
> Great! When the test fails, it outputs a path where all logs are stored. These are logs from the e2e run as well as beacon node logs (and some other as well but looking at beacon node logs should be enough)

Hey @rkapka @james-prysm , sorry for the delay — I've fixed it now. Thanks for pointing out the log path.

**Review by rkapka — CHANGES_REQUESTED** [review]
~~Simply ignoring SSZ is not correct~~

Ignoring SSZ is fine, but we should do it in a more reliable way. The user can specify two values in the `Accept` header, in which case even though `application/octet-stream` is a part of the header, the type of the response can still be `application/json`

**Comment by rkapka** [comment]
@rose2221 Do you mind cherry-picking https://github.com/OffchainLabs/prysm/commit/5dcbb5294a1fc53286e7391ec9b4c6ac79fc5363 into your branch? I believe this is the correct way to ignore SSZ responses

**Comment by rose2221** [comment]
> @rose2221 Do you mind cherry-picking [5dcbb52](https://github.com/OffchainLabs/prysm/commit/5dcbb5294a1fc53286e7391ec9b4c6ac79fc5363) into your branch? I believe this is the correct way to ignore SSZ responses

sure ! will complete it in a day or two! thanks for the same!

**Comment by rkapka** [comment]
Also the PR has some conflicts now @rose2221

**Comment by rose2221** [comment]
> Also the PR has some conflicts now @rose2221

i've applied the changes as suggested! thanks very much for the same!

**Review by prestonvanloon — APPROVED** [review]

**Review by rkapka — APPROVED** [review]
