### PR TITLE
Resolve Flakey P2P Tests

### LINKED ISSUE #5283: v0.11: Flaky p2p tests
Test target `//beacon-chain/p2p:go_default_test ` in the v0.11 branch has been very flaky.

The tests I see fail the most are
- TestStaticPeering_PeersAreAdded
- TestDiscv5_AddRetrieveForkEntryENR

Example errors:
```
TestDiscv5_AddRetrieveForkEntryENR: fork_test.go:246: Wanted fork digest: [24 174 76 203], received [245 165 253 66] 
```

After running 100 tests sequentially (can't run in parallel because the test demands port 2000), the results show that it fails 19 out of 118 runs. (Not sure why it ran 18 extra but ok).

### PR DESCRIPTION
**Pull request by rauljordan**
Resolves #5283 

---

# Description

**Write why you are making the changes in this pull request**

Some p2p tests were relying on too short of a time tolerance and causing flakeyness.

**Write a summary of the changes you are making**

This PR resolves:

- TestStaticPeering_PeersAreAdded
- TestDiscv5_AddRetrieveForkEntryENR

by increasing the time tolerance of the first test and eliminating time dependence in the second test.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Tests fail

FAIL: TestStaticPeering_PeersAreAdded

File: beacon-chain/p2p/discovery_test.go [hunk 1]
```diff
@@ -188,7 +188,7 @@ func TestStaticPeering_PeersAreAdded(t *testing.T) {
 	}
 	s.Start()
 
-	time.Sleep(2 * time.Second)
+	time.Sleep(10 * time.Second)
```
Comment (prestonvanloon) [inline beacon-chain/p2p/discovery_test.go:191]: Yikes! OK for now.
