### PR TITLE
changes for safe validator shutdown and restarts on healthcheck

### LINKED ISSUE #15296: --enable-doppelganger prevents fallback to secondary beacon node
### Describe the bug

When running the validator with `--enable-doppelganger` and `multiple --beacon-rest-api-provider` endpoints, the fallback to the secondary beacon node does not work properly if the primary node is down. 

The validator either fails during the doppelganger check or keeps retrying the primary endpoint after restart, never switching to the secondary.

### Has this worked before in a previous version?

```text
Not tested in prior versions — this behavior is observed on v6.0.0.
```

### 🔬 Minimal Reproduction

**Two Prysm beacon nodes** 
`http://primary-beacon:5052`, `http://fallback-beacon:5052`

**Prysm Validator client args**
`--enable-doppelganger `
`--enable-beacon-rest-api `
`--beacon-rest-api-provider=http://primary-beacon:5052,http://fallback-beacon:5052 `

### **Steps to reproduce:**
**Case 1 – Runtime fallback failure**
1. Start validator with `--enable-doppelganger`, and both primary and fallback beacon nodes running.
2. Stop the primary beacon node.
3. Observe validator logs: 
Fallback switching log appears. Then, validator fails with doppelganger error and restarts.
  ```
  level=info msg="Beacon node at http://primary-beacon:5052 is not responding, switching to http://fallback-beacon:5052..." prefix=client
  level=fatal msg="Could not succeed with doppelganger check" error="failed to get map from validator index to liveness for previous epoch 13483: failed to get liveness for epoch 13483: HTTP request unsuccessful (400: No data submitted)" prefix=client
  ```
4. After restart, validator attempts to reconnect only to primary node, failing repeatedly:
```
level=warning msg="Could not determine if beacon chain started" error="failed to perform request for endpoint http://primary-beacon:5052/eth/v1/beacon/genesis"
```

**Case 2 – Initial fallback failure**
1. Ensure primary beacon node is down and fallback is up.
2. Start the validator client.
3. Validator never connects to fallback; keeps retrying primary endpoint with connection errors.

**Control test**
When `--enable-doppelganger` is not used, fallback to the secondary node works as expected.

### Error

```text

```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

v6.0.0

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

the PR attempts to solve 2 things while making some refactors for separation of concerns. 
### remove the log.fatals in the validator client runner. we use these log.fatals instead of returning an error from the runner to shut down everything ( the 3 services and the validator client) this is very old code. To do this we are changing the following refactors

a. separating the runner into 2 parts, an initialized object and the main loop. the main loop doesn't throw any errors and just exits just like before, when we error we just continue on the loop, but the initialization portion has these log.fatals to indicate a bad startup that isn't a connection issue, this could be connecting to the wrong beacon node or a beacon node that is totally unhealthy. 

b. without the log.fatal we can't actually stop the validator client, and because the runner runs in the validator service ( and in its own go routine for no good reason) we have to inherit the parent (validator client) close function in order to stop everything when we receive an error. 

c. because i had to move things around for the runner, it made sense to make changes to the health checker that was already working incorrectly.

### reworking the health checker which didn't work totally smoothly, and had a few bugs such as https://github.com/OffchainLabs/prysm/issues/15296

a. getting rid of the old healthtracker which had its logic sprawled across several components from the validator to the restclients to the runner, consolidating them into the health monitor that lives in the validator client package ( since it's checking the health of the beacon node for the validator client I think it makes more sense)

b. reworking how the runner deals with the health checks, so that it reinitializes the entire runner instead of only what we put https://github.com/OffchainLabs/prysm/blob/bc7664321b477f159ad92559ddfb9de62e95d718/validator/client/runner.go#L131, this also cleans up how our validator client connects to the events api as a client

added `max-health-checks` flag that takes an integer representing the times the validator client will check the beacon node's health before timing out and shutting down.

kurtosis tests:
```


participants_matrix:
  el:
    - el_type: geth
      el_image: ethpandaops/geth:master
  cl:
    - cl_type: prysm
      count: 2
      cl_image: gcr.io/offchainlabs/prysm/beacon-chain:latest
      cl_extra_params: [--minimal-config=true]
      vc_image: gcr.io/offchainlabs/prysm/validator:latest
      vc_extra_params: [--minimal-config=true]
    - cl_type: prysm
      count: 1
      cl_image: gcr.io/offchainlabs/prysm/beacon-chain:latest
      cl_extra_params: [--minimal-config=true]
      vc_image: gcr.io/offchainlabs/prysm/validator:latest
      vc_extra_params: [--minimal-config=true,--verbosity=debug, --max-health-checks=5]
network_params:
  electra_fork_epoch: 1
  preset: minimal
additional_services:
  - dora
snooper_enabled: true
port_publisher:
  cl:
    enabled: true
    public_port_start: 33000
```
tested by 
- turning cl3 off for vc3 to see graceful shutdown
- restarting cl3 for v3 to see recoverystarting a new runner
- test that https://github.com/OffchainLabs/prysm/pull/7133 still works
- test that https://github.com/OffchainLabs/prysm/pull/13433 still works
- cancel the validator while running does not panic anything
- starting the validator targeting a non healthy beacon node, turned beacon node on, see that it connects, turn beacon node off see that it disconnects, and tested using a proxy.

notes from testing
```
[2025-06-30 13:50:33] DEBUG gRPC request finished. backend=[] duration=3.192542ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetSyncSubcommitteeIndex
[2025-06-30 13:50:33] DEBUG gRPC request finished. backend=[] duration=3.283292ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetSyncSubcommitteeIndex
[2025-06-30 13:50:33] DEBUG gRPC request finished. backend=[] duration=2.826792ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetSyncSubcommitteeIndex
[2025-06-30 13:50:33] DEBUG gRPC request finished. backend=[] duration=2.919708ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetSyncSubcommitteeIndex
[2025-06-30 13:50:33] DEBUG client: Received head event
[2025-06-30 13:50:33] ERROR client: Event stream interrupted error=rpc error: code = Canceled desc = Context canceled: could not connect
[2025-06-30 13:50:35] DEBUG gRPC request finished. backend=[] duration=2.63525ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetSyncMessageBlockRoot
[2025-06-30 13:50:35] DEBUG gRPC request finished. backend=[] duration=7.675334ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData
[2025-06-30 13:50:35] DEBUG gRPC request finished. backend=[] duration=8.049792ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetSyncMessageBlockRoot
[2025-06-30 13:50:35] DEBUG gRPC request finished. backend=[] duration=7.9255ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData
```
grpc goes to fallback node without even triggering healthcheck issues

if retry triggers, then it will try to connect to the first node and give up before trying the whole list.

## testing gRPC fall back

steps
- kurtosis file
```
participants_matrix:
  el:
    - el_type: geth
      el_image: ethereum/client-go:stable
  cl:
    - cl_type: prysm
      count: 2
      cl_image: gcr.io/offchainlabs/prysm/beacon-chain:latest
      cl_extra_params: [--minimal-config=true]
      vc_image: gcr.io/offchainlabs/prysm/validator:latest
      vc_extra_params: [--minimal-config=true]
    - cl_type: prysm
      count: 2
      cl_image: gcr.io/offchainlabs/prysm/beacon-chain:latest
      cl_extra_params: [--minimal-config=true]
      # cl_extra_params: [--minimal-config=true,--enable-tracing,--tracing-endpoint=http://jaeger:4318]
      vc_image: gcr.io/offchainlabs/prysm/validator:latest
      vc_extra_params: [--minimal-config=true,--verbosity=debug]
      validator_count: 1
      # vc_extra_params: [--minimal-config=true,--enable-tracing,--tracing-endpoint=http://jaeger:4318]
network_params:
  electra_fork_epoch: 1
  preset: minimal
additional_services:
  - dora
port_publisher:
  cl:
    enabled: true
    public_port_start: 33000
```
- copy key from validator 4 all-accounts.keystore.json file
- turn off validators 3 & 4
- run ( note beacon-rpc-provider is set to rpc of cl nodes 4 &3
```
bazel run //cmd/validator:validator --config=minimal -- \
  --max-health-checks=10 \
  --chain-config-file=/Users/james/git/prysm/cmd/validator/tmp/network/config.yaml \
  --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776 \
  --beacon-rpc-provider=127.0.0.1:33026,127.0.0.1:33019 \
  --wallet-dir=/Users/james/git/prysm/cmd/validator/tmp \
  --datadir=/Users/james/git/prysm/cmd/validator/tmp \
  --wallet-password-file=/Users/james/git/prysm/cmd/validator/tmp/prysm-password.txt \
  --minimal-config=true \
  --verbosity=debug
```
- turn off cl 4, notice that validator falls back to cl 3
- delete network keys of cl 3 & turn off cl 3
- note that validator polls for healthy node
- restart cl 3 & note that validator reconnects with the below logs

```
[2025-07-07 10:49:03]  INFO client: Submitted new aggregate attestations blockRoot=0xe6964f4cf4f8 committeeIndices=[0] pubkeys=[0x870342ee85d1] slot=50 sourceEpoch=5 sourceRoot=0xaa02fe8b8f7a targetEpoch=6 targetRoot=0xe22e786cab63
[2025-07-07 10:49:03] DEBUG gRPC request finished. backend=[] duration=949µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:04] DEBUG gRPC request finished. backend=[] duration=129.958µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:05] DEBUG gRPC request finished. backend=[] duration=2.04175ms method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:06] DEBUG gRPC request finished. backend=[] duration=109.25µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:07] DEBUG gRPC request finished. backend=[] duration=74.041µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:07] DEBUG failed to get health of node error=rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:33026: connect: connection refused"
[2025-07-07 10:49:07]  WARN client: Failed health check, beacon node is unresponsive fails=0 maxFails=20
[2025-07-07 10:49:07]  WARN client: Beacon node unhealthy, stopping runner
[2025-07-07 10:49:07]  WARN client: Validator service health check failed, waiting for healthy beacon node...
[2025-07-07 10:49:09] DEBUG gRPC request finished. backend=[] duration=63.208µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:10] DEBUG gRPC request finished. backend=[] duration=38.375µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:11] DEBUG gRPC request finished. backend=[] duration=79.125µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:12] DEBUG gRPC request finished. backend=[] duration=44.583µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:13] DEBUG gRPC request finished. backend=[] duration=68.75µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:13] DEBUG failed to get health of node error=rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:33026: connect: connection refused"
[2025-07-07 10:49:13]  WARN client: Failed health check, beacon node is unresponsive fails=1 maxFails=20
[2025-07-07 10:49:15] DEBUG gRPC request finished. backend=[] duration=118.791µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:16] DEBUG gRPC request finished. backend=[] duration=74.334µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:17] DEBUG gRPC request finished. backend=[] duration=94.125µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:18] DEBUG gRPC request finished. backend=[] duration=132.792µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:19] DEBUG gRPC request finished. backend=[] duration=531.416µs method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:19] DEBUG failed to get health of node error=rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:33026: connect: connection refused"
[2025-07-07 10:49:19]  WARN client: Failed health check, beacon node is unresponsive fails=2 maxFails=20
[2025-07-07 10:49:21] DEBUG gRPC request finished. backend=[] duration=4.418875ms method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:21]  INFO client: Starting validator runner
[2025-07-07 10:49:21]  INFO client: Syncing with beacon node to align on chain genesis info
[2025-07-07 10:49:21] DEBUG gRPC stream started. backend=[] method=/ethereum.eth.v1alpha1.BeaconNodeValidator/WaitForChainStart
[2025-07-07 10:49:21]  INFO client: Beacon chain started genesisTime=2025-07-07 10:43:59 -0500 CDT
[2025-07-07 10:49:21] DEBUG gRPC request finished. backend=[] duration=599.083µs method=/ethereum.eth.v1alpha1.Node/GetSyncStatus
[2025-07-07 10:49:21] DEBUG gRPC request finished. backend=[] duration=415.125µs method=/ethereum.eth.v1alpha1.BeaconNodeValidator/MultipleValidatorStatus
[2025-07-07 10:49:21]  INFO client: Validator activated index=129 pubkey=0x870342ee85d1 status=ACTIVE validatorIndex=129
[2025-07-07 10:49:21] DEBUG gRPC request finished. backend=[] duration=587.875µs method=/ethereum.eth.v1alpha1.BeaconChain/GetChainHead
[2025-07-07 10:49:21] DEBUG gRPC request finished. backend=[] duration=706.375µs method=/ethereum.eth.v1alpha1.BeaconNodeValidator/GetDuties
[2025-07-07 10:49:21]  INFO client: Schedule for epoch 6 attesterCount=1 proposerCount=0
[2025-07-07 10:49:21]  INFO client: Duties schedule attesterCount=1 attesterPubkeys=[0x870342ee85d1] slot=50 slotInEpoch=2
[2025-07-07 10:49:21] DEBUG gRPC request finished. backend=[] duration=400.333µs method=/ethereum.eth.v1alpha1.BeaconNodeValidator/PrepareBeaconProposer
[2025-07-07 10:49:21]  INFO client: Starting event stream topics=[head]
[2025-07-07 10:49:21] DEBUG gRPC stream started. backend=[] method=/ethereum.eth.v1alpha1.BeaconNodeValidator/StreamSlots
[2025-07-07 10:49:21] DEBUG gRPC request finished. backend=[] duration=356.5µs method=/ethereum.eth.v1alpha1.BeaconNodeValidator/DomainData
[2025-07-07 10:49:21] DEBUG gRPC request finished. backend=[] duration=433.458µs method=/ethereum.eth.v1alpha1.BeaconNodeValidator/SubscribeCommitteeSubnets
[2025-07-07 10:49:23] DEBUG client: Set deadline for proposals and attestations deadline=2025-07-07 10:49:29 -0500 CDT slot=54
[2025-07-07 10:49:23] DEBUG gRPC request finished. backend=[] duration=1.70175ms method=/ethereum.eth.v1alpha1.BeaconNodeValidator/PrepareBeaconProposer
[2025-07-07 10:49:23] DEBUG client: Received head event
[2025-07-07 10:49:27] DEBUG gRPC request finished. backend=[] duration=49.668583ms method=/ethereum.eth.v1alpha1.Node/GetHealth
[2025-07-07 10:49:29] DEBUG client: Set deadline for proposals and attestations deadline=2025-07-07 10:49:35 -0500 CDT slot=55
[2025-07-07 10:49:29] DEBUG gRPC request finished. backend=[] duration=604.417µs method=/ethereum.eth.v1alpha1.BeaconNodeValidator/PrepareBeaconProposer
[2025-07-07 10:49:29] DEBUG gRPC request finished. backend=[] duration=358.083µs method=/ethereum.eth.v1alpha1.BeaconNodeValidator/DomainData
[2025-07-07 10:49:29] DEBUG gRPC request finished. backend=[] duration=745.125µs method=/ethereum.eth.v1alpha1.BeaconChain/GetValidatorPerformance
[2025-07-07 10:49:29]  INFO client: Previous epoch voting summary correctlyVotedHead=false correctlyVotedSource=false correctlyVotedTarget=false epoch=5 inactivityScore=0 newBalance=31.997571823 oldBalance=31.998199383 percentChange=-0.00196% percentChangeSinceStart=-0.00981% pubkey=0x870342ee85d1 startBalance=32.000709623
[2025-07-07 10:49:29] DEBUG gRPC request finished. backend=[] duration=466.208µs method=/ethereum.eth.v1alpha1.BeaconNodeValidator/DomainData
```

**Which issues(s) does this PR fix?**

I believe it should fix https://github.com/OffchainLabs/prysm/issues/15296
part of https://github.com/OffchainLabs/prysm/issues/15362

**Other notes for review**

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

File: api/client/beacon/health/health.go [hunk 1]
```diff
@@ -27,32 +30,28 @@ func (n *NodeHealthTracker) HealthUpdates() <-chan bool {
...
+		// Non-blocking send to channel
 		select {
-		case <-n.healthChan:
-			n.healthChan <- newStatus
+		case n.healthChan <- newStatus:
 		default:
+			// Channel full, drain and send
+			<-n.healthChan
 			n.healthChan <- newStatus
 		}
```
Comment (rkapka) [inline api/client/beacon/health/health.go]: Why change this logic?

File: changelog/james-prysm_safe-validator-shutdown.md [hunk 2]
```diff
@@ -0,0 +1,11 @@
+## Added
+
+- Added `max-health-checks` flag that sets the maximum times the validator tries to check the health of the beacon node before timing out. -1 is indefinite.
```
Comment (rkapka) [inline changelog/james-prysm_safe-validator-shutdown.md]: How about using `0` as indefinite? Otherwise there is a gap where setting to `-1` makes sense and setting to `1` makes some sense, but `0` doesn't make sense.

File: changelog/james-prysm_safe-validator-shutdown.md [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+
+## Fixed
+
+- Validator client shutsdown cleanly on error instead of fatal error.
```
Comment (rkapka) [inline changelog/james-prysm_safe-validator-shutdown.md]:
```suggestion
- Validator client shuts down cleanly on error instead of fatal error. 
```

File: changelog/james-prysm_safe-validator-shutdown.md [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+
+- Added `max-health-checks` flag that sets the maximum times the validator tries to check the health of the beacon node before timing out. -1 is indefinite.
+
+## Fixed
+
+- Validator client shutsdown cleanly on error instead of fatal error. 
+
+## Changed
+
+- If beacon node disconnects we can retry before failing.
```
Comment (rkapka) [inline changelog/james-prysm_safe-validator-shutdown.md]: But the current code already works like this

File: cmd/validator/flags/flags.go [hunk 5]
```diff
@@ -19,6 +19,8 @@ const (
 	WalletDefaultDirName = "prysm-wallet-v2"
 	// DefaultHTTPServerHost for the validator client.
 	DefaultHTTPServerHost = "127.0.0.1"
+
+	currentDefaultMaxHealthChecks = 60
```
Comment (rkapka) [inline cmd/validator/flags/flags.go]: Does `current` mean here "The value that we had before this PR"? If yes then it should be removed because the dev doesn't care that this is the same value as at some point in the past. Also, `current` means what we have now so all constants in the codebase are current :-)

Let's just call it `defaultMaxHealthChecks`

File: validator/client/runner.go [hunk 6]
```diff
@@ -52,10 +53,9 @@ func run(ctx context.Context, v iface.Validator) {
 	startCtx, startCancel := context.WithDeadline(ctx, startDeadline)
 	if err := v.UpdateDuties(startCtx); err != nil {
 		handleAssignmentError(err, headSlot)
+		// Don't return error here, just log it
```
Comment (rkapka) [inline validator/client/runner.go:54]: Is this comment meant to be for `handleAssignmentError(err, headSlot)`? If yes, then it's much more idiomatic to place it before the call.

File: validator/client/runner.go [hunk 7]
```diff
@@ -64,16 +64,37 @@ func run(ctx context.Context, v iface.Validator) {
...
 	for {
 		select {
 		case <-ctx.Done():
 			log.Info("Context canceled, stopping validator")
-			return // Exit if context is canceled.
+			return nil // Exit if context is canceled.
 		case slot := <-v.NextSlot():
 			if !healthTracker.IsHealthy(ctx) {
-				continue
+				return nil
```
Comment (rkapka) [inline validator/client/runner.go]: You replaced a `continue` with a `return`, this can't be right

File: validator/client/runner.go [hunk 8]
```diff
@@ -64,16 +64,37 @@ func run(ctx context.Context, v iface.Validator) {
...
+
+// run executes the main validator routine. This routine exits if the context is
+// canceled. It returns a channel that will be closed when the routine exits.
+//
+// Order of operations:
+// 1 - Wait for the next slot start
+// 2 - Update assignments if needed
+// 3 - Determine role at current slot
+// 4 - Perform assigned role, if any
+func (r *runner) run(ctx context.Context) error {
```
Comment (rkapka) [inline validator/client/runner.go]: This function returns `error` but you always return `nil`, so it should be just `func (r *runner) run(ctx context.Context)`

File: validator/client/runner.go [hunk 9]
```diff
@@ -310,39 +310,53 @@ func handleAssignmentError(err error, slot primitives.Slot) {
...
+			case <-ticker.C:
+
+				ishealthy := performHealthCheck()
+				if ishealthy {
+					healthCheckCounter = 0
+				} else {
+					healthCheckCounter++
+				}
+				if maxHealthChecks != -1 && healthCheckCounter >= maxHealthChecks {
+					log.Info("Health check timed out")
```
Comment (rkapka) [inline validator/client/runner.go]:
```suggestion
					log.Infof("Maximum health checks of %d reached. Stopping health check routine", maxHealthChecks)
```

File: validator/client/runner.go [hunk 10]
```diff
@@ -310,39 +310,53 @@ func handleAssignmentError(err error, slot primitives.Slot) {
...
+		// Continue periodic checks
+		for {
+			select {
+			case <-ticker.C:
+
+				ishealthy := performHealthCheck()
+				if ishealthy {
+					healthCheckCounter = 0
+				} else {
+					healthCheckCounter++
```
Comment (rkapka) [inline validator/client/runner.go]: I would say this is probably wrong because in my opinion `maxHealthChecks` should be tried for each node. So if there are 3 nodes, we should make e.g. 60 attempts _**per node**_, so 180 attempts in total.

File: validator/client/runner.go [hunk 11]
```diff
@@ -310,39 +310,53 @@ func handleAssignmentError(err error, slot primitives.Slot) {
...
+	ticker := time.NewTicker(interval)
 	tracker := v.HealthTracker()
 	go func() {
-		// trigger the healthcheck immediately the first time
-		for ; true; <-healthCheckTicker.C {
-			if ctx.Err() != nil {
-				log.WithError(ctx.Err()).Error("Context cancelled")
-				return
-			}
+		defer ticker.Stop()
```
Comment (rkapka) [inline validator/client/runner.go]: I think it would be cleaner to move this right after `ticker := time.NewTicker(interval)`

File: validator/client/service.go [hunk 12]
```diff
@@ -227,8 +233,47 @@ func (v *ValidatorService) Start() {
 		eventsChannel:                  make(chan *eventClient.Event, 1),
 	}
 
-	v.validator = valStruct
-	go run(v.ctx, v.validator)
+	healthTracker := v.validator.HealthTracker()
+	// Start the health check routine
+	go runHealthCheckRoutine(v.ctx, v.cancel, v.validator, v.MaxHealthChecks)
```
Comment (rkapka) [inline validator/client/service.go]:
```suggestion
	runHealthCheckRoutine(v.ctx, v.cancel, v.validator, v.MaxHealthChecks)
```
There is no point in using `go` here because `runHealthCheckRoutine` is non-blocking

File: validator/client/service.go [hunk 13]
```diff
@@ -55,12 +55,14 @@ type ValidatorService struct {
...
 	web3SignerConfig        *remoteweb3signer.SetupConfig
 	proposerSettings        *proposer.Settings
+	MaxHealthChecks         int
 	validatorsRegBatchSize  int
 	enableAPI               bool
 	emitAccountMetrics      bool
 	logValidatorPerformance bool
 	distributed             bool
 	disableDutiesPolling    bool
+	onRunnerExit            func() // validator client stop function is used here
```
Comment (rkapka) [inline validator/client/service.go]: Can you rename it to `close`? In the service it's used in 3 places and only one of them is when the run function exits

File: validator/client/service.go [hunk 14]
```diff
@@ -227,8 +233,47 @@ func (v *ValidatorService) Start() {
...
+			// This ensures these steps are retried if the runner restarts
+			runner, err := newRunner(runnerCtx, v.validator)
+			if err != nil {
+				log.WithError(err).Error("Could not create validator runner")
+				runnerCancel() // Ensure context is cancelled
+				v.onRunnerExit()
+				return
+			}
+
+			// Run the runner in a goroutine
```
Comment (rkapka) [inline validator/client/service.go]: It's not ran in a goroutine. Should it be?

File: validator/client/runner.go [hunk 15]
```diff
@@ -310,39 +310,53 @@ func handleAssignmentError(err error, slot primitives.Slot) {
...
+			select {
+			case <-ticker.C:
+
+				ishealthy := performHealthCheck()
+				if ishealthy {
+					healthCheckCounter = 0
+				} else {
+					healthCheckCounter++
+				}
+				if maxHealthChecks != -1 && healthCheckCounter >= maxHealthChecks {
```
Comment (rkapka) [inline validator/client/runner.go]:
```suggestion
				if maxHealthChecks != -1 && healthCheckCounter > maxHealthChecks {
```

File: validator/client/runner.go [hunk 16]
```diff
@@ -310,39 +310,53 @@ func handleAssignmentError(err error, slot primitives.Slot) {
...
+
+		// Initial check immediately
+		performHealthCheck()
+
+		healthCheckCounter := 0
+		// Continue periodic checks
+		for {
+			select {
+			case <-ticker.C:
+
```
Comment (rkapka) [inline validator/client/runner.go]:
```suggestion
```

File: validator/client/runner.go [hunk 17]
```diff
@@ -310,39 +310,53 @@ func handleAssignmentError(err error, slot primitives.Slot) {
...
+				ishealthy := performHealthCheck()
+				if ishealthy {
+					healthCheckCounter = 0
+				} else {
+					healthCheckCounter++
+				}
+				if maxHealthChecks != -1 && healthCheckCounter >= maxHealthChecks {
+					log.Info("Health check timed out")
+					cancel()
```
Comment (rkapka) [inline validator/client/runner.go]: What's the difference in the behavior of the validator client between `cancel` here and `onRunnerExit`?

File: validator/client/runner.go [hunk 18]
```diff
@@ -310,39 +310,53 @@ func handleAssignmentError(err error, slot primitives.Slot) {
...
+				}
+			case <-ctx.Done():
```
Comment (rkapka) [inline validator/client/runner.go]: We should log something here

File: validator/client/runner.go [hunk 19]
```diff
@@ -310,39 +310,53 @@ func handleAssignmentError(err error, slot primitives.Slot) {
...
-
-				slot, err := v.CanonicalHeadSlot(ctx)
-				if err != nil {
-					log.WithError(err).Error("Could not get canonical head slot")
-					return
-				}
-				if err := v.PushProposerSettings(ctx, slot, true); err != nil {
-					log.WithError(err).Warn("Failed to update proposer settings")
-				}
+				isHealthy = tracker.CheckHealth(ctx) // Re-check after host change
```
Comment (rkapka) [inline validator/client/runner.go]: I think this line is not needed. We perform check on node A, change the host to node B, the loop below calls this function again, we check node B.

File: changelog/james-prysm_safe-validator-shutdown.md (hunk 4 above)
Comment (james-prysm) [reply changelog/james-prysm_safe-validator-shutdown.md]: our retries go forever right now i believe

File: changelog/james-prysm_safe-validator-shutdown.md (hunk 2 above)
Comment (james-prysm) [reply changelog/james-prysm_safe-validator-shutdown.md]: will make this change

File: validator/client/runner.go (hunk 11 above)
Comment (james-prysm) [reply validator/client/runner.go]: i think that would just call stop right away beacuse after the goroutine is triggered it will call it exiting this function right

File: validator/client/runner.go (hunk 19 above)
Comment (james-prysm) [reply validator/client/runner.go]: it would need to wait for the next ticker, is that ok?

File: validator/client/service.go (hunk 14 above)
Comment (james-prysm) [reply validator/client/service.go]: old comment will remove, it doesn't have to be

File: validator/client/runner.go (hunk 17 above)
Comment (james-prysm) [reply validator/client/runner.go]: hmm I guess maybe I can switch to that and test it, this is the cancel context on the validator so it would cancel the outside contex and routine ( it's probably safer that way)

File: validator/client/runner.go (hunk 8 above)
Comment (james-prysm) [reply validator/client/runner.go]: that's a good point I thought there would be other errors let me see how i can clean this up for now

File: validator/client/runner.go (hunk 7 above)
Comment (james-prysm) [reply validator/client/runner.go]: we want to exit the run so that we can restart this process if it's unhealthy

File: validator/client/service.go (hunk 13 above)
Comment (james-prysm) [reply validator/client/service.go]: let me try, i thought maybe the names would be conflict but might be wrong here

File: validator/client/runner.go (hunk 10 above)
Comment (james-prysm) [reply validator/client/runner.go]: That's true but I think this is flawed to begin with how hosts move to the next one, currently it tries every host and then dies I think

File: api/client/beacon/health/health.go (hunk 1 above)
Comment (james-prysm) [reply api/client/beacon/health/health.go]: that makes it non blocking and more safe

File: validator/client/runner.go (hunk 10 above)
Comment (james-prysm) [reply validator/client/runner.go]: I think i'm wrong on this and that it wraps back

File: cmd/validator/flags/flags.go [hunk 20]
```diff
@@ -394,6 +396,13 @@ var (
 		Usage: "Disables polling of duties on dependent root changes.",
 		Value: false,
 	}
+
+	// MaxHealthChecksFlag sets a maximum amount of times to check for beacon node health before validator client times out and shuts down
+	MaxHealthChecksFlag = &cli.IntFlag{
+		Name:  "max-health-checks",
+		Usage: "Maximum number of health checks to perform before exiting if not healthy. Set to 0 or a negative number for indefinite checks.",
+		Value: DefaultMaxHealthChecks, // Default to current behavior
```
Comment (rkapka) [inline cmd/validator/flags/flags.go]:
```suggestion
		Value: DefaultMaxHealthChecks,
```

File: validator/client/service.go [hunk 21]
```diff
@@ -227,8 +233,38 @@ func (v *ValidatorService) Start() {
 		eventsChannel:                  make(chan *eventClient.Event, 1),
 	}
 
-	v.validator = valStruct
-	go run(v.ctx, v.validator)
+	healthTracker := v.validator.HealthTracker()
+	// Start the health check routine
+	runHealthCheckRoutine(v.ctx, v.cancel, v.validator, v.MaxHealthChecks)
+
+	for {
```
Comment (rkapka) [inline validator/client/service.go:240]: Note for self
> Review contexts

**Review by rkapka — DISMISSED** [review]

File: validator/client/health_monitor.go [hunk 22]
```diff
@@ -0,0 +1,123 @@
...
+}
+
+func (m *healthMonitor) performHealthCheck() {
+	m.Lock()
+	defer m.Unlock()
+
+	ishealthy := m.v.FindHealthyHost(m.ctx)
+	if ishealthy {
+		m.fails = 0
+	} else {
```
Comment (rkapka) [inline validator/client/health_monitor.go]:
```suggestion
	} else if m.maxFails > 0 {
```

File: validator/client/health_monitor.go [hunk 23]
```diff
@@ -0,0 +1,123 @@
...
+		}
+	}
+}
+
+// Start launches the monitor loop (non-blocking).
+func (m *healthMonitor) Start() {
+	go m.loop()
+}
+
+// Stop terminates the monitor and closes its channel.
```
Comment (rkapka) [inline validator/client/health_monitor.go:101]: You forgot to close the channel

File: validator/client/runner.go [hunk 24]
```diff
@@ -203,13 +203,11 @@ func initializeValidatorAndGetHeadSlot(ctx context.Context, v iface.Validator) (
 				continue
 			}
 
-			log.WithError(err).Fatal("Could not determine if beacon chain started")
+			return 0, errors.Wrap(err, "Could not determine if beacon chain started")
```
Comment (rkapka) [inline validator/client/runner.go]: All errors in this function should be lowercase

File: validator/client/service.go [hunk 25]
```diff
@@ -69,6 +71,7 @@ type Config struct {
 	DB                      db.Database
 	Wallet                  *wallet.Wallet
 	WalletInitializedFeed   *event.Feed
+	MaxHealthChecks         int
```
Comment (rkapka) [inline validator/client/service.go:74]: I think this can be private

File: validator/client/validator.go [hunk 26]
```diff
@@ -1242,23 +1241,39 @@ func (v *validator) EventStreamIsRunning() bool {
...
-func (v *validator) HealthTracker() health.Tracker {
-	return v.nodeClient.HealthTracker()
-}
-
 func (v *validator) Host() string {
 	return v.validatorClient.Host()
 }
 
-func (v *validator) ChangeHost() {
+func (v *validator) ChangeHost() bool {
```
Comment (rkapka) [inline validator/client/validator.go]: This function doesn't need to be exported. Also there is no point in returning anything from this function because `FindHealthyHost` can do the `== 1` check.

```
func (v *validator) changeHost() {
    next := (v.currentHostIndex + 1) % uint64(len(v.beaconNodeHosts))
	log.Infof("Beacon node at %s is not responding, switching to %s...", v.beaconNodeHosts[v.currentHostIndex], v.beaconNodeHosts[next])
	v.validatorClient.SetHost(v.beaconNodeHosts[next])
	v.currentHostIndex = next
}

func (v *validator) FindHealthyHost(ctx context.Context) bool {
    // Tail-recursive closure keeps retry count private.
	var check func(remaining int) bool
	check = func(remaining int) bool {
		if v.nodeClient.IsHealthy(ctx) { // healthy → done
			return true
		}
        if len(v.beaconNodeHosts) == 1 {
            return false
        }
		if remaining == 0 || !features.Get().EnableBeaconRESTApi {
            return false // exhausted or REST disabled
		}
		v.changeHost()
		return check(remaining - 1) // recurse
	}

	return check(len(v.beaconNodeHosts))
}
```

File: validator/client/validator.go [hunk 27]
```diff
@@ -1242,23 +1241,39 @@ func (v *validator) EventStreamIsRunning() bool {
...
+	// Tail-recursive closure keeps retry count private.
+	var check func(remaining int) bool
+	check = func(remaining int) bool {
+		if v.nodeClient.IsHealthy(ctx) { // healthy → done
+			return true
+		}
+		if remaining == 0 || !features.Get().EnableBeaconRESTApi {
+			return false // exhausted or REST disabled
+		}
+		if !v.ChangeHost() { // no switch possible
```
Comment (rkapka) [inline validator/client/validator.go]: I don't understand this comment - was it generated?

File: validator/client/health_monitor.go [hunk 28]
```diff
@@ -0,0 +1,123 @@
...
+) *healthMonitor {
+	m := &healthMonitor{
+		ctx:       parentCtx,
+		cancel:    parentCancel,
+		maxFails:  maxFails,
+		v:         v,
+		healthyCh: make(chan bool, 1),
+	}
+
+	// Prime channel with the current status so consumers have an initial value.
```
Comment (rkapka) [inline validator/client/health_monitor.go]: Why is it important that there is an initial value?

File: validator/client/validator.go [hunk 29]
```diff
@@ -1242,23 +1241,39 @@ func (v *validator) EventStreamIsRunning() bool {
...
+}
+
+func (v *validator) FindHealthyHost(ctx context.Context) bool {
+	// Tail-recursive closure keeps retry count private.
+	var check func(remaining int) bool
+	check = func(remaining int) bool {
+		if v.nodeClient.IsHealthy(ctx) { // healthy → done
+			return true
+		}
+		if remaining == 0 || !features.Get().EnableBeaconRESTApi {
```
Comment (rkapka) [inline validator/client/validator.go:1273]: Doesn't this mean that with grpc the health check will always fail?

File: validator/client/service.go [hunk 30]
```diff
@@ -227,8 +233,42 @@ func (v *ValidatorService) Start() {
...
+				log.Warn("Validator service health check failed, waiting for healthy beacon node...")
+				continue
+			}
+			// Reconnect event stream if needed
+			if !v.validator.EventStreamIsRunning() {
+				go v.validator.StartEventStream(v.ctx, eventClient.DefaultEventTopics)
+			}
+
+			log.Info("Starting validator runner")
+			runnerCtx, runnerCancel := context.WithCancel(v.ctx)
```
Comment (rkapka) [inline validator/client/service.go:253]: Is it necessary to call `runnerCancel()` before `v.closeClientFunc()`? Because if not, then you can remove calls to `runnerCancel()` and write this:
```suggestion
			runnerCtx, runnerCancel := context.WithCancel(v.ctx)
			defer runnerCancel()
```

File: validator/client/validator.go (hunk 27 above)
Comment (james-prysm) [reply validator/client/validator.go]: You can't switch the host if it's grpc

File: validator/client/health_monitor.go (hunk 28 above)
Comment (james-prysm) [reply validator/client/health_monitor.go]: The runner loop needs it now that the channel is healthy to run

File: validator/client/validator.go (hunk 29 above)
Comment (james-prysm) [reply validator/client/validator.go:1273]: This line will , but check the above it's checking the health for grpc and rest and if its returns true then its healthy

File: validator/client/service.go (hunk 30 above)
Comment (james-prysm) [reply validator/client/service.go:253]: we should close the entire run if the runner fails on the health loop

File: validator/client/health_monitor.go (hunk 22 above)
Comment (james-prysm) [reply validator/client/health_monitor.go]: actually i should combine it with the bottom one too

File: validator/client/health_monitor.go (hunk 23 above)
Comment (james-prysm) [reply validator/client/health_monitor.go:101]: it cancels the parent context so that cleans up the channel via garbage collection without closing the channel explicitly i think

Comment (rkapka) [reply validator/client/health_monitor.go:101]: > i think

:smile: 

Can you verify that it is indeed the case?

File: validator/client/validator.go [hunk 31]
```diff
@@ -1242,25 +1241,41 @@ func (v *validator) EventStreamIsRunning() bool {
...
-	if len(v.beaconNodeHosts) == 1 {
-		log.Infof("Beacon node at %s is not responding, no backup node configured", v.Host())
-		return
-	}
 	next := (v.currentHostIndex + 1) % uint64(len(v.beaconNodeHosts))
-	log.Infof("Beacon node at %s is not responding, switching to %s...", v.beaconNodeHosts[v.currentHostIndex], v.beaconNodeHosts[next])
+	log.WithFields(logrus.Fields{
+		"current_host": v.beaconNodeHosts[v.currentHostIndex],
+		"next_host":    v.beaconNodeHosts[next],
+	}).Warn("Beacon node is not responding, switching to host")
```
Comment (rkapka) [inline validator/client/validator.go]:
```suggestion
	}).Warn("Beacon node is not responding, switching host")
```
nitpick

File: validator/client/validator.go [hunk 32]
```diff
@@ -1242,25 +1241,41 @@ func (v *validator) EventStreamIsRunning() bool {
...
 func (v *validator) ChangeHost() {
-	if len(v.beaconNodeHosts) == 1 {
-		log.Infof("Beacon node at %s is not responding, no backup node configured", v.Host())
-		return
-	}
 	next := (v.currentHostIndex + 1) % uint64(len(v.beaconNodeHosts))
-	log.Infof("Beacon node at %s is not responding, switching to %s...", v.beaconNodeHosts[v.currentHostIndex], v.beaconNodeHosts[next])
+	log.WithFields(logrus.Fields{
+		"current_host": v.beaconNodeHosts[v.currentHostIndex],
+		"next_host":    v.beaconNodeHosts[next],
```
Comment (rkapka) [inline validator/client/validator.go]:
```suggestion
		"currentHost": v.beaconNodeHosts[v.currentHostIndex],
		"nextHost":    v.beaconNodeHosts[next],
```
We use camel case everywhere else for log fields

File: validator/client/validator.go [hunk 33]
```diff
@@ -1242,25 +1241,41 @@ func (v *validator) EventStreamIsRunning() bool {
...
 
-func (v *validator) HealthTracker() health.Tracker {
-	return v.nodeClient.HealthTracker()
-}
-
 func (v *validator) Host() string {
 	return v.validatorClient.Host()
 }
 
 func (v *validator) ChangeHost() {
```
Comment (rkapka) [inline validator/client/validator.go]: This can be private and removed from the interface because it's not used anywhere outside of this package

File: validator/client/health_monitor.go [hunk 34]
```diff
@@ -0,0 +1,122 @@
...
+	default:
+		// Channel full, drain and send
+		<-m.healthyCh
+		m.healthyCh <- ishealthy
+	}
+}
+
+func (m *healthMonitor) loop() {
+	log.Info("Starting health check routine for beacon node apis")
+	// just check one a slot
```
Comment (rkapka) [inline validator/client/health_monitor.go]:
```suggestion
	// just check once a slot
```
nitpick

File: validator/client/health_monitor.go (hunk 28 above)
Comment (rkapka) [reply validator/client/health_monitor.go]: In the `loop` function you have
```
// Initial check immediately
m.performHealthCheck()
```
which should take care of setting the initial value. I have a feeling that this code here is redundant

File: validator/client/health_monitor.go [hunk 35]
```diff
@@ -0,0 +1,122 @@
...
+	if ishealthy {
+		m.fails = 0
+	} else if m.maxFails > 0 && m.fails < m.maxFails {
+		log.WithFields(logrus.Fields{
+			"fails":    m.fails,
+			"maxFails": m.maxFails,
+		}).Debug("Failed health check, beacon node is unresponsive")
+		m.fails++
+	} else if m.maxFails > 0 && m.fails >= m.maxFails {
+		log.WithField("max_fails", m.maxFails).Debug("Maximum health checksreached. Stopping health check routine")
```
Comment (rkapka) [inline validator/client/health_monitor.go]:
```suggestion
		log.WithField("maxFails", m.maxFails).Debug("Maximum health checks reached. Stopping health check routine")
```

File: validator/client/service.go [hunk 36]
```diff
@@ -227,8 +233,42 @@ func (v *ValidatorService) Start() {
...
+		case isHealthy := <-hm.HealthyChan():
+			if !isHealthy {
+				// wait until the next health tracker update
+				log.Warn("Validator service health check failed, waiting for healthy beacon node...")
+				continue
+			}
+			// Reconnect event stream if needed
+			if !v.validator.EventStreamIsRunning() {
+				go v.validator.StartEventStream(v.ctx, eventClient.DefaultEventTopics)
+			}
```
Comment (rkapka) [inline validator/client/service.go]: I wonder about this part... Shouldn't we just stop the event stream when `run` is finished and start it again every time here?

File: validator/client/service.go (hunk 30 above)
Comment (rkapka) [reply validator/client/service.go:253]: OK but why call `runnerCancel` twice manually inside this function instead of using `defer`?

File: validator/client/health_monitor.go [hunk 37]
```diff
@@ -0,0 +1,122 @@
...
+	case m.healthyCh <- ishealthy:
+	default:
+		// Channel full, drain and send
+		<-m.healthyCh
+		m.healthyCh <- ishealthy
+	}
+}
+
+func (m *healthMonitor) loop() {
+	log.Info("Starting health check routine for beacon node apis")
```
Comment (rkapka) [inline validator/client/health_monitor.go]:
```suggestion
	log.Debug("Starting health check routine for beacon node apis")
```
because all other logs in the monitor are debug level

File: validator/client/validator.go [hunk 38]
```diff
@@ -1242,25 +1241,41 @@ func (v *validator) EventStreamIsRunning() bool {
...
 
+func (v *validator) FindHealthyHost(ctx context.Context) bool {
+	// Tail-recursive closure keeps retry count private.
+	var check func(remaining int) bool
+	check = func(remaining int) bool {
+		if v.nodeClient.IsHealthy(ctx) { // healthy → done
+			return true
+		}
+		if len(v.beaconNodeHosts) == 1 {
+			log.WithField("host", v.Host()).Debug("Beacon node is not responding, no backup node configured")
```
Comment (rkapka) [inline validator/client/validator.go]:
```suggestion
			log.WithField("host", v.Host()).Info("Beacon node is not responding, no backup node configured")
```
because the switching log above is info level

File: validator/client/service.go (hunk 36 above)
Comment (james-prysm) [reply validator/client/service.go]: let me check on this

File: validator/client/health_monitor.go (hunk 28 above)
Comment (james-prysm) [reply validator/client/health_monitor.go]: good point let me retry this I moved this over but thought i should set it up in the initialization let me try

File: validator/client/service.go (hunk 30 above)
Comment (james-prysm) [reply validator/client/service.go:253]: because we don't exit the loop, the defer i believe triggers at the function level so when Start() completes

File: validator/client/service.go (hunk 36 above)
Comment (james-prysm) [reply validator/client/service.go]: updated this

File: validator/client/health_monitor.go (hunk 23 above)
Comment (james-prysm) [reply validator/client/health_monitor.go:101]: it does cancel it

Comment (james-prysm) [reply validator/client/health_monitor.go:101]: for our case I think it's fine
> It's only necessary to close a channel when it is important to tell the receiving goroutines that all data has been sent. A channel that the garbage collector determines to be unreachable will have its resources reclaimed, whether or not it is closed.

File: validator/client/service.go [hunk 39]
```diff
@@ -272,9 +272,6 @@ func (v *ValidatorService) Start() {
 func (v *ValidatorService) Stop() error {
 	v.cancel()
 	log.Info("Stopping service")
-	if v.conn != nil {
```
Comment (james-prysm) [inline validator/client/service.go:238]: we don't need this, the connection uses the parent concext that is canceled

File: validator/client/validator.go [hunk 40]
```diff
@@ -1266,8 +1266,8 @@ func (v *validator) FindHealthyHost(ctx context.Context) bool {
 		if v.nodeClient.IsHealthy(ctx) { // healthy → done
 			return true
 		}
-		if len(v.beaconNodeHosts) == 1 {
-			log.WithField("host", v.Host()).Info("Beacon node is not responding, no backup node configured")
+		if len(v.beaconNodeHosts) == 1 && features.Get().EnableBeaconRESTApi {
```
Comment (james-prysm) [inline validator/client/validator.go:1269]: I was wrong in the assumption that gRPC doesn't have node hosts  i guess it's still populated because we can have both, so i will only display this log if it's for beacon rest

File: validator/node/node.go [hunk 41]
```diff
@@ -161,13 +162,15 @@ func (c *ValidatorClient) Start() {
...
 // Close handles graceful shutdown of the system.
 func (c *ValidatorClient) Close() {
-	c.lock.Lock()
-	defer c.lock.Unlock()
-
-	c.services.StopAll()
-	log.Info("Stopping Prysm validator")
-	c.cancel()
-	close(c.stop)
+	c.once.Do(func() { // runs exactly one time
```
Comment (james-prysm) [inline validator/node/node.go:165]: I was running into some panic issues cancelling the validator run manually, if close is caleld we should only do it once, we don't need to close it multiple times

File: validator/client/health_monitor.go [hunk 42]
```diff
@@ -0,0 +1,105 @@
...
+}
+
+// Start launches the monitor loop (non-blocking).
+func (m *healthMonitor) Start() {
+	go m.loop()
+}
+
+// Stop terminates the monitor and closes its channel.
+func (m *healthMonitor) Stop() {
+	m.cancel()
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply validator/client/health_monitor.go:103]: it's ok because the parenet context is canceled

File: validator/client/validator.go (hunk 40 above)
Comment (rkapka) [reply validator/client/validator.go:1269]: But why display it only for REST? Doesn't the log make sense for grpc too?

**Review by rkapka — DISMISSED** [review]

File: validator/client/runner_test.go [hunk 43]
```diff
@@ -606,5 +564,7 @@ func TestRunnerPushesProposerSettings_ValidContext(t *testing.T) {
 		submittedAggregates:            make(map[submittedAttKey]*submittedAtt),
 	}
 
-	run(timedCtx, v)
+	go runTest(t, timedCtx, v)
+	// Wait a bit for the runner to process slots and submit validator registrations
+	time.Sleep(2 * time.Second)
```
Comment (prestonvanloon) [inline validator/client/runner_test.go]: Is there any other way to wait until assertions have completed? Using time.Sleep is very likely to cause flaky tests.

File: cmd/validator/flags/flags.go [hunk 44]
```diff
@@ -19,6 +19,8 @@ const (
 	WalletDefaultDirName = "prysm-wallet-v2"
 	// DefaultHTTPServerHost for the validator client.
 	DefaultHTTPServerHost = "127.0.0.1"
+
+	DefaultMaxHealthChecks = 60
```
Comment (prestonvanloon) [inline cmd/validator/flags/flags.go]:
```suggestion
	DefaultMaxHealthChecks = 0
```

I have issue with this. The default should match the existing behavior which was 0.

With a default of 60, there is new behavior where validators were voluntarily shut down rather than report unhealthy (infra should restart unhealthy nodes according to infra operators' configuration)

**Review by prestonvanloon — CHANGES_REQUESTED** [review]

File: cmd/validator/flags/flags.go (hunk 44 above)
Comment (james-prysm) [reply cmd/validator/flags/flags.go]: Ok I am fine with that

File: changelog/james-prysm_safe-validator-shutdown.md [hunk 45]
```diff
@@ -0,0 +1,11 @@
...
+
+- Added `max-health-checks` flag that sets the maximum times the validator tries to check the health of the beacon node before timing out. 0 or a negative number is indefinite.
+
+## Fixed
+
+- Validator client shuts down cleanly on error instead of fatal error. 
+
+## Changed
+
+- If beacon node disconnects can now time out on retries
```
Comment (prestonvanloon) [inline changelog/james-prysm_safe-validator-shutdown.md]: Incomplete sentence

File: validator/client/runner_test.go (hunk 43 above)
Comment (james-prysm) [reply validator/client/runner_test.go]: i don't actually remember why i added this, I think i can revert to runTest and it should work as before ( runs for a minute though it's your test) I think i might have changed this test before more refactors. thanks for catching

File: changelog/james-prysm_safe-validator-shutdown.md (hunk 45 above)
Comment (james-prysm) [reply changelog/james-prysm_safe-validator-shutdown.md]: i should remove this since we changed the default to 0

**Review by prestonvanloon — APPROVED** [review]
