### PR TITLE
Use Connection Gater to Manage Peer Connections

### LINKED ISSUE #6229: P2P Peer Limits Not Respected
# 🐞 Bug Report

### Description

When running Prysm on Alpha.10 with default flags, my beacon node was observing 100+ peers. The default flag is to allow only 30 peers.

https://github.com/prysmaticlabs/prysm/blob/c725a9c8f24e442751848233b825d8cb090a3fde/shared/cmd/flags.go#L121-L126 

### Has this worked before in a previous version?

This worked in Alpha.9 and in Topaz testnet.

## 🔬 Minimal Reproduction

Run a node with default flags.

## 🔥 Error

N/A

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>Linux AMD64</code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>v1.0.0-alpha.10</code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Feature Improvement 

**What does this PR do? Why is it needed?**

This uses a connection gater instead of a connection manager. Unfortunately connection manager
still has been ineffective leading to a very high amount of peer churn without any eventual stable network backbone being created. This replaces it with a connection gater, which allows us to have a more granular control over the network. We are able to intercept incoming dials and prevent external peers from dialing us if we are overwhelmed.

**Which issues(s) does this PR fix?**

Fixes #6229 and follows up from #6184 .

**Other notes for review**

### CODE REVIEW

File: beacon-chain/p2p/testing/p2p.go [hunk 1]
```diff
@@ -9,6 +9,9 @@ import (
 	"testing"
 	"time"
 
+	"github.com/libp2p/go-libp2p-core/control"
+	"github.com/multiformats/go-multiaddr"
+
```
Comment (nisdas) [inline beacon-chain/p2p/testing/p2p.go:14]:
```suggestion
```

**Comment by nisdas** [comment]
Yeap, definetly. Using this we can also fix peer allow lists, which currently do not work. I will add these both in the follow up PR.
