### PR TITLE
QSP-9 Prevent Casting to Int if Possible

### LINKED ISSUE #6049: Potential integer overflow cases
# 🐞 Bug Report

### Description

 Following issue #6038, other places in code are also subject to integer overflow. 

Quantstamp reported:

> Some [potential] integer overflow cases:
(1) beacon-chain/rpc/validator/proposer.go: On L324, `BeaconConfig().MaxDeposits` is a `uint64`, but it is casted to `int`; (2) beacon-chain/rpc/validator/proposer.go (L296), beacon-chain/core/state/state.go (L81, L86),  beacon-chain/powchain/service.go (L175): `BeaconConfig().DepositContractTreeDepth` is a `uint64`, but it is casted to int in code; (3) beacon-chain/rpc/beacon/validators.go: On L84, L98, L228, L242, index is uint64, but it is casted to int

## 🔥 Error

Possible overflow.

### PR DESCRIPTION
**Pull request by rauljordan**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

QSP-9 of the Quantstamp audit found many places where we downcast uint64s to int values and could cause catastrophic consequences at launch. This PR fixes all dangerous instances of this.

**Which issues(s) does this PR fix?**

Fixes #6049 and is part of #6327

### CODE REVIEW

File: beacon-chain/db/kv/state.go [hunk 1]
```diff
@@ -3,16 +3,16 @@ package kv
 import (
 	"bytes"
 	"context"
-	"math"
 
 	"github.com/pkg/errors"
 	ethpb "github.com/prysmaticlabs/ethereumapis/eth/v1alpha1"
+	bolt "go.etcd.io/bbolt"
+	"go.opencensus.io/trace"
+
```
Comment (rauljordan) [inline beacon-chain/db/kv/state.go:11]:
```suggestion
```

File: beacon-chain/db/kv/blocks.go [hunk 2]
```diff
@@ -4,22 +4,22 @@ import (
...
 	"strconv"
 
 	"github.com/prysmaticlabs/prysm/beacon-chain/state/stateutil"
 
 	"github.com/pkg/errors"
 	ethpb "github.com/prysmaticlabs/ethereumapis/eth/v1alpha1"
+	log "github.com/sirupsen/logrus"
+	bolt "go.etcd.io/bbolt"
+	"go.opencensus.io/trace"
+
```
Comment (rauljordan) [inline beacon-chain/db/kv/blocks.go:16]:
```suggestion
```
