### PR TITLE
Fix default mainnet log when using chain config

### LINKED ISSUE #10821: Prysm Incorrectly Reports `Running on Ethereum Consensus Mainnet`
If you run on ropsten by using `--chain-config-file` and `--genesis-state` instead of `--ropsten`, it says `Running on Ethereum Consensus Mainnet`.

### PR DESCRIPTION
**Pull request by saolyn**
Add a log to specify the use of a chain-config-file rather than
defaulting to that of mainnet.
Related to #10821.

**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

When passing a config with the `chain-config-file` flag and not passing a network flag, the default log was "Running on Ethereum Consensus Mainnet" despite another network name being set in the config file eg: "ropsten".

This PR adds a new log message "Running on Ethereum network with chainconfig" if a `chain-config-file` has been set, otherwise defaults to mainnet.

**Which issues(s) does this PR fix?**

Fixes #10821.

**Other notes for review**

### CODE REVIEW

File: config/features/config.go [hunk 1]
```diff
@@ -130,7 +131,11 @@ func configureTestnet(ctx *cli.Context) error {
 		}
 		params.UseRopstenNetworkConfig()
 	} else {
-		log.Warn("Running on Ethereum Consensus Mainnet")
+		if ctx.IsSet(cmd.ChainConfigFileFlag.Name) {
+			log.Warn("Running on Ethereum network with chainconfig")
```
Comment (rauljordan) [inline config/features/config.go:135]: Is there a way we can figure out which network it is from the yaml file itself? If not then maybe we can say "Running on custom Ethereum network specified in a chain configuration yaml file"

Comment (saolyn) [reply config/features/config.go:135]: The `chain-config-file` is unmarshalled after this code is called. 
Therefore we cannot get the value at this point and only have the default  `mainnet` that may not match the config value.

A way around this would be to reorganize the code below to load the file before or log after. https://github.com/prysmaticlabs/prysm/blob/fce9e6883db7e5452b1469db714f73ea4b5eccab/beacon-chain/node/node.go#L123-L130

Comment (rauljordan) [reply config/features/config.go:135]: That might be a more invasive change that could break stuff. I would recommend going with your approach and saying something like "Running on custom Ethereum network specified in a chain configuration yaml file"

**Review by rauljordan — APPROVED** [review]

File: config/features/config.go (hunk 1 above)
Comment (saolyn) [reply config/features/config.go]: done!
