### PR TITLE
Validator REST api: adding in check for empty keys changed

### LINKED ISSUE #14636: Validator panics when adding keys to remote signer file
### Describe the bug

The validator panics when adding keys to remote signer file.

### Has this worked before in a previous version?

_No response_

### 🔬 Minimal Reproduction

1. Start with remote signer file
2. Add validator keys to  external_keys.txt
3. It throws this sometimes

### Error

```text
time="2024-11-11 23:37:23" level=info msg="Successfully initialized file watcher" path="/data/external_keys.txt" prefix=remote-keymanager
time="2024-11-11 23:37:23" level=info msg="Remote signer key file updated" prefix=remote-keymanager
time="2024-11-11 23:37:23" level=info msg="Remote signer key file updated" prefix=remote-keymanager
panic: runtime error: index out of range [0] with length 0

goroutine 52 [running]:
github.com/prysmaticlabs/prysm/v5/validator/client/beacon-api.(*beaconApiValidatorClient).validatorsStatusResponse(0xc00043c000, {0x1ae6c70, 0xc0006914a0}, {0x4410340, 0x0, 0xc000508001?}, {0x4410340, 0x0, 0x0})
        validator/client/beacon-api/status.go:104 +0xe6d
github.com/prysmaticlabs/prysm/v5/validator/client/beacon-api.(*beaconApiValidatorClient).multipleValidatorStatus(0xc00043c000, {0x1ae6c70, 0xc0006914a0}, 0xc000753260)
        validator/client/beacon-api/status.go:35 +0xbf
github.com/prysmaticlabs/prysm/v5/validator/client/beacon-api.(*beaconApiValidatorClient).MultipleValidatorStatus.func1()
        validator/client/beacon-api/beacon_api_validator_client.go:135 +0x25
github.com/prysmaticlabs/prysm/v5/validator/client/beacon-api.wrapInMetrics[...]({0x1523119?, 0x17}, 0xc0005dadc0)
        validator/client/beacon-api/beacon_api_validator_client.go:312 +0x53
github.com/prysmaticlabs/prysm/v5/validator/client/beacon-api.(*beaconApiValidatorClient).MultipleValidatorStatus(0xc00043c000, {0x1ae6c70?, 0xc0006914a0?}, 0xc000753260)
        validator/client/beacon-api/beacon_api_validator_client.go:134 +0x11b
github.com/prysmaticlabs/prysm/v5/validator/client.(*validator).updateValidatorStatusCache(0xc0001b0fc8, {0x1ae6c70, 0xc0006914a0}, {0x4410340?, 0x0?, 0xc0dbc327b0?})
        validator/client/validator.go:1250 +0x209
github.com/prysmaticlabs/prysm/v5/validator/client.(*validator).HandleKeyReload(0xc0001b0fc8, {0x1ae6c70?, 0xc0006914a0?}, {0x4410340, 0x0, 0x0})
        validator/client/key_reload.go:19 +0x108
github.com/prysmaticlabs/prysm/v5/validator/client.onAccountsChanged({0x1ae6c70, 0xc0006914a0}, {0x1b0c130, 0xc0001b0fc8}, {0x4410340?, 0x2d1801?, 0xc0dfeee9c0?}, 0xc000988960)
        validator/client/runner.go:140 +0x6b
github.com/prysmaticlabs/prysm/v5/validator/client.run({0x1ae6c70, 0xc0006914a0}, {0x1b0c130, 0xc0001b0fc8})
        validator/client/runner.go:134 +0x1265
created by github.com/prysmaticlabs/prysm/v5/validator/client.(*ValidatorService).Start in goroutine 316
        validator/client/service.go:221 +0xd0b
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

5.1.2 current docker stable

### Anything else relevant (validator index / public key)?

_No response_

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

 Bug fix

**What does this PR do? Why is it needed?**

validator REST mode did not handle cases where the validator checks for validator status after removing all keys. This PR handles the panic presented when the endpoint is called but no keys are provided.

**Which issues(s) does this PR fix?**

Fixes #14636

**Other notes for review**

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have made an appropriate entry to [CHANGELOG.md](https://github.com/prysmaticlabs/prysm/blob/develop/CHANGELOG.md).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

File: validator/client/beacon-api/status.go [hunk 1]
```diff
@@ -50,6 +50,10 @@ func (c *beaconApiValidatorClient) validatorsStatusResponse(ctx context.Context,
 	[]*ethpb.ValidatorStatusResponse,
 	error,
 ) {
+	// if no parameters are provided we should just return an empty response
+	if len(inPubKeys) == 0 && len(inIndexes) == 0 {
+		return make([][]byte, 0), make([]primitives.ValidatorIndex, 0), make([]*ethpb.ValidatorStatusResponse, 0), nil
```
Comment (kasey) [inline validator/client/beacon-api/status.go:55]: a little more compact:
```
return [][]byte{}, []primitives.ValidatorIndex{}, []*ethpb.ValidatorStatusResponse{}, nil
```

File: validator/client/validator.go [hunk 2]
```diff
@@ -1224,6 +1224,10 @@ func (v *validator) filterAndCacheActiveKeys(ctx context.Context, pubkeys [][fie
 
 // updateValidatorStatusCache updates the validator statuses cache, a map of keys currently used by the validator client
 func (v *validator) updateValidatorStatusCache(ctx context.Context, pubkeys [][fieldparams.BLSPubkeyLength]byte) error {
+	if len(pubkeys) == 0 {
+		v.pubkeyToStatus = make(map[[fieldparams.BLSPubkeyLength]byte]*validatorStatus, 0)
```
Comment (kasey) [inline validator/client/validator.go:1228]: This looks like it could overwrite an existing cache? I'm not sure why we would need to do this here.

Comment (james-prysm) [reply validator/client/validator.go:1228]: It's the validators statuses cache, it's used to track what validators are available and their statuses on the validator client. In this case if it's updated to nil or no keys we should override it. Typically this is handled as the api endpoint would return no statuses and it would be overridden below but the validator rest implementation of this didn't handle 0 keys correctly.

File: CHANGELOG.md [hunk 3]
```diff
@@ -79,7 +79,7 @@ The format is based on Keep a Changelog, and this project adheres to Semantic Ve
 - Small log imporvement, removing some redundant or duplicate logs
 - EIP7521 - Fixes withdrawal bug by accounting for pending partial withdrawals and deducting already withdrawn amounts from the sweep balance. [PR](https://github.com/prysmaticlabs/prysm/pull/14578)
 - unskip electra merkle spec test
-
+- Fix panic in validator REST mode when updating status to all keys removed
```
Comment (saolyn) [inline CHANGELOG.md:82]: Nit
```suggestion
- Fix panic in validator REST mode when checking status after removing all keys
```

**Review by kasey — APPROVED** [review]
