### PR TITLE
Keymanager-Kind: fix cli kind parsing and allow for backward compatability

### LINKED ISSUE #10181: `validator wallet create` does not recognize `imported`
# 🐞 Bug Report

### Description

When running `validator --datadir /var/lib/prysm wallet create --wallet-dir /var/lib/prysm --keymanager-kind imported --accept-terms-of-use --wallet-password-file /var/lib/prysm/password.txt`, the following errors are logged:

```
[2022-02-03 12:20:49]  WARN flags: Running on Ethereum Consensus Mainnet
[2022-02-03 12:20:49] FATAL wallet: Could not create a wallet: imported is not an allowed keymanager
```

The usage for the command shows:

```
NAME:
   validator wallet create - creates a new wallet with a desired type of keymanager: either on-disk (imported), derived, or using remote credentials

USAGE:
   validator wallet create [command options] [arguments...]

OPTIONS:
   --wallet-dir value                     Path to a wallet directory on-disk for Prysm validator accounts (default: "/nonexistent/.eth2validators/prysm-wallet-v2")
   --keymanager-kind value                Kind of keymanager, either imported, derived, or remote, specified during wallet creation
```

I'd expect `keymanager-kind` to either accept `imported` or the usage text to be changed.

### Has this worked before in a previous version?

Unknown

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
validator version Prysm/v2.0.6/e26cde5e091befe0c777992734c37e7a1e6c53c2. Built at: 2022-01-25 21:30:35+00:00
  </code>
</pre>

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

> Uncomment one line below and remove others.

Bug fix

**What does this PR do? Why is it needed?**

for the longest time, the wallet creation keymanager kind didn't match the type internally. introducing a fix to provide more flexibility while having backward compatibility for this keymanager kind check. users will be able to use the wallet creation more easily.

**Which issues(s) does this PR fix?**

Fixes #10181

### CODE REVIEW

File: validator/keymanager/types.go [hunk 1]
```diff
@@ -85,7 +86,7 @@ func (k Kind) String() string {
 	case Derived:
 		return "derived"
 	case Local:
-		return "direct"
+		return "local"
```
Comment (rauljordan) [inline validator/keymanager/types.go:89]: We need to support direct, as the majority of Prysm users still have this. The goal is that we support direct, local, and imported, as the same thing...Im not 100% sure how changing this line of code will affect existing validators. Need to think about this more

Comment (james-prysm) [reply validator/keymanager/types.go:89]: I will revert and leave a comment regarding this.

**Review by rauljordan — APPROVED** [review]
