### PR TITLE
Fix Interop Mode

### LINKED ISSUE #7673: Interop testnet's beacon node can't find peers in beta.0
# 🐞 Bug Report

### Description

 Running the interop testnet produces the following beacon node error:
```
ERROR p2p: Failed to find peers error=failed to find peers for subnet
github.com/prysmaticlabs/prysm/beacon-chain/p2p.(*Service).broadcastAttestation.func1
    beacon-chain/p2p/broadcaster.go:105
github.com/prysmaticlabs/prysm/beacon-chain/p2p.(*Service).broadcastAttestation
    beacon-chain/p2p/broadcaster.go:106
runtime.goexit
    GOROOT/src/runtime/asm_amd64.s:1373
```

Validator also reports errors:
```
ERROR validator: Failed to propose block error=rpc error: code = DeadlineExceeded desc = context deadline exceeded pubKey=0xa90dfa8114a0
ERROR validator: Could not submit signed aggregate and proof to beacon node: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

### Has this worked before in a previous version?

It works fine in `beta.0.rc`

## 🔬 Minimal Reproduction
Terminal 1
```
bazel run //tools/genesis-state-gen -- --num-validators=1000 --output-ssz=/tmp/genesis.ssz --mainnet-config
bazel run //beacon-chain -- --datadir /tmp/chaindata --force-clear-db --interop-genesis-state /tmp/genesis.ssz --interop-eth1data-votes --min-sync-peers=0 --http-web3provider=https://goerli.prylabs.net --deposit-contract 0x8A04d14125D0FDCDc742F4A05C051De07232EDa4
```
Terminal 2
```
bazel run //validator -- --beacon-rpc-provider localhost:4000 --interop-num-validators=1000 --interop-start-index=0 --clear-db
```

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

- [x] Fix interop mode by allowing broadcasts without the requisite number of peers.

**Which issues(s) does this PR fix?**

Fixes #7673 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/p2p/pubsub.go [hunk 1]
```diff
@@ -53,7 +54,7 @@ func (s *Service) PublishToTopic(ctx context.Context, topic string, data []byte,
 
 	// Wait for at least 1 peer to be available to receive the published message.
```
Comment (terencechain) [inline beacon-chain/p2p/pubsub.go:55]: Can you update this command for the second condition?

**Review by rauljordan — APPROVED** [review]

**Comment by ibrahim419** [comment]
Xlm
