### PR TITLE
Fix memory usability 

### LINKED ISSUE #9263: Check slight memory utilization impact of #9155
After separating out validators from the "BeaconState" in #9155. We memory utilisation seems to be slightly higher than normal. The issue is to track and see if the memory utilization is due to #9155 relate changes and fix it. Also he cache hit ratio has come down after https://github.com/prysmaticlabs/prysm/pull/9155#discussion_r672336449 fix. we need to find a good way to **increase the cache hit** ratio.

915_final

_Originally posted by @jmozah in https://github.com/prysmaticlabs/prysm/issues/9155#issuecomment-885446271_

### PR DESCRIPTION
**Pull request by jmozah**
**What type of PR is this?**
 Bug fix

**What does this PR do? Why is it needed?**
1) Fix validator entry cache usability 

**Which issues(s) does this PR fix?**
Fixes #9263

**Other notes for review**
- this should improve cache hit count

### CODE REVIEW

File: beacon-chain/db/kv/kv.go [hunk 1]
```diff
@@ -47,6 +47,10 @@ var (
 		Name: "validator_entry_cache_miss",
 		Help: "The total number of cache misses on the validator entry cache.",
 	})
+	validatorEntryCacheDelete = promauto.NewCounter(prometheus.CounterOpts{
+		Name: "validator_entry_cache_delete",
```
Comment (terencechain) [inline beacon-chain/db/kv/kv.go:51]: this can better conformed to naming standard: https://prometheus.io/docs/practices/naming/

how does `validator_entry_cache_delete_total` sound? Same with the above as well

File: beacon-chain/db/kv/state.go [hunk 2]
```diff
@@ -418,6 +418,9 @@ func (s *Store) validatorEntries(ctx context.Context, blockRoot [32]byte) ([]*v1
 				}
 				validatorEntries = append(validatorEntries, encValEntry)
 				validatorEntryCacheMiss.Inc()
+
+				// should add here in cache
+				s.validatorEntryCache.Set(key, encValEntry, int64(encValEntry.SizeSSZ()))
```
Comment (terencechain) [inline beacon-chain/db/kv/state.go:423]: Is there any concern with cardinality? How often does this happen?

**Comment by jmozah** [comment]
comparing with develop, this branch clearly shows the use of "validatorCache" hits (rectangled)

load_generation

File: beacon-chain/db/kv/state.go (hunk 2 above)
Comment (jmozah) [reply beacon-chain/db/kv/state.go:423]: Nope. Updates to the entries of this bucket are low (per spec).
Most of the times they are the same, per my analysis of the mainnet DB and conformed by the cache hit count in the screen shot attached.

**Review by rauljordan — APPROVED** [review]
