### PR TITLE
Disallow Creation of Multiple Wallets at Wallet Path

### LINKED ISSUE #7281: Different wallet types don't mix well within the same wallet directory
# 🐞 Bug Report

Example:

Start w/ user w/  No Prysm wallets/never used Prysm before/just freshly installed Prysm after going through eth2.0-deposit-cli

1) accounts-v2 import --keys-dir ........ (as one may import launchpad keys).  During interaction w/ the program, create the wallet [direct] with Password A and in default dir
2) accounts-v2 list   ---> works as expected
3) wallet-v2 create HD (DERIVED) type wallet in default directory w/ Password B
----After this point, behavior is as if Direct (pass A) wallet no longer exists
4) accounts-v2 create --> Input Password A (direct pass) -> Fail w/ "Could not create new account: wrong wallet password entered"
5) try 4 again with Password B (derived) --> success
6) accounts-v2 list, fails with A, good with B but only show's B (HD) account, no mention of Direct account
7) run the validator, only password B works (A fails w/ "could not read keymanager for wallet: could not initialize derived keymanager: could not decrypt seed configuration with password: invalid checksum").

### Description

See above

### Has this worked before in a previous version?

Complex set of steps, unclear what variety may have worked before.  Sorry

## 🔬 Minimal Reproduction

See above

## 🔥 Error

See above

## 🌍  Your Environment

Ubuntu VM running Docker

**What version of Prysm are you running? (Which release)**

current Master

**Anything else relevant (validator index / public key)?**
No

### PR DESCRIPTION
**Pull request by rauljordan**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

Our accounts logic assumes there can only be a single wallet at the wallet-path, yet we were not properly throwing an error if a user tries to do this. This PR now throws an error if the directory at the wallet-path is non-empty.

**Which issues(s) does this PR fix?**

Fixes #7281

### CODE REVIEW

**Comment by rauljordan** [comment]
cc @dv8silencer

File: validator/accounts/v2/wallet_create.go [hunk 1]
```diff
@@ -40,15 +39,12 @@ func CreateAndSaveWalletCli(cliCtx *cli.Context) (*wallet.Wallet, error) {
 	}
 
 	dir := createWalletConfig.WalletCfg.WalletDir
-	kmKind := createWalletConfig.WalletCfg.KeymanagerKind
-	accountsPath := filepath.Join(dir, kmKind.String())
-	ok, err := fileutil.HasDir(accountsPath)
+	ok, err := fileutil.HasDir(dir)
```
Comment (rkapka) [inline validator/accounts/v2/wallet_create.go:42]: I feel like in this particular case it would be better to name the variable `hasDir` instead of `ok`. I know this is a standard Go pattern, but checking `if ok` and then returning an error looks confusing.

**Comment by rauljordan** [comment]
Ready again @rkapka

**Review by rkapka — APPROVED** [review]
