### PR TITLE
Warn Users In Case Slashing Protection Exports are Empty

### LINKED ISSUE #9897: Empty `slashing_protection.json` after export
# 🐞 Bug Report

### Description

I have exported in more than 1 prater validator the **slashing protection database** using the CLI. In all cases, the slashing protection database results in a JSON file with empty key values that seems to be wrong, like the following:
```
{
	"metadata": {
		"interchange_format_version": "5",
		"genesis_validators_root": "0x043db0d9a83813551ee2f33450d23797757d430911a9320530ad8a0eabc43efb"
	},
	"data": [
		{
			"pubkey": "0x80b11b83eb8c1858c657dc55936bd4b47d2418c8906777cecae9c14495796f3d52b44652684e25e9ebb3e9efcfea33c6",
			"signed_blocks": [],
			"signed_attestations": []
		}
	]
}
```
### Has this worked before in a previous version?

I have not tried the slashing protection database export before.
## 🔬 Minimal Reproduction
To reproduce the issue just do a normal **export of the validator slashing protection database** with 
```
validator slashing-protection export --datadir=/root/.eth2validators
```
The output logs are
```
validator --prater slashing-protection export --datadir=/root/.eth2validators
[2021-11-12 16:35:02]  WARN flags: Running on the Prater Testnet
[2021-11-12 16:35:02]  INFO slashingprotection: This command exports your validator's attestation and proposal history into a file that can then be imported into any other Prysm setup across computers
Extracting signed blocks by validator public key 100% [================================]  [0s:0s]
Enter your desired output directory for your slashing protection history file:
/root 
[2021-11-12 16:35:13]  INFO slashingprotection: Writing slashing protection export JSON file to /root/slashing_protection.json
[2021-11-12 16:35:13]  INFO slashingprotection: Successfully wrote /root/slashing_protection.json
```

## 🔥 Error
The `slashing_protection.json` JSON file seems to have something wrong, especially the following empty key-values
<pre><code>

"signed_blocks": [],
"signed_attestations": []
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Docker container running on a Debian host
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.0.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
The validator was executed with the following flags
```
validator \
  --prater \
  --datadir=/root/.eth2 \
  --rpc-host 0.0.0.0 \
  --monitoring-host 0.0.0.0 \
  --beacon-rpc-provider=\"$BEACON_RPC_PROVIDER\" \
  --beacon-rpc-gateway-provider=\"$BEACON_RPC_GATEWAY_PROVIDER\" \
  --wallet-dir=/root/.eth2validators \
  --wallet-password-file=/root/.eth2wallets/wallet-password.txt \
  --write-wallet-password-on-web-onboarding \
  --graffiti=\"$GRAFFITI\" \
  --web \
  --grpc-gateway-host=0.0.0.0 \
  --grpc-gateway-port=80 \
  --accept-terms-of-use
```

### PR DESCRIPTION
**Pull request by rauljordan**
Resolves #9897, we finally confirmed and were able to reproduce the problem reported by the dappnode team where exporting their slashing protection history would result in an empty JSON history. This was because the wallet was created with an older version of Prysm that would place their `validator.db` in the top-level wallet directory. However, newer versions of Prysm create and use their `validator.db` in the wallet/direct or wallet/derived folder instead.

```
wallet/
  validator.db # This is a faulty DB created in older versions of Prysm!
  direct/
    accounts/
      all-accounts.keystore.json
    validator.db # This is the correct DB
```

The problem and resolution was **confirmed** by the dappnode team today.

We issue a warning to users here and exit early instead:

```
No slashing protection data was found in your database. This is likely because an older version of " +
				"of Prysm would place your validator database in your wallet directory as a validator.db file. Now, " +
				"Prysm keeps its validator database inside the direct/ or derived/ folder in your wallet directory. " +
				"Try running this command again, but add direct/ or derived/ to the path where your wallet " +
				"directory is in and you should obtain your slashing protection history
```

### CODE REVIEW

File: cmd/validator/slashing-protection/export.go [hunk 1]
```diff
@@ -70,16 +70,12 @@ func exportSlashingProtectionJSON(cliCtx *cli.Context) error {
...
-				"this may be because your validator database is stored in a --datadir which could be a different "+
-				"directory than the --wallet-dir you set when running your validator. You might have an empty "+
-				"validator.db in your --wallet-dir that was created by accident in a previous Prysm version. "+
-				"Check if the directory you are passing in has a validator.db file in it and then run "+
-				"the command with right directory. Also, check if your --wallet-dir is different from your --datadir "+
-				"when you ran your Prysm validator",
-			dataDir,
+		log.Fatal(
+			"No slashing protection data was found in your database. This is likely because an older version of " +
+				"of Prysm would place your validator database in your wallet directory as a validator.db file. Now, " +
```
Comment (potuz) [inline cmd/validator/slashing-protection/export.go:75]:
```suggestion
				"Prysm would place your validator database in your wallet directory as a validator.db file. Now, " +
```

**Review by potuz — CHANGES_REQUESTED** [review]

File: cmd/validator/slashing-protection/export.go [hunk 2]
```diff
@@ -70,16 +70,12 @@ func exportSlashingProtectionJSON(cliCtx *cli.Context) error {
...
-				"Check if the directory you are passing in has a validator.db file in it and then run "+
-				"the command with right directory. Also, check if your --wallet-dir is different from your --datadir "+
-				"when you ran your Prysm validator",
-			dataDir,
+		log.Fatal(
+			"No slashing protection data was found in your database. This is likely because an older version of " +
+				"Prysm would place your validator database in your wallet directory as a validator.db file. Now, " +
+				"Prysm keeps its validator database inside the direct/ or derived/ folder in your wallet directory. " +
+				"Try running this command again, but add direct/ or derived/ to the path where your wallet " +
+				"directory is in and you should obtain your slashing protection history",
```
Comment (potuz) [inline cmd/validator/slashing-protection/export.go:78]:
```suggestion
				"directory is in and you should obtain your slashing protection history"
```

**Review by potuz — CHANGES_REQUESTED** [review]

**Review by potuz — APPROVED** [review]
