### PR TITLE
Fix Range Request Responses

### LINKED ISSUE #7464: Beacon Node Still Returns Out of Order Blocks From Range Requests
# 🐞 Bug Report

### Description

Currently Lighthouse Peers score Prysm Nodes down due to the fact that prysm nodes occasionally 
send back out of order blocks. 

### Has this worked before in a previous version?

Supposed to. 

## 🔬 Minimal Reproduction

Run a Prysm Node in medalla, and after a while lighthouse nodes start banning them.

## 🔥 Error

```
DEBUG sync: Peer has sent a goodbye message Reason=unknown goodbye value of 251 Received 
```
Consistent goodbyes received from lighthouse nodes.

## 🌍  Your Environment

**Operating System:**

Ubuntu

**What version of Prysm are you running? (Which release)**

https://github.com/prysmaticlabs/prysm/commit/390a589afb6a38925b2d6da25a3df3d4f84a9bf7

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

We were responding to range request with invalid blocks which were non linear. This lead to lighthouse nodes to disconnect 
from us. This PR adds a new method to filter all blocks to be sent and to ensure their linearity.

- [x] Add in a new filtration method to make sure blocks are valid.
- [x] Add regression test cases for this.

**Which issues(s) does this PR fix?**

Fixes #7464 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go [hunk 1]
```diff
@@ -214,6 +217,37 @@ func (s *Service) validateRangeRequest(r *pb.BeaconBlocksByRangeRequest) error {
 	return nil
 }
 
+// filters all the provided blocks to ensure they are canonical
+// and are strictly linear.
+func (s *Service) filterBlocks(ctx context.Context, blks []*ethpb.SignedBeaconBlock, roots [][32]byte, prevRoot *[32]byte,
+	step, startSlot uint64) ([]*ethpb.SignedBeaconBlock, error) {
+
+	newBlks := make([]*ethpb.SignedBeaconBlock, 0, len(blks))
+
```
Comment (farazdagi) [inline beacon-chain/sync/rpc_beacon_blocks_by_range.go:226]:
```suggestion
```

**Review by farazdagi — DISMISSED** [review]
Our implementation of `beaconBlocksByRangeRPCHandler()` and `writeBlockRangeToStream()` is a bit convoluted and hard to review (complexity isn't introduced in this PR, though), so not 100% sure I haven't missed anything - but imo, the PR is solid.

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go [hunk 2]
```diff
@@ -82,14 +85,20 @@ func (s *Service) beaconBlocksByRangeRPCHandler(ctx context.Context, msg interfa
...
 		}
-
+		// Reduce capacity of peer in the rate limiter first.
 		// Decrease allowed blocks capacity by the number of streamed blocks.
 		if startSlot <= endSlot {
 			s.rateLimiter.add(stream, int64(1+(endSlot-startSlot)/m.Step))
 		}
+		// Exit in the event we have a disjoint chain to
+		// return.
+		if err == errInvalidParent {
```
[the remark this answers is not in the document]
Comment (rauljordan) [reply beacon-chain/sync/rpc_beacon_blocks_by_range.go:99]: That would seem best IMO

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go [hunk 3]
```diff
@@ -214,6 +217,37 @@ func (s *Service) validateRangeRequest(r *pb.BeaconBlocksByRangeRequest) error {
...
 
+// filters all the provided blocks to ensure they are canonical
+// and are strictly linear.
+func (s *Service) filterBlocks(ctx context.Context, blks []*ethpb.SignedBeaconBlock, roots [][32]byte, prevRoot *[32]byte,
+	step, startSlot uint64) ([]*ethpb.SignedBeaconBlock, error) {
+
+	newBlks := make([]*ethpb.SignedBeaconBlock, 0, len(blks))
+
+	for i, b := range blks {
+		isRequestedSlotStep := (b.Block.Slot-startSlot)%step == 0
```
Comment (rauljordan) [inline beacon-chain/sync/rpc_beacon_blocks_by_range.go:228]: Should we validate start slot <= b.Block.Slot ?

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go [hunk 4]
```diff
@@ -214,6 +217,37 @@ func (s *Service) validateRangeRequest(r *pb.BeaconBlocksByRangeRequest) error {
...
+		isCanonical, err := s.chain.IsCanonical(ctx, roots[i])
```
Comment (rauljordan) [inline beacon-chain/sync/rpc_beacon_blocks_by_range.go:229]: This func will never return err, is that ok?

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go [hunk 5]
```diff
@@ -214,6 +217,37 @@ func (s *Service) validateRangeRequest(r *pb.BeaconBlocksByRangeRequest) error {
 	return nil
 }
 
+// filters all the provided blocks to ensure they are canonical
+// and are strictly linear.
+func (s *Service) filterBlocks(ctx context.Context, blks []*ethpb.SignedBeaconBlock, roots [][32]byte, prevRoot *[32]byte,
```
Comment (terencechain) [inline beacon-chain/sync/rpc_beacon_blocks_by_range.go:222]: what does `prevRoot` mean? is it like a starting head root?

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go [hunk 6]
```diff
@@ -214,6 +217,37 @@ func (s *Service) validateRangeRequest(r *pb.BeaconBlocksByRangeRequest) error {
...
+	step, startSlot uint64) ([]*ethpb.SignedBeaconBlock, error) {
+
```
Comment (terencechain) [inline beacon-chain/sync/rpc_beacon_blocks_by_range.go:224]: perhaps do a defensive check that `blks` and `roots` are the same length

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go [hunk 7]
```diff
@@ -214,6 +217,37 @@ func (s *Service) validateRangeRequest(r *pb.BeaconBlocksByRangeRequest) error {
...
+		isRequestedSlotStep := (b.Block.Slot-startSlot)%step == 0
+		isCanonical, err := s.chain.IsCanonical(ctx, roots[i])
+		if err != nil {
+			return nil, err
+		}
+		parentValid := *prevRoot != [32]byte{}
+		isLinear := *prevRoot == bytesutil.ToBytes32(b.Block.ParentRoot)
+		isSingular := step == 1
+		if isRequestedSlotStep && isCanonical {
+			// Exit early if our valid block is non linear.
```
Comment (terencechain) [inline beacon-chain/sync/rpc_beacon_blocks_by_range.go:237]: do we want to be nicer here and actually return the resorted blocks for linearity? or exit early is good enough

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go (hunk 3 above)
Comment (nisdas) [reply beacon-chain/sync/rpc_beacon_blocks_by_range.go:228]: all this validation is already done and taken care of in `validateRangeRequest`

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go (hunk 4 above)
Comment (nisdas) [reply beacon-chain/sync/rpc_beacon_blocks_by_range.go:229]: Ah I think we might need to fix the api of that method then. It can be done in another PR

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go (hunk 5 above)
Comment (nisdas) [reply beacon-chain/sync/rpc_beacon_blocks_by_range.go:222]: I added a comment in the main request handler of what prevRoot is and why it is used.

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go (hunk 6 above)
Comment (nisdas) [reply beacon-chain/sync/rpc_beacon_blocks_by_range.go:224]: This is actually already done in `dedupBlocksAndRoots`  but I can add it in again too.

File: beacon-chain/sync/rpc_beacon_blocks_by_range.go (hunk 7 above)
Comment (nisdas) [reply beacon-chain/sync/rpc_beacon_blocks_by_range.go:237]: We do return the blocks if we find the next block is non-linear. In the caller of this function, it checks the error and if it is invalidParent we just exit early and return what we have so far.

**Review by rauljordan — APPROVED** [review]
