### PR TITLE
disable backfill if the checkpoint sync origin slot is in fulu

### LINKED ISSUE #15978: Running Prysm with the `--enable-backfill` does not work starting at Fulu
### Describe the bug

If starting a fresh node from a checkpoint post Fulu with the `--enable-backfill` flag, those errors are displayed:

Image

### PR DESCRIPTION
**Pull request by kasey**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Until DataColumnSidecar backfill is fully supported in develop we want to prevent backfill from being enabled when back syncing from a fulu block, because currently running backfill in a post-fulu network will cause bugs and not be helpful.

For context see https://github.com/OffchainLabs/prysm/issues/15982

**Which issues(s) does this PR fix?**

Fixes #15978

**Other notes for review**

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

File: beacon-chain/sync/backfill/service.go [hunk 1]
```diff
@@ -281,6 +293,12 @@ func (s *Service) Start() {
 		return
 	}
 	status := s.store.status()
+	if fuluOrigin(params.BeaconConfig(), status) {
+		log.WithField("originSlot", s.store.status().OriginSlot).
+			Warn("backfill disabled; DataColumnSidecar currently unsupported, for updates follow https://github.com/OffchainLabs/prysm/issues/15982")
```
Comment (prestonvanloon) [inline beacon-chain/sync/backfill/service.go:298]: Thanks for pointing to a tracking issue!

**Review by prestonvanloon — APPROVED** [review]
