### PR TITLE
Correct how AllValidatorsAreExited creates status request

### LINKED ISSUE #7707: All validators are exited, no more work to perform...
# 🐞 Bug Report

### Description

Validator process shows two exited validators (from the initial time sync bug), but then states that all validators are exited.

### Has this worked before in a previous version?

Behavior was not observed until updating to beta.1

## 🔬 Minimal Reproduction

`~/Downloads/prysm/prysm.sh beacon-chain --config-file ~/.eth2/prysm/medallabeacon.yaml --blst --head-sync`

```
p2p-host-ip: '1.2.3.4'
monitoring-host: 'earth.thegalaxy'
monitoring-port: 8082
p2p-udp-port: 13428
p2p-tcp-port: 13428
http-web3provider: 'http://192.168.0.2:8545/'
tls-cert: '/etc/ssl/certs/earth.thegalaxy.crt'
tls-key: '/etc/ssl/private/earth.thegalaxy.key'
rpc-host: 'earth.thegalaxy'
rpc-port: 4000
p2p-max-peers: 1000
datadir: '/home/seamonkey/.eth2/prysm'
medalla: true
```
`~/Downloads/prysm/prysm.sh validator --config-file ~/.eth2/prysm/medallavalidator.yaml`
```
monitoring-host: 'earth.thegalaxy'
tls-cert: '/etc/ssl/certs/earth.thegalaxy.crt'
beacon-rpc-provider: 'earth.thegalaxy:4000'
graffiti: 'poappyHaPQaBPnZOlKI+N3zD4XKfz9UA'
wallet-password-file: '$HOME/.eth2/prysm/password.txt'
wallet-dir: '$HOME/.eth2/prysm/.eth2validators/prysm-wallet-v2'
monitoring-port: 8083
```
## 🔥 Error

```
[2020-11-03 02:20:19]  INFO validator: Validator exited index=11762 pubKey=0x84b227da4d40 status=EXITED
[2020-11-03 02:20:19]  INFO validator: Validator exited index=11760 pubKey=0x88e06872b53f status=EXITED
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11758 publicKey=0xb7ead186071b
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11765 publicKey=0x8bdd0ad880e3
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11766 publicKey=0xa25f842e6dce
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11763 publicKey=0xa8290a097d56
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11759 publicKey=0x82f749b2489c
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11764 publicKey=0xa22526ece1e1
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xb7ead186071b] slot=653474
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0x8bdd0ad880e3] slot=653476
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xa25f842e6dce] slot=653479
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xa22526ece1e1] slot=653492
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xa8290a097d56] slot=653494
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0x82f749b2489c] slot=653502
[2020-11-03 02:20:32]  INFO validator: All validators are exited, no more work to perform...
```

## 🌍  Your Environment

Linux Mint 20

**What version of Prysm are you running? (Which release)**

beta.1

**Anything else relevant (validator index / public key)?**

https://medalla.beaconcha.in/dashboard?validators=11758,11759,11760,11762,11763,11764,11765,11766

### PR DESCRIPTION
**Pull request by dv8silencer**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**
This bug fixes #7707 -- If you look at this in validator/client/validator.go

```
	var publicKeys [][]byte
	for _, key := range validatingKeys {
		publicKeys = append(publicKeys, key[:])
	}
	request := &ethpb.MultipleValidatorStatusRequest{
		PublicKeys: publicKeys,
	}
```

What I saw during debugging is that after the range-for loop, publicKeys ends up with a set of identical keys that match the last key appended.  This is likely because the iterating variable (key)'s memory address is appended and since this address will last hold the last key iterated over in validatorKeys, publicKey ends up with multiple copies of the same key.  If the validator associated with the last key is exited, then this function will true that all validators are exited and this leads to the described bug.  To fix this I just create a copy and append that instead.  There is a regression test created as well which creates a couple of sample keys and sees if the request is as expected.  This test fails on current master and passes with this PR.

**Which issues(s) does this PR fix?**

Fixes #7707 

**Other notes for review**

### CODE REVIEW

File: validator/client/validator.go [hunk 1]
```diff
@@ -597,7 +597,9 @@ func (v *validator) AllValidatorsAreExited(ctx context.Context) (bool, error) {
 	}
 	var publicKeys [][]byte
 	for _, key := range validatingKeys {
-		publicKeys = append(publicKeys, key[:])
+		copyKey := make([]byte, len(key))
```
Comment (nisdas) [inline validator/client/validator.go:600]: fyi, fixed sized arrays are copied by value not reference. So you can simply do 
```
copiedKey := key
```

**Review by nisdas — APPROVED** [review]

**Comment by prestonvanloon** [comment]
Excellent find! Thanks!
