### PR TITLE
Return `INVALID` validator status if the BLS signature is invalid

### LINKED ISSUE #6036: Invalid deposit shows as DEPOSITED in witti
# 🐞 Bug Report

### Description
This issue captures a discussion on the #witti channel. User virus-in-numeris made a deposit which turned out to be created without the witti flag. This means with an invalid signature for the witti chain due to the different fork-versions

Link to deposit
https://goerli.etherscan.io/tx/0x49a51b838523c08fcc4e9dccca65a8a9d9153e58be4358a3d16bb7c979239df6

In the validator (confirmed to have been started *with* the witti flag), the pubkey shows up as status=DEPOSITED :

`INFO validator: Deposit for validator received but not processed into the beacon state eth1DepositBlockNumber=2771968 expectedInclusionSlot=8479 pubKey=0x8aaebd437a72 status=DEPOSITED`

Proto confirmed the wrong signature
`BAD signature on deposit #471, tx: 0x49a51b838523c08fcc4e9dccca65a8a9d9153e58be4358a3d16bb7c979239df6, pubkey: 8aaebd437a72f2d9620dfaca15f801b2f77c806c3816fc39de9e8739ce62703200339bb8dcd134df7093e3fa27f78766`

(full list from proto of all witti signature verifications at the time: https://gist.github.com/protolambda/34a44e23720ee6666e551d64e6a1dddc)

User is waiting for the validator to become ACTIVE. This does not happen because of the invalid deposit.

Issue is that it shows up in the validator log as normal, whereas it:
- should not show up at all
- show up with status "INVALID" to indicate something is wrong.

Current situation is confusing and misleading.

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction
create a validator without the --witti flag.
Use the deposit data of this validator to make a goerli deposit.
Start the validator with the witti flag.

Pubkey then shows DEPOSITED but nothing else happens.

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

### LINKED ISSUE #6334: Display an error/warning message if a deposit is invalid
# 💎 Issue
My deposit of 32 gETH is invalid (likely because I did the deposit with an older version the validator client) as shown in the link here: https://beaconcha.in/validator/a308dc8b2571ac658488f41bb0cf9fa6811e2a23c36ffbc6a6fb478b1104db61ff2b795c0b35f9c5f69191f3b8c8e2bd#deposits

The validator client is however displaying this message:
`INFO validator: Deposit processed, entering activation queue after finalization positionInActivationQueue=0 pubKey=0xa308dc8b2571 status=DEPOSITED`

It would be preferable to display an error or warning message to the user that his deposit has failed.

### Background
Discussed with @nisdas : https://discordapp.com/channels/476244492043812875/476588476393848832/724477548414894080

### PR DESCRIPTION
**Pull request by fabdarice**
**What type of PR is this?**
Feature

**What does this PR do? Why is it needed?**
ETH1 deposits with invalid signature were showing "DEPOSITED" as a status to validator clients. 
This PR adds a new ValidatorStatus `INVALID` to alert properly users if their deposit is invalid.

**Which issues(s) does this PR fix?**
Fixes #6334 
FIxes #6036 

**Other notes for review**
Protobuf generation handled in this PR: https://github.com/prysmaticlabs/ethereumapis/pull/169

### CODE REVIEW

File: beacon-chain/rpc/validator/status.go [hunk 1]
```diff
@@ -159,11 +160,15 @@ func (vs *Server) validatorStatus(
...
 			return resp, nonExistentIndex
 		}
-		_, eth1BlockNumBigInt := vs.DepositFetcher.DepositByPubkey(ctx, pubKey)
+		deposit, eth1BlockNumBigInt := vs.DepositFetcher.DepositByPubkey(ctx, pubKey)
 		if eth1BlockNumBigInt == nil { // No deposit found in ETH1.
 			return resp, nonExistentIndex
 		}
-
+		err := depositutil.VerifyDepositSignature(deposit.Data)
+		if err != nil {
```
Comment (0xKiwi) [inline beacon-chain/rpc/validator/status.go:168]:
```suggestion
		if err := depositutil.VerifyDepositSignature(deposit.Data); err != nil {
```

File: validator/client/validator.go [hunk 2]
```diff
@@ -277,6 +277,8 @@ func (v *validator) checkAndLogValidatorStatus(validatorStatuses []*ethpb.Valida
 			validatorActivated = true
 		case ethpb.ValidatorStatus_EXITED:
 			log.Info("Validator exited")
+		case ethpb.ValidatorStatus_INVALID:
+			log.Error("Invalid BLS signature")
```
Comment (0xKiwi) [inline validator/client/validator.go:281]: This log could be a bit confusing as a user, maybe it should say something like "Invalid Eth1 deposit"? Also, I don't think it should be an error, it's not necessarily an error.

File: beacon-chain/rpc/validator/status_test.go [hunk 3]
```diff
@@ -27,16 +27,12 @@ import (
 func TestValidatorStatus_DepositedEth1(t *testing.T) {
```
Comment (0xKiwi) [inline beacon-chain/rpc/validator/status_test.go:27]: Can you add a new function of this called `TestValidatorStatus_Invalid`?

File: shared/depositutil/deposit.go [hunk 4]
```diff
@@ -75,3 +78,43 @@ func WithdrawalCredentialsHash(withdrawalKey bls.SecretKey) []byte {
 	h := hashutil.Hash(withdrawalKey.PublicKey().Marshal())
 	return append([]byte{params.BeaconConfig().BLSWithdrawalPrefixByte}, h[1:]...)[:32]
 }
+
+// VerifyDepositSignature verifies the correctness of Eth1 deposit BLS signature
+func VerifyDepositSignature(dd *ethpb.Deposit_Data) error {
```
Comment (0xKiwi) [inline shared/depositutil/deposit.go:83]: Is there anywhere else this utility can be used?

File: validator/client/validator.go (hunk 2 above)
Comment (fabdarice) [reply validator/client/validator.go:281]: Hmm, are you suggesting Warning?
If a validator has an invalid Eth1 deposit, he shouldn't be able to operate right? Wouldn't "error" be appropriate here?

Comment (0xKiwi) [reply validator/client/validator.go:281]: Errors don't stop execution, and even if they have an invalid deposit, it doesn't mean it should stop the client. If a deposit is invalid their validator will never be activated anyways right?
This is mainly just to inform the user that the deposit is invalid.
I was thinking of it being an info log, because all this is doing is informing the user. But maybe it would be a good idea to be a warning to make sure the user notices the mistake. Wdyt @prestonvanloon ? Info or warning log from the validator client?

File: shared/depositutil/deposit.go [hunk 5]
```diff
@@ -4,15 +4,16 @@ package depositutil
 
 import (
 	"fmt"
+	p2ppb "github.com/prysmaticlabs/prysm/proto/beacon/p2p/v1"
 
 	"github.com/ethereum/go-ethereum/core/types"
```
Comment (0xKiwi) [inline shared/depositutil/deposit.go:9]: Can you fix the import formatting here please?

**Comment by fabdarice** [comment]
image

File: shared/depositutil/deposit.go (hunk 4 above)
Comment (nisdas) [reply shared/depositutil/deposit.go:87]: This method is an exact duplicate of 
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/blocks/deposit.go#L222

Comment (nisdas) [reply shared/depositutil/deposit.go:87]: Anyway to refactor that method and only use 1 method throughout the repo.

Comment (fabdarice) [reply shared/depositutil/deposit.go:87]: oOoo :( 
which function would you rather keep? the one in blocks/deposit.go or the one I "re-implemented" ?

Comment (nisdas) [reply shared/depositutil/deposit.go:87]: lets keep the one that you have implemented, this is a useful shared method for deposits, so I can see this being used elsewhere. You would just need to have the one in `blocks/deposit.go` use the logic from your method. As long as the logic is only implemented once it should be ok. You can maybe have this chunk in /shared/depositutil
```go
publicKey, err := bls.PublicKeyFromBytes(pub)
	if err != nil {
		return errors.Wrap(err, "could not convert bytes to public key")
	}
	sig, err := bls.SignatureFromBytes(signature)
	if err != nil {
		return errors.Wrap(err, "could not convert bytes to signature")
	}
	root, err := ssz.SigningRoot(obj)
	if err != nil {
		return errors.Wrap(err, "could not get signing root")
	}
	signingData := &pb.SigningData{
		ObjectRoot: root[:],
		Domain:     domain,
	}
	ctrRoot, err := ssz.HashTreeRoot(signingData)
	if err != nil {
		return errors.Wrap(err, "could not get container root")
	}
	if !sig.Verify(publicKey, ctrRoot[:]) {
		return helpers.ErrSigFailedToVerify
	}
	return nil
```
and use that wherever it is needed.

Comment (fab-spring) [reply shared/depositutil/deposit.go:87]: Updated @nisdas

File: beacon-chain/core/blocks/deposit.go [hunk 6]
```diff
@@ -220,30 +221,7 @@ func verifyDeposit(beaconState *stateTrie.BeaconState, deposit *ethpb.Deposit) e
...
-	}
-	ctrRoot, err := ssz.HashTreeRoot(signingData)
-	if err != nil {
-		return errors.Wrap(err, "could not get container root")
-	}
-	if !sig.Verify(publicKey, ctrRoot[:]) {
-		return helpers.ErrSigFailedToVerify
-	}
-	return nil
+	return depositutil.VerifyDepositSignature(obj)
```
Comment (fab-spring) [inline beacon-chain/core/blocks/deposit.go:224]: a bit strange :)

File: shared/depositutil/deposit.go (hunk 4 above)
Comment (fabdarice) [reply shared/depositutil/deposit.go:87]: Updated.

**Comment by fabdarice** [comment]
Hmm, this might not be ready.
Seems like loading a keystore with an invalid signature is also prompting this message on the beacon-chain client:
```
[2020-07-22 22:41:52]  WARN sync: Failed to handle p2p RPC error=invalid finalized root peer=16Uiu2HAmJWmKzisixDhUXV9oP9h1qgRWYa2JMCkXRA1nqsQmSnFu topic=/eth2/beacon_chain/req/status/1/ssz_snappy
```

File: beacon-chain/core/blocks/deposit.go (hunk 6 above)
Comment (nisdas) [inline beacon-chain/core/blocks/deposit.go:224]: this ignores the provided domain in the method

Comment (fabdarice) [reply beacon-chain/core/blocks/deposit.go]: @nisdas refactored to include the domain as an args of `depositutil.VerifyDepositSignature`

File: beacon-chain/core/blocks/deposit.go [hunk 7]
```diff
@@ -218,30 +219,9 @@ func verifyDeposit(beaconState *stateTrie.BeaconState, deposit *ethpb.Deposit) e
...
-	}
-	ctrRoot, err := ssz.HashTreeRoot(signingData)
-	if err != nil {
-		return errors.Wrap(err, "could not get container root")
-	}
-	if !sig.Verify(publicKey, ctrRoot[:]) {
-		return helpers.ErrSigFailedToVerify
-	}
-	return nil
+	obj.PublicKey = pub
```
Comment (nisdas) [inline beacon-chain/core/blocks/deposit.go:222]: can you remove the setting of these 2 fields, they are already set in `obj`

File: beacon-chain/rpc/validator/status.go [hunk 8]
```diff
@@ -159,11 +160,22 @@ func (vs *Server) validatorStatus(
...
 		}
-		_, eth1BlockNumBigInt := vs.DepositFetcher.DepositByPubkey(ctx, pubKey)
+		deposit, eth1BlockNumBigInt := vs.DepositFetcher.DepositByPubkey(ctx, pubKey)
 		if eth1BlockNumBigInt == nil { // No deposit found in ETH1.
 			return resp, nonExistentIndex
 		}
-
+		domain, err := helpers.ComputeDomain(
+			params.BeaconConfig().DomainDeposit,
+			params.BeaconConfig().GenesisForkVersion,
```
Comment (nisdas) [inline beacon-chain/rpc/validator/status.go:169]: to be inline with the spec, lets set it as nil over here.

File: beacon-chain/rpc/validator/status.go [hunk 9]
```diff
@@ -159,11 +160,22 @@ func (vs *Server) validatorStatus(
...
+			params.BeaconConfig().ZeroHash[:],
```
Comment (nisdas) [inline beacon-chain/rpc/validator/status.go:170]: same here

Comment (fabdarice) [reply beacon-chain/rpc/validator/status.go]: updated.

File: beacon-chain/core/blocks/deposit.go (hunk 7 above)
Comment (fabdarice) [reply beacon-chain/core/blocks/deposit.go]: removed.

File: beacon-chain/rpc/validator/status.go [hunk 10]
```diff
@@ -159,11 +160,22 @@ func (vs *Server) validatorStatus(
...
 		}
-		_, eth1BlockNumBigInt := vs.DepositFetcher.DepositByPubkey(ctx, pubKey)
+		deposit, eth1BlockNumBigInt := vs.DepositFetcher.DepositByPubkey(ctx, pubKey)
 		if eth1BlockNumBigInt == nil { // No deposit found in ETH1.
 			return resp, nonExistentIndex
 		}
-
+		domain, err := helpers.ComputeDomain(
+			params.BeaconConfig().DomainDeposit,
+			nil,
```
Comment (terencechain) [inline beacon-chain/rpc/validator/status.go:169]: In general, it's a good practice to add a comment after `nil,` so one knows what this nil refers to

File: beacon-chain/rpc/validator/status.go [hunk 11]
```diff
@@ -159,11 +160,22 @@ func (vs *Server) validatorStatus(
...
+			nil,
+		)
+		if err != nil {
+			return resp, nonExistentIndex
```
Comment (terencechain) [inline beacon-chain/rpc/validator/status.go:173]: Any reason to not log the error here?

File: beacon-chain/rpc/validator/status.go [hunk 12]
```diff
@@ -159,11 +160,22 @@ func (vs *Server) validatorStatus(
...
+		}
+		if err := depositutil.VerifyDepositSignature(deposit.Data, domain); err != nil {
+			resp.Status = ethpb.ValidatorStatus_INVALID
```
Comment (terencechain) [inline beacon-chain/rpc/validator/status.go:176]: Same here

File: beacon-chain/rpc/validator/status.go (hunk 10 above)
Comment (fabdarice) [reply beacon-chain/rpc/validator/status.go]: done

File: beacon-chain/rpc/validator/status.go (hunk 11 above)
Comment (fabdarice) [reply beacon-chain/rpc/validator/status.go:174]: added log warn here.

File: beacon-chain/rpc/validator/status.go (hunk 12 above)
Comment (fabdarice) [reply beacon-chain/rpc/validator/status.go:177]: added log warn here.
