### PR TITLE
Fix Flaky Tests

### LINKED ISSUE #377: Tests Fail With Race Detection
```text
bazel test //... --features=race
```
Results
```text
INFO: Build completed, 3 tests FAILED, 4 total actions
//beacon-chain/blockchain:go_default_test                       (cached) PASSED in 0.0s
//beacon-chain/node:go_default_test                             (cached) PASSED in 0.1s
//beacon-chain/powchain:go_default_test                         (cached) PASSED in 0.1s
//beacon-chain/rpc:go_default_test                              (cached) PASSED in 0.3s
//beacon-chain/simulator:go_default_test                        (cached) PASSED in 0.0s
//beacon-chain/sync:go_default_test                             (cached) PASSED in 0.0s
//beacon-chain/utils:go_default_test                            (cached) PASSED in 0.1s
//client/attester:go_default_test                               (cached) PASSED in 0.1s
//client/contracts:go_default_test                              (cached) PASSED in 0.1s
//client/mainchain:go_default_test                              (cached) PASSED in 0.3s
//client/node:go_default_test                                   (cached) PASSED in 0.1s
//client/observer:go_default_test                               (cached) PASSED in 0.1s
//client/params:go_default_test                                 (cached) PASSED in 0.1s
//client/rpcclient:go_default_test                              (cached) PASSED in 0.3s
//client/syncer:go_default_test                                 (cached) PASSED in 0.1s
//client/txpool:go_default_test                                 (cached) PASSED in 0.0s
//client/types:go_default_test                                  (cached) PASSED in 0.1s
//contracts:go_default_test                                     (cached) PASSED in 0.1s
//shared:go_default_test                                        (cached) PASSED in 0.3s
//shared/cmd:go_default_test                                    (cached) PASSED in 0.1s
//shared/database:go_default_test                               (cached) PASSED in 0.5s
//shared/p2p:go_feed_concurrent_write_test                      (cached) PASSED in 0.0s
//client/proposer:go_default_test                                        FAILED in 3.7s
  /home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/execroot/__main__/bazel-out/k8-fastbuild/testlogs/client/proposer/go_default_test/test.log
//client/simulator:go_default_test                                       FAILED in 0.7s
  /home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/execroot/__main__/bazel-out/k8-fastbuild/testlogs/client/simulator/go_default_test/test.log
//shared/p2p:go_default_test                                             FAILED in 1.3s
  /home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/execroot/__main__/bazel-out/k8-fastbuild/testlogs/shared/p2p/go_default_test/test.log
```

This is likely due to some p2p issues where the tests are attempting discovery.

### PR DESCRIPTION
**Pull request by rawfalafel**
This fixes #377, as well as flaky tests in `sync` and `rpc` that were reproduced on buildkite but haven't been reported on GitHub.

I didn't find any race conditions for `blockchain`, `casper`, `types`, so I re-enabled race there as well.

### CODE REVIEW

File: beacon-chain/node/node_test.go [hunk 1]
```diff
@@ -41,27 +41,6 @@ func TestNodeValidator_Builds(t *testing.T) {
...
-	set.Bool("demo-config", true, "demo configuration")
-
-	context := cli.NewContext(app, set, nil)
-
-	node, err := NewBeaconNode(context)
-	if err != nil {
-		t.Fatalf("Failed to create BeaconNode: %v", err)
-	}
-
-	go node.Start()
```
Comment (rawfalafel) [inline beacon-chain/node/node_test.go]: The problem here is that this goroutine is still running during execution of the _next_ test. This isn't actually testing anything, so I just deleted it.

File: beacon-chain/rpc/service_test.go [hunk 2]
```diff
@@ -250,10 +249,25 @@ func TestLatestAttestation(t *testing.T) {
 	}(t)
 
 	rpcService.incomingAttestation <- attestation
+	rpcService.cancel()
+	exitRoutine <- true
```
Comment (rawfalafel) [inline beacon-chain/rpc/service_test.go]: The issue here is that the test isn't waiting for the goroutine to finish.

File: beacon-chain/rpc/service_test.go [hunk 3]
```diff
@@ -262,9 +276,10 @@ func TestLatestAttestation(t *testing.T) {
 		<-exitRoutine
 	}(t)
 	rpcService.incomingAttestation <- attestation
-	testutil.AssertLogsContain(t, hook, "Sending attestation to RPC clients")
```
Comment (rawfalafel) [inline beacon-chain/rpc/service_test.go]: Same here. The assertion needs to come _after_ `exitRoutine <- true`. 

Another issue is that this test originally combined two tests that should have been separated.

```go
func TestBadExample(t *testing.T) {
  go func() {
    testSomething(testChan)
    <-exitRoutine
  }
  testChan <- struct{}{}
  assertSomething()

  go func() {
    testSomething(testChan)
    <-exitRoutine
  }
  testChan <- struct{}{}
  exitRoutine <- true
  assertSomethingElse() 
}
```

The above is a race condition on `assertSomething()`. The fix is to separate into two tests:

```go
func TestSomething(t *testing.T) {
  go func() {
    testSomething(testChan)
    <-exitRoutine
  }
  testChan <- struct{}{}
  exitRountine <- true
  assertSomething()
}

fun TestSomethingElse(t *testing.T){
  go func() {
    testSomething(testChan)
    <-exitRoutine
  }
  testChan <- struct{}{}
  exitRoutine <- true
  assertSomethingElse() 
}
```

In general, each test should assert one case anyways. Long tests that sequentially assert multiple cases are hard to read/debug.

File: beacon-chain/sync/service_test.go [hunk 4]
```diff
@@ -265,7 +265,22 @@ func TestBlockRequestErrors(t *testing.T) {
 	}
 
 	ss.blockRequestBySlot <- invalidmsg
+	ss.cancel()
+	exitRoutine <- true
```
Comment (rawfalafel) [inline beacon-chain/sync/service_test.go]: This test had the same issue. They need to be separated, and the `exitRoutine` check was missing.
