### PR TITLE
Less restrictive block stream for slashing detection

### LINKED ISSUE #6163: proposer slashing cannot be detected on p2p
# 🐞 Bug Report

### Description

p2p validation prevents blocks from getting into slasher feed because it fails validation as per eth2.0 networking spec.

### Has this worked before in a previous version?

no

### PR DESCRIPTION
**Pull request by shayzluf**
**What type of PR is this?**
Bug fix

**What does this PR do? Why is it needed?**
after #6164 has been reverted this PR is aiming to move validation responsibility of streamed block to rpc function (stream blocks). it adds StateSummaryCache to rpc service in order to handle validation of recent states using the new state gen.

**Which issues(s) does this PR fix?**

Fixes #6163

**Other notes for review**
block sig validation is dependant on new state get

### CODE REVIEW

File: beacon-chain/rpc/beacon/blocks.go [hunk 1]
```diff
@@ -192,6 +194,24 @@ func (bs *Server) StreamBlocks(_ *ptypes.Empty, stream ethpb.BeaconChain_StreamB
 					// One nil block shouldn't stop the stream.
 					continue
 				}
+				if featureconfig.Get().NewStateMgmt {
+					hasStateSummaryDB := bs.BeaconDB.HasStateSummary(bs.Ctx, bytesutil.ToBytes32(data.SignedBlock.Block.ParentRoot))
+					hasStateSummaryCache := bs.stateSummaryCache.Has(bytesutil.ToBytes32(blk.Block.ParentRoot))
```
Comment (terencechain) [inline beacon-chain/rpc/beacon/blocks.go:199]: You dont need state summary cache. It's only for syncing

File: beacon-chain/rpc/service.go [hunk 2]
```diff
@@ -132,6 +133,7 @@ type Config struct {
 	BlockNotifier           blockfeed.Notifier
 	OperationNotifier       opfeed.Notifier
 	StateGen                *stategen.State
+	StateSummaryCache       *cache.StateSummaryCache
```
Comment (0xKiwi) [inline beacon-chain/rpc/service.go:136]: Can you look through all these stateSummaryCache additions and make sure they're all needed? Looks like theres only one usage of it.

File: beacon-chain/rpc/beacon/blocks.go (hunk 1 above)
Comment (shayzluf) [reply beacon-chain/rpc/beacon/blocks.go]: it didn't work in runtime without it

Comment (shayzluf) [reply beacon-chain/rpc/beacon/blocks.go]: i tried

Comment (shayzluf) [reply beacon-chain/rpc/beacon/blocks.go]:
```[2020-06-15 17:59:00]  WARN rpc: No access to parent state to verify block signature blockSlot=10108
[2020-06-15 17:59:00]  INFO blockchain: Synced new block block=0xa8ba7d59... epoch=315 finalizedEpoch=313 finalizedRoot=0x9a4a86ae... slot=10108
[2020-06-15 17:59:00]  INFO blockchain: Finished applying state transition attestations=44 attesterSlashings=0 deposits=0 proposerSlashings=0 voluntaryExits=0```

Comment (terencechain) [reply beacon-chain/rpc/beacon/blocks.go]: Ah ok. I'll make improvement on not making state summary cache a criterial. For now, this is good 👍

File: beacon-chain/rpc/service.go (hunk 2 above)
Comment (shayzluf) [reply beacon-chain/rpc/service.go:136]: i looked. they are all required

File: beacon-chain/rpc/beacon/blocks.go [hunk 3]
```diff
@@ -192,6 +194,24 @@ func (bs *Server) StreamBlocks(_ *ptypes.Empty, stream ethpb.BeaconChain_StreamB
...
 					continue
 				}
+				if featureconfig.Get().NewStateMgmt {
+					hasStateSummaryDB := bs.BeaconDB.HasStateSummary(bs.Ctx, bytesutil.ToBytes32(data.SignedBlock.Block.ParentRoot))
+					hasStateSummaryCache := bs.StateSummaryCache.Has(bytesutil.ToBytes32(data.SignedBlock.Block.ParentRoot))
+					if !hasStateSummaryDB && !hasStateSummaryCache {
+						log.WithField("blockSlot", data.SignedBlock.Block.Slot).Warn("No access to parent state to verify block signature")
+						continue
+					}
+					parentState, err := bs.StateGen.StateByRoot(bs.Ctx, bytesutil.ToBytes32(data.SignedBlock.Block.ParentRoot))
```
Comment (0xKiwi) [inline beacon-chain/rpc/beacon/blocks.go:204]: Have you checked how expensive it is to look up the parent root? This also assumes we have the parent root for every block we get, is there a reason we can't use head state?

Comment (shayzluf) [reply beacon-chain/rpc/beacon/blocks.go:204]: terence suggested it will be less accurate when i asked. worth checking again

File: beacon-chain/rpc/beacon/blocks.go [hunk 4]
```diff
@@ -192,6 +194,18 @@ func (bs *Server) StreamBlocks(_ *ptypes.Empty, stream ethpb.BeaconChain_StreamB
 					// One nil block shouldn't stop the stream.
 					continue
 				}
+				if featureconfig.Get().NewStateMgmt {
```
Comment (0xKiwi) [inline beacon-chain/rpc/beacon/blocks.go:197]: Is this check still needed?

File: beacon-chain/rpc/beacon/blocks.go [hunk 5]
```diff
@@ -192,6 +194,18 @@ func (bs *Server) StreamBlocks(_ *ptypes.Empty, stream ethpb.BeaconChain_StreamB
...
+					headState, err := bs.HeadFetcher.HeadState(bs.Ctx)
```
Comment (terencechain) [inline beacon-chain/rpc/beacon/blocks.go:198]: Dont need `NewStateMgmt` for `bs.HeadFetcher.HeadState(`

File: beacon-chain/sync/validate_beacon_blocks_test.go [hunk 6]
```diff
@@ -51,15 +51,17 @@ func TestValidateBeaconBlockPubSub_InvalidSignature(t *testing.T) {
 	if err != nil {
 		t.Fatal(err)
 	}
+	chainService := &mock.ChainService{Genesis: time.Now(),
```
Comment (terencechain) [inline beacon-chain/sync/validate_beacon_blocks_test.go:54]: Thanks for doing this! Much cleaner

File: beacon-chain/rpc/beacon/blocks.go (hunk 4 above)
Comment (shayzluf) [reply beacon-chain/rpc/beacon/blocks.go:197]: sure

File: beacon-chain/rpc/beacon/blocks.go (hunk 5 above)
Comment (shayzluf) [reply beacon-chain/rpc/beacon/blocks.go:198]: thanks

File: beacon-chain/rpc/beacon/blocks.go (hunk 4 above)
Comment (shayzluf) [reply beacon-chain/rpc/beacon/blocks.go]: thanks

File: beacon-chain/sync/validate_beacon_blocks_test.go (hunk 6 above)
Comment (shayzluf) [reply beacon-chain/sync/validate_beacon_blocks_test.go:54]: thanks you for helping to make it clean
