### PR TITLE
Don't create payload with same timestamp as terminal block

### LINKED ISSUE #11069: Transition payload production might fail if the TTD block timestamp coincides with the slot time
# 🐞 Bug Report

### Description

Transition payload production might fail with the following error if the TTD block matches the slot time, because Prysm attempts to produce a payload with `timestamp==parent.timestamp`, where `parent` is the terminal PoW block.

Block is skipped in the beacon chain because of this.

### Has this worked before in a previous version?

Not sure.

## 🔬 Minimal Reproduction

Using branch https://github.com/marioevz/hive/tree/all-tests-plus-cl-clients and the following command reproduces the issue every time:
```
go build -v .
./hive --client go-ethereum,prysm-bn,prysm-vc --sim eth2/engine --sim.limit "/equal-timestamp-terminal-transition-block" --sim.logle
vel 5
```

## 🔥 Error

[Geth/v1.10.21-unstable-a7d47ee7-20220718]
<pre><code>
TRACE[07-19|02:07:23.238] Engine API request received              method=ForkchoiceUpdated head=b26e6a..d45b18 finalized=000000..000000 safe=b26e6a..d45b18
ERROR[07-19|02:07:23.238] Failed to create empty sealing payload   err="invalid timestamp, parent 1658196443 given 1658196443"
WARN [07-19|02:07:23.238] Served engine_forkchoiceUpdatedV1        conn=172.17.0.3:38672 reqid=274 duration="323.194µs"        err="Invalid payload attributes"           errdata="{Error:invalid timestamp, parent 1658196443 given 1658196443}"
</code></pre>

[validator version Prysm/v2.1.3/97dc9ebbc8bb3e8a8bbc25195d338211e5c2a44d. Built at: 2022-07-18 15:58:45+00:00]
<pre><code>
time="2022-07-19 02:07:23" level=error msg="Failed to request block from beacon node" blockSlot=78 error="rpc error: code = Unknown desc = could not prepare payload: payload attributes are invalid / inconsistent" prefix=validator pubKey=0x8c405832ec39
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04.6 LTS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
beacon-chain version Prysm/v2.1.3/97dc9ebbc8bb3e8a8bbc25195d338211e5c2a44d. Built at: 2022-07-18 15:44:24+00:00
validator version Prysm/v2.1.3/97dc9ebbc8bb3e8a8bbc25195d338211e5c2a44d. Built at: 2022-07-18 15:58:45+00:00
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
Docker version 20.10.17, build 100c701

### PR DESCRIPTION
**Pull request by terencechain**
Fixes #11069

This PR fixes an issue where prysm will create a transition block where `block.execution_payload().timestamp == terminal_block.timestamp` and such block would have failed `forkchoiceUpdate` call

### CODE REVIEW

File: beacon-chain/powchain/engine_client.go [hunk 1]
```diff
@@ -254,13 +254,23 @@ func (s *Service) GetTerminalBlockHash(ctx context.Context) ([]byte, bool, error
...
+			// If terminal block has time same timestamp or greater than transition time,
+			// then the node violates the invariant that a block's timestamp must be
+			// greater than its parent's timestamp. Execution layer will reject
+			// a fcu call with such payload attributes. It's best that we return `None` in this a case.
 			parentReachedTTD := parentTotalDifficulty.Cmp(terminalTotalDifficulty) >= 0
 			if !parentReachedTTD {
+				if blk.Time >= transitionTime {
+					return nil, false, nil
+				}
+
```
Comment (terencechain) [inline beacon-chain/powchain/engine_client.go:273]: review

Comment (potuz) [reply beacon-chain/powchain/engine_client.go:273]: I am worried about this solution, the transition time being passed to this function is purely on the CL side (you're passing a slot time) while the condition we want to prevent is that the block timestamp is not that of the TTD. Why not simply comparing the timestamp of these two blocks here instead of comparing to `transitionTime`?

**Review by potuz — APPROVED** [review]
