### PR TITLE
Fix Issues With Peer Handshakes

### LINKED ISSUE #5741: Nodes Send Status Requests for Inbound Dials
🐞 Bug Report

### Description

Currently Prysm nodes send status requests irregardless whether the connection is inbound/outbound. 

## 🔬 Minimal Reproduction

Peer a prysm node with any other node, no matter which is the initiating dialer, the prysm node 
will send in a status request. This is incorrect according to the networking spec, as only the initiating 
peer sends in the status request.

## 🔥 Error

N.A

## 🌍  Your Environment

**Operating System:**

N.A

**What version of Prysm are you running? (Which release)**

4958c0372ce335e2caa9e68732e8949f0cadc3ce

**Anything else relevant (validator index / public key)?**

N.A

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

- [x] Does not perform status requests on inbound dials, instead waiting for the peer
to send their status request and then appropriately responding. 
- [x] Prevents multiple handshakes happening for the same peer at once to prevent multiple redundant goodbyes.
- [x] We add a small delay for each goodbye, so that it gives enough time for the remote peer to be able to read the message. 

**Which issues(s) does this PR fix?**

Fixes #5741 #5796 

**Other notes for review**

### CODE REVIEW

File: beacon-chain/p2p/handshake.go [hunk 1]
```diff
@@ -16,39 +19,107 @@ import (
 // and validating the response from the peer.
 func (s *Service) AddConnectionHandler(reqFunc func(ctx context.Context, id peer.ID) error,
 	goodbyeFunc func(ctx context.Context, id peer.ID) error) {
+
+	// peer map and lock to keep track of current connection attempts.
```
Comment (terencechain) [inline beacon-chain/p2p/handshake.go:23]:
```suggestion
	// Peer map and lock to keep track of current connection attempts.
```

File: beacon-chain/p2p/handshake.go [hunk 2]
```diff
@@ -16,39 +19,107 @@ import (
...
+				}
+				s.peers.SetConnectionState(remotePeer, peers.PeerDisconnected)
 			}
-			s.peers.Add(nil /* ENR */, conn.RemotePeer(), conn.RemoteMultiaddr(), conn.Stat().Direction)
-			if len(s.peers.Active()) >= int(s.cfg.MaxPeers) {
-				go func() {
+			// Connection handler must be non-blocking as part of libp2p design.
+			go func() {
+				if peerHandshaking(remotePeer) {
+					// exit this if there is already another connection
```
Comment (terencechain) [inline beacon-chain/p2p/handshake.go:64]:
```suggestion
					// Exit this if there is already another connection
```

**Comment by nisdas** [comment]
@farazdagi alright changed it so as to declare them as constants first. Although I am not sure on this point. 
> not sure if repeatPeerConnections is used anywhere. It is declared in monigoring.go and then incremented, but not sure whether its data is used anywhere.
This is for our prometheus metrics collection, it usually isn't used anywhere else. 

@terencechain Yeap this is a bit complicated to do, as there as many moving parts to this. The handshake process involves code from `sync` too and has a lot of pre-conditions which will be difficult to write a test for. On top of that testing libp2p related paths are non-trivial.

File: beacon-chain/p2p/monitoring.go [hunk 3]
```diff
@@ -11,6 +11,10 @@ var (
 		Help: "The number of peers in a given state.",
 	},
 		[]string{"state"})
+	repeatPeerConnections = promauto.NewCounter(prometheus.CounterOpts{
+		Name: "p2p_repeat_attempts",
+		Help: "The number of repeat attempts the connection handler is triggered for a peer.",
```
Comment (shayzluf) [inline beacon-chain/p2p/monitoring.go:16]:
```suggestion
		Help: "The number of repeated attempts to connect to peers.",
```

File: beacon-chain/sync/rpc_goodbye.go [hunk 4]
```diff
@@ -38,7 +38,7 @@ func (r *Service) goodbyeRPCHandler(ctx context.Context, msg interface{}, stream
 		return fmt.Errorf("wrong message type for goodbye, got %T, wanted *uint64", msg)
 	}
 	log := log.WithField("Reason", goodbyeMessage(*m))
-	log.WithField("peer", stream.Conn().RemotePeer()).Info("Peer has sent a goodbye message")
+	log.WithField("peer", stream.Conn().RemotePeer()).Debug("Peer has sent a goodbye message")
```
Comment (shayzluf) [inline beacon-chain/sync/rpc_goodbye.go:41]: currently it takes so long to get peers for me. if i just see them connect and don't see that they disconnected i won't understand what is happening and why my node doesn't sync already

File: beacon-chain/p2p/handshake.go [hunk 5]
```diff
@@ -4,51 +4,134 @@ import (
...
+						disconnectFromPeer()
+						return
+					}
+					if peerExists {
+						updated, err := s.peers.ChainStateLastUpdated(remotePeer)
+						if err != nil {
+							disconnectFromPeer()
+							return
+						}
+						if !updated.After(currentTime) {
```
Comment (shayzluf) [inline beacon-chain/p2p/handshake.go:125]: why are we disconnecting in this case?

File: beacon-chain/sync/rpc_goodbye.go (hunk 4 above)
Comment (nisdas) [reply beacon-chain/sync/rpc_goodbye.go:41]: We have close to 100 goodbye logs in a minute, we should definitely not put it into a `Info` log. This will spam the node. If you need to debug further you can change the verbosity of it.

File: beacon-chain/p2p/handshake.go (hunk 5 above)
Comment (nisdas) [reply beacon-chain/p2p/handshake.go:125]: Because they haven't sent a status message.

File: beacon-chain/p2p/monitoring.go (hunk 3 above)
Comment (nisdas) [reply beacon-chain/p2p/monitoring.go:16]: Dont agree with the change, its not repeated connection attempts, its the connection handler getting triggered multiple times, the distinction is important here. A peer can only be connected once to another peer.

File: beacon-chain/p2p/handshake.go (hunk 5 above)
Comment (shayzluf) [reply beacon-chain/p2p/handshake.go:136]: thanks

File: beacon-chain/sync/rpc_goodbye.go (hunk 4 above)
Comment (shayzluf) [reply beacon-chain/sync/rpc_goodbye.go:41]: sg
