### PR TITLE
Nil state fallback in Blockchain.HeadState()

### LINKED ISSUE #4037: Handle Missing Data Fallback in Blockchain.HeadState()
Issues such as #4036 shows that headFetcher.HeadState() is not a safe function. It should:

- Check if the state is nil, if so
- Fallback into checking from the DB
- If that fails or is nil, return an error

This will prevent most problems we have been seeing regarding panics at runtime

### PR DESCRIPTION
**Pull request by terencechain**
This fixes #4037 and #4036

### CODE REVIEW

**Comment by terencechain** [comment]
Yes. Regardless this is needed to alleviate test net and downgrade p0 issue to p3. 
The nil state could be happening due to race. Likely rpc service got init'ed before chain service

File: beacon-chain/blockchain/chain_info.go [hunk 1]
```diff
@@ -88,11 +90,24 @@ func (s *Service) HeadBlock() *ethpb.BeaconBlock {
...
 	defer s.headLock.RUnlock()
 
-	return proto.Clone(s.headState).(*pb.BeaconState)
+	if s.headState == nil {
+		h, err := s.beaconDB.HeadState(ctx)
+		if err != nil {
+			return nil, err
+		}
+		if h == nil {
+			return nil, errors.New("head state does not exists")
```
Comment (rauljordan) [inline beacon-chain/blockchain/chain_info.go]:
```suggestion
			return nil, errors.New("head state does not exist")
```
