### PR TITLE
Accounts-V2: Fix wallet-v2 recover and wallet-v2 create for derived

### LINKED ISSUE #7068: When I recover mnemonic, it always generates a new one instead
# 🐞 Bug Report

### Description

I cannot recover mnemonic phrase. When I recover mnemonic, it always generates a new one instead. 

### Has this worked before in a previous version?

Yes It worked before.  I think version alpha-20

## 🔬 Minimal Reproduction

1. Generate new wallet `./prysm.sh validator wallet-v2 create`
2. Generate account `./prysm.sh validator accounts-v2 create`
3. Step 2 gives mnemonic
4. Delete wallet folder
5. Use mnemonic in step 3 to recover: `./prysm.sh validator wallet-v2 recover` but it generates a new one:
```
Starting Prysm validator wallet-v2 recover --wallet-password-file=./prysm-wallet-v2-password.txt --wallet-dir=./prysm-wallet-v2
Enter the language of your seed phrase: chinese_simplified, chinese_traditional, english, french, italian, japanese, korean, spanish:
english
Enter the seed phrase for the wallet you would like to recover:
[my mnemonic here]
[2020-08-20 20:00:01]  INFO derived-keymanager-v2: Write down the sentence below, as it is your only means of recovering your wallet
=================Wallet Seed Recovery Phrase====================

[a new mnemonic here]

===================================================================
Enter how many accounts you would like to recover (default: 0):
1

```

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Mac OS
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
alpha-23
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by 0xKiwi**
**What type of PR is this?**
Bug fix

**What does this PR do? Why is it needed?**
Fixes #7068, this PR fixes 2 major bugs with accounts-v2 wallet. One prevents properly recovering an account, while the other would not create a mnemonic until an account was created.

### CODE REVIEW

File: validator/accounts/v2/wallet_create.go [hunk 1]
```diff
@@ -3,6 +3,8 @@ package v2
 import (
 	"context"
 
+	"github.com/prysmaticlabs/prysm/validator/flags"
+
```
Comment (rauljordan) [inline validator/accounts/v2/wallet_create.go:7]:
```suggestion
```
