### PR TITLE
Fix issue with custom chain/network ID configuration

### LINKED ISSUE #8108: Wrong chain ID when configuring testnet
# 🐞 Bug Report

### Description

When configuring a custom testnet, the chain ID and network ID config variables are ignored.

### Has this worked before in a previous version?

It appears that the current testnets all hardcode the variables, whereas it should be configurable.

See #6727

## 🔬 Minimal Reproduction

Load a custom testnet config, containing:
```
# Ethereum goerli testnet
DEPOSIT_CHAIN_ID: 5
DEPOSIT_NETWORK_ID: 5
```

## 🔥 Error

<pre><code>
time="2020-12-14 14:11:40" level=debug msg="Trying to dial endpoint: https:// (our goerli endpoint, ignore this) " prefix=powchain
time="2020-12-14 14:11:41" level=error msg="Could not connect to powchain endpoint" error="could not dial eth1 nodes: eth1 node using incorrect chain id, 5 != 1" prefix=powchain
</code></pre>

## 🌍  Your Environment

.

**What version of Prysm are you running? (Which release)**

v1.0.4

**Anything else relevant (validator index / public key)?**
-

cc @parithosh who is working on testnets, new to the EF Eth2 devops team

### PR DESCRIPTION
**Pull request by farazdagi**
**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**
- [x] Allows to use `DEPOSIT_CHAIN_ID` and `DEPOSIT_NETWORK_ID` in network configuration file.
  - Moves `ChainID` and `NetworkID` from `params/network_config.go -> params/config_go` and updates all corresponding references
- [x] In addition to `DEPOSIT_CHAIN_ID` and `DEPOSIT_NETWORK_ID`, the following parameters have been exposed (overridable via config file):
  - `RANDOM_SUBNETS_PER_VALIDATOR `
  - `EPOCHS_PER_RANDOM_SUBNET_SUBSCRIPTION`
  - `DEPOSIT_CONTRACT_ADDRESS`
- [x] Improves tests (to cover all the exposed parameters):
  - Checks all the parameters from [/eth2.0-spec-tests/master/tests/minimal/config/phase0.yaml](https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/minimal/config/phase0.yaml) i.e. not only we ensure that `DEPOSIT_CHAIN_ID` and `DEPOSIT_NETWORK_ID` are correctly loaded from config file, but any of the parameters from `phase0.yaml` 
- [x] Fixes incorrect values in `minimal_config.go`:
  - `MinGenesisTime`
  - `TargetAggregatorsPerCommittee `

**Which issues(s) does this PR fix?**

Fixes #8108

**Other notes for review**

### CODE REVIEW

File: shared/params/loader.go [hunk 1]
```diff
@@ -19,6 +19,10 @@ func LoadChainConfigFile(chainConfigFileName string) {
 	// Convert 0x hex inputs to fixed bytes arrays
 	lines := strings.Split(string(yamlFile), "\n")
 	for i, line := range lines {
+		// Ignore for deposit contract address - configuration object defines it as a string.
```
Comment (terencechain) [inline shared/params/loader.go:22]: Why ignore deposit contract address from config yaml? Is the reason solely due to string?

I'm concernd users will report this as a bug

Comment (farazdagi) [reply shared/params/loader.go:22]: We are **not** ignoring it from YAML config (we actually **ignored** it before, and this PR makes sure it is used, and users can pass that paramter *in config file* and override our hard-coded values). So, it is ignored from "conversion" (should I update the comment, it seems it is confusing??).

Now why we do not need to convert (ignore from conversions), it is because we use `0x` number as string, our code expects is as string:
https://github.com/prysmaticlabs/prysm/blob/ff64fdcfb53047948e558b9ca2b8fe1d41a60977/shared/params/network_config.go#L32

So, I do not need to convert, we are already in format our code expects (string).
The reason we have that string -> []byte conversion is because other params, like `GENESIS_FORK_VERSION` or `BLS_WITHDRAWAL_PREFIX` are  fixed byte arrays:
https://github.com/prysmaticlabs/prysm/blob/ff64fdcfb53047948e558b9ca2b8fe1d41a60977/shared/params/config.go#L112-L113

**Review by terencechain — DISMISSED** [review]

**Review by terencechain — APPROVED** [review]
