### PR TITLE
Handle Syncing Executon Client

### LINKED ISSUE #13566: Panic occurred" error="runtime error: index out of range [0] with length 0"
### Error

```text
time="2024-01-31 23:17:00" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-01-31 23:17:01" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x44040f2619c8 prefix=blockchain slot=8326283
time="2024-01-31 23:17:01" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xd2a9667ceb49 headPayloadBlockHash=0x44040f2619c8 headSlot=8326283 prefix=blockchain
time="2024-01-31 23:17:01" level=info msg="Synced new block" block=0xff62a4f5... epoch=260196 finalizedEpoch=260194 finalizedRoot=0x1a4e6a3f... prefix=blockchain slot=8326283
time="2024-01-31 23:17:01" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x44040f2619c8 prefix=blockchain slot=8326283 syncBitsCount=510 txCount=151
time="2024-01-31 23:17:14" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x26b5850591c8 prefix=blockchain slot=8326284
time="2024-01-31 23:17:14" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xd2a9667ceb49 headPayloadBlockHash=0x26b5850591c8 headSlot=8326284 prefix=blockchain
time="2024-01-31 23:17:14" level=info msg="Synced new block" block=0x757907db... epoch=260196 finalizedEpoch=260194 finalizedRoot=0x1a4e6a3f... prefix=blockchain slot=8326284
time="2024-01-31 23:17:14" level=info msg="Finished applying state transition" attestations=68 payloadHash=0x26b5850591c8 prefix=blockchain slot=8326284 syncBitsCount=508 txCount=124
time="2024-01-31 23:17:14" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-01-31 23:17:22" level=info msg="Peer summary" activePeers=70 inbound=0 outbound=70 prefix=p2p
time="2024-01-31 23:17:24" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x7bf92824cdf6 prefix=blockchain slot=8326285
time="2024-01-31 23:17:25" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xd2a9667ceb49 headPayloadBlockHash=0x7bf92824cdf6 headSlot=8326285 prefix=blockchain
time="2024-01-31 23:17:25" level=info msg="Synced new block" block=0xe412f89c... epoch=260196 finalizedEpoch=260194 finalizedRoot=0x1a4e6a3f... prefix=blockchain slot=8326285
time="2024-01-31 23:17:25" level=info msg="Finished applying state transition" attestations=66 payloadHash=0x7bf92824cdf6 prefix=blockchain slot=8326285 syncBitsCount=505 txCount=128
time="2024-01-31 23:17:28" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-01-31 23:17:34" level=error msg="Panic occurred" error="runtime error: index out of range [0] with length 0" prefix=sync recovered_at=registerRPC stack="goroutine 32252522 [running]:
runtime/debug.Stack()
        GOROOT/src/runtime/debug/stack.go:24 +0x5e
github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*Service).registerRPC.func1.1()
        beacon-chain/sync/rpc.go:132 +0x1d6
panic({0x5e9c00?, 0xc1436be7e0?})
        GOROOT/src/runtime/panic.go:920 +0x270
github.com/prysmaticlabs/prysm/v4/beacon-chain/execution.(*Service).retrievePayloadsFromExecutionHashes(0xd93cfac3d3e0ba49?, {0xd1b740, 0xc136a5a3f0}, {0xc09d812600?, 0xd, 0x10}, {0xc0a7a42180, 0xd, 0x0?}, {0xc09d2fd100, ...})
        beacon-chain/execution/engine_client.go:657 +0x3f0
github.com/prysmaticlabs/prysm/v4/beacon-chain/execution.(*Service).ReconstructFullBellatrixBlockBatch(0xc09d80b580?, {0xd1b740, 0xc136a5a3f0}, {0xc09d2fd100, 0xd, 0x10})
        beacon-chain/execution/engine_client.go:604 +0x696
github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*Service).writeBlockBatchToStream(0xc000176480, {0xd1b778?, 0xc0a4e12230?}, {0x7f0c81, 0x7f0cc0, {0xc10f26a500, 0xd, 0xd}, {0x37aa600, 0x0, ...}, ...}, ...)
        beacon-chain/sync/rpc_beacon_blocks_by_range.go:151 +0x571
github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*Service).beaconBlocksByRangeRPCHandler(0xc000176480, {0xd1b740?, 0xc14755c960?}, {0x63f940?, 0xc1104292c0}, {0xd30e20, 0xc09d1b0f80})
        beacon-chain/sync/rpc_beacon_blocks_by_range.go:72 +0xe68
github.com/prysmaticlabs/prysm/v4/beacon-chain/sync.(*Service).registerRPC.func1({0xd30e20?, 0xc09d1b0f80})
        beacon-chain/sync/rpc.go:215 +0xfd5
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0x47fc80?, 0x74cb29?}, {0x7f6ee7336100?, 0xc09d1b0f80})
        external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:598 +0x3f
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler(0xc0003b2a80, {0xd30e20, 0xc09d1b0f80})
        external/com_github_libp2p_go_libp2p/p2p/host/basic/basic_host.go:440 +0x5d9
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).start.func1.1()
        external/com_github_libp2p_go_libp2p/p2p/net/swarm/swarm_conn.go:137 +0xa7
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).start.func1 in goroutine 32008611
        external/com_github_libp2p_go_libp2p/p2p/net/swarm/swarm_conn.go:123 +0x1d6
" topic="/eth2/beacon_chain/req/beacon_blocks_by_range/2/ssz_snappy"
time="2024-01-31 23:17:36" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x785361a25146 prefix=blockchain slot=8326286
time="2024-01-31 23:17:36" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xd2a9667ceb49 headPayloadBlockHash=0x785361a25146 headSlot=8326286 prefix=blockchain
time="2024-01-31 23:17:36" level=info msg="Synced new block" block=0x573e6e25... epoch=260196 finalizedEpoch=260194 finalizedRoot=0x1a4e6a3f... prefix=blockchain slot=8326286
time="2024-01-31 23:17:36" level=info msg="Finished applying state transition" attestations=66 payloadHash=0x785361a25146 prefix=blockchain slot=8326286 syncBitsCount=511 txCount=129
time="2024-01-31 23:17:42" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-01-31 23:17:48" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x9f04ab2095cf prefix=blockchain slot=8326287
time="2024-01-31 23:17:48" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xd2a9667ceb49 headPayloadBlockHash=0x9f04ab2095cf headSlot=8326287 prefix=blockchain
time="2024-01-31 23:17:48" level=info msg="Synced new block" block=0xf9c7760f... epoch=260196 finalizedEpoch=260194 finalizedRoot=0x1a4e6a3f... prefix=blockchain slot=8326287
time="2024-01-31 23:17:48" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x9f04ab2095cf prefix=blockchain slot=8326287 syncBitsCount=509 txCount=191
time="2024-01-31 23:17:56" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-01-31 23:18:02" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x1e9bfe664ead prefix=blockchain slot=8326288
time="2024-01-31 23:18:02" level=info msg="Called fork choice updated with optimistic block" finalizedPayloadBlockHash=0xd2a9667ceb49 headPayloadBlockHash=0x1e9bfe664ead headSlot=8326288 prefix=blockchain
time="2024-01-31 23:18:02" level=info msg="Synced new block" block=0x67a4faf1... epoch=260196 finalizedEpoch=260194 finalizedRoot=0x1a4e6a3f... prefix=blockchain slot=8326288
time="2024-01-31 23:18:02" level=info msg="Finished applying state transition" attestations=128 payloadHash=0x1e9bfe664ead prefix=blockchain slot=8326288 syncBitsCount=509 txCount=225
time="2024-01-31 23:18:10" level=warning msg="Execution client is not syncing" prefix=execution
```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

Prysm/v4.2.1/59b310a2216c57fcf67ea0fdec739dad07aeec8b.

### PR DESCRIPTION
**Pull request by nisdas**
**What type of PR is this?**

Bug Fix

**What does this PR do? Why is it needed?**

Handles the case where an EL is syncing and cannot provide us with the desired payloads.

**Which issues(s) does this PR fix?**

Fixes #13566

**Other notes for review**

### CODE REVIEW

File: beacon-chain/execution/engine_client.go [hunk 1]
```diff
@@ -649,6 +651,10 @@ func (s *Service) retrievePayloadsFromExecutionHashes(
 		return nil, fmt.Errorf("could not fetch payload bodies by hash %#x: %v", executionHashes, err)
 	}
 
+	if len(payloadBodies) != len(executionHashes) {
```
Comment (nalepae) [inline beacon-chain/execution/engine_client.go:654]: Should not this check be directly in the `GetPayloadBodiesByHash` function?

According to [the specification](https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_getpayloadbodiesbyhashv1), is such a length mismatch happen, it is a bug in the EL.

If this check is written directly in the `GetPayloadBodiesByHash` function, then all calls to this function will benefit of this check.

In the contrary, all callers of `GetPayloadBodiesByHash`will need to do the same check.

**Review by terencechain — APPROVED** [review]

File: beacon-chain/execution/engine_client.go (hunk 1 above)
Comment (nisdas) [reply beacon-chain/execution/engine_client.go:654]: In the case referenced in the issue description the node is optimistically syncing which indicates that the EL might have just come online, which is why they return nothing instead of empty payloads.  It might be a race condition on the EL's side but in the event of bugs across different clients we can just handle it on our end. I have pushed up the change to handle the mismatch in the function

**Review by nalepae — APPROVED** [review]
