### PR TITLE
Guard against deleting genesis and finalized state in DB

### LINKED ISSUE #3841: Panic on startup
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1091680]

goroutine 171 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(Service).initializeChainInf
o(0xc000a4b500, 0x186ad00, 0xc000044040, 0x0, 0x0)
beacon-chain/blockchain/service.go:316 +0x2d0
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(Service).Start(0xc000a4b500
)
beacon-chain/blockchain/service.go:112 +0x1a8
created by github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StartAll
shared/service_registry.go:44 +0x23e
```

Offending line of code: https://github.com/prysmaticlabs/prysm/blob/be5451abef69a9b501945f96e36f03b6bb8874ae/beacon-chain/blockchain/service.go#L316

Not sure how to reproduce yet, asked user for copy of beaconchain.db.

### PR DESCRIPTION
**Pull request by terencechain**
Change list:
- Revert the order on `SaveFinalizedCheckpoint` and `rmStatesBySlots`
- Guard `DeleteState` against deleting genesis and finalized states

Resolves #3841

### CODE REVIEW

File: beacon-chain/blockchain/forkchoice/process_block.go [hunk 1]
```diff
@@ -381,11 +382,6 @@ func (s *Store) rmStatesBySlots(ctx context.Context, startSlot uint64, endSlot u
 	ctx, span := trace.StartSpan(ctx, "forkchoice.rmStatesBySlots")
 	defer span.End()
 
-	// Do not remove genesis state.
```
Comment (prestonvanloon) [inline beacon-chain/blockchain/forkchoice/process_block.go]: Why remove this?

File: beacon-chain/db/kv/state.go [hunk 2]
```diff
@@ -104,8 +105,21 @@ func (k *Store) SaveState(ctx context.Context, state *pb.BeaconState, blockRoot
...
+		return err
+	}
+
 	return k.db.Batch(func(tx *bolt.Tx) error {
-		bkt := tx.Bucket(stateBucket)
+		bkt := tx.Bucket(blocksBucket)
+		genesisBlockRoot := bkt.Get(genesisBlockRootKey)
+		// Safe guard against deleting genesis or finalized state.
+		if bytes.Equal(blockRoot[:], finalizedCheckpt.Root) || bytes.Equal(blockRoot[:], genesisBlockRoot) {
+			return nil
```
Comment (prestonvanloon) [inline beacon-chain/db/kv/state.go]: This should be an error

File: beacon-chain/blockchain/forkchoice/process_block.go (hunk 1 above)
Comment (terencechain) [reply beacon-chain/blockchain/forkchoice/process_block.go]: Yeah. You are right. I should have it back as 2nd layer check

File: beacon-chain/db/kv/state.go [hunk 3]
```diff
@@ -104,8 +105,21 @@ func (k *Store) SaveState(ctx context.Context, state *pb.BeaconState, blockRoot
 func (k *Store) DeleteState(ctx context.Context, blockRoot [32]byte) error {
 	ctx, span := trace.StartSpan(ctx, "BeaconDB.DeleteState")
 	defer span.End()
+
+	finalizedCheckpt, err := k.FinalizedCheckpoint(ctx)
```
Comment (prestonvanloon) [inline beacon-chain/db/kv/state.go]: Can you do this in the batch? it would make it faster with batch processing / go routines
