### PR TITLE
Fix an edge case when loading replay start state by slot

### LINKED ISSUE #7298: ListValidatorBalances responds "Could not get state"
# 🐞 Bug Report

### Description

This GRPC query
```json
{
  "publicKeys": [],
  "indices": [
    "32831"
  ],
  "epoch": "10575"
}
```

leads to an error:
```
Internal (13)
Could not get state
```

### Has this worked before in a previous version?

It worked on the current version because I was running very similar queries without having any problems.

## 🔬 Minimal Reproduction

1. Public API

```
% curl -i "https://api.prylabs.net/eth/v1alpha1/validators/balances?epoch=10575&indices=32831" -H "accept: application/json"
HTTP/2 500 
content-type: application/grpc
grpc-status: 13
grpc-message: Could not get state
x-envoy-upstream-service-time: 1828
x-backend: beacon-chain-prod-4
x-source: unknown
date: Tue, 22 Sep 2020 02:13:59 GMT
server: istio-envoy
content-length: 0
x-backend: beacon-chain-prod-4
x-source: istio-ingressgateway
```

2. GRPC
```
% grpcurl -plaintext -d '{"epoch": "10575","publicKeys": [],"indices": ["32831"]}' -protoset beacon_chain.protoset localhost:4000 ethereum.eth.v1alpha1.BeaconChain/ListValidatorBalances
ERROR:
  Code: Internal
  Message: Could not get state
```

## 🔥 Error

Nothing in logs

## 🌍  Your Environment

**Operating System:**

macOS, Linux

**What version of Prysm are you running? (Which release)**

`v1.0.0-alpha.25`

**Anything else relevant (validator index / public key)?**

epoch=10575

indices=[32831]

### PR DESCRIPTION
**Pull request by terencechain**
Fixes #7298

This ensures when `loadStateBySlot` is used, the correct parent state is used to replay the first block.

Verified and tested this fix on the incident DB, confirmed the fix is valid

### CODE REVIEW

File: beacon-chain/state/stategen/replay.go [hunk 1]
```diff
@@ -27,7 +27,10 @@ func (s *State) ReplayBlocks(ctx context.Context, state *state.BeaconState, sign
 			if state.Slot() >= targetSlot {
 				break
 			}
-
+			// A node shouldn't process the block if the block slot is lower than the state slot.
```
Comment (prestonvanloon) [inline beacon-chain/state/stategen/replay.go:30]: Want to add a test for this?

Comment (terencechain) [reply beacon-chain/state/stategen/replay.go:30]: Sure

Comment (terencechain) [reply beacon-chain/state/stategen/replay.go:30]: Done, thanks

**Review by prestonvanloon — APPROVED** [review]
