### PR TITLE
Keymanager fixes for bad file writes

### LINKED ISSUE #12281: keystore: Deleting keys via keymanager API may not fully delete keys
# 🐞 Bug Report

### Description

When attempting to delete keys from the validator keystores, the process first deletes the key from the in-memory keystore then attempts to save the keystore to disk. If they keystore fails to save to disk, the in memory keystore is still modified and users may be convinced that the keys were indeed removed unless they restarted the validator.

Current flow:
1) Call DELETE /eth/v1/keystores with `n` public keys 
2) Delete public keys from in memory keystore
3) [Log success](https://github.com/prysmaticlabs/prysm/blob/52d72c989eb3955fed0cd8d9abdc5543e2b7bfc3/validator/keymanager/local/delete.go#L80) (This is a bad message because the routine hasn't completed yet and should not indicate a success yet)
4) Save the in memory keystore to disk
5) [Log success again](https://github.com/prysmaticlabs/prysm/blob/52d72c989eb3955fed0cd8d9abdc5543e2b7bfc3/validator/keymanager/local/delete.go#L96) and return without error

If step 4 fails, the in memory keystore was modified and GET /eth/v1/keystores would indicate that the keys were deleted until the process is restarted and the on disk keystore is reloaded. When paired with the improper success message from line 80, the user can easily be convinced that they properly deleted keys. 

### Has this worked before in a previous version?

No. This is an old bug.

## 🔬 Minimal Reproduction

- Start the validator
- Change the file permissions of the keystore to readonly
- Attempt to delete keys from the keystore via keymanager API

## 🔥 Error

None.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>All</code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>v4.0.2</code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

 Bug fix

**What does this PR do? Why is it needed?**

addresses concerns in #12281 by serializing the process and making sure that local data is not updated until file write is done. if the file is disrupted and cannot finish then the process will roll back.
// 1) Copy the in memory keystore
// 2) Delete the keys from copied in memory keystore
// 3) Save the copy to disk
// 4) Reinitialize account store ~~from disk~~ reinitializing with copy instead
~~// 5) Verify keys are indeed deleted~~ removing this step as the in memory is updated with copy instead of reading from file.
// 6) Return API response

similar steps needed for Import
// 1) Copy the in memory keystore
// 2) Import the keys into copied in memory keystore
// 3) Save the copy to disk
// 4) Reinitialize account store ~~from disk~~ reinitializing with copy instead
~~// 5) Verify keys are indeed Imported~~ removing this step as the in memory is updated with copy instead of reading from file.
// 6) Return Statuses

**Which issues(s) does this PR fix?**

Fixes #12281

### CODE REVIEW

File: validator/keymanager/local/delete.go [hunk 1]
```diff
@@ -16,17 +15,27 @@ import (
...
 ) ([]*ethpbservice.DeletedKeystoreStatus, error) {
 	// Check for duplicate keys and filter them out.
 	trackedPublicKeys := make(map[[fieldparams.BLSPubkeyLength]byte]bool)
 	statuses := make([]*ethpbservice.DeletedKeystoreStatus, 0, len(publicKeys))
-	var store *AccountsKeystoreRepresentation
-	var err error
 	deletedKeys := make([][]byte, 0, len(publicKeys))
+	originalKeyLen := len(km.accountsStore.PublicKeys)
+	// 1) Copy the in memory keystore
+	storeCopy := &accountStore{}
```
Comment (nisdas) [inline validator/keymanager/local/delete.go:33]: its probably better to have this as a receiver method of the `accountStore` struct

File: validator/keymanager/local/delete.go [hunk 2]
```diff
@@ -16,17 +15,25 @@ import (
...
 	// Check for duplicate keys and filter them out.
 	trackedPublicKeys := make(map[[fieldparams.BLSPubkeyLength]byte]bool)
 	statuses := make([]*ethpbservice.DeletedKeystoreStatus, 0, len(publicKeys))
-	var store *AccountsKeystoreRepresentation
-	var err error
 	deletedKeys := make([][]byte, 0, len(publicKeys))
+	originalKeyLen := len(km.accountsStore.PublicKeys)
+	// 1) Copy the in memory keystore
+	storeCopy := km.accountsStore.Copy()
+	//
```
Comment (rauljordan) [inline validator/keymanager/local/delete.go:34]:
```suggestion
```

File: validator/keymanager/local/delete_test.go [hunk 3]
```diff
@@ -83,7 +94,9 @@ func TestLocalKeymanager_DeleteKeystores(t *testing.T) {
 		require.LogsContain(t, hook, fmt.Sprintf("%#x", bytesutil.Trunc(accountPubKey[:])))
 		require.LogsContain(t, hook, "Successfully deleted validator key(s)")
 	})
+
 	t.Run("returns NOT_ACTIVE status for duplicate public key in request", func(t *testing.T) {
+		fmt.Println(wallet.HasWriteFileError)
```
Comment (rauljordan) [inline validator/keymanager/local/delete_test.go:99]:
```suggestion
```

**Review by rauljordan — APPROVED** [review]

File: validator/keymanager/local/delete.go [hunk 4]
```diff
@@ -48,22 +54,31 @@ func (km *Keymanager) DeleteKeystores(
...
-		if err != nil {
-			return nil, errors.Wrap(err, "could not rewrite accounts keystore")
-		}
+		storeCopy.PrivateKeys = append(storeCopy.PrivateKeys[:index], storeCopy.PrivateKeys[index+1:]...)
+		storeCopy.PublicKeys = append(storeCopy.PublicKeys[:index], storeCopy.PublicKeys[index+1:]...)
 		statuses = append(statuses, &ethpbservice.DeletedKeystoreStatus{
 			Status: ethpbservice.DeletedKeystoreStatus_DELETED,
 		})
 		trackedPublicKeys[bytesutil.ToBytes48(publicKey)] = true
+		//
```
Comment (prestonvanloon) [inline validator/keymanager/local/delete.go:67]:
```suggestion
```

File: validator/keymanager/local/delete.go [hunk 5]
```diff
@@ -48,22 +54,31 @@ func (km *Keymanager) DeleteKeystores(
...
 	}
 	if len(deletedKeys) == 0 {
 		return statuses, nil
 	}
+	//3 & 4) save to disk and re-initializes keystore
```
Comment (prestonvanloon) [inline validator/keymanager/local/delete.go:72]:
```suggestion
	// 3 & 4) save to disk and re-initializes keystore
```

File: validator/keymanager/local/delete.go [hunk 6]
```diff
@@ -48,22 +54,31 @@ func (km *Keymanager) DeleteKeystores(
...
+	if err := km.SaveStoreAndReInitialize(ctx, storeCopy); err != nil {
+		return nil, err
+	}
+	//
+	// 5) Verify keys are indeed deleted
+	if len(km.accountsStore.PublicKeys) == originalKeyLen || len(km.accountsStore.PublicKeys) != len(storeCopy.PublicKeys) {
+		return nil, errors.New("keys were not successfully deleted in file")
+	}
+	//
```
Comment (prestonvanloon) [inline validator/keymanager/local/delete.go:81]:
```suggestion

	// 5) Verify keys are indeed deleted
	if len(km.accountsStore.PublicKeys) == originalKeyLen || len(km.accountsStore.PublicKeys) != len(storeCopy.PublicKeys) {
		return nil, errors.New("keys were not successfully deleted in file")
	}

```

File: validator/keymanager/local/import.go [hunk 7]
```diff
@@ -33,7 +39,14 @@ func (km *Keymanager) ImportKeystores(
 	keys := map[string]string{}
 	statuses := make([]*ethpbservice.ImportedKeystoreStatus, len(keystores))
 	var err error
-
+	// 1) Copy the in memory keystore
+	storeCopy := km.accountsStore.Copy()
+	//
```
Comment (prestonvanloon) [inline validator/keymanager/local/import.go:44]:
```suggestion

```

File: validator/keymanager/local/import.go [hunk 8]
```diff
@@ -49,52 +62,67 @@ func (km *Keymanager) ImportKeystores(
...
+	if err := km.SaveStoreAndReInitialize(ctx, storeCopy); err != nil {
 		return nil, err
 	}
-	if err := km.wallet.WriteFileAtPath(ctx, AccountsPath, AccountsKeystoreFileName, encodedAccounts); err != nil {
-		return nil, err
+	// 5) Verify keys are indeed Imported
+	if len(km.accountsStore.PublicKeys) < len(storeCopy.PublicKeys) {
+		return nil, fmt.Errorf("keys were not imported successfully, expected %d got %d", len(storeCopy.PublicKeys), len(km.accountsStore.PublicKeys))
 	}
+	//
```
Comment (prestonvanloon) [inline validator/keymanager/local/import.go:99]:
```suggestion

```

File: validator/keymanager/local/import.go [hunk 9]
```diff
@@ -49,52 +62,67 @@ func (km *Keymanager) ImportKeystores(
...
+			"number of private keys and public keys is not equal: %d != %d", len(privKeys), len(pubKeys),
+		)
+	}
+	// 1) Copy the in memory keystore
+	storeCopy := km.accountsStore.Copy()
+	//
+	// 2) Update store and remove duplicates
+	updateAccountsStoreInMemory(storeCopy, privKeys, pubKeys)
+	//
+	//3 & 4) save to disk and re-initializes keystore
```
Comment (prestonvanloon) [inline validator/keymanager/local/import.go:117]:
```suggestion

	// 2) Update store and remove duplicates
	updateAccountsStoreInMemory(storeCopy, privKeys, pubKeys)

	// 3 & 4) save to disk and re-initializes keystore
```

File: validator/accounts/wallet_create.go [hunk 10]
```diff
@@ -34,6 +34,7 @@ func (acm *AccountsCLIManager) WalletCreate(ctx context.Context) (*wallet.Wallet
 		if !ok {
 			return nil, errors.Wrap(err, ErrCouldNotInitializeKeymanager)
 		}
+
```
Comment (prestonvanloon) [inline validator/accounts/wallet_create.go:37]:
```suggestion
```

This new line in this file seems like an accidental change

File: validator/keymanager/local/delete.go [hunk 11]
```diff
@@ -48,22 +54,31 @@ func (km *Keymanager) DeleteKeystores(
 			})
 			continue
 		}
-		deletedPublicKey := km.accountsStore.PublicKeys[index]
+		//
```
Comment (prestonvanloon) [inline validator/keymanager/local/delete.go:57]:
```suggestion

```

File: validator/keymanager/local/import.go [hunk 12]
```diff
@@ -17,6 +16,13 @@ import (
 )
 
 // ImportKeystores into the local keymanager from an external source.
+// protection history in the database.
```
Comment (prestonvanloon) [inline validator/keymanager/local/import.go:19]: Whats this?

File: validator/keymanager/local/import.go [hunk 13]
```diff
@@ -49,52 +62,67 @@ func (km *Keymanager) ImportKeystores(
...
+	// 5) Verify keys are indeed Imported
+	if len(km.accountsStore.PublicKeys) < len(storeCopy.PublicKeys) {
+		return nil, fmt.Errorf("keys were not imported successfully, expected %d got %d", len(storeCopy.PublicKeys), len(km.accountsStore.PublicKeys))
 	}
+	//
+	// 6) Return Statuses
 	return statuses, nil
 }
 
 // ImportKeypairs directly into the keymanager.
```
Comment (prestonvanloon) [inline validator/keymanager/local/import.go:104]: I think this could be updated. This routine does more than import directly into km

**Review by prestonvanloon — CHANGES_REQUESTED** [review]
A few comments on the commentary, but haven't tested this locally yet

File: validator/keymanager/local/import.go (hunk 12 above)
Comment (james-prysm) [reply validator/keymanager/local/import.go:19]: hmm i wonder where that came from will remove it.

File: validator/keymanager/local/import.go (hunk 13 above)
Comment (james-prysm) [reply validator/keymanager/local/import.go:102]: do you suggest breaking this function up?

File: validator/keymanager/local/keymanager.go [hunk 14]
```diff
@@ -276,44 +337,35 @@ func (km *Keymanager) CreateAccountsKeystore(
...
-			pk := publicKeys[i]
-			_, privKeyExists := existingPrivKeys[string(sk)]
-			_, pubKeyExists := existingPubKeys[string(pk)]
-			if privKeyExists || pubKeyExists {
-				continue
-			}
-			km.accountsStore.PublicKeys = append(km.accountsStore.PublicKeys, pk)
-			km.accountsStore.PrivateKeys = append(km.accountsStore.PrivateKeys, sk)
-		}
+		updateAccountsStoreInMemory(km.accountsStore, privateKeys, publicKeys)
```
Comment (nisdas) [inline validator/keymanager/local/keymanager.go:340]: You don't set `km.accountsStore` after executing this function call. Its better to be explicit of what struct fields are being updated in this method.

File: validator/keymanager/local/import.go [hunk 15]
```diff
@@ -49,52 +60,66 @@ func (km *Keymanager) ImportKeystores(
...
-	encodedAccounts, err := json.MarshalIndent(accountsKeystore, "", "\t")
-	if err != nil {
+	//3 & 4) save to disk and re-initializes keystore
+	if err := km.SaveStoreAndReInitialize(ctx, storeCopy); err != nil {
 		return nil, err
 	}
-	if err := km.wallet.WriteFileAtPath(ctx, AccountsPath, AccountsKeystoreFileName, encodedAccounts); err != nil {
-		return nil, err
+	// 5) Verify keys are indeed Imported
+	if len(km.accountsStore.PublicKeys) < len(storeCopy.PublicKeys) {
```
Comment (nisdas) [inline validator/keymanager/local/import.go:94]: any point of this check now ?

File: validator/keymanager/local/import.go (hunk 13 above)
Comment (prestonvanloon) [reply validator/keymanager/local/import.go:101]: No, I think it's already split up well. I think the comment could mention how this first attempts to save to disk then updates the keymanager rather than "imports directly into keymanager"

**Review by prestonvanloon — APPROVED** [review]
Tested this locally and confirmed that the key is not deleted from the in memory keystore when the keystore is not successfully written to disk. 

LGTM - but please address other comments

File: validator/keymanager/local/keymanager.go [hunk 16]
```diff
@@ -256,17 +264,70 @@ func (km *Keymanager) initializeAccountKeystore(ctx context.Context) error {
 }
 
 // CreateAccountsKeystore creates a new keystore holding the provided keys.
-func (km *Keymanager) CreateAccountsKeystore(
+func (km *Keymanager) CreateAccountsKeystore(ctx context.Context, privateKeys [][]byte, publicKeys [][]byte) (*AccountsKeystoreRepresentation, error) {
+	if err := km.CreateOrUpdateInMemoryAccountsStore(ctx, privateKeys, publicKeys); err != nil {
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply validator/keymanager/local/keymanager.go:268]: Will take a look again this is only used during the wallet creation process with 0 imports perhaps i can make this cleaner

File: validator/keymanager/local/import.go (hunk 15 above)
Comment (james-prysm) [reply validator/keymanager/local/import.go:94]: maybe not I can probably remove this... as the in memory already updated

**Review by prestonvanloon — DISMISSED** [review]

File: validator/keymanager/local/keymanager.go (hunk 14 above)
Comment (james-prysm) [reply validator/keymanager/local/keymanager.go]: updated the name to better represent this.

**Review by rauljordan — APPROVED** [review]

**Review by prestonvanloon — APPROVED** [review]
