### PR TITLE
Ignore deposits with invalid signatures instead of throwing error

### LINKED ISSUE #2857: Fix BLS to work with uncompressed format
For BLS, if the uncompressed format is not compatible, it will cause an issue in [DecompressG2]( https://github.com/phoreproject/bls/blob/master/g2.go#L233)
This was reproduced by the [invalid_sig_new_deposit](https://media.githubusercontent.com/media/ethereum/eth2.0-spec-tests/master/tests/operations/deposit/deposit_minimal.yaml) deposit test, an invalid signature was in uncompressed format and `the process_deposit` function failed with:
```
could not convert bytes to signature: could not unmarshal bytes into signature: unexpected compression mode
```

### PR DESCRIPTION
**Pull request by blacktemplar**
Resolves #2857 

# Description

According to the spec invalid signatures should lead to ignoring the deposit instead of throwing an error. 
Maybe we should add a log for this cases?

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Thanks for proposing this change. However, this is not an acceptable solution for #2857. 

@terencechain do you think it's OK to silently skip a deposit if the signature fails? Is this why we have this boolean argument for verify signatures?

**Comment by terencechain** [comment]
This does not resolve #2857 and it's not ok to silently skip a deposit if the signature fails, there's greater consequences such as deposit count and deposit root. We should discuss what would happen to them

**Comment by blacktemplar** [comment]
@terencechain If I understand you correct you mean the deposit count and deposit root as specified in the specs. If this change would break those, then the problem lies within the spec, since this pull request only realizes the behaviour from the spec, see also my comment in #2857: https://github.com/prysmaticlabs/prysm/issues/2857#issuecomment-513578448

**Comment by nisdas** [comment]
This isnt correct, the solution isnt to skip processing a deposit if a signature fails. The reason this issue was created was because we were having problems with verifying uncompressed signatures from the spec test. The underlying BLS library we use https://github.com/phoreproject/bls , uncompressed signatures are generated differently in the its implementation compared to the python implementation leading to test failures. This is captured in this conversation here: https://discordapp.com/channels/476244492043812875/491437380792877067/591799179425087490

**Comment by rauljordan** [comment]
I agree with the reasoning @nisdas and other team members mentioned above. This doesn't seem like the best approach and quite risky to do IMO. Anything in the core state transition is built to throw an error if it fails and should not advance the state if an error does exist.

**Comment by blacktemplar** [comment]
Since everybody is responding here on the pull request and I am not sure if you read my answer on the issue #2857 I will post it here again:

The specs clearly states that only compressed format is allowed:

> ...
> Respecting bit ordering, `z` is decomposed as `(c_flag, b_flag, a_flag, x)`.
> ...
> A point in G2 is represented as a pair of 384-bit integers `(z1, z2)`. We decompose `z1` as above into `x1`, `a_flag1`, `b_flag1`, `c_flag1` and `z2` into `x2`, `a_flag2`, `b_flag2`, `c_flag2`.
>
>We require:
>
>* ...
>* `c_flag1 == 1`
>* ...

This basically says that the most significant bit must always be one which indicates that the format is compressed (see https://github.com/zkcrypto/pairing/tree/master/src/bls12_381#serialization)

Therefore, any uncompressed signature must be treated as invalid and therefore `bls_verify` should return False.

Our implementation returns an error if the signature is uncompressed. The reason why the test fails and the difference to the spec is, that in the spec there is no error thrown if the signature is invalid but the deposit is silently ignored, i.e. process_deposit returns at this point, see https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#deposits.

So to strictly follow the spec the only change needed would be to return beaconState, nil instead of returning an error in the following line:
https://github.com/prysmaticlabs/prysm/blob/4a422b13f066cbf05afec1c6eab17572d2f88a5b/beacon-chain/core/blocks/block_operations.go#L872

I am only arguing over the specs here. Maybe also an important point for this discussion (again from the specs):

>   # Note: The deposit contract does not check signatures.

this means that an invalid signature (in our case ANY decompressed signature is invalid) is not a client error or something but may be just a malicious actor. So I think if you want to still throw an error then it should at least get handled properly so that all the other deposits get processed normally. We need to process the other deposits after an invalid signature, otherwise we are not doing what the spec says...

**Comment by nisdas** [comment]
@blacktemplar Looking at this again, you are correct that we shouldnt be returning an error for failed signature verification. But it should still be logged for being an invalid signature. 
it would be something like this: 
```go
          log.Errorf("could not verify deposit data signature: %v", err)
          return beaconState, nil
```

**Comment by blacktemplar** [comment]
@nisdas Thanks for the hint, logging is what I asked at the creation of the pull request to begin with ;), but I should have communicated my response to the issue here in the pull request better. I added your proposed logging line.

File: beacon-chain/core/blocks/block_operations.go [hunk 1]
```diff
@@ -864,7 +867,9 @@ func ProcessDeposit(
 			domain := helpers.Domain(beaconState, helpers.CurrentEpoch(beaconState), params.BeaconConfig().DomainDeposit)
 			depositSig := deposit.Data.Signature
 			if err := verifySigningRoot(deposit.Data, pubKey, depositSig, domain); err != nil {
-				return nil, fmt.Errorf("could not verify deposit data signature: %v", err)
+				//ignore this error as in the spec pseudo code
```
Comment (prestonvanloon) [inline beacon-chain/core/blocks/block_operations.go]:
```suggestion
				// Ignore this error as in the spec pseudo code.
```

File: beacon-chain/core/blocks/block_operations.go [hunk 2]
```diff
@@ -864,7 +867,9 @@ func ProcessDeposit(
...
+				log.Errorf("could not verify deposit data signature: %v", err)
```
Comment (prestonvanloon) [inline beacon-chain/core/blocks/block_operations.go]:
```suggestion
				log.Errorf("Skipping deposit: could not verify deposit data signature: %v", err)
```

It would be really nice to have a prometheus metric for this event. Could you follow up with one in another PR?

**Comment by blacktemplar** [comment]
Why is the codecov bot spamming this thread ^^? I added now three unit tests. One for checking the skipping of deposits with invalid signatures, one the skipping of deposits with a valid but uncompressed signature and the third for processing a deposit with a valid (compressed) signature with checkSignature on.

File: beacon-chain/core/blocks/block_operations.go (hunk 2 above)
Comment (blacktemplar) [reply beacon-chain/core/blocks/block_operations.go]: I never worked with Prometheus metrics before so I would have to look into that, but I can definitely try.

**Comment by prestonvanloon** [comment]
yeah.. Not sure why codecov spammed this. Sorry about that!

**Comment by prestonvanloon** [comment]
@blacktemplar I synced your branch with master and fixed the build issues. Unfortunately, there is more test setup required now that we made deposit tree verification and signature verification always on.

Take a look at how some tests use [SetupInitialDeposits](https://github.com/prysmaticlabs/prysm/blob/9d0e9fa77d46d011e2e0d0694f9e23aac52227e3/shared/testutil/helpers.go#L25) to generate deposits that would pass the newly required validation. Specifically when generating the deposit merkle trees (`deposit.Proof`).

Let me or anyone on the team know if you need help with that. We can prioritize this review to prevent further breakages. Lets get your changes in :)

**Comment by blacktemplar** [comment]
I adapted now the tests. The test which is now called TestProcessDeposit_AddsNewValidatorDeposit is very similar to the old one (which I renaimed to TestProcessDeposits_AddsNewValidatorDeposit since it tests ProcessDeposits) except that it calls directly ProcessDeposit, so I am not sure if we want to keep it. But the other two tests are both based on this test with the only difference that the signature is one time invalid and one time uncompressed.
