### PR TITLE
validator startup deadline bug

### LINKED ISSUE #12000: Validator Client Could Shut Down Prematurely
# 🐞 Bug Report

### Description

Depending on when a user starts up their validator client and how long their beacon node takes to sync/get ready a certain fatal error path could be triggered which leads to the validator client being shut down and a user being offline. The root cause of this error is how we apply our deadline here in `PushProposerSettings` 

https://github.com/prysmaticlabs/prysm/blob/develop/validator/client/validator.go#L993

We round up the slot to the end of the epoch here in `RoundUpToNearestEpoch` in the majority of the cases. However if our current slot is the first slot of the epoch, we will not round it up. Instead it will apply the deadline to the end of the current slot. While this is fine if the current time is earlier on in the slot, this becomes an issue if our current time falls towards the end of a slot. If our current time is already close to the end of a slot and the deadline is at the end of it, it might give us a very short time period to execute all the calls in `PushProposerSettings`. In this case our deadline will very likely expire and the validator client will produce a fatal log and shut down. 

The correct solution would be to apply a fixed time period to execute all these calls rather than relying on rounded up slots as being a marker of how long we have to execute these calls. 

Found by Antithesis

cc @0xTylerHolmes

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction

This error is difficult to reproduce as it requires the validator client to start up in a short time period in an epoch (1 second).  

## 🔥 Error

<pre><code>
level=fatal msg="Failed to update proposer settings" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator
</code></pre>

## 🌍  Your Environment

**Operating System:**

x86_64 GNU/Linux

**What version of Prysm are you running? (Which release)**

v3.2.1

**Anything else relevant (validator index / public key)?**

N.A

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

tries to set the deadline for the first run of the pushProposerSettings when very close to the end of epoch to a constant time.

**Which issues(s) does this PR fix?**

Fixes #12000

### CODE REVIEW

File: validator/client/runner.go [hunk 1]
```diff
@@ -59,7 +59,9 @@ func run(ctx context.Context, v iface.Validator) {
 	if v.ProposerSettings() != nil {
 		log.Infof("Validator client started with provided proposer settings that sets options such as fee recipient"+
 			" and will periodically update the beacon node and custom builder (if --%s)", flags.EnableBuilderFlag.Name)
-		if err := v.PushProposerSettings(ctx, km); err != nil {
+		deadline := 12 * time.Second
```
Comment (terencechain) [inline validator/client/runner.go:62]: Probably better to use config instead of 12

**Comment by james-prysm** [comment]
need to add tests

File: validator/client/validator.go [hunk 2]
```diff
@@ -985,13 +985,23 @@ func (v *validator) SetProposerSettings(settings *validatorserviceconfig.Propose
...
-func (v *validator) PushProposerSettings(ctx context.Context, km keymanager.IKeymanager) error {
+func (v *validator) PushProposerSettings(ctx context.Context, km keymanager.IKeymanager, overrideDeadline ...time.Duration) error {
 	if km == nil {
 		return errors.New("keymanager is nil when calling PrepareBeaconProposer")
 	}
-
-	deadline := v.SlotDeadline(slots.RoundUpToNearestEpoch(slots.CurrentSlot(v.genesisTime)))
-	ctx, cancel := context.WithDeadline(ctx, deadline)
+	var deadline time.Time
+	if len(overrideDeadline) > 0 && overrideDeadline[0] > 0*time.Second {
```
Comment (nisdas) [inline validator/client/validator.go:993]: why not just provide the deadline into the main loop ? rather than doing it this way where you have it as an optional parameter

Comment (james-prysm) [reply validator/client/validator.go]: updated based on slack discussion on this feedback.

File: validator/client/runner.go [hunk 3]
```diff
@@ -129,8 +130,9 @@ func run(ctx context.Context, v iface.Validator) {
 
 			if slots.IsEpochStart(slot) && v.ProposerSettings() != nil {
 				go func() {
-					//deadline set for next epoch rounded up
-					if err := v.PushProposerSettings(ctx, km); err != nil {
+					//deadline set for end of epoch
+					epochDeadline := v.SlotDeadline(slot + params.BeaconConfig().SlotsPerEpoch - 1)
```
Comment (nisdas) [inline validator/client/runner.go:134]: This doesn't seem like the end of the epoch, if I am understanding this correctly. If our current slot is 20 , then we would use 51 as the slot for the deadline. However the end of the current epoch would be at the end of slot 31 and not 51. As 51 comes under the next epoch

Comment (james-prysm) [reply validator/client/runner.go:134]: it shouldn't run on slot 20 as the if statement above checks if the slot is epoch start. hope I'm thinking about that correctly..

**Review by nisdas — APPROVED** [review]

**Review by nisdas — APPROVED** [review]
