### PR TITLE
fixed the empty dirs not being removed

### LINKED ISSUE #15442: Blobs by-epoch layout: Empty directories remain
### Describe the bug

When running a beacon node with the `--blob-storage-layout=by-epoch` flag, emptied directories are not removed.

Here directories `88` and `89` remain.

```
by-epoch tree -L 2
.
├── 88
├── 89
├── 90
│   ├── 371176
│   ├── 371177
│   ├── 371178
│   ├── 371179
│   ├── 371180
│   ├── 371181
│   ├── 371182
│   ├── 371183
│   ├── 371184
│   ├── 371185
│   ├── 371186
...
```

Also, when converting from `by-epoch` to `flat`, then the whole `by-epoch` directory remains, with all the (now empty) subdirectories.

### PR DESCRIPTION
**Pull request by Muzry**
**What type of PR is this?**
Bug fix

**What does this PR do? Why is it needed?**
The RemoveAll function in periodicEpochLayout.pruneBefore deletes only the files within a directory, but leaves the directory.
This PR fixes the issue of empty directories not being deleted when using --blob-storage-layout=by-epoch.

**Which issues(s) does this PR fix?**

Partially Fixes #15442

**Other notes for review**
>when converting from by-epoch to flat, then the whole by-epoch directory remains, with all the (now empty) subdirectories. 

This issue is also mentioned in #15442, but I’m unable to reproduce it, so I don’t know how to fix it.

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [x] I have included a uniquely named [changelog fragment file](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md#maintaining-changelogmd).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

### CODE REVIEW

File: beacon-chain/db/filesystem/layout_by_epoch.go [hunk 1]
```diff
@@ -116,19 +116,34 @@ func (l *periodicEpochLayout) pruneBefore(before primitives.Epoch) (*pruneSummar
...
 			}
 		} else {
 			log.WithField("dir", rmdir).WithField("numFailed", len(sum.failedRemovals)).WithError(err).Error("Unable to remove epoch directory due to pruning failures")
 		}
 	}
 
+	//Clean up empty period directories
+	for periodDir := range periodsToCheck {
+		if err := l.fs.Remove(periodDir); err != nil {
+			log.WithField("dir", periodDir).WithError(err).Error("Period directory not empty or failed to remove")
```
Comment (kasey) [inline beacon-chain/db/filesystem/layout_by_epoch.go]: The loop should list the dir first and only attempt to remove empty dirs. Otherwise this approach will create a lot of error log spam, as prune runs every epoch, but we only delete a period directory every 4096 epochs.

**Review by kasey — CHANGES_REQUESTED** [review]
Thanks!

**Comment by Muzry** [comment]
I appreciate your reply and suggestions. I will list the directories first, and then remove any that are empty.

File: beacon-chain/db/filesystem/layout_by_epoch.go (hunk 1 above)
Comment (Muzry) [reply beacon-chain/db/filesystem/layout_by_epoch.go]: Hi @kasey, I have updated the code. Could you take another look?

**Review by kasey — APPROVED** [review]

**Comment by kasey** [comment]
LGTM, thanks very much for the contribution @Muzry!
