### PR TITLE
Optimal Local Slashing Protection DB Schema

### LINKED ISSUE #8066: Prysm Validator Missing Attestations
# 🐞 Bug Report

### Description

The prysm client occasionally misses attestations for slots due to grpc deadline for making the attestations passing before it's able to make the attestations.  It errors out with `Could not request attestation to sign at slot` when it does this.

As the number of keys that the validator client is attesting for goes up, the probability of this happening also seems to rise, since the deadline is fixed at 12 seconds for retrieving proposals and attestations and the amount of work to do appears to linearly scale with the amount of keys attesting.  Resource usage for the validator and for the beacon chain remain fairly low (compared to the available resources), so it doesn't seem to be a resource starvation issue.

### Has this worked before in a previous version?

This behavior has been observed in previous versions, but it was only recently that it became apparent it was directly related to the number of attesting validators.

## 🔬 Minimal Reproduction

The beacon chain and validator are run separately from each other, with the validator talking to a remote keymanager.

Beacon chain
```
beacon-chain
  --accept-terms-of-use
  --datadir /data
  --rpc-host 0.0.0.0
  --rpc-port 4000
  --grpc-gateway-host 0.0.0.0
  --grpc-gateway-port 4001
  --block-batch-limit=512
  --tls-cert certfile.crt
  --tls-key keyfile.crt
  --http-web3provider=$WEB3_PROVIDER
```

Validator
```
validator 
  --accept-terms-of-use
  --wallet-dir=/home/prysm/
  --beacon-rpc-provider $BEACON_DNS:4000
  --tls-cert certfile.crt
  --verbosity debug
  --wallet-password-file file.txt
```

The validator is also running using a remote keymanager.

## 🔥 Error

<pre><code>
time="2020-12-07 15:57:11" level=debug msg="Set deadline for proposals and attestations" deadline=2020-12-07 15:57:23 +0000 UTC prefix=validator slot=TARGET_SLOT
time="2020-12-07 15:57:13" level=debug msg="gRPC request finished." backend=[] duration=1.864267969s method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetDuties"
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=2 prefix=validator pubKeys=[0xKEY1 0xKEY2] slot=TARGET_SLOT
...
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=... prefix=validator pubKeys=[...] slot=...
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=... prefix=validator pubKeys=[...] slot=...
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=... prefix=validator pubKeys=[...] slot=...
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=... prefix=validator pubKeys=[...] slot=...
time="2020-12-07 15:57:20" level=debug msg="gRPC request finished." backend=[] duration=88.037671ms method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetDuties"
time="2020-12-07 15:57:20" level=debug msg="gRPC request finished." backend=[] duration=624.1µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/DomainData"
time="2020-12-07 15:57:26" level=debug msg="gRPC request finished." backend=[] duration=895.563µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/SubscribeCommitteeSubnets"
time="2020-12-07 15:57:26" level=debug msg="gRPC request finished." backend=[] duration=38.785µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData"
time="2020-12-07 15:57:26" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xKEY1 slot=TARGET_SLOT
time="2020-12-07 15:57:26" level=debug msg="gRPC request finished." backend=[] duration=42.394µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData"
time="2020-12-07 15:57:26" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xKEY2 slot=TARGET_SLOT
time="2020-12-07 15:57:26" level=error msg="Could not sign slot: rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm v1.0.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

### PR DESCRIPTION
**Pull request by rauljordan**
Fixes #8066

**What type of PR is this?**

> Feature

First of two PRs. The second PR will run a database migration to actually utilize this new schema in validator client code.

**What does this PR do? Why is it needed?**

Local slashing protection has been a really big problem for performance on Pyrmont, and as mainnet approaches Pyrmont levels, we need to have a much better schema for validator local slashing protection. At the time of writing, we use an extremely suboptimal approach. For every public key, we store in the database a slice of 54,000 (signing root, source epoch, target epoch) triples every single slot for every single attestation we produce. We also read this data from disk to check for slashing protection. All of this can be resolved by instead having a smarter schema that we can check against and save smaller blobs of data every slot to support large numbers of validators.

Upon creating a new attestation, we need to check if it is slashable before submitting it to a beacon node. That is, for an attestation `A` we want to check that no other attestation `B` exists with:

`B.source_epoch < A.source_epoch and B.target_epoch > A.target_epoch`

and

`B.source_epoch > A.source_epoch and B.target_epoch < A.target_epoch`

The boltDB docs [mention](https://github.com/boltdb/bolt#iterating-over-keys) the following

> Iterating over keys

> Bolt stores its keys in byte-sorted order within a bucket. This makes sequential iteration over these keys extremely fast. To iterate over keys we'll use a Cursor:

```go
db.View(func(tx *bolt.Tx) error {
	// Assume bucket exists and has keys
	b := tx.Bucket([]byte("MyBucket"))

	c := b.Cursor()

	for k, v := c.First(); k != nil; k, v = c.Next() {
		fmt.Printf("key=%s, value=%s\n", k, v)
	}

	return nil
})
```

The key phrase here is “Bolt stores its keys in byte-sorted order”, meaning we can leverage quick scans over buckets. A simple approach is to have a bucket of public keys and each public key has a sub-bucket where the (key, value) pairs are source_epoch, target_epoch. Then, for an incoming attestation with source epoch X, we can scan through this subbucket where keys are all source epochs and check for surround and surrounding votes. The complexity of this would be O(k*n) where k is the number of validating public keys in the validator client and n is the number of source epochs each key has attested for. This all depends on the speed of iterating through this subbucket of source epochs in boltDB. If this is extremely fast, with a max number of keys of WEAK_SUBJECTIVITY_PERIOD (54,000), then it could be a decent approach for us. Moreover, if each validating key is attesting in its own goroutine, the `k` factor in this time complexity is not relevant. 

To prove the effectiveness of the approach, here is a timed approach towards checking surround votes:

**Embedded KV Store: BoltDB**

Using a ForEach leveraging bolt DB's byte ordered keys, we get

```
=== RUN   TestKVStore_CheckSurroundVote
Checking surround vote with (source 27000, target 54000), took 1.891648ms
Checking surround vote with (source 0, target 54000), took 7.321µs
Checking surround vote with (source 53997, target 54000), took 2.222819ms
Checking safe vote with (source 54000, target 54001), took 1.229145ms
```

**SQLite Relational DB**

Using the following query
```
select source_epoch, target_epoch
from attestations
where source_epoch < ? and target_epoch > ?
order by target_epoch DESC
```
We get
```
=== RUN   TestSQLite_CheckSurroundVote
Checking surround vote with (source 27000, target 54000), took 4.933052ms
Checking surround vote with (source 0, target 54000), took 7.618146ms
Checking surround vote with (source 53997, target 54000), took 2.007821ms
Checking safe vote with (source 54000, target 54001), took 2.000708ms
```

Our approach ends up being better than SQLite even in the **worst case scenario**.

### CODE REVIEW

File: validator/db/kv/attester_protection.go [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+			return nil
+		}
+
+		// First we check for double votes.
+		signingRootsBucket := pkBucket.Bucket(attestationSigningRootsBucket)
+		if signingRootsBucket != nil {
+			targetEpochBytes := bytesutil.Uint64ToBytesBigEndian(att.Data.Target.Epoch)
+			existingSigningRoot := signingRootsBucket.Get(targetEpochBytes)
+			if existingSigningRoot != nil && !bytes.Equal(signingRoot[:], existingSigningRoot) {
+				return errors.New("double vote found")
```
Comment (terencechain) [inline validator/db/kv/attester_protection.go:31]: i think it'll be valuable to dump more info here such as what signing root

File: validator/db/kv/attester_protection.go [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+		}
+		// Check for surround votes.
+		return sourceEpochsBucket.ForEach(func(sourceEpochBytes []byte, targetEpochBytes []byte) error {
+			existingSourceEpoch := bytesutil.BytesToUint64BigEndian(sourceEpochBytes)
+			existingTargetEpoch := bytesutil.BytesToUint64BigEndian(targetEpochBytes)
+			surrounding := att.Data.Source.Epoch < existingSourceEpoch && att.Data.Target.Epoch > existingTargetEpoch
+			surrounded := att.Data.Source.Epoch > existingSourceEpoch && att.Data.Target.Epoch < existingTargetEpoch
+			if surrounding || surrounded {
+				// Returning an error allows us to exit early.
+				return errors.New("slashable vote found")
```
Comment (terencechain) [inline validator/db/kv/attester_protection.go:47]:
```suggestion
				return errors.New("surround vote found")
```

File: validator/db/kv/attester_protection.go [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+			return nil
+		}
+		// Check for surround votes.
+		return sourceEpochsBucket.ForEach(func(sourceEpochBytes []byte, targetEpochBytes []byte) error {
+			existingSourceEpoch := bytesutil.BytesToUint64BigEndian(sourceEpochBytes)
+			existingTargetEpoch := bytesutil.BytesToUint64BigEndian(targetEpochBytes)
+			surrounding := att.Data.Source.Epoch < existingSourceEpoch && att.Data.Target.Epoch > existingTargetEpoch
+			surrounded := att.Data.Source.Epoch > existingSourceEpoch && att.Data.Target.Epoch < existingTargetEpoch
+			if surrounding || surrounded {
+				// Returning an error allows us to exit early.
```
Comment (terencechain) [inline validator/db/kv/attester_protection.go:46]: I dont think this comment adds meaningful content, consider remove

File: validator/db/kv/attester_protection.go (hunk 2 above)
Comment (terencechain) [reply validator/db/kv/attester_protection.go:47]: again, it'll be valuable to dump more info such as epoch numbers

File: validator/db/kv/attester_protection.go [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+				return errors.New("slashable vote found")
+			}
+			return nil
+		})
+	})
+	return err != nil
```
Comment (terencechain) [inline validator/db/kv/attester_protection.go:52]: Why dont we want to return the `err`? Won't we miss useful debug info?

**Review by terencechain — APPROVED** [review]
