### PR TITLE
Remove Websockets for ETH1 From Prysm

### LINKED ISSUE #5826: Remove possibility of conflict between --web3provider and --http-web3provider
# 🐞 Bug Report

### Description
There are 2 parameters for pointing to an Eth1-node: --web3provider and --http-web3provider 
However these parameters **cannot** be used "independently".
Only populating one parameter (say --http-web3provider ) and omit the other defaults that one to goerli.prylabs.net.

Having two eth1 sources seems to lead to conflicting data and the beacon log start showing errors:
[2020-05-12 08:16:29] ERROR powchain: Unable to process past logs Could not process deposit log: could not get correct merkle index: latest index observed is not accurate, wanted 30928, but received  3090

The local (Nethermind) Eth1-node is also suffering from this conflict and is bombarded with RPC/http eth_logs-calls, as the conflicting data is causing a loop.

In other words, -web3provider and --http-web3provider **have to** point to the same eth1-node so there is only one source of eth1 data.

@nisdas confirmed that any mixing here would be the cause of the error message and the looping.

If this is indeed a restriction of the current eth1-code, the web3-parameters should be defined accordingly:
--web3provider =>ip address only
--web3_ws-port
--web3_http-port

### Has this worked before in a previous version?
n/a

 Yes, the previous version in which this bug was not present was: ....

## 🔬 Minimal Reproduction
Use Nethermind as local eth1 node. Run the beacon node with "only" the http parameter. That is causing the above (looping) error. Adding the ws-parameter is not possible. Nethermind does not support websocket subscriptions. So activating parameter --web3provider (ws) gives the following error messages (both in Nethermind and in beacon-node):

So leaving the ws-parameter out:
-local_node=>http 
-goerli.prylabs.net=>ws 
This is causing the RPC loops.
From a user perspective: there is no error/warning message in the beacon that setting only one parameter is actually not possible.

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
docker with latest beacon and Nethermind 1.8.30
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
96219fc9fad6b72b751352c2c198eb067749f3e0
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

I think it is important to reduce the dependency on goerli.prylabs.net for eth1 data. Any obstacle or unclarity of using a local eth1-node should be removed.

### PR DESCRIPTION
**Pull request by rauljordan**
**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

A much requested feature is the ability to run different types of eth1 nodes with Prysm, especially nethermind. This PR removes. websocket enforced support from Prysm, making it easy to run Prysm with any eth1 HTTP endpoint!

**Which issues(s) does this PR fix?**

Fixes #5826

### CODE REVIEW

File: beacon-chain/powchain/service.go [hunk 1]
```diff
@@ -608,25 +565,20 @@ func (s *Service) initPOWService() ethereum.Subscription {
...
-	headSub := s.initPOWService()
-	if headSub == nil {
-		log.Error("Received a nil head subscription, exiting service")
-		return
-	}
+	s.initPOWService()
 
 	ticker := time.NewTicker(1 * time.Second)
-	defer headSub.Unsubscribe()
+	headTicker := time.NewTicker(10 * time.Second)
```
Comment (nisdas) [inline beacon-chain/powchain/service.go:581]: change this to our eth1 block time param
