### PR TITLE
Check if all validators are exited on every slot

### LINKED ISSUE #7707: All validators are exited, no more work to perform...
# 🐞 Bug Report

### Description

Validator process shows two exited validators (from the initial time sync bug), but then states that all validators are exited.

### Has this worked before in a previous version?

Behavior was not observed until updating to beta.1

## 🔬 Minimal Reproduction

`~/Downloads/prysm/prysm.sh beacon-chain --config-file ~/.eth2/prysm/medallabeacon.yaml --blst --head-sync`

```
p2p-host-ip: '1.2.3.4'
monitoring-host: 'earth.thegalaxy'
monitoring-port: 8082
p2p-udp-port: 13428
p2p-tcp-port: 13428
http-web3provider: 'http://192.168.0.2:8545/'
tls-cert: '/etc/ssl/certs/earth.thegalaxy.crt'
tls-key: '/etc/ssl/private/earth.thegalaxy.key'
rpc-host: 'earth.thegalaxy'
rpc-port: 4000
p2p-max-peers: 1000
datadir: '/home/seamonkey/.eth2/prysm'
medalla: true
```
`~/Downloads/prysm/prysm.sh validator --config-file ~/.eth2/prysm/medallavalidator.yaml`
```
monitoring-host: 'earth.thegalaxy'
tls-cert: '/etc/ssl/certs/earth.thegalaxy.crt'
beacon-rpc-provider: 'earth.thegalaxy:4000'
graffiti: 'poappyHaPQaBPnZOlKI+N3zD4XKfz9UA'
wallet-password-file: '$HOME/.eth2/prysm/password.txt'
wallet-dir: '$HOME/.eth2/prysm/.eth2validators/prysm-wallet-v2'
monitoring-port: 8083
```
## 🔥 Error

```
[2020-11-03 02:20:19]  INFO validator: Validator exited index=11762 pubKey=0x84b227da4d40 status=EXITED
[2020-11-03 02:20:19]  INFO validator: Validator exited index=11760 pubKey=0x88e06872b53f status=EXITED
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11758 publicKey=0xb7ead186071b
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11765 publicKey=0x8bdd0ad880e3
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11766 publicKey=0xa25f842e6dce
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11763 publicKey=0xa8290a097d56
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11759 publicKey=0x82f749b2489c
[2020-11-03 02:20:19]  INFO validator: Validator activated index=11764 publicKey=0xa22526ece1e1
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xb7ead186071b] slot=653474
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0x8bdd0ad880e3] slot=653476
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xa25f842e6dce] slot=653479
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xa22526ece1e1] slot=653492
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0xa8290a097d56] slot=653494
[2020-11-03 02:20:19]  INFO validator: Attestation schedule attesters=1 pubKeys=[0x82f749b2489c] slot=653502
[2020-11-03 02:20:32]  INFO validator: All validators are exited, no more work to perform...
```

## 🌍  Your Environment

Linux Mint 20

**What version of Prysm are you running? (Which release)**

beta.1

**Anything else relevant (validator index / public key)?**

https://medalla.beaconcha.in/dashboard?validators=11758,11759,11760,11762,11763,11764,11765,11766

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

The set of validating public keys can change in run-time. Because of this on every slot we have to check if all validators exited.

**Which issues(s) does this PR fix?**

Fixes #7707 

**Other notes for review**

N/A

### CODE REVIEW

**Review by terencechain — COMMENTED** [review]
This would be fun for a regression test. Want to add one?

**Comment by rkapka** [comment]
I would love to ;-)

File: validator/client/mock_validator.go [hunk 1]
```diff
@@ -43,6 +43,10 @@ type FakeValidator struct {
 	PubkeysToStatusesMap              map[[48]byte]ethpb.ValidatorStatus
 }
 
+type ctxKey string
+
+var allValidatorsAreExitedCtxKey = ctxKey("exited")
```
Comment (rkapka) [inline validator/client/mock_validator.go:48]: https://deepsource.io/gh/prysmaticlabs/prysm/run/d9c103a2-6ecf-4f5d-89f7-260c2bc2e6c2/go/RVV-B0003/

**Review by terencechain — APPROVED** [review]
