### PR TITLE
Reduce JSON-RPC queries

### LINKED ISSUE #6206: Rate limiting on infura eth1 node, no backoff of beacon-chain
# 🐞 Bug Report

### Description

After getting rate limited on the infura eth1 node beacon-chain keeps trying to poll the endpoint every second. This causes the rate limiting to not resolve.

### Has this worked before in a previous version?

Have not seen any rate limiting. It is to check if polling is too fast either way.

## 🔬 Minimal Reproduction

Use infura endpoint.

## 🔥 Error

beacon chain error message, repeating every second
<pre>
time="2020-06-10 16:01:00" level=error msg="could not get block timestamp: could not query block with height 2848026: 429 Too Many Requests {"jsonrpc":"2.0","id":61386,"error":{"code":-32005,"message":"daily request count exceeded, request rate limited","data":{"rate":{"allowed_rps":1,"backoff_seconds":30,"current_rps":1.1},"see":"https://infura.io/dashboard"}}}" prefix=powchain
</pre>

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04
Docker 19.03.8

**What version of Prysm are you running? (Which release)**

alpha.10
gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-1f20cb

### PR DESCRIPTION
**Pull request by prestonvanloon**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

This reduces the total 1 request per second call to ETH1 to ETH1 block seconds interval
Given that we only need to process logs after a new ETH1 follow distance voting around (1024 slots), these calls to ETH1 should be rather infrequent. ~Setting this to 5 minutes for now to relieve the immediate pressure on users.~ Set to ETH1 block time interval based on feedback.

**Which issues(s) does this PR fix?**

Fixes #6206

**Other notes for review**

Also deleted "client" field which was unused.

### CODE REVIEW

File: beacon-chain/powchain/service.go [hunk 1]
```diff
@@ -613,9 +606,13 @@ func (s *Service) run(done <-chan struct{}) {
 
 	s.initPOWService()
 
-	ticker := time.NewTicker(1 * time.Second)
+	ticker := time.NewTicker(5 * time.Minute)
```
Comment (nisdas) [inline beacon-chain/powchain/service.go:609]: can we instead change this to eth1 block time ?

Comment (prestonvanloon) [reply beacon-chain/powchain/service.go]: In that case, we don't need a second ticker. I've just combined this with the headTicker case in the select statement.
