### PR TITLE
Fix attestation pool clean up for new db

### LINKED ISSUE #3302: New DB: delete processed attestation from pool
When using the new DB stack, it seems like we dont remove processed attestation from the attestation pool: https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/operations/service.go#L333

Which is why there's always max amount of attestations contain in a block

### PR DESCRIPTION
**Pull request by terencechain**
This fixes #3302 

When using the new DB, processed attestation isn't deleted properly because we use `hashutil.HashProto` for key, this changes it to `ssz.HashTreeRoot(attestation.Data)`

### CODE REVIEW

File: beacon-chain/operations/service.go [hunk 1]
```diff
@@ -326,15 +326,25 @@ func (s *Service) handleProcessedBlock(ctx context.Context, message proto.Messag
 // after they have been included in a beacon block.
 func (s *Service) removeAttestationsFromPool(ctx context.Context, attestations []*ethpb.Attestation) error {
 	for _, attestation := range attestations {
-		hash, err := hashutil.HashProto(attestation.Data)
-		if err != nil {
-			return err
+		var root [32]byte
+		var err error
+		if _, isLegacyDB := s.beaconDB.(*db.BeaconDB); isLegacyDB {
```
Comment (prestonvanloon) [inline beacon-chain/operations/service.go]: Why? Both if/else paths are the same

Comment (prestonvanloon) [reply beacon-chain/operations/service.go]: oh nvm, they have different roots
