### PR TITLE
Peer scoring: init sync

### LINKED ISSUE #6459: Beacon-chain not able to resume syncing after network connection was down
# 🐞 Bug Report

### Description

After an outage of the internet connection for a couple of hours beacon-chain is not able to sync up with the chain again. Initial-sync always starts at block 117537, syncs up to block 117983 and starts over at 117537 again.

The log does not reach back far enough to the point the internet connection was available again. There was no new docker container started, so the process has not crashed in between.

A restart fixed this issue and beacon-chain was able to sync up to the chain head.

### Has this worked before in a previous version?

Not tried

## 🔬 Minimal Reproduction

Not tried to reproduce

## 🔥 Error

<pre><code>
time="2020-06-30 16:45:43" level=info msg="Processing block 0x6954467b... 117981/118641 - estimated time remaining 1m29s" blocksPerSecond=7.3 peers=29 prefix=initial-sync
time="2020-06-30 16:45:43" level=info msg="Block is not processed" error="could not process block: could not save finalized checkpoint: missing block in database: block root=0xce5a746a5a4d4b7401a2a49b3737b5cf5f7fd11a144b1e8a877d1cae9a453c18" prefix=initial-sync
time="2020-06-30 16:45:43" level=info msg="Processing block 0x61347955... 117983/118641 - estimated time remaining 1m28s" blocksPerSecond=7.4 peers=29 prefix=initial-sync
time="2020-06-30 16:45:43" level=info msg="Block is not processed" error="could not process block: could not save finalized checkpoint: missing block in database: block root=0xce5a746a5a4d4b7401a2a49b3737b5cf5f7fd11a144b1e8a877d1cae9a453c18" prefix=initial-sync
time="2020-06-30 16:45:43" level=info msg="Processing block 0x98b2b875... 117537/118641 - estimated time remaining 2m28s" blocksPerSecond=7.5 peers=29 prefix=initial-sync
time="2020-06-30 16:45:46" level=info msg="Block is not processed" error="could not process block: could not save finalized checkpoint: missing block in database: block root=0xce5a746a5a4d4b7401a2a49b3737b5cf5f7fd11a144b1e8a877d1cae9a453c18" prefix=initial-sync
time="2020-06-30 16:45:46" level=info msg="Processing block 0x8f7a09b5... 117538/118641 - estimated time remaining 2m55s" blocksPerSecond=6.3 peers=29 prefix=initial-sync
</code></pre>

Starting at block 117537 over and over again.

For all the available log see:
[onyx.log](https://github.com/prysmaticlabs/prysm/files/4853379/onyx.log)

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04 on arm64
Docker

**What version of Prysm are you running? (Which release)**

Commit 2bce9c8 compiled on arm64
Running in Docker

### PR DESCRIPTION
**Pull request by farazdagi**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**
- [x] Integrates `PeerScorer` with `init-sync`.
- [x] Put new functionality behind a flag.

**Which issues(s) does this PR fix?**

Part of #6622
Fixes #6459 

**Other notes for review**
- Review after #6979
- Block fetcher and queue updated to allow passing through `peer.ID`, that's when batch is requested, system keeps track which peer block was requested/fetched from. This is necessary to keep track of peers' performance. (extracted to #6979)
- Init-sync has new function: `filterScoredPeers()`: basically, it is what connects peer scorer to sync, that filter function relies on scorer to sort out suitable peers. Since we are in opt-in phase of the feature, by default, the previous `filterPeers` function is used (that function was our round robin shuffling).
- The new `filterScoredPeers` function:
  - Shuffles (to make sure that the same score doesn't mean same order)
  - Calculates overall score (taking remaining capacity into account)
  - Uses weighted random selection to build the list of available peers (higher the score higher the probability of being selected earlier)
- Another moving piece of PeerScorer - InitSync integration resides inside of `processFetchedData()`: there on successfully processed blocks, peer stats is updated.
- Peer scoring code in `filterScoredPeers()`  and `processFetchedData()` is used only if flag is enabled (we are in opt-in phase). To enable, use on of the flags:
  - `--dev`
  - `--enable-peer-scorer`
- When disabled (by default):
image
- When enabled:
image

### CODE REVIEW

File: beacon-chain/sync/initial-sync/blocks_fetcher_test.go [hunk 1]
```diff
@@ -743,6 +745,200 @@ func TestBlocksFetcher_filterPeers(t *testing.T) {
...
+			for _, pid := range tt.args.peers {
+				peerIDs = append(peerIDs, pid.ID)
+				fetcher.rateLimiter.Add(pid.ID.String(), pid.usedCapacity)
+			}
+			if tt.update != nil {
+				tt.update(fetcher.p2p.Peers().Scorers().BlockProviderScorer())
+			}
+			// Since peer selection is probabilistic (weighted, with high scorers having higher
+			// chance of being selected), we need multiple rounds of filtering to test the order:
+			// over multiple attempts, high scorers should be picked on high posstions more often.
```
Comment (shayzluf) [inline beacon-chain/sync/initial-sync/blocks_fetcher_test.go:889]:
```suggestion
			// over multiple attempts, top scorers should be picked on high positions more often.
```
maybe change high scorers to top scorers

File: beacon-chain/sync/initial-sync/blocks_fetcher_test.go [hunk 2]
```diff
@@ -743,6 +745,200 @@ func TestBlocksFetcher_filterPeers(t *testing.T) {
...
+				peersPercentage: 1.0,
+				capacityWeight:  0.2,
+			},
+			want: []peer.ID{"abc"},
+		},
+		{
+			name: "multiple peers same capacity",
+			args: args{
+				peers: []weightedPeer{
+					{"abc", 2400},
```
Comment (shayzluf) [inline beacon-chain/sync/initial-sync/blocks_fetcher_test.go:790]: i think it will be more readable if peers will have one letter name
```suggestion
					{"a", 2400},
```

Comment (farazdagi) [reply beacon-chain/sync/initial-sync/blocks_fetcher_test.go:790]: On error, our assertions use `%#v`, so output will be like `unexpected peer.ID[]{"abc", "def"}` i.e. no problems with readability. I don't have any strong opinion about this, though.

Comment (shayzluf) [reply beacon-chain/sync/initial-sync/blocks_fetcher_test.go:790]: i just thought the wanted will look more readable if it looked like b,a,c,d

Comment (farazdagi) [reply beacon-chain/sync/initial-sync/blocks_fetcher_test.go:790]: Got, it! Agree, will fix in a moment. Thanks!

File: beacon-chain/sync/initial-sync/blocks_fetcher_peers.go [hunk 3]
```diff
@@ -118,3 +120,39 @@ func (f *blocksFetcher) filterPeers(peers []peer.ID, peersPercentage float64) ([
...
+	// Sort peers using both block provider score and, custom, capacity based score (see
+	// peerFilterCapacityWeight if you want to give different weights to provider's and capacity
+	// scores).
+	// Scores produced are used as weights, so peers are ordered probabilistically i.e. peer with
+	// a higher score has higher chance to end up higher in the list.
+	scorer := f.p2p.Peers().Scorers().BlockProviderScorer()
+	peers = scorer.WeightSorted(f.rand, peers, func(peerID peer.ID, blockProviderScore float64) float64 {
+		remaining, capacity := float64(f.rateLimiter.Remaining(peerID.String())), float64(f.rateLimiter.Capacity())
+		// When no capacity for a good peer left, allow less performant peer to take a chance.
+		if remaining < float64(f.blocksPerSecond) {
```
Comment (nisdas) [inline beacon-chain/sync/initial-sync/blocks_fetcher_peers.go:143]: For this to be true wouldnt `remaining` be equal to zero ? 
if `remaining` <  `f.blocksPerSecond` , there is still some capacity, no ?

File: beacon-chain/sync/initial-sync/blocks_fetcher_peers.go [hunk 4]
```diff
@@ -118,3 +120,39 @@ func (f *blocksFetcher) filterPeers(peers []peer.ID, peersPercentage float64) ([
...
+			return 0.0
+		}
+		capScore := remaining / capacity
+		overallScore := blockProviderScore*(1.0-f.capacityWeight) + capScore*f.capacityWeight
+		return math.Round(overallScore*scorers.ScoreRoundingFactor) / scorers.ScoreRoundingFactor
+	})
+
+	// Weak/slow peers will be pushed down the list and trimmed since only percentage of peers is selected.
+	limit := uint64(math.Round(float64(len(peers)) * ratio))
```
Comment (nisdas) [inline beacon-chain/sync/initial-sync/blocks_fetcher_peers.go:152]:
```go
	limit := uint64(math.Round(float64(len(peers)) * ratio))
	limit = mathutil.Max(limit, uint64(flags.Get().MinimumSyncPeers))
	limit = mathutil.Min(limit, uint64(len(peers)))
```
This whole chunk of code maybe needs more explanation , my main question is what exactly this does
```go
	limit := uint64(math.Round(float64(len(peers)) * ratio))
```
why does it need to be done by a ratio ?

File: beacon-chain/sync/initial-sync/blocks_fetcher_peers.go (hunk 3 above)
Comment (farazdagi) [reply beacon-chain/sync/initial-sync/blocks_fetcher_peers.go:143]: Well, I suppose this is an issue in comment, it should read as "When remaining capacity approaches to exhaustion.."

File: beacon-chain/sync/initial-sync/blocks_fetcher_peers.go (hunk 4 above)
Comment (farazdagi) [reply beacon-chain/sync/initial-sync/blocks_fetcher_peers.go:152]: That param was called `peersPercentage `, renaming it to `ratio` without adding more comments wasn't very prudent indeed. Will change name back to `peersPercentage`, and add comment that this param allows to limit how many of sorted peers caller wants to be returned.

File: beacon-chain/sync/initial-sync/blocks_fetcher.go [hunk 5]
```diff
@@ -102,6 +108,11 @@ func newBlocksFetcher(ctx context.Context, cfg *blocksFetcherConfig) *blocksFetc
 		float64(blocksPerSecond), int64(allowedBlocksBurst-blocksPerSecond),
 		false /* deleteEmptyBuckets */)
 
+	capacityWeight := cfg.peerFilterCapacityWeight
+	if capacityWeight == 0 || capacityWeight > 1 {
```
Comment (nisdas) [inline beacon-chain/sync/initial-sync/blocks_fetcher.go:112]:
```suggestion
	if capacityWeight  >= 1 {
```
