### PR TITLE
Identify invalid signature within batch verification (#11582)

### LINKED ISSUE #11582: Add capability to narrow down to which signature fails
For performance reasons, we batch-verify all the signatures in the block. The downside of this is if any of the signatures are invalid, the process block will fail and there's no way to which signature was invalid on what object. It may be nice to provide an option to Prysm state transition cmd to identify precisely which signature is invalid. This could also be part of prysmctl util

### PR DESCRIPTION
**Pull request by dyng**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

The signatures of newly received blocks are collected and verified as a batch, while it's perfect if everything is ok, we can't tell which signature is invalid if batch verification fails.

**Which issues(s) does this PR fix?**

Fixes #11582 

**Other notes for review**

This PR is not yet complete because I need to discuss with reviewer to determine where `VerifyVerbosely` is supposed to be used.

### CODE REVIEW

File: beacon-chain/core/blocks/signature.go [hunk 1]
```diff
@@ -216,11 +218,14 @@ func createAttestationSignatureBatch(
 			return nil, errors.Wrap(err, "could not get signing root of object")
 		}
 		msgs[i] = root
+
+		descs[i] = "attestation signature"
```
[the remark this answers is not in the document]
Comment (dyng) [reply beacon-chain/core/blocks/signature.go:222]: It looks better, thanks!

File: crypto/bls/signature_batch.go [hunk 2]
```diff
@@ -25,6 +32,11 @@ func (s *SignatureBatch) Join(set *SignatureBatch) *SignatureBatch {
 	s.Signatures = append(s.Signatures, set.Signatures...)
 	s.PublicKeys = append(s.PublicKeys, set.PublicKeys...)
 	s.Messages = append(s.Messages, set.Messages...)
+	if s.Descriptions != nil && set.Descriptions != nil {
```
Comment (nisdas) [inline crypto/bls/signature_batch.go:35]: Remove this nil check, since all signature sets now have a `description` attached to it.

File: crypto/bls/signature_batch.go [hunk 3]
```diff
@@ -33,12 +45,58 @@ func (s *SignatureBatch) Verify() (bool, error) {
...
+			if len(s.Descriptions) != len(s.Signatures) {
+				desc = "non-specific signature"
+			} else {
+				desc = s.Descriptions[i]
+			}
+
+			if err != nil {
+				_, e := fmt.Fprintf(&sb, "signature '%s' is invalid."+
+					" signature: %v, public key: %v, message: %v, error: %v\n", desc, sig, pubKey, msg, err)
+				if e != nil {
```
Comment (nisdas) [inline crypto/bls/signature_batch.go:77]: don't ignore errors here, also why are we using `Fprintf` here ? Wrap the error and then return it.

File: crypto/bls/signature_batch.go [hunk 4]
```diff
@@ -33,12 +45,58 @@ func (s *SignatureBatch) Verify() (bool, error) {
...
+
+	for i := 0; i < len(s.Signatures); i++ {
+		sig := s.Signatures[i]
+		msg := s.Messages[i]
+		pubKey := s.PublicKeys[i]
+
+		valid, err := VerifySignature(sig, msg, pubKey)
+		if !valid {
+			var desc string
+			if len(s.Descriptions) != len(s.Signatures) {
```
Comment (nisdas) [inline crypto/bls/signature_batch.go:68]: These checks are going to be ugly and a source of bugs, it would be much better to always have the same number of descriptions and signatures in a set.

File: beacon-chain/core/blocks/signature.go [hunk 5]
```diff
@@ -33,15 +33,16 @@ func signatureBatch(signedData, pub, signature, domain []byte) (*bls.SignatureBa
...
+		PublicKeys:   []bls.PublicKey{publicKey},
+		Messages:     [][32]byte{root},
+		Descriptions: []string{desc},
 	}, nil
 }
 
 // verifies the signature from the raw data, public key and domain provided.
 func verifySignature(signedData, pub, signature, domain []byte) error {
-	set, err := signatureBatch(signedData, pub, signature, domain)
+	set, err := signatureBatch(signedData, pub, signature, domain, "")
```
Comment (nisdas) [inline beacon-chain/core/blocks/signature.go:45]: better to name it as "unknown" rather than an empty string

File: crypto/bls/signature_batch.go [hunk 6]
```diff
@@ -33,12 +45,58 @@ func (s *SignatureBatch) Verify() (bool, error) {
...
+
+			if err != nil {
+				_, e := fmt.Fprintf(&sb, "signature '%s' is invalid."+
+					" signature: %v, public key: %v, message: %v, error: %v\n", desc, sig, pubKey, msg, err)
+				if e != nil {
+					// ignore
+				}
+			} else {
+				_, e := fmt.Fprintf(&sb, "signature '%s' is invalid."+
+					" signature: %v, public key: %v, message: %v\n", desc, sig, pubKey, msg)
```
Comment (nisdas) [inline crypto/bls/signature_batch.go:82]: Better to represent `msg` as hex rather than an array of bytes when printing the error message. Same applies to signature and public keys. Also you need to marshal the public key into bytes otherwise you end up printing pointers to the struct which isn't useful

File: crypto/bls/signature_batch.go [hunk 7]
```diff
@@ -82,6 +145,10 @@ func (s *SignatureBatch) RemoveDuplicates() (int, *SignatureBatch, error) {
 	sigs := s.Signatures[:0]
 	pubs := s.PublicKeys[:0]
 	msgs := s.Messages[:0]
+	var descs []string
+	if s.Descriptions != nil {
```
Comment (nisdas) [inline crypto/bls/signature_batch.go:149]: same thing here, do not have a nil check here. The correct thing to do would be to make sure all signature sets always have an attached description.

**Review by nisdas — CHANGES_REQUESTED** [review]

File: crypto/bls/signature_batch.go (hunk 3 above)
Comment (dyng) [reply crypto/bls/signature_batch.go:77]: Here I used `strings.Builder` for better performance (not a big problem though). `strings.Builder` follows `StringWriter` interface that emits error but actually always returns `nil` as error, so I decided to ignore it. I'll consider to use string concatenation instead.

File: beacon-chain/core/blocks/signature.go (hunk 5 above)
Comment (dyng) [reply beacon-chain/core/blocks/signature.go:45]: As @terencechain's comment, I'll use enums instead. Thanks!

File: crypto/bls/signature_batch.go (hunk 6 above)
Comment (dyng) [reply crypto/bls/signature_batch.go:82]: Thanks! I'll make error message more readable.

**Comment by dyng** [comment]
I have done the changes, please take a review when you have time. Thanks! @nisdas @terencechain

File: crypto/bls/constants.go [hunk 8]
```diff
@@ -5,3 +5,31 @@ const DomainByteLength = 4
 
 // CurveOrder for the BLS12-381 curve.
 const CurveOrder = "52435875175126190479447740508185965837690552500527637822603658699938581184513"
+
+// List of descriptions for different kinds of signatures
+const (
```
[the remark this answers is not in the document]
Comment (dyng) [reply crypto/bls/constants.go]: Thanks for your comment! I have moved these constants to signing package, but left `AggregatedSignature` in bls package as it is a local knowledge belongs to bls package.

File: crypto/bls/signature_batch.go [hunk 9]
```diff
@@ -119,12 +172,14 @@ func (s *SignatureBatch) AggregateBatch() (*SignatureBatch, error) {
 			currBatch.Signatures = append(currBatch.Signatures, s.Signatures[i])
 			currBatch.Messages = append(currBatch.Messages, s.Messages[i])
 			currBatch.PublicKeys = append(currBatch.PublicKeys, s.PublicKeys[i])
+			currBatch.Descriptions = append(currBatch.Descriptions, s.Descriptions[i])
```
[the remark this answers is not in the document]
Comment (dyng) [reply crypto/bls/signature_batch.go:175]: I have added length validation for descriptions. Thanks for the comment!

I reordered the empty check and length check because I think length mismatch of signatures and messages should  always be an error even in case that signatures are empty and messages are non-empty.

File: crypto/bls/signature_batch.go [hunk 10]
```diff
@@ -140,6 +195,7 @@ func (s *SignatureBatch) AggregateBatch() (*SignatureBatch, error) {
 			b.PublicKeys = []PublicKey{aggPub}
 			b.Signatures = [][]byte{aggSig.Marshal()}
 			b.Messages = [][32]byte{copiedRt}
+			b.Descriptions = []string{AggregatedSignature}
```
[the remark this answers is not in the document]
Comment (dyng) [reply crypto/bls/signature_batch.go:198]: I thought about the information loss, but still used a generic description here for two reason:

1. the signatures themself are aggregated and we can hardly identify invalid individual signature.
2. `AggregateBatch()` is called in `validateWithBatchVerifier()` but not `VerifyVerbosely()`, currently only `VerifyVerbosely()` is responsible to nail down failed signature.

But I'm not sure if I have fully understood the whole picture of block processing, correct me if I am wrong! Thanks! Maybe as you said, we can fix this later.

**Review by nisdas — DISMISSED** [review]
Thanks for addressing all the comments, great work on this feature !

**Comment by nisdas** [comment]
Build is failing @dyng 

```
crypto/bls/signature_batch_test.go:657:9: Unhandled error for function call  (errcheck)
crypto/bls/signature_batch_test.go:681:9: Unhandled error for function call  (errcheck)
```

**Review by nisdas — APPROVED** [review]

**Comment by dyng** [comment]
@nisdas I have fixed build failure, sorry for that (I should build locally at first). Thanks for your review and precious comments!
