### PR TITLE
Disallow duties request where req.Epoch > current.Epoch+1

### LINKED ISSUE #8240: Validator Api allows you to get duties for the epochs in the future
# 🐞 Bug Report

The API allows you to request duties for many epochs ahead. It should disallow that and treat them as out of bounds.

<pre>
  <code>
http://127.0.0.1:3500/eth/v1alpha1/validator/duties?epoch=12002&publicKeys=j06vCdrV0dRjk%2BbSgNjx1pxc1J8OzFMP0wCux9ta2iakZOMjHM0%2BSUkqYQc05i7%2B
current == 384072
next == 384120

http://127.0.0.1:3500/eth/v1alpha1/validator/duties?epoch=12003&publicKeys=j06vCdrV0dRjk%2BbSgNjx1pxc1J8OzFMP0wCux9ta2iakZOMjHM0%2BSUkqYQc05i7%2B
current == 384120
next == 384129

http://127.0.0.1:3500/eth/v1alpha1/validator/duties?epoch=12004&publicKeys=j06vCdrV0dRjk%2BbSgNjx1pxc1J8OzFMP0wCux9ta2iakZOMjHM0%2BSUkqYQc05i7%2B
current == 384129
next == 384162

http://127.0.0.1:3500/eth/v1alpha1/validator/duties?epoch=12005&publicKeys=j06vCdrV0dRjk%2BbSgNjx1pxc1J8OzFMP0wCux9ta2iakZOMjHM0%2BSUkqYQc05i7%2B
current == 384162
next == 384213
  </code>
</pre>

### PR DESCRIPTION
**Pull request by terencechain**
**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

This prevents the duties request to go beyond next epoch. I also renamed `GenesisTimeFetcher` to `TimeFetcher`

Fixes #8240

### CODE REVIEW

**Review by rauljordan — DISMISSED** [review]

File: beacon-chain/rpc/validator/server.go [hunk 1]
```diff
@@ -50,7 +50,6 @@ type Server struct {
 	DepositFetcher         depositcache.DepositFetcher
 	ChainStartFetcher      powchain.ChainStartFetcher
 	Eth1InfoFetcher        powchain.ChainInfoFetcher
-	GenesisTimeFetcher     blockchain.TimeFetcher
```
Comment (terencechain) [inline beacon-chain/rpc/validator/server.go:53]: Duplicated as `TimeFetcher            blockchain.TimeFetcher`

**Review by prestonvanloon — APPROVED** [review]
