### PR TITLE
Fixed nil pointer error in DepositCache

### LINKED ISSUE #6588: --enable-finalized-deposits-cache panics in e2e
```
time="2020-07-13 20:22:08" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 3390 [running]:
runtime/debug.Stack(0xc000174000, 0x1b50643, 0x5)
	GOROOT/src/runtime/debug/stack.go:24 +0x9d
github.com/prysmaticlabs/prysm/shared/traceutil.RecoveryHandlerFunc(0x1f4efe0, 0xc001446450, 0x192d740, 0x2c057b0, 0xc002153080, 0x203000)
	shared/traceutil/recovery_interceptor_option.go:29 +0x155
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x1f4efe0, 0xc001446450, 0x192d740, 0x2c057b0, 0x1d205d8, 0xc002152fa0, 0x0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:53 +0x5a
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0x1f4efe0, 0xc001446450, 0xc000640088, 0xc002153ab0)
	external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:27 +0x77
panic(0x192d740, 0x2c057b0)
	GOROOT/src/runtime/panic.go:969 +0x166
github.com/prysmaticlabs/prysm/beacon-chain/cache/depositcache.(*DepositCache).FinalizedDeposits(0xc0004ed1f0, 0x1f4efe0, 0xc001446540, 0x0)
	beacon-chain/cache/depositcache/deposits_cache.go:252 +0xe8
github.com/prysmaticlabs/prysm/beacon-chain/rpc/validator.(*Server).depositTrie(0xc0002fc300, 0x1f4efe0, 0xc001446540, 0xc0017b1440, 0xc003388800, 0x20, 0x20)
	beacon-chain/rpc/validator/proposer.go:363 +0x382
github.com/prysmaticlabs/prysm/beacon-chain/rpc/validator.(*Server).deposits(0xc0002fc300, 0x1f4efe0, 0xc001446540, 0xc0038b8cc0, 0xc0038b8cc0, 0x0, 0x0, 0x0, 0xc001446540)
	beacon-chain/rpc/validator/proposer.go:299 +0x1e1
github.com/prysmaticlabs/prysm/beacon-chain/rpc/validator.(*Server).GetBlock(0xc0002fc300, 0x1f4efe0, 0xc001446540, 0xc0037c8180, 0x0, 0x0, 0x0)
	beacon-chain/rpc/validator/proposer.go:63 +0x3ff
github.com/prysmaticlabs/ethereumapis/eth/v1alpha1._BeaconNodeValidator_GetBlock_Handler.func1(0x1f4efe0, 0xc001446510, 0x1ac6fc0, 0xc0037c8180, 0xc0005b2758, 0x5a049d, 0x1a41740, 0xc001446510)
	bazel-out/k8-fastbuild/bin/external/com_github_prysmaticlabs_ethereumapis/eth/v1alpha1/linux_amd64_stripped/go_proto%/github.com/prysmaticlabs/ethereumapis/eth/v1alpha1/validator.pb.go:2473 +0x86
github.com/prysmaticlabs/prysm/beacon-chain/rpc.(*Service).validatorUnaryConnectionInterceptor(0xc00012a780, 0x1f4efe0, 0xc001446510, 0x1ac6fc0, 0xc0037c8180, 0xc0037e01c0, 0xc0037e01e0, 0x2da5608, 0x1f4efe0, 0xc001446510, ...)
	beacon-chain/rpc/service.go:393 +0x77
```

Nil pointer here: https://github.com/prysmaticlabs/prysm/blob/f7088e037cc1401500240ac3b180bee1c1d9b25e/beacon-chain/cache/depositcache/deposits_cache.go#L252

_Originally posted by @prestonvanloon in https://github.com/prysmaticlabs/prysm/pull/6391#issuecomment-657783540_

### PR DESCRIPTION
**Pull request by rkapka**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Fixes nil pointer error occurring while returning cached Finalized Deposits. The error was introduced when modifying the code to return a copy of the deposits trie instead of the original trie.

**Which issues(s) does this PR fix?**

Fixes #6588

**Other notes for review**

I added a trivial test in the spirit of including tests for bug fixes.

### CODE REVIEW

File: beacon-chain/cache/depositcache/deposits_cache_test.go [hunk 1]
```diff
@@ -409,6 +409,16 @@ func TestFinalizedDeposits_UtilizesPreviouslyCachedDeposits(t *testing.T) {
 	}
 }
 
+func TestFinalizedDeposits_DepositsAreNil_ReturnsNil(t *testing.T) {
+	dc := DepositCache{}
+
+	deposits := dc.finalizedDeposits
```
Comment (prestonvanloon) [inline beacon-chain/cache/depositcache/deposits_cache_test.go:415]:
```suggestion
	deposits := dc.FinalizedDeposits()
```

File: beacon-chain/cache/depositcache/deposits_cache_test.go [hunk 2]
```diff
@@ -409,6 +409,16 @@ func TestFinalizedDeposits_UtilizesPreviouslyCachedDeposits(t *testing.T) {
...
+
+	if deposits != nil {
```
Comment (terencechain) [inline beacon-chain/cache/depositcache/deposits_cache_test.go:417]: Can we use the new `assert` package? 

Reference: #6597

**Comment by 0xKiwi** [comment]
Please uncomment the flag in E2E when you merge from master. :+1:

File: beacon-chain/cache/depositcache/deposits_cache_test.go (hunk 1 above)
Comment (rkapka) [reply beacon-chain/cache/depositcache/deposits_cache_test.go:415]: `finalizedDeposits`  is not a function. Is there something that I'm missing here?

File: beacon-chain/cache/depositcache/deposits_cache_test.go (hunk 2 above)
Comment (rkapka) [reply beacon-chain/cache/depositcache/deposits_cache_test.go:417]: Not really because the package only has a `NotNil` condition and I want the variable to be `nil`

File: beacon-chain/cache/depositcache/deposits_cache_test.go (hunk 1 above)
Comment (terencechain) [reply beacon-chain/cache/depositcache/deposits_cache_test.go:415]: You are testing the function `FinalizedDeposits(ctx context.Context)`, that's entry point to the panic

File: beacon-chain/cache/depositcache/deposits_cache_test.go (hunk 2 above)
Comment (terencechain) [reply beacon-chain/cache/depositcache/deposits_cache_test.go:417]: You can use `Equal` to compare against nil

File: beacon-chain/cache/depositcache/deposits_cache_test.go (hunk 1 above)
Comment (rkapka) [reply beacon-chain/cache/depositcache/deposits_cache_test.go:415]: Uhhh... Gotta be more careful next time. Thanks!

File: beacon-chain/cache/depositcache/deposits_cache_test.go (hunk 2 above)
Comment (rkapka) [reply beacon-chain/cache/depositcache/deposits_cache_test.go:417]: `deposits_cache_test.go:418 Deposits should be nil, got: <nil>, want: <nil>`

I guess it's a similar problem as with https://github.com/prysmaticlabs/prysm/issues/6590#issuecomment-658417687

File: beacon-chain/cache/depositcache/deposits_cache.go [hunk 3]
```diff
@@ -248,6 +248,10 @@ func (dc *DepositCache) FinalizedDeposits(ctx context.Context) *FinalizedDeposit
 	dc.depositsLock.RLock()
 	defer dc.depositsLock.RUnlock()
 
+	if dc.finalizedDeposits == nil {
```
Comment (nisdas) [inline beacon-chain/cache/depositcache/deposits_cache.go:251]: I dont think this is the right solution, this just puts a band-aid over the original error. Why is there a nil finalized deposits cache in the first place ?

Comment (rkapka) [reply beacon-chain/cache/depositcache/deposits_cache.go]: Thank you for pointing this out. I did not notice the `NewDepositCache()` constructor function. Taking advantage of the constructor allowed me to simplify the code.

I am a bit unsure about the `finalizedDepositsTrie, MerkleTrieIndex: -1` initialization. Is this acceptable?

File: beacon-chain/cache/depositcache/deposits_cache.go [hunk 4]
```diff
@@ -61,9 +61,15 @@ type DepositCache struct {
...
 func NewDepositCache() *DepositCache {
+	finalizedDepositsTrie, err := trieutil.NewTrie(int(params.BeaconConfig().DepositContractTreeDepth))
+	if err != nil {
+		panic(err)
+	}
+
 	return &DepositCache{
 		pendingDeposits:    []*dbpb.DepositContainer{},
 		deposits:           []*dbpb.DepositContainer{},
+		finalizedDeposits:  &FinalizedDeposits{Deposits: finalizedDepositsTrie, MerkleTrieIndex: -1},
```
Comment (terencechain) [inline beacon-chain/cache/depositcache/deposits_cache.go:72]: We should add a comment to explain why it starts at -1

**Comment by rkapka** [comment]
There is no regression test any more because the `finalizedDeposits` struct pointer is initialized in the constructor and should never become `nil`. If this ever happens, then the code should panic.

File: beacon-chain/cache/depositcache/deposits_cache.go (hunk 3 above)
Comment (nisdas) [reply beacon-chain/cache/depositcache/deposits_cache.go]: That is the correct behaviour, the first deposit will lead to an index of `0` which is correct.

**Comment by rkapka** [comment]
Testing this seems a bit of an overkill to me, but I can do it. It won't hurt anyone.

**Comment by terencechain** [comment]
@rkapka please run go fmt

File: beacon-chain/cache/depositcache/deposits_cache.go [hunk 5]
```diff
@@ -61,9 +61,17 @@ type DepositCache struct {
 
 // NewDepositCache instantiates a new deposit cache
 func NewDepositCache() *DepositCache {
+	finalizedDepositsTrie, err := trieutil.NewTrie(int(params.BeaconConfig().DepositContractTreeDepth))
+	if err != nil {
+		panic(err)
```
Comment (prestonvanloon) [inline beacon-chain/cache/depositcache/deposits_cache.go:66]: No panic please, return an error if needed

Comment (rkapka) [reply beacon-chain/cache/depositcache/deposits_cache.go:66]: I based my solution on this:

https://github.com/prysmaticlabs/prysm/blob/c2615168d9af98c6c1a348b943b43dc158d57fbf/beacon-chain/cache/hot_state_cache.go#L33-L37

I will change my constructor's return type to `(*DepositCache, error)`.

Comment (terencechain) [reply beacon-chain/cache/depositcache/deposits_cache.go:66]: That should be return an errors. In fact for all the instantiations of caches

**Comment by rkapka** [comment]
I moved the comment about `MerkleTrieIndex` before the `return` statement because having a comment between field initializers messes up gofmt.
