### PR TITLE
Unregister validator - fix behind feature flag

### LINKED ISSUE #12274: Investigate potential builder setting caching
# 💎 Issue

### Background

several users have reported issues with proposing with validators that have their builder options disabled in the --proposer-settings config flag. This setting allows users to dynamically change whether they want to use the builder setting or not. some users mention that despite updating the file to have enabled as false, the validator client was still trying to register the validator.
There is no concrete evidence of this yet but warrants investigation.

references from discord.
User:mxs#5437

> we have a set of keys relying on the default config, builder set to false, and other keys with specific overrides, where we also set everything to false, and we saw the issue on both sets of keys

> we are trying to on top of it make the beacon point to a non-existing MEV boost, with the rationale it could fallback if it can;; t reach it

User:ArchiFleKs#7852

> Thanks, we seems (not definitly sure) to have mitigate our issue (with @mxs ) by re-enabling mev boost and using a dummy URL to trigger fallback tto local building. Proposed 2 blocks but haven't seen the stack trace since

User: Karmastic#1266

despite updating the proposer settings file it seemed that the builder settings were still calling the validator registration

### PR DESCRIPTION
**Pull request by james-prysm**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

This cache implementation is hidden behind a feature flag and is only applicable while using mev relay features.
`--enable-registration-cache` and will not completely replace the db.
By enabling the registration cache we are migrating away from persistent registration storage on the beacon node side. We will also be adding expiration to validator registrations to be more aligned with other client teams. 

**note**: This flag and feature will not be recommended for those who are still using the[ keymanager apis](https://ethereum.github.io/keymanager-APIs) to configure the fee recipients

jaeger with db (old)
image

jaeger with cache (new)
image

Learn more about builders here.
https://ethereum.github.io/builder-specs/#/Builder

**Which issues(s) does this PR fix?**

Fixes #12274

### CODE REVIEW

File: beacon-chain/cache/registration.go [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+	if err != nil {
+		return false
+	}
+	return time.Unix(t, 0).Add(expiryDuration).Unix() < time.Now().Unix()
+}
+
+// UpdateIndexToRegisteredMap adds or updates values in the cache based on the argument.
+func (regCache *RegistrationCache) UpdateIndexToRegisteredMap(m map[primitives.ValidatorIndex]*ethpb.ValidatorRegistrationV1) {
+	regCache.RLock()
+	defer regCache.RUnlock()
```
Comment (prestonvanloon) [inline beacon-chain/cache/registration.go:58]: You need to secure the write lock here.

```suggestion
	regCache.Lock()
	defer regCache.Unlock()
```

File: beacon-chain/cache/registration.go [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+	v, ok := regCache.indexToRegistration[id]
+	if !ok {
+		return nil, errors.Wrapf(ErrNotFoundRegistration, "validator id %d", id)
+	}
+	if timeStampExpired(v.Timestamp) {
+		delete(regCache.indexToRegistration, id)
+		return nil, errors.Wrapf(ErrNotFoundRegistration, "validator id %d", id)
+	}
```
Comment (prestonvanloon) [inline beacon-chain/cache/registration.go:41]: This is a mutating operation. You will need to use a write lock if you want to modify the map in this method

File: beacon-chain/db/kv/blocks.go [hunk 3]
```diff
@@ -549,11 +551,28 @@ func (s *Store) RegistrationByValidatorID(ctx context.Context, id primitives.Val
...
 
+func timeStampExpired(ts uint64) bool {
+	expiryDuration := time.Duration(params.BeaconConfig().SecondsPerSlot*uint64(params.BeaconConfig().SlotsPerEpoch)*3) * time.Second
+	// safely convert unint64 to int64
+	t, err := strconv.ParseInt(fmt.Sprint(ts), 10, 64)
+	if err != nil {
+		return false
+	}
+	return time.Unix(t, 0).Add(expiryDuration).Unix() < time.Now().Unix()
+}
```
Comment (prestonvanloon) [inline beacon-chain/db/kv/blocks.go:574]: Is this different from the other timeStampExpired in this PR?

File: beacon-chain/cache/registration.go [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+	return v, nil
+}
+
+func timeStampExpired(ts uint64) bool {
+	expiryDuration := time.Duration(params.BeaconConfig().SecondsPerSlot*uint64(params.BeaconConfig().SlotsPerEpoch)*3) * time.Second
+	// safely convert unint64 to int64
+	t, err := strconv.ParseInt(fmt.Sprint(ts), 10, 64)
```
Comment (prestonvanloon) [inline beacon-chain/cache/registration.go:48]: This seems like an expensive conversion to string and then to int64. Don't we have some more performance based conversions somewhere?

**Review by prestonvanloon — DISMISSED** [review]

File: beacon-chain/db/kv/blocks.go (hunk 3 above)
Comment (james-prysm) [reply beacon-chain/db/kv/blocks.go:574]: yes this is the same, I didn't find a great place to place this but will try to put it in a place where it'd make sense. was thinking maybe we can keep it in both places until full removal but will try to find a better spot without circular dependencies.

File: beacon-chain/builder/service.go [hunk 5]
```diff
@@ -154,12 +161,34 @@ func (s *Service) RegisterValidator(ctx context.Context, reg []*ethpb.SignedVali
...
+	} else {
+		return s.cfg.beaconDB.SaveRegistrationsByValidatorIDs(ctx, idxs, msgs)
+	}
+}
+
+// RegistrationByValidatorID returns either the values from the cache or db.
+func (s *Service) RegistrationByValidatorID(ctx context.Context, id primitives.ValidatorIndex) (*ethpb.ValidatorRegistrationV1, error) {
+	if s.cfg == nil || s.cfg.beaconDB == nil {
+		return nil, errors.New("nil beacon db")
+	}
```
Comment (prestonvanloon) [inline beacon-chain/builder/service.go:185]: Could this be a problem if you only had a registration cache but no db?

File: beacon-chain/cache/registration.go [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+	if RegistrationTimeStampExpired(v.Timestamp) {
+		regCache.RUnlock()
+		regCache.Lock()
+		defer regCache.Unlock()
+		delete(regCache.indexToRegistration, id)
+		return nil, errors.Wrapf(ErrNotFoundRegistration, "validator id %d", id)
+	}
+	defer regCache.RUnlock()
+	return v, nil
+}
```
Comment (prestonvanloon) [inline beacon-chain/cache/registration.go:46]:
```suggestion
func (regCache *RegistrationCache) GetRegistrationByIndex(id primitives.ValidatorIndex) (*ethpb.ValidatorRegistrationV1, error) {
	regCache.RLock()
	v, ok := regCache.indexToRegistration[id]
	if !ok {
		regCache.RUnlock()
		return nil, errors.Wrapf(ErrNotFoundRegistration, "validator id %d", id)
	}
	if RegistrationTimeStampExpired(v.Timestamp) {
		regCache.RUnlock()
		regCache.Lock()
		defer regCache.Unlock()
		delete(regCache.indexToRegistration, id)
		return nil, errors.Wrapf(ErrNotFoundRegistration, "validator id %d", id)
	}
	regCache.RUnlock()
	return v, nil
}
```
For these RUnlock calls, you dont need a defer really because you've already read the data you need and you are returning on the next line for both of these.

File: beacon-chain/cache/registration.go [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+
+// NewRegistrationCache initializes the map and underlying cache.
+func NewRegistrationCache() *RegistrationCache {
+	return &RegistrationCache{
+		indexToRegistration: make(map[primitives.ValidatorIndex]*ethpb.ValidatorRegistrationV1),
+	}
+}
+
+// GetRegistrationByIndex returns the registration by index in the cache and also removes items in the cache if expired.
+func (regCache *RegistrationCache) GetRegistrationByIndex(id primitives.ValidatorIndex) (*ethpb.ValidatorRegistrationV1, error) {
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply beacon-chain/cache/registration.go:30]: This should only happen about once an epoch for a limited number of validators, and once it's registered it's not that important again as long as it doesn't expire ( which is how validators unregister in this case). I don't think it needs to be that performant I think.

File: beacon-chain/cache/registration.go [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+	}
+	regCache.RUnlock()
+	return v, nil
+}
+
+func RegistrationTimeStampExpired(ts uint64) bool {
+	expiryDuration := time.Duration(params.BeaconConfig().SecondsPerSlot*uint64(params.BeaconConfig().SlotsPerEpoch)*3) * time.Second
+	// safely convert unint64 to int64
+	t := new(big.Int).SetUint64(ts).Int64()
+	return time.Unix(t, 0).Add(expiryDuration).Unix() < time.Now().Unix()
```
Comment (prestonvanloon) [inline beacon-chain/cache/registration.go:52]: Use  after

```suggestion
	return time.Unix(t, 0).Add(expiryDuration).After(time.Now())
```

File: beacon-chain/builder/service.go (hunk 5 above)
Comment (james-prysm) [reply beacon-chain/builder/service.go:185]: perhaps the suggestion here is to move it below

File: beacon-chain/cache/registration.go (hunk 8 above)
Comment (james-prysm) [reply beacon-chain/cache/registration.go]: should be before * . corrected now

File: beacon-chain/cache/registration.go [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+		defer regCache.Unlock()
+		delete(regCache.indexToRegistration, id)
+		return nil, errors.Wrapf(ErrNotFoundRegistration, "validator id %d", id)
+	}
+	regCache.RUnlock()
+	return v, nil
+}
+
+func RegistrationTimeStampExpired(ts uint64) bool {
+	expiryDuration := time.Duration(params.BeaconConfig().SecondsPerSlot*uint64(params.BeaconConfig().SlotsPerEpoch)*3) * time.Second
```
[the remark this answers is not in the document]
Comment (james-prysm) [reply beacon-chain/cache/registration.go:51]: it's not in the specs, but was a number that most other clients also chose from the original proposal

File: beacon-chain/cache/registration.go [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+	return v, nil
+}
+
+func RegistrationTimeStampExpired(ts uint64) (bool, error) {
+	// safely convert unint64 to int64
+	i, err := math.Int(ts)
+	if err != nil {
+		return false, err
+	}
+	expiryDuration := params.BeaconConfig().RegistrationDuration
```
Comment (james-prysm) [inline beacon-chain/cache/registration.go:63]: I hope this is a good way of doing it...

File: beacon-chain/cache/registration.go [hunk 11]
```diff
@@ -0,0 +1,82 @@
...
+type RegistrationCache struct {
+	indexToRegistration map[primitives.ValidatorIndex]*ethpb.ValidatorRegistrationV1
+	lock                sync.RWMutex
+}
+
+// NewRegistrationCache initializes the map and underlying cache.
+func NewRegistrationCache() *RegistrationCache {
+	return &RegistrationCache{
+		indexToRegistration: make(map[primitives.ValidatorIndex]*ethpb.ValidatorRegistrationV1),
+		lock:                sync.RWMutex{},
```
Comment (james-prysm) [inline beacon-chain/cache/registration.go:29]: deepsource complained the lock was open on the struct so now i added it internally here, can revert to align with other caches.

File: beacon-chain/cache/registration.go [hunk 12]
```diff
@@ -0,0 +1,82 @@
...
+	}
+}
+
+// GetRegistrationByIndex returns the registration by index in the cache and also removes items in the cache if expired.
+func (regCache *RegistrationCache) GetRegistrationByIndex(id primitives.ValidatorIndex) (*ethpb.ValidatorRegistrationV1, error) {
```
Comment (prestonvanloon) [inline beacon-chain/cache/registration.go:34]: Optional: effective go guidelines suggest that you don't use the prefix "Get" for a getter and simply call it the thing like `regCache.RegistrationByIndex(...`

https://go.dev/doc/effective_go#Getters

**Review by prestonvanloon — COMMENTED** [review]
One comment, otherwise LGTM

**Review by prestonvanloon — APPROVED** [review]
